#!/bin/sh
#
# $Id: login-ssh,v 2.0 2004/09/13 19:44:54 alexios Exp $
#
# $Log: login-ssh,v $
# Revision 2.0  2004/09/13 19:44:54  alexios
# Stepped version to recover CVS repository after near-catastrophic disk
# crash.
#
# Revision 1.2  2004/05/03 05:45:43  alexios
# Fixed login-ssh. It's now remarkably similar to login-telnet.
#

# Get the prefix

PREFIX=`echo $0 | sed 's/bin\/[^\/]\+$//'`

# Check the prefix.

[ -r ${PREFIX}/etc/paths ] || exit 1

# Set us up.

. ${PREFIX}/etc/paths

# BAUD=0 indicates this is a telnet connection.

export BAUD="-1"
declare -xr BAUD

# Off we go.

exec ${PREFIX}/bin/daemons/emud
