LEVEL2 {}


ENTRYKEY {Key required to enter the Infocom Adventure module: 0} N 0 129

TOPKEY {Key required to look at top games: 0} N 0 129

PLAYKEY {Key required to play a game: 2} N 0 129


LEVEL3 {}


SAVEDGAME {˜¨«å›˜ §˜ ®¤ › ¦ç §œ¨ §â«œ ˜ª} S 50 Description for saved game downloads 


NOENTRY {[0;1;31m
Š¬§á£˜ , ›œ¤ â®œ«œ §¨æ©™˜© ©œ ˜¬«ã «¤ §œ¨ ¦®ã.
} T Access to the Infocom Adventure module denied


MENU {[2J[0;47;1;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;30;47m¿ [40m
[47;1;37m ³          [0;47;30m˜ ®¤å› ˜ œ¨ §â«œ ˜ª          ³ [40m
[47;1;37m ³  [0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ  [0;47;30m³ [40m
[47;1;37m ³  [0;31;47mA[0;47;30mbout . . . . . . ‚œ¤ ¡âª §¢¨¦­¦¨åœª  [30m³ [40m
[47;1;37m ³  [0;31;47mH[0;47;30mow to play  . . . . .  éª §˜å¦¤«˜   [30m³ [40m
[47;1;37m ³  [0;31;47mP[0;47;30mlay game . . . . ˜å¥«œ â¤˜ §˜ ®¤å›   [30m³ [40m
[47;1;37m ³  [0;31;47mT[0;47;30mop games  . . . . ƒ£¦­ ¢ã §˜ ®¤å› ˜  [30m³ [40m
[47;1;37m ³                                         [0;47;30m³ [40m
[47;1;37m ³ [0;30;47me[31mX[0;47;30mit  . . . . . . . . . . . . . „¥¦›¦ª  [30m³ [40m
[47;1;37m À[0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m

[0;1m˜ ®¤å› ˜ œ¨ §â«œ ˜ª (adventure games)
† ©¬¢¢¦šã £˜ª §œ¨ â®œ  [32m%d[37m §˜ ®¤å› ˜!
˜¨˜¡˜¢é ›é©«œ «¤ œ§ ¢¦šã ©˜ª: [0m} T Menu


SHMENU {
[0;1m˜ ®¤å› ˜ œ¨ §â«œ ˜ª (adventure games)
† ©¬¢¢¦šã £˜ª §œ¨ â®œ  [32m%d[37m §˜ ®¤å› ˜!
!Wƒ ˜¢â¥«œ â¤˜ š¨á££˜ ([33mA[37m,[33mH[37m,[33mP[37m,[33mT[37m,[33mX[37m ã [33m?[37m š ˜ «¦ £œ¤¦ç):!) [0m} T Short Menu


ERRSEL {[0;1;31m
ƒœ¤ ¬§á¨®œ  œ§ ¢¦šã "%c".
[0;1m} T Wrong selection


LEAVE {[0;1m
!J„§ ©«¨¦­ã ©«¦¤ §¨˜š£˜« ¡æ ¡æ©£¦ (š ˜ §æ©¦;).!)
[0;1m} T Leaving module


ABOUT {[2J[0;1;35m!RYou are in a maze of twisty little passages, all alike. -- [37mWill Crowther, ADVENT, 1976!)

!W  £œš˜¢ç«œ¨¦  (ã å©àª æ®  ¡˜  «æ©¦!) Ÿ˜ Ÿ¬£¦ç¤«˜  ¤˜ §œ¨ £â¤¦¬¤ 10-15 ¢œ§«á
¤˜ ­¦¨«é©œ  ¦ Spectrum «¦ [32mThe Hobbit[37m ˜§æ «¦ ¡˜©©œ«æ­à¤¦ ¡˜  £œ«á
«¤ â¤«¦¤ œ¤«ç§à© «¦¬ text adventure, £œ «¦¤ ¬§¦¢¦š ©«ã ¤˜ "¡˜«˜¢˜™˜å¤œ "
«  š¨á­œ ª (˜¢¢á ¡˜  «¦¤ œ¡¤œ¬¨ ©£æ «à¤ bugs ¡˜  «ª â¢¢œ ¯ª ¬§¦©«ã¨ ¥ª
¡˜  ™¦ãŸœ ˜ª).!)

!J€§æ «˜ £â©˜ «ª ›œ¡˜œ«å˜ª «¦¬ '70, æ§¦¬ â¤˜ PDP-10 â«¨œ¥œ «¦
[32mADVENT[37m, «¦ §¨é«¦ §˜ ®¤å›  §œ¨ §â«œ ˜ª (§¦¬ œ§ œå £â®¨  « ª £â¨œª
£˜ª àª  ©œ ¨á [32mZork[37m), ˜¬«á «˜ §˜ ®¤å› ˜ œå®˜¤ â¤˜ œ › ¡æ ¡¦ ¤æ --
˜¤Ÿ¨é§¦¬ª £œ ­˜¤«˜©å˜ §¦¬ ›œ¤  ¡˜¤¦§¦ ¦ç«˜¤ £œ «¦ Space Invaders (ã, ©ã£œ¨˜,
£œ «¦ Quake). ”˜ ¤¦£œ¤ ¡á, «˜ text adventures œ¥˜­˜¤å©«¡˜¤ ©«˜ «â¢ «ª
›œ¡˜œ«å˜ª «¦¬ '80 š ˜ ¤˜ ˜¤« ¡˜«˜©«˜Ÿ¦ç¤ ˜§æ «˜ š¨˜­ ¡á adventures «ª
Sierra, «ª Lucas Arts ¡˜  á¢¢à¤ œ«˜ ¨œ é¤.!)

!J€¬«æ §¦¬ ›œ¤ œå¤˜  §¦¢ç š¤à©«æ œå¤˜  æ«  §˜ ®¤å› ˜ š¨˜££â¤˜ š ˜ «¦
§œ¨å­£¦ Z-Machine «ª [32mInfocom[37m (1979-1989) š¨á­¦¤«˜  ˜¡æ£˜ ¡˜ 
©ã£œ¨˜ ˜§æ  › é«œª. ’¦ œå›¦ª, £á¢ ©«˜, œ  ˜¨¡œ«ã â¥˜¨©.   §œ¨ ¦¨ ©£¦å «¦¬
§˜¨œ¢Ÿæ¤«¦ª â®¦¬¤ ¥œ§œ¨˜©«œå ¡˜  ¦ ›£ ¦¬¨šæª â®œ  § ˜ £æ¤¦ « ­˜¤«˜©å˜ «¦¬
š ˜ æ¨ ¦. ¨ ©£â¤˜ ˜§æ «˜ ¤â˜, ›à¨œá¤ §˜ ®¤å› ˜ œå¤˜  §¨˜š£˜« ¡á
˜¨ ©«¦¬¨šã£˜«˜.!)

!J„›é Ÿ˜ ™¨œå«œ £ ˜ ©¬¢¢¦šã ˜§æ «â«¦ ˜ §˜ ®¤å› ˜ ¡áŸœ œå›¦¬ª, ˜§æ «˜
¡¢˜©© ¡á §˜ ®¤å› ˜ §œ¨ §â«œ ˜ª, àª «˜ §˜ ®¤å› ˜ §¦¬ ¡â¨› ©˜¤ «¦¬ª
› ˜šà¤ ©£¦çª Interractive Fiction «à¤ «œ¢œ¬«˜åà¤ œ«é¤. ‰˜¢ã ©˜ª
› ˜©¡â›˜©!!)

[0;1m} T Information about adventure games

HOWTO {[2J[0;1m!J€¤ ›œ¤ â®œ«œ ¥˜¤˜§˜å¥œ  text adventure, å©àª ¤˜ ©˜ª
­˜¤œå ¢åš¦ ˜©¬¤ãŸ ©« ¡˜  "§˜¨à®£â¤"  œ§ ¡¦ ¤à¤å˜ £â©à š¢é©©˜ª -- ˜¢¢á
©¡œ­«œå«œ «¤ ›ç¤˜£ «ª š¢é©©˜ª, «¤ ›ç¤˜£ «¦¬ ›œå¡« ©˜ª, ¡˜  Ÿ˜ ›œå«œ
æ«   œ§ ¡¦ ¤à¤å˜ £â©à ­¬© ¡ãª š¢é©©˜ª œå¤˜  §¦¢ç § ¦  ©®¬¨ã ¡˜ 
œ¤©« ¡«é›ª ˜§æ «¦ "point and click".!)

!J§àª ¡˜  ¤˜'®œ , ¢åš ™¦ãŸœ ˜ œå¤˜  §á¤«˜ ®¨ã© £. ‚ ˜ ˜¨®ã: ˜¤ š ˜
¦§¦ ¦›ã§¦«œ ¢æš¦ «¦ §˜ ®¤å›  ¡¦¢¢ã©œ , ã Ÿâ¢œ«œ ¤˜ ™šœå«œ š¨ãš¦¨˜, § â©«œ
[33mCtrl-C[37m. ‰á¤¦¬£œ æ,«  £§¦¨¦ç£œ ¤˜ œ¨£¤œç©¦¬£œ ¡˜  «¦ ©¬¤Ÿ ©£â¤¦
[33mX[37m, ˜¢¢á ˜¬«æ ›œ¤ œå¤˜  §á¤«˜ œ­ ¡«æ (§® æ«˜¤ «¦ Z-Machine
™¨å©¡œ«˜  ©œ ¡á§¦ ¦ £œ¤¦ç).!)

!J€¤ ™¨å©¡œ©«œ ©œ £œ¤¦ç ¡˜  ›œ¤ ¬§á¨®¦¬¤ §¨¦­˜¤œåª ¦›šåœª ¡å¤©ª, ˜¤á¯«œ
«¦ [33mNum Lock[37m ¡˜  ®¨© £¦§¦ ã©«œ «¦ ™œ¢á¡ ˜ «¦¬ ˜¨ Ÿ£« ¡¦ç ©˜ª
§¢¡«¨¦¢¦šå¦¬, ã «˜ §¢ã¡«¨˜ [33m8[37m, [33m2[37m, [33m6[37m, [33m4[37m
(§á¤à, ¡á«à, ›œ¥ á, ˜¨ ©«œ¨á ˜¤«å©«¦ ®˜).!)

!J€¤ ™¨œŸœå«œ ©œ ›¬©¡¦¢åœª,  œ¤«¦¢ã [33mHELP[37m £§¦¨œå ¤˜ ©˜ª ™¦Ÿã©œ .
¨ ©£â¤˜ §˜ ®¤å› ˜ â®¦¬¤ hints ã ¡˜  walkthroughs £â©˜ ©«˜ £œ¤¦ç «¦¬ª. ƒé©«œ
[33mSAVE[37m š ˜ ¤˜ ©é©œ«œ â¤˜ §˜ ®¤å›  («¦ ˜¨®œå¦ Ÿ˜ ©˜ª §¨¦©­œ¨Ÿœå š ˜
¢ã¯), ã [33mRESTORE[37m š ˜ ¤˜ ­¦¨«é©œ«œ â¤˜ §¨¦š¦¬£â¤àª ©à©£â¤¦
§˜ ®¤å›  (Ÿ˜ ©˜ª «Ÿœå ¤˜ «¦ ˜§¦©«œå¢œ«œ ˜§æ «¦ £®á¤£á ©˜ª).!)

!J† š¢é©©˜ œ§ ¡¦ ¤à¤å˜ª œå¤˜  ©®œ›¦¤ §á¤«˜ «˜ ˜šš¢ ¡á. •¨© £¦§¦ ã©«œ ˜§¢ã
š¢é©©˜. ‘« ª §œ¨ ©©æ«œ¨œª §œ¨ §«é©œ ª ˜¨¡¦ç¤ ›ç¦ ¢â¥œ ª (¨ã£˜ ¡˜ 
˜¤« ¡œå£œ¤¦), ®à¨åª á¨Ÿ¨˜. €¤ «¦ §˜ ®¤å›  â®œ  ˜¤áš¡ §œ¨ ©©æ«œ¨œª
§¢¨¦­¦¨åœª, Ÿ˜ ©˜ª «¦ ›¢é©œ .!)

!J‹œ «¤ œ¤«¦¢ã [33mLOOK[37m £§¦¨œå«œ ¤˜ ¡¦ «á¥œ«œ šç¨à ©˜ª. ‚ ˜ ¤˜
¡ ¤Ÿœå«œ ©«˜ «â©©œ¨˜ ©£œå˜ «¦¬ ¦¨å¦¤«˜ ®¨© £¦§¦ œå«˜ « ª ¡¢˜©© ¡âª
©¬¤«£ã©œ ª [33mN[37m, [33mS[37m, [33mE[37m, [33mW[37m (æ¨œ ˜,
Œæ« ˜, €¤˜«¦¢ ¡á, ƒ¬« ¡á).!)

!J’â¢¦ª, æ§¦¬ £§¦¨œå«œ ¤˜ š¨á¯œ«œ œ¤«¦¢âª ¦¢¦š¨á­àª, £§¦¨œå«œ ¡˜  ¤˜
®¨© £¦§¦ ã©œ«œ « ª œ¤«¦¢âª «ª ™á©ª. [32m‘•†[37m: £§¦¨œå«œ ¤˜
®¨© £¦§¦ ã©œ«œ «¤ œ¤«¦¢ã [33m/GO[37m š ˜ ¤˜ ­çšœ«œ š¨ãš¦¨˜ ˜§æ «¦
§˜ ®¤å› , ˜¢¢á â«©  [32m®á¤œ«œ[37m «¦ §˜ ®¤å›  ©˜ª. €¤ Ÿâ¢œ«œ ¤˜ «¦
¡¨˜«ã©œ«œ, Ÿ˜ §¨â§œ  §¨é«˜ ¤˜ «¦ ©é©œ«œ.!)

[0;1m} T How to play adventure games


PLAYWARN {[0;1;32m
!Jœ¡ ¤á£œ «¦ §˜ ®¤å› . €¤ š ˜ ¦§¦ ¦›ã§¦«œ ¢æš¦ ¦ œ¥¦£¦ à«ãª «¦¬ Z-Machine
©«˜£˜«ã©œ  ¤˜ ¢œ «¦¬¨šœå, § â©«œ [33mCtrl-C[32m.!)

!J,«  ˜¨®œå˜ ›£ ¦¬¨šŸ¦ç¤ ˜§æ «¦ §˜ ®¤å›  (saved games, scripts, ¡¢§) Ÿ˜
©˜ª §¨¦©­œ¨Ÿ¦ç¤ š ˜ ¢ã¯ œ§ ©«¨â­¦¤«˜ª ©'˜¬«æ «¦ £œ¤¦ç.!)

[0;1m[2J} T Starting game, use Ctrl-C in case of emergency







XCONFRM {[0;1;31m
!W˜¨˜¡˜¢é œ§ ™œ™˜ é©«œ æ«  Ÿâ¢œ«œ ¤˜ [37mœš¡˜«˜¢œå¯œ«œ[31m «¦ §˜ ®¤å›  ©˜ª
(˜¤ ›œ¤ «¦ â®œ«œ ©é©œ , ¦  àª «é¨˜ ¡ ¤ã©œ ª ©˜ª Ÿ˜ ®˜Ÿ¦ç¤).!)
[0;1m([[33mY[0;1m]es=¤˜  / [[33mN[0;1m]o=æ® ): [0m} T Exit from game, are you sure?


RESTORE {[0;1;33m
!J‘£œåà©: £§¦¨œå«œ ¤˜ ­¦¨«é©œ«œ œå«œ £ ˜ §˜¨«å›˜ §¦¬ â®œ«œ ©é©œ  ©ã£œ¨˜,
œå«œ ¤˜ ˜§¦©«œå¢œ«œ œ©œåª «¦ ˜¨®œå¦. ‘«¤ §¨é« §œ¨å§«à© §¨â§œ  ¤˜ Ÿ¬£á©«œ
«¦ æ¤¦£˜ «¦¬ ˜¨®œå¦¬. ‚ ˜ ¤˜ ˜§¦©«œå¢œ«œ (upload) «¦ ˜¨®œå¦, ›é©«œ
"." («œ¢œå˜) ˜¤«å š ˜ æ¤¦£˜ ˜¨®œå¦¬.!)

[0m} T Note on restoring games


NAMELESS {[0;1;33m
!J¨¦©¦®ã: ˜¤ «¦ §¨à«æ¡¦¢¦ £œ«˜­¦¨áª ›œ¤ ©¬š¡¨˜«œå «¦ æ¤¦£˜ «¦¬ ˜¨®œå¦¬ (§®
X-Modem), «æ«œ «¦ ˜¨®œå¦ Ÿ˜ ¦¤¦£˜©«œå "[32msavedgame[33m". ‡˜ ®¨œ ˜©«œå ¤˜
š¤à¨åœ«œ «¦ æ¤¦£á «¦¬ ˜¤ Ÿœ¢ã©œ«œ ¤˜ «¦ ­¦¨«é©œ«œ ®à¨åª ¤˜ «¦
¥˜¤˜©«œå¢œ«œ.!)

[0m} T Note on nameless files


XFERERR {[0;1;31m
!J‘¬šš¤é£, ¬§ã¨¥œ ¡á§¦ ¦ ¢áŸ¦ª ¡˜«á «¤ ¢ã¯ «¦¬ ˜¨®œå¦¬. ‹§¦¨œå«œ ˜¤
Ÿâ¢œ«œ ¤˜ œ§ ®œ ¨ã©œ«œ «¤ ˜§¦©«¦¢ã á¢¢ £ ˜ ­¦¨á.!)
[0m} T Upload failed, try again



SAVE {[0;1;33m
!J‘£œåà©:  §˜¨«å›˜ §¦¬ Ÿ˜ ©é©œ«œ «é¨˜ Ÿ˜ ©˜ª §¨¦©­œ¨Ÿœå š ˜ ¢ã¯ ¡˜«á
«¤ â¥¦›æ ©˜ª ˜§æ «¦ §˜ ®¤å› . ‘«¦ £œ«˜¥ç, £§¦¨œå«œ ˜¤ Ÿâ¢œ«œ ¤˜ «¤
­¦¨«é©œ«œ ©˜ ¤˜ ™¨ ©¡æ«˜¤ ©«¦¤ «¦§ ¡æ ©˜ª ›å©¡¦ (˜¢¢á Ÿ˜ §¨â§œ  ¤˜ Ÿ¬£á©«œ
ã ¤˜ š¨á¯œ«œ ¡á§¦¬ «¦ æ¤¦£˜ «¦¬ ˜¨®œå¦¬).!)

[0m} T Note on saving games


DLNOW {[0;1;33m!J¨ã¡˜£œ ˜§¦Ÿ¡œ¬£â¤˜ §˜ ®¤å› ˜. ‘˜ª «˜ §¨¦©­â¨¦¬£œ š ˜ ¢ã¯. ”¬¢á¥«œ æ,« 
˜¨®œå˜ â®œ«œ £œ ¡á§¦ ¦ ®˜¨˜¡«¨ ©« ¡æ æ¤¦£˜. ’˜ ˜¨®œå˜ [37mƒ„Œ ‹„Œ“Œ ‘’†Œ
@BBS@[33m, Ÿ˜ ©™©«¦ç¤ ˜¤ ›œ¤ «˜ ¢á™œ«œ ˜¬«ã « ©« š£ã!!)
[0;1m} T Found saved games for download






CHOOSE {[0;1m
!W˜¨˜¡˜¢é ›é©«œ «¦¤ ˜¨ Ÿ£æ «¦¬ §˜ ®¤ › ¦ç §¦¬ Ÿâ¢œ«œ ¤˜ §˜å¥œ«œ,
([33m%d[37m-[33m%d[37m, [33m0[37m=â¤˜ §˜ ®¤å›  ©«¤ «ç®), ã
[33m?[37m š ˜ ¡˜«á¢¦š¦, ã [33mX[37m š ˜ â¥¦›¦.!)[0m } T Choose game

CHOOSERR {[0;1;31m
!JŠ¬§á£˜ , ˜¬«æ «¦ §˜ ®¤å›  ›œ¤ ¬§á¨®œ . ˜¤˜›¦¡ £á©«œ.!)
[0;1m} T Choose game, invalid choice



RANDOM {[0;1;36m
!Jƒ ˜¢â¥˜£œ «¦ §˜ ®¤å›  £œ ˜¨ Ÿ£æ [33m%d[37m: [37m%s!)
[0;1m} T Random game chosen




TOPHDR {[0;1;32m
’˜ %d § ¦ ›£¦­ ¢ã §˜ ®¤å› ˜ §œ¨ §â«œ ˜ª «ª @BBS@:

[32m‡â©  [35m—¨œª:Šœ§«á  ˜¨«å›œª  [37m’å«¢¦ª/§œ¨ š¨˜­ã
!FÄ
[0;1m} T Top 10 header


TOPLIN {[32m%3d     [35m%4d:%02d    %4d     [37m!i!W%s!)
!0l
[0;1m} T Top 10 entry


TOPFTR {[0;1m!FÄ
[0;1m
} T Top 10 footer


NOTOP {[0;1;31m
!Wƒœ¤ â®¦¬£œ Top 10 š ˜«å ›œ¤ â®œ  §˜ ®«œå ¡˜¤â¤˜ §˜ ®¤å›  (ã «¦¬¢á® ©«¦¤
â«©  ›œå®¤œ   ¡˜«á©«˜©)!!)
[0;1m} T Top 10 file unavailable





LISTHDR {[0;1;32m
!C‰˜«á¢¦š¦ª ˜ ®¤ › é¤ œ¨ §â«œ ˜ª!)

€¨ Ÿ£æª  ’å«¢¦ª, ©¬šš¨˜­â˜ª, §œ¨ š¨˜­ã ¡˜  â¡›¦©
!FÄ
[0;1m} T Game list header


LISTGAM {
  [33m%3d[37m    !i!W%s!)
!0l} T Game list item


LISTFTR {[0;1m!FÄ
[0;1m} T Game list footer


LANG {}




SAVEDGAME {Saved adventure game} S 50 Description for saved game downloads 


NOENTRY {[0;1;31m
Sorry, you don't have access to this area.
} T Access to the Infocom Adventure module denied


MENU {[2J[0;47;1;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;30;47m¿ [40m
[47;1;37m ³  [0;47;30mAdventure Games  ³ [40m
[47;1;37m ³  [0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ  [0;47;30m³ [40m
[47;1;37m ³  [0;31;47mA[0;47;30mbout            [30m³ [40m
[47;1;37m ³  [0;31;47mH[0;47;30mow to play      [30m³ [40m
[47;1;37m ³  [0;31;47mP[0;47;30mlay game        [30m³ [40m
[47;1;37m ³  [0;31;47mT[0;47;30mop games        [30m³ [40m
[47;1;37m ³                   [0;47;30m³ [40m
[47;1;37m ³ [0;30;47me[31mX[0;47;30mit              [30m³ [40m
[47;1;37m À[0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m

[0;1mAdventure Games
We have [32m%d[37m games in our collection!
Please enter your selection: [0m} T Menu


SHMENU {
[0;1mAdventure Games
We have [32m%d[37m games in our collection!
!WEnter your selection ([33mA[37m,[33mH[37m,[33mP[37m,[33mT[37m,[33mX[37m
or [33m?[37m for the menu):!) [0m} T Short Menu


ERRSEL {[0;1;31m
Sorry, there's no option "%c".
[0;1m} T Wrong selection


LEAVE {[0;1m
!JReturning to the real world...!)
[0;1m} T Leaving module


ABOUT {[2J[0;1;35m!RYou are in a maze of twisty little passages, all alike. -- [37mWill Crowther, ADVENT, 1976!)

!JThe older (or maybe not so old!) among us probably remember waiting ten
minutes for their ZX-Spectrum to load [32mThe Hobbit[37m off a tape. nd
then there was the impression caused by computers "understanding" what you
wrote (and, of course, all the annoying bugs and lack of support and help).!)

!JSince the mid-Seventies, when a PDP-10 computer played [32mADVENT[37m,
the first ever adventure game (still alive and kicking nowadays as the
[32mZork[37m series), adventure games have always had a special audience ---
imaginative people who weren't satisfied with Space Invaders (or, today,
Quake). By all appearances, text adventures became extinct at the same time as
the Eighties, only to be replaced by graphic adventures by Sierra On-line,
Lucas Arts and others.!)

!JWhat's not widely known is that new games for [32mInfocom's[37m
(1979-1989) famous Z-Machine are still written today by independent authors.
In fact, the adventure game genre enjoys quite an active group of authors and
gamers. Small wonder: the hardware and software limitations of the Eighties
are long past, leaving the game author free to express their imagination. Some
of the new, free games are real works of art.!)

!JWhat we have here is a collection of such games. The games cover all styles
and tastes, ranging from some of the great classics (now freeware), to games
that won interactive fiction (i.e. adventure game creation) contests in recent
years. Have fun!!)

[0;1m} T Information about adventure games

HOWTO {[2J[0;1m!JIf you've never played an adventure game before, the
"obsolete" way of communicating with words may seem unusual -- but think of
the sheer power of language, the power of your mouse finger, and you'll see
that communicating through natural language is much more powerful and
intuitive than pointing and clicking.!)

!JAt any rate, a little help is always helpful. For starters: if a game
crashes for any reason, or you want to quit in a hurry, press
[33mCtrl-C[37m. We'll try our best to interpret the usual exit command
([33mX[37m), but this isn't always possible (for instance with the Z-Machine
is displaying a menu).!)

!JIf you're in a menu without obvious navigation instructions, turn on your
[33mNum Lock[37m and use the arrow keys on your numeric keypad, or the
[33m8[37m, [33m2[37m, [33m6[37m and [33m4[37m keys (respectively up,
down, right, left).!)

!JIf you're stuck with a game, try the [33mHELP[37m command. Some games
include hints and tips or even their own walkthroughs somewhere in their menu
systems. Enter [33mSAVE[37m to save a game (the saved game will be offered
for download), or [33mRESTORE[37m to load a previously saved game (you'll be
asked to upload the game file).!)

!JUse simple English sentences to communicate. In most cases, two words are
enough (verb-object). No articles are necessary, but most games will
understand them if you feel like typing syntantically correct English. If a
game needs more details, it'll say so.!)

!JIssue the [33mLOOK[37m command to look around. You can move around with
the usual shorthands [33mN[37m, [33mS[37m, [33mE[37m and [33mW[37m
(North, South, East, West respectively).!)

!JFinally, outside of menus, BBS global commands work too. [32mCAUTION[37m:
you can use the [33m/GO[37m command to leave a game in a hurry, but in doing
so you [32mforfeit[37m your game. Consider saving the game first.!)

[0;1m} T How to play adventure games


PLAYWARN {[0;1;32m
!JStarting the game. If the Z-Machine emulator crashes, press
[33mCtrl-C[32m.!)

!JAny files created by the game (saved games, scripts, etc) will be offered
to you for download when you return to this menu.!)

[0;1m[2J} T Starting game, use Ctrl-C in case of emergency







XCONFRM {[0;1;31m
!WYou are about to [37mabandon[31m your game. If you haven't saved your
position, it will be lost. Do you confirm?!) [0;1m([[33mY[0;1m]es / [[33mN[0;1m]o): [0m} T Exit from game, are you sure?


RESTORE {[0;1;33m

!JNote: you can either load a game you saved in this session, or upload one
you have on your own computer. In the former case, you'll have to remember the
save game's filename. To upload a file, enter "." (period) instead of a
filename.!)

[0m} T Note on restoring games


NAMELESS {[0;1;33m
!JCaution: if the transfer protocol doesn't retain filenames (e.g. X-Modem),
then the file will be named "[32msavedgame[33m". You'll have to know this
name to restore the saved game.!)

[0m} T Note on nameless files


XFERERR {[0;1;31m
!JSorry, there was an error while transferring this file. You can try the
upload again.!)
[0m} T Upload failed, try again



SAVE {[0;1;33m
!JNote: the position you're about to save will be offered for download once
you exit the game. In the meantime, you can load the saved game, but you'll
have to remember its filename (or, better yet, write it down).!)

[0m} T Note on saving games


DLNOW {[0;1;33m!JThere are saved files for you to download. The files are
[37mNOT STORED ON @BBS@[33m. They'll be deleted unless you download them
now.!!)
[0;1m} T Found saved games for download






CHOOSE {[0;1m
!WPlease select a game by number
([33m%d[37m-[33m%d[37m, [33m0[37m=a random game),
[33m?[37m for a list, or [33mX[37m to exit.!)[0m } T Choose game

CHOOSERR {[0;1;31m
!JSorry, there's no such game. Please try again.!)
[0;1m} T Choose game, invalid choice



RANDOM {[0;1;36m
!JGame chosen: [33m#%d[37m, [37m%s!)
[0;1m} T Random game chosen




TOPHDR {[0;1;32m
Here are the %d most popular games on @BBS@:

[32mPlace [35mHours:Mins  Games     [37mTitle/Description
!FÄ
[0;1m} T Top 10 header


TOPLIN {[32m%3d     [35m%4d:%02d    %4d     [37m!i!W%s!)
!0l
[0;1m} T Top 10 entry


TOPFTR {[0;1m!FÄ
[0;1m
} T Top 10 footer


NOTOP {[0;1;31m
!WThere's no Top-10 because no games have been played!!)
[0;1m} T Top 10 file unavailable





LISTHDR {[0;1;32m
!CList of adventure games!)

Number   Title, author, description and version
!FÄ
[0;1m} T Game list header


LISTGAM {
  [33m%3d[37m    !i!W%s!)
!0l} T Game list item


LISTFTR {[0;1m!FÄ
[0;1m} T Game list footer


LANGEND {}
