/***********************************************************
 **                                                       **
 **  This header file generated by msgidx. Do not alter.  **
 **                                                       **
 ***********************************************************/

#ifndef __ADVENTURE_UNAMBIGUOUS__
#define	ENTRYKEY 1
#define	TOPKEY 2
#define	PLAYKEY 3
#define	SAVEDGAME 4
#define	NOENTRY 5
#define	MENU 6
#define	SHMENU 7
#define	ERRSEL 8
#define	LEAVE 9
#define	ABOUT 10
#define	HOWTO 11
#define	PLAYWARN 12
#define	XCONFRM 13
#define	RESTORE 14
#define	NAMELESS 15
#define	XFERERR 16
#define	SAVE 17
#define	DLNOW 18
#define	CHOOSE 19
#define	CHOOSERR 20
#define	RANDOM 21
#define	TOPHDR 22
#define	TOPLIN 23
#define	TOPFTR 24
#define	NOTOP 25
#define	LISTHDR 26
#define	LISTGAM 27
#define	LISTFTR 28
#else
#define	ADVENTURE_ENTRYKEY 1
#define	ADVENTURE_TOPKEY 2
#define	ADVENTURE_PLAYKEY 3
#define	ADVENTURE_SAVEDGAME 4
#define	ADVENTURE_NOENTRY 5
#define	ADVENTURE_MENU 6
#define	ADVENTURE_SHMENU 7
#define	ADVENTURE_ERRSEL 8
#define	ADVENTURE_LEAVE 9
#define	ADVENTURE_ABOUT 10
#define	ADVENTURE_HOWTO 11
#define	ADVENTURE_PLAYWARN 12
#define	ADVENTURE_XCONFRM 13
#define	ADVENTURE_RESTORE 14
#define	ADVENTURE_NAMELESS 15
#define	ADVENTURE_XFERERR 16
#define	ADVENTURE_SAVE 17
#define	ADVENTURE_DLNOW 18
#define	ADVENTURE_CHOOSE 19
#define	ADVENTURE_CHOOSERR 20
#define	ADVENTURE_RANDOM 21
#define	ADVENTURE_TOPHDR 22
#define	ADVENTURE_TOPLIN 23
#define	ADVENTURE_TOPFTR 24
#define	ADVENTURE_NOTOP 25
#define	ADVENTURE_LISTHDR 26
#define	ADVENTURE_LISTGAM 27
#define	ADVENTURE_LISTFTR 28
#endif /* __ADVENTURE_UNAMBIGUOUS__ */
