LEVEL2 {}


ENTRYKEY {Key required to enter the Graffiti Wall: 0} N 0 129

MAXLEN {Max length of each message in characters: 80} N 1 255

MAXSIZE {Max number of messages on wall: 100} N 1 32767

MAXMSGS {Max messages entered at once. 4} N 1 100

WRTKEY {Key required to write ont he wall: 2} N 0 129

OVRKEY {Key required to override MAXMSGS restriction: 11} N 0 129

SYSKEY {Key required for sysop access to the wall: 11} N 0 129


LEVEL3 {}


NOENTRY {[0;1;31m
Š¬§á£˜ , ›œ¤ â®œ«œ §¨æ©™˜© ©œ ˜¬«ã «¤ §œ¨ ¦®ã.
} T Access to the Graffiti Wall denied


HITHERE {[2J[0;1;35m!Jœ¨§˜«é¤«˜ª ©«˜ ©¡¦«œ ¤á ›¨¦£á¡ ˜ «ª §æ¢ª,
­«á¤œ«œ ©œ â¤˜¤ «¦å®¦ §¦¬ ¥œ®à¨åœ . „å¤˜  šœ£á«¦ª ˜§æ ©¬¤Ÿã£˜«˜,
˜­ œ¨é©œ ª, ¡˜  æ,«  á¢¢¦ £§¦¨œå«œ ¤˜ ­˜¤«˜©«œå«œ, æ¢˜ š¨˜££â¤˜ ˜§æ
˜š¤é©«¦¬ª £œ spray. ‰¦¤«á ©«¦¤ «¦å®¦ ™¨å©¡œ«˜  â¤˜ ¡¦¬«å £œ §¦¢ç®¨à£˜ spray.!)

} T Greeting text


MENU {[2J[0;1;32m‘œ¢å›˜: [37m@PAGE@

[0;47;1;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;30;47m¿ [40m
[47;1;37m ³           [0;47;30m’¦å®¦ª š ˜ š¨á¯ £¦!           ³ [40m
[47;1;37m ³  [0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ  [0;47;30m³ [40m
[47;1;37m ³  [0;31;47mA[34mbout . . . . . . . . . . ¢¨¦­¦¨åœª  [30m³ [40m
[47;1;37m ³  [0;31;47mR[34mead wall  . . . . .  ƒ á™˜©£˜ «¦å®¦¬  [30m³ [40m
[47;1;37m ³  [0;31;47mD[34mraw on wall  . .  ‚¨á¯ £¦ ©«¦¤ «¦å®¦  [30m³ [40m
[47;1;37m ³                                         [0;47;30m³ [40m
[47;1;37m ³ [0;34;47me[31mX[34mit  . . . . . . . . . . . . . „¥¦›¦ª  [30m³ [40m
[47;1;37m À[0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m
} T Menu


VSHMENU {[0;1m
˜¨˜¡˜¢é ›é©«œ «¤ œ§ ¢¦šã ©˜ª: [0m} T Very short menu prompt


SHMENU {
[0;1;35m’[36m¦[33må[32m®[31m¦[34mª[37m š ˜ š¨á¯ £¦!
ƒ ˜¢â¥«œ â¤˜ š¨á££˜ ([33mA[37m,[33mR[37m,[33mD[37m,[33mX[37m ã [33m?[37m š ˜ menu): [0m} T Short Menu


SYSMENU {[2J[0;1;32m‘œ¢å›˜: [37m@PAGE@

[0;47;1;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;30;47m¿ [40m
[47;1;37m ³           [0;47;30m’¦å®¦ª š ˜ š¨á¯ £¦!           ³ [40m
[47;1;37m ³  [0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ  [0;47;30m³ [40m
[47;1;37m ³  [0;31;47mA[34mbout . . . . . . . . . . ¢¨¦­¦¨åœª  [30m³ [40m
[47;1;37m ³  [0;31;47mR[34mead wall  . . . . .  ƒ á™˜©£˜ «¦å®¦¬  [30m³ [40m
[47;1;37m ³  [0;31;47mD[34mraw on wall  . .  ‚¨á¯ £¦ ©«¦¤ «¦å®¦  [30m³ [40m
[47;1;37m ³                                         [0;47;30m³ [40m
[47;1;37m ³  [0;31;47mL[34mist wall  . .  ‡œä¡æ › á™˜©£˜ «¦å®¦¬  [30m³ [40m
[47;1;37m ³  [0;31;47mC[34mlean . . . . . .  ¢ç© £¦ «¦¬ «¦å®¦¬  [30m³ [40m
[47;1;37m ³                                         [0;47;30m³ [40m
[47;1;37m ³ [0;34;47me[31mX[34mit  . . . . . . . . . . . . . „¥¦›¦ª  [30m³ [40m
[47;1;37m À[0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m
} T Sysop menu


SYSSHMENU {
[0;1;35m’[36m¦[33må[32m®[31m¦[34mª[37m š ˜ š¨á¯ £¦!
ƒ ˜¢â¥«œ â¤˜ š¨á££˜ ([33mA[37m,[33mR[37m,[33mD[37m,[33mL[37m,[33mC[37m,[33mX[37m ã [33m?[37m š ˜ menu): [0m} T Sysop short Menu


ERRSEL {[0;1;31m
ƒœ¤ ¬§á¨®œ  œ§ ¢¦šã "%c".
[0;1m} T Wrong selection


ABOUT {[2J[0;1;35m!J "«¦å®¦ª" ©˜ª œ§ «¨â§œ  ¤˜ š¨á­œ«œ £ ¡¨á ˜¤é¤¬£˜ £¤ç£˜«˜ «˜ ¦§¦å˜ Ÿ˜
£§¦¨¦ç¤ ¤˜ › ˜™á¦¬¤ æ¢˜ «˜ £â¢ «ª Acrobase.!)

!J «¦å®¦ª ¡˜Ÿ˜¨åœ«˜  ˜§æ « ª ˜¨®âª «ª §æ¢ª ¡áŸœ £œ¨ ¡âª £â¨œª ˜¢¢á
©®œ›æ¤ ˜£â©àª ¥˜¤˜šœ£åœ  ˜§æ «¦¬ª ­˜¤˜« ¡¦çª «¦¬ œå›¦¬ª.!)

!J«˜¤ š¨á­œ«œ ©«¦¤ «¦å®¦ Ÿ¬£Ÿœå«œ æ«  £§¦¨œå ¦  ˜¨®âª ¤˜ Ÿœà¨¦ç¤ «¦
™á¯ £¦ £ ˜ æ£¦¨­ ¡˜  š¨˜­ ¡ã §˜¨á›¦© ˜¢¢á « £à¨¦ç¤ ˜¬©«¨æ«˜«˜
(£â®¨  2 ®¨æ¤ ˜ £ œ¥˜š¦¨á© £˜ ¡˜  ®à¨åª ˜¤˜©«¦¢ã) «˜ ¬™¨ ©« ¡á,
¨˜«© ©« ¡á, ¡˜  šœ¤ ¡éª §¨¦©™¢« ¡á š ˜ ¦§¦ ¦¤›ã§¦«œ £¤ç£˜«˜.
‘«¦ ¡á«à ¡á«à ›œ¤ ¥â¨œ«œ §¦«â §¦ æª £§¦¨œå ¤˜ ¡¨¬­¦¡¦ «áœ  §å©à ˜§æ «
šà¤å˜ «¤ é¨˜ §¦¬ œ©œåª š¨á­œ«œ ©«¦¤ «¦å®¦...!)

[0;1m} T Information about wall


MSGDENY {[0;1;31m
!J˜­¤ ¡á ˜¡¦ç«œ ™ã£˜«˜ ¡˜  ™¢â§œ«œ ˜©«¬¤¦£ ¡¦çª ¤˜ §¢© á¦¬¤. €¤˜š¡áœ©«œ
¤˜ œš¡˜«˜¢œå¯œ«œ «¦ spray ©˜ª ¡˜  ¤˜ «¨â¥œ«œ æ©¦ § ¦ š¨ãš¦¨˜ £§¦¨œå«œ.!)

!J‹§¦¨œå«œ ¤˜ §œ¨ £â¤œ«œ ¢åš¦ ©œ £ ˜ šà¤å«©˜ ©«˜ ©¡¦«œ ¤á £â®¨  ¤˜ ­çš¦¬¤
(«é¨˜ š¨á­¦¬¤ ˜¬«¦å ©«¦¤ «¦å®¦) ¡˜  ¤˜ ¥˜¤á¨Ÿœ«œ æ«˜¤ Ÿ˜ ¬§á¨®œ 
¨œ£å˜...!)
[0;1m
} T Cannot write any more due to limit


WRTNAX {[0;1;31m
!J‘¬šš¤é£, ›œ¤ â®œ«œ §¨æ©™˜© ¤˜ š¨á¯œ«œ ©«¦¤ «¦å®¦ ˜¬«ã « ©« š£ã.!)
[0;1m} T Write access denied


NEWMSG {[0;1m
ƒé©«œ «¦ ¡œå£œ¤¦ §¦¬ Ÿâ¢œ«œ ¤˜ š¨á¯œ«œ ©«¦¤ «¦å®¦
ã §˜«ã©«œ ENTER š ˜ â¥¦›¦.
>[0m} T Enter your graffiti


OOPS {[0;1;31m
!W’¦ ¡œå£œ¤æ ©˜ª ›œ¤ £§æ¨œ©œ ¤˜ š¨˜­«œå ¢æšà ¢áŸ¦¬ª. ’¤ á¢¢ ­¦¨á
¤˜ §˜å¨¤œ«œ spray ¡˜¢ç«œ¨ª §¦ æ««˜ª![0;1m!)
} T I/O error while writing, sorry!


WALLSAV {[0;1;33m
’¦ ¡œå£œ¤æ ©˜ª š¨á­œ«˜  ©«¦¤ «¦å®¦!
} T Saving graffiti


WALLDON {[0;1m
’¦ spray ©˜ª ©«âš¤à©œ!
} T Done Saving entry


EMPTY {[0;1;31m
!J‹æ¢ ª §â¨˜©œ «¦ ©¬¤œ¨šœå¦ ¡˜Ÿ˜¨ æ««˜ª «¦¬ ›ã£¦¬, ¡˜  ¦ «¦å®¦ª œå¤˜ 
¡á«˜©§¨¦ª. ‹§¦¨œå«œ ™â™˜ ˜ ¤˜ ¥˜¤˜¡á¤œ«œ œ©œåª «¤ ˜¨®ã...!)
[0;1m} T The wall is empty


WALLHEAD {[0;1m
‘«â¡œ©«œ £§¨¦©«á ©«¦¤ «¦å®¦ ¡˜  › ˜™áœ«œ «˜ àš¨˜­ ©£â¤˜ £¤ç£˜«˜ ...  [0m
              //\\\
              ³OÄO³
          ooOÄ\ ø /Ä¦¦
[43mÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂ[40m
[43mÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁ[40m
[43mÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄ[40m
[43mÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂ[40m
[0;1m} T Heading on Wall display


WALLEND {
[0;1m} T End of Wall display


ABORT {
[0;1m€­ã¤œ«œ «¦¤ «¦å®¦ ©«¤ ©¬®å˜ «¦¬ ¡˜  ©¬¤œ®åœ«œ «¤ ™æ¢«˜ ©˜ª...
} T Abort listing


DELMSG {[0;1m
¦ ¦ £ã¤¬£˜ Ÿâ¢œ«œ ¤˜ ©™ã©œ«œ ˜§æ «¦¤ «¦å®¦; } T Delete which


BADNUM {[0;1m
€¤ç§˜¨¡«¦ª ˜¨ Ÿ£æª £¤ç£˜«¦ª.} T Bad message ID


WALLDEL {[0;1m
‹œ ¢åš¦ ™á¯ £¦ ¡˜  ˜©™â©«, «¦ £ã¤¬£˜ ©™ã©«¡œ.} T Message now deleted


WALLEMPTY {[0;1;31m
†¨â£©œ, ®˜©á§!  «¦å®¦ª œå¤˜  á›œ ¦ª!
[0;1m} T The wall is empty


TIMEOUT {[0;1;31m
‘¬šš¤é£, ›œ¤ £§æ¨œ©˜ ¤˜ › ˜š¨á¯à «¤ š¨˜££ã §¦¬ «ã©˜«œ.
[0;1m} T Can't erase line


LEAVE {[0;1m
„¬®˜¨ ©«¦ç£œ š ˜ «¤ œ§å©¡œ¯ã ©˜ª ©«¤ šœ «¦¤ á £˜ª!
} T Bye messsage


LANG {}

NOENTRY {[0;1;31m
I'm sorry, you don't have access to this part of the system.
} T Access to the Graffiti Wall denied


HITHERE {[2J[0;1;35m!JWalking through dark city alleys, you come across
an unusual wall. It's covered with mottos, dedications, and lots more, all
written by anonymous people. There are cans of paint of various colours
lying nearby.!)

} T Greeting text


MENU {[2J[0;1;32mPage: [37m@PAGE@

[0;47;1;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;30;47m¿ [40m
[47;1;37m ³   [0;47;30mGraffiti Wall!   ³ [40m
[47;1;37m ³  [0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ  [0;47;30m³ [40m
[47;1;37m ³  [0;31;47mA[34mbout             [30m³ [40m
[47;1;37m ³  [0;31;47mR[34mead the wall     [30m³ [40m
[47;1;37m ³  [0;31;47mD[34mraw on the wall  [30m³ [40m
[47;1;37m ³                    [0;47;30m³ [40m
[47;1;37m ³ [0;34;47me[31mX[34mit               [30m³ [40m
[47;1;37m À[0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m
} T Menu


VSHMENU {[0;1m
Please enter your choice: [0m} T Very short menu prompt


SHMENU {
[0;1;35mG[36mr[33ma[32mf[31mf[34mi[36mt[32mi[37m Wall!
Enter your choice ([33mA[37m,[33mR[37m,[33mD[37m,[33mX[37m or [33m?[37m to see the menu): [0m} T Short Menu


SYSMENU {[2J[0;1;32m‘œ¢å›˜: [37m@PAGE@

[0;47;1;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;30;47m¿ [40m
[47;1;37m ³   [0;47;30mGraffiti Wall!   ³ [40m
[47;1;37m ³  [0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ  [0;47;30m³ [40m
[47;1;37m ³  [0;31;47mA[34mbout             [30m³ [40m
[47;1;37m ³  [0;31;47mR[34mead the wall     [30m³ [40m
[47;1;37m ³  [0;31;47mD[34mraw on the wall  [30m³ [40m
[47;1;37m ³                    [0;47;30m³ [40m
[47;1;37m ³  [0;31;47mL[34mist graffiti     [30m³ [40m
[47;1;37m ³  [0;31;47mC[34mlean graffiti    [30m³ [40m
[47;1;37m ³                    [0;47;30m³ [40m
[47;1;37m ³ [0;34;47me[31mX[34mit               [30m³ [40m
[47;1;37m À[0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m
} T Sysop menu


SYSSHMENU {
[0;1;35mG[36mr[33ma[32mf[31mf[34mi[36mt[33mt[32mi[37m Wall!
!WMake your selection ([33mA[37m,[33mR[37m,[33mD[37m,[33mL[37m,[33mC[37m,[33mX[37m
or [33m?[37m for the menu):!) [0m} T Sysop short Menu


ERRSEL {[0;1;31m
Sorry, there is no option "%c".
[0;1m} T Wrong selection


ABOUT {[2J[0;1;35m!JThe "wall" allows you to write short anonymous
messages which all @BBS@ members will be able to read.!)

!JThe city authorities whitewash the wall every few days, but fans of
the art of graffiti paint it again almost immediately.!)

!JWhen writing on the wall, remember that although the authorities
consider graffiti a nice and colourful tradition, they punish severely
(up to two years, no parole) those who write indecent or generally 
offending messages. Besides, you never know who's peeking at you around
the corner while you're writing...!)
[0;1m} T Information about wall


MSGDENY {[0;1;31m
!JSuddenly you hear footsteps and see cops coming your way. You are forced
to abandon your can of paint and run as fast as you can.!)

!JYou can wait in a dark corner for a while, until they leave (it's their
turn on the wall now), and come back when it's quieter...!)
[0;1m
} T Cannot write any more due to limit


WRTNAX {[0;1;31m
!JSorry, you can't write on the wall.!)
[0;1m} T Write access denied


NEWMSG {[0;1m
Enter the message you want to write on the wall,
or press X and Enter to exit.
>[0m} T Enter your graffiti


OOPS {[0;1;31m
!WCouldn't write your message because of a system error. Next time use
better paint![0;1m!)
} T I/O error while writing, sorry!


WALLSAV {[0;1;33m
Your message is being written on the wall!
} T Saving graffiti


WALLDON {[0;1m
Your paint has dried!
} T Done Saving entry


EMPTY {[0;1;31m
!JThe cleaners were here a few minutes ago, and the wall has been
whitewashed. You can always be the first to repaint it, of course...!)
0;1m} T The wall is empty


WALLHEAD {[0;1m
You stand in front of the wall and read the graffiti...[0m
              //\\\
              ³OÄO³
          ooOÄ\ ø /Ä¦¦
[43mÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂ[40m
[43mÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁ[40m
[43mÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄ[40m
[43mÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂÄÁÂ[40m
[0;1m} T Heading on Wall display


WALLEND {
[0;1m} T End of Wall display


ABORT {
[0;1mYou leave the wall and go on on your walk...
} T Abort listing


DELMSG {[0;1m
What message number do you want to whitewash? } T Delete which


BADNUM {[0;1m
Invalid message number.} T Bad message ID


WALLDEL {[0;1m
A bit of paint, and the message is gone.} T Message now deleted


WALLEMPTY {[0;1;31m
Hey, take it easy, there's no graffiti on the wall!
[0;1m} T The wall is empty


TIMEOUT {[0;1;31m
Sorry, couldn't delete that message.
[0;1m} T Can't erase line


LEAVE {[0;1m
Thank you for visiting our neighbourhood!
} T Bye messsage


LANGEND {}
