/***********************************************************
 **                                                       **
 **  This header file generated by msgidx. Do not alter.  **
 **                                                       **
 ***********************************************************/

#ifndef __GRAFFITI_UNAMBIGUOUS__
#define	ENTRYKEY 1
#define	MAXLEN 2
#define	MAXSIZE 3
#define	MAXMSGS 4
#define	WRTKEY 5
#define	OVRKEY 6
#define	SYSKEY 7
#define	NOENTRY 8
#define	HITHERE 9
#define	MENU 10
#define	VSHMENU 11
#define	SHMENU 12
#define	SYSMENU 13
#define	SYSSHMENU 14
#define	ERRSEL 15
#define	ABOUT 16
#define	MSGDENY 17
#define	WRTNAX 18
#define	NEWMSG 19
#define	OOPS 20
#define	WALLSAV 21
#define	WALLDON 22
#define	EMPTY 23
#define	WALLHEAD 24
#define	WALLEND 25
#define	ABORT 26
#define	DELMSG 27
#define	BADNUM 28
#define	WALLDEL 29
#define	WALLEMPTY 30
#define	TIMEOUT 31
#define	LEAVE 32
#else
#define	GRAFFITI_ENTRYKEY 1
#define	GRAFFITI_MAXLEN 2
#define	GRAFFITI_MAXSIZE 3
#define	GRAFFITI_MAXMSGS 4
#define	GRAFFITI_WRTKEY 5
#define	GRAFFITI_OVRKEY 6
#define	GRAFFITI_SYSKEY 7
#define	GRAFFITI_NOENTRY 8
#define	GRAFFITI_HITHERE 9
#define	GRAFFITI_MENU 10
#define	GRAFFITI_VSHMENU 11
#define	GRAFFITI_SHMENU 12
#define	GRAFFITI_SYSMENU 13
#define	GRAFFITI_SYSSHMENU 14
#define	GRAFFITI_ERRSEL 15
#define	GRAFFITI_ABOUT 16
#define	GRAFFITI_MSGDENY 17
#define	GRAFFITI_WRTNAX 18
#define	GRAFFITI_NEWMSG 19
#define	GRAFFITI_OOPS 20
#define	GRAFFITI_WALLSAV 21
#define	GRAFFITI_WALLDON 22
#define	GRAFFITI_EMPTY 23
#define	GRAFFITI_WALLHEAD 24
#define	GRAFFITI_WALLEND 25
#define	GRAFFITI_ABORT 26
#define	GRAFFITI_DELMSG 27
#define	GRAFFITI_BADNUM 28
#define	GRAFFITI_WALLDEL 29
#define	GRAFFITI_WALLEMPTY 30
#define	GRAFFITI_TIMEOUT 31
#define	GRAFFITI_LEAVE 32
#endif /* __GRAFFITI_UNAMBIGUOUS__ */
