/***********************************************************
 **                                                       **
 **  This header file generated by msgidx. Do not alter.  **
 **                                                       **
 ***********************************************************/

#ifndef __NOTIFY_UNAMBIGUOUS__
#define	ENTRYKEY 1
#define	INVKEY 2
#define	SOPKEY 3
#define	NUMUSR 4
#define	NOENTRY 5
#define	MENU 6
#define	SHMENU 7
#define	ERRSEL 8
#define	LEAVE 9
#define	HELP 10
#define	ADDLIM 11
#define	ADDLM2 12
#define	ADDASK 13
#define	ADDHUH 14
#define	ADDERR 15
#define	ADDEXS 16
#define	ADDOK 17
#define	ADDSEXM 18
#define	ADDSEXF 19
#define	NOUSERS 20
#define	DELASK 21
#define	DELERR 22
#define	DELOK 23
#define	LISTHD 24
#define	LISTU 25
#define	LISTFT 26
#define	INJMSG 27
#define	SEXM 28
#define	SEXF 29
#define	LOGIN1 30
#define	CONM 31
#define	CONF 32
#define	CONP 33
#define	LOGIN2 34
#define	LOGIN3 35
#define	LOGIN4 36
#define	LOGIN5 37
#else
#define	NOTIFY_ENTRYKEY 1
#define	NOTIFY_INVKEY 2
#define	NOTIFY_SOPKEY 3
#define	NOTIFY_NUMUSR 4
#define	NOTIFY_NOENTRY 5
#define	NOTIFY_MENU 6
#define	NOTIFY_SHMENU 7
#define	NOTIFY_ERRSEL 8
#define	NOTIFY_LEAVE 9
#define	NOTIFY_HELP 10
#define	NOTIFY_ADDLIM 11
#define	NOTIFY_ADDLM2 12
#define	NOTIFY_ADDASK 13
#define	NOTIFY_ADDHUH 14
#define	NOTIFY_ADDERR 15
#define	NOTIFY_ADDEXS 16
#define	NOTIFY_ADDOK 17
#define	NOTIFY_ADDSEXM 18
#define	NOTIFY_ADDSEXF 19
#define	NOTIFY_NOUSERS 20
#define	NOTIFY_DELASK 21
#define	NOTIFY_DELERR 22
#define	NOTIFY_DELOK 23
#define	NOTIFY_LISTHD 24
#define	NOTIFY_LISTU 25
#define	NOTIFY_LISTFT 26
#define	NOTIFY_INJMSG 27
#define	NOTIFY_SEXM 28
#define	NOTIFY_SEXF 29
#define	NOTIFY_LOGIN1 30
#define	NOTIFY_CONM 31
#define	NOTIFY_CONF 32
#define	NOTIFY_CONP 33
#define	NOTIFY_LOGIN2 34
#define	NOTIFY_LOGIN3 35
#define	NOTIFY_LOGIN4 36
#define	NOTIFY_LOGIN5 37
#endif /* __NOTIFY_UNAMBIGUOUS__ */
