/***********************************************************
 **                                                       **
 **  This header file generated by msgidx. Do not alter.  **
 **                                                       **
 ***********************************************************/

#ifndef __LOGIN_UNAMBIGUOUS__
#define	LONALRM 1
#define	TERMINAL 2
#define	METAB4 3
#define	METALG 4
#define	UNIXUID 5
#define	DESCR 6
#define	LDOWN 7
#define	XLATEM 8
#define	XLATEE 9
#define	SANSI 10
#define	QANSI 11
#define	QANSIERR 12
#define	ASKLNG1 13
#define	ASKLNG2 14
#define	ASKLNG3 15
#define	ASKLNGR 16
#define	HELLO 17
#define	THELLO 18
#define	TFULL 19
#define	ENTUSID 20
#define	LOGUID 21
#define	ENTUSIDM 22
#define	LOGUIDM 23
#define	UIDNOG 24
#define	LOGNOG 25
#define	ALRDON 26
#define	STRUKO 27
#define	METAKO 28
#define	ACCSUS 29
#define	ACCDEL 30
#define	LOKOUT 31
#define	NOKEY 32
#define	BBSOFF 33
#define	ENTPSW 34
#define	PSWNOG 35
#define	GREETINGS 36
#define	NEWGREET 37
#define	GPL 38
#define	SEEYA 39
#define	TIMEOUT 40
#else
#define	LOGIN_LONALRM 1
#define	LOGIN_TERMINAL 2
#define	LOGIN_METAB4 3
#define	LOGIN_METALG 4
#define	LOGIN_UNIXUID 5
#define	LOGIN_DESCR 6
#define	LOGIN_LDOWN 7
#define	LOGIN_XLATEM 8
#define	LOGIN_XLATEE 9
#define	LOGIN_SANSI 10
#define	LOGIN_QANSI 11
#define	LOGIN_QANSIERR 12
#define	LOGIN_ASKLNG1 13
#define	LOGIN_ASKLNG2 14
#define	LOGIN_ASKLNG3 15
#define	LOGIN_ASKLNGR 16
#define	LOGIN_HELLO 17
#define	LOGIN_THELLO 18
#define	LOGIN_TFULL 19
#define	LOGIN_ENTUSID 20
#define	LOGIN_LOGUID 21
#define	LOGIN_ENTUSIDM 22
#define	LOGIN_LOGUIDM 23
#define	LOGIN_UIDNOG 24
#define	LOGIN_LOGNOG 25
#define	LOGIN_ALRDON 26
#define	LOGIN_STRUKO 27
#define	LOGIN_METAKO 28
#define	LOGIN_ACCSUS 29
#define	LOGIN_ACCDEL 30
#define	LOGIN_LOKOUT 31
#define	LOGIN_NOKEY 32
#define	LOGIN_BBSOFF 33
#define	LOGIN_ENTPSW 34
#define	LOGIN_PSWNOG 35
#define	LOGIN_GREETINGS 36
#define	LOGIN_NEWGREET 37
#define	LOGIN_GPL 38
#define	LOGIN_SEEYA 39
#define	LOGIN_TIMEOUT 40
#endif /* __LOGIN_UNAMBIGUOUS__ */
