#!/bin/bash
#
# This program is free software; you  can redistribute it and/or modify
# it under the terms of the GNU  General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
#
# This program is distributed  in the hope  that it will be useful, but
# WITHOUT    ANY WARRANTY;   without  even  the    implied warranty  of
# MERCHANTABILITY or  FITNESS FOR  A PARTICULAR  PURPOSE.   See the GNU
# General Public License for more details.
#                                                                      
# You  should have received a copy   of the GNU  General Public License
# along with    this program;  if   not, write  to  the   Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.            
#
# $Id$
#
# $Log$
# Revision 2.0  2004/09/13 19:44:53  alexios
# Stepped version to recover CVS repository after near-catastrophic disk
# crash.
#
# Revision 1.1  2004/05/21 20:07:01  alexios
# Initial revision.
#
#

#
# This script calls various modules with the -cleanup argument.
#

# Uncomment this for debugging (very verbose)
#set -x

# Read the global configuration

set -e
[ -r /etc/megistos.conf ] && . /etc/megistos.conf
set +e

# Sanity checks

if [ \
    x$BBSPREFIX = x -o \
    x$BBSCODE   = x -o \
    x$BBSOWNER  = x -o \
    x$BBSGROUP  = x -o \
    x$BBSUSER   = x -o \
    x$BBSUID    = x -o \
    x$BBSGID    = x -o \
    x$BBSUUID   = x \
   ]; then
    echo >&2 "$0: environment not properly set up."
    echo >&2 "Please do not call this script directly. Use megistos-admin instead."
    exit 1
fi

## Find out what our directory prefix is
#if [ x$BBSPREFIX = x ]; then
#    prefix=$0
#    basename=`basename $prefix`
#    prefix=`echo $prefix|sed 's/\/etc\/'$basename'$//'`
#    prefix=`(((echo $prefix|grep ^/) && echo $prefix) || echo $PWD/$prefix)`
#    prefix=`echo $prefix|sed 's/\/'$basename'$//'`
#    prefix=`(cd $prefix;pwd) 2>/dev/null|sed 's/\/\+etc\/*$//'`
#else
    prefix=$BBSPREFIX
#fi

# Paranoia check.

if [ ! -d $prefix/etc/module.rc ]; then
    echo >&2 "$0: paranoia check failed for prefix \"$prefix\", bailing out."
    exit 1
fi



# Stdout and stderr of all programs will be redirected to ${prefix}/log/cleanup.
# Up to three older cleanup logs are kept, renamed to ${prefix}/log/cleanup.O,
# cleanup.OO and cleanup.OOO. Additional information is kept in the
# cleanup audit trail file.

LOG=${prefix}/log/cleanup
AUDIT=${prefix}/log/audit.cleanup
PATH=$PATH:${prefix}/bin
LOCK=${prefix}/lock/LCK..CLEANUP


# Keep a safe copy of the sysvar file.
if file ${prefix}/etc/sysvar|grep -q "Megistos System Variable"; then
    chmod 660 ${prefix}/sysvar-backup >&/dev/null
    cp -f ${prefix}/etc/sysvar ${prefix}/etc/sysvar-backup >&/dev/null
    chmod 000 ${prefix}/sysvar-backup >&/dev/null
fi


# Lock the cleanup process in case someone runs two or more cleanups

if [ -r $LOCK -a -r /proc/`cat $LOCK` ]; then
    echo Cleanup not done, cleanup lock exists.
    exit 1
fi

#echo $$ >$LOCK

# Delete cleanup.OOO
rm -f $LOG.OOO 2>/dev/null

# 'Age' all cleanup logs
mv -f $LOG.OO $LOG.OOO 2>/dev/null
mv -f $LOG.O $LOG.OO 2>/dev/null
mv -f $LOG $LOG.O 2>/dev/null

>$LOG

#echo >>$AUDIT

# Ok... here goes!


# module cleanup stuff
for a in ${prefix}/etc/module.rc/cleanup/[0-9]*; do
    [ -x $a ] && $a --cleanup 2>>$LOG >>$LOG
done

# End of cleanup
#rm -f $LOCK

# End of file.
