LEVEL2 {}

 „›é ¨¬Ÿ£åœ«˜   §¨æ©™˜© «à¤ demo users ©«¦
 €¤˜š¤à©«ã¨ ¦.

ENTRYKEY {Key needed to enter the bulletin reader: 0} N 0 129

SOPKEY {Key needed for privileged access to the bulletin reader: 128} N 0 129



 €¬«ã  œ§ ¢¦šã œ§ «¨â§œ  ã ˜§˜š¦¨œçœ  ©«¦¬ª co-ops ¡˜ 
 club-ops «¤ §¨æ©Ÿœ©, ˜­˜å¨œ© ¡˜  œ¤£â¨à© «à¤
 bulletins «¦¬ club «¦¬ª.

FLAXES {Full bulletin access granted to CO-OPS} E CO-OPS CLUB-OP PRIVILEGED




 ‹œ ˜¬«ã «¤ £œ«˜™¢«ã œ¤œ¨š¦§¦ £â¤, ¡áŸœ œ ©˜šàšã
 á¨Ÿ¨¦¬ ¡˜«˜š¨á­œ«˜  ©«¦ audit trail.

AUDINS {Record bulletin insertions in the Audit Trail? YES} B

 ‹œ ˜¬«ã «¤ £œ«˜™¢«ã œ¤œ¨š¦§¦ £â¤, ¡áŸœ › ˜š¨˜­ã
 á¨Ÿ¨¦¬ ¡˜«˜š¨á­œ«˜  ©«¦ audit trail.

AUDDEL {Record bulletin deletions in the Audit Trail? YES} B

 ‹œ ˜¬«ã «¤ £œ«˜™¢«ã œ¤œ¨š¦§¦ £â¤, ¡áŸœ œ¤£â¨à©
 (edit) á¨Ÿ¨¦¬ ¡˜«˜š¨á­œ«˜  ©«¦ audit trail.

AUDEDT {Record bulletin editing in the Audit Trail? YES} B

 ‹œ ˜¬«ã «¤ £œ«˜™¢«ã œ¤œ¨š¦§¦ £â¤, ¡áŸœ ˜¤áš¤à©
 á¨Ÿ¨¦¬ ¡˜«˜š¨á­œ«˜  ©«¦ audit trail.

AUDRD {Record bulletin reads in the Audit Trail? YES} B


 €¬«ã  œ§ ¢¦šã ¨¬Ÿ£åœ  «¤ default œ§ ¢¦šã æ«˜¤, ¡˜«á
 «¤ › á¨¡œ ˜ «ª ˜¤å®¤œ¬©ª á¨Ÿ¨à¤, ¦ ®¨ã©«ª œ¨à«á«˜ 
 ˜¤ Ÿâ¢œ  ¤˜ › ˜™á©œ  â¤˜ á¨Ÿ¨¦. €¤ ¦ ®¨ã©«ª § â©œ  ˜-
 §¢éª Enter, Ÿ˜  ©®ç©œ  ˜¬«ã  ¨çŸ£ ©.

ASKDEF {Default ASKREAD answer while scanning YES} B

 €¬«ã  œ§ ¢¦šã œ¢âš®œ  ˜¤ ¦ ›œå¡«ª Ÿ˜ œ£­˜¤åœ«˜ 
 ©«¤ › á¨¡œ ˜ «ª ˜¤å®¤œ¬©ª.

INDSEL {Scan Indicator Enabled: YES} B

 €¬«ã  œ§ ¢¦šã ¨¬Ÿ£åœ  «¤ «˜®ç««˜ «¦¬ "›œå¡«" «ª
 ˜¤å®¤œ¬©ª œ¤æª á¨Ÿ¨¦¬ («ª š¨˜££ãª §¦¬ "§œ¨ ©«¨â­œ«˜ "
 š ˜ ¤˜ ›œå¥œ  æ«   ˜¤å®¤œ¬© «¦¬ ˜¨®œå¦¬ ©¬¤œ®åœ«˜ .)
 ‹§¦¨œå«œ ¤˜ ›é©œ«œ « £âª ˜§æ 1 àª 500, £œ 1 ¤˜ œå¤˜  
 £œš˜¢ç«œ¨ «˜®ç««˜, ¡˜  500  £ ¡¨æ«œ¨.  ˜¨ Ÿ£æª
 ˜¤« §¨¦©à§œçœ  ˜¨ Ÿ£æ š¨˜££é¤ «à¤ á¨Ÿ¨à¤ §¦¬
 œ¨œ¬¤¦ç¤«˜ .

INDSPD {Scan Indicator animation speed 100} N 1 500


 €¬«ã  œ§ ¢¦šã ¨¬Ÿ£åœ  «¤ default ˜§á¤«© ©«¤ œ¨é-
 «© "Ÿâ¢œ«œ ¤˜ œ ©ášœ«œ «¦ á¨Ÿ¨¦", ¡˜«á «¤ › á¨¡œ ˜
 «ª ˜¬«æ£˜«ª œ ©˜šàšãª. «˜¤ ¦ ®¨ã©«ª § âœ  Enter,
 ˜¬«ã  ˜§á¤«© Ÿ˜ œ§œ¥œ¨šáœ«˜ .

AINSDEF {Default answer to ASKINS question YES} B




LEVEL3 {}

DNLDESC {€¨Ÿ¨¦ ˜§æ «¦ €¤˜š¤à©«ã¨ ¦} S 50 Description for downloads



MENU {[2J[0m[47;1;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;30;47m¿ [40m
[47;1;37m ³  [0;47;30m                 €¤˜š¤à©«ã¨ ¦ €¨Ÿ¨à¤                   [0;47;30m³ [40m
[47;1;37m ³  [0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ  [0;47;30m³ [40m
[47;1;37m ³  [0;31;47mH[30melp . . . . . . . . . . . . . .  ‚œ¤ ¡âª ¢¨¦­¦¨åœª  [30m³ [40m
[47;1;37m ³  [0;31;47mL[30mist Bulletins  . . . . . . . . . .  ‰˜«á¢¦š¦ª á¨Ÿ¨à¤  [30m³ [40m
[47;1;37m ³  [0;31;47mF[30mull List  . . . . . . . . . . . . . ¢ã¨ª ¡˜«á¢¦š¦ª  [30m³ [40m
[47;1;37m ³  [0;31;47mR[30mead Bulletin . . . . . . . . . . . . €¤áš¤à© A¨Ÿ¨¦¬  [30m³ [40m
[47;1;37m ³  [0;31;47mD[30mownload Bulletin  . . . . . . . . . . .  Šã¯ €¨Ÿ¨¦¬  [30m³ [40m
[47;1;37m ³  [0;31;47mK[30meyword Scan  . . . . . . . . . . . . €¤œç¨œ© €¨Ÿ¨¦¬  [30m³ [40m
[47;1;37m ³  [0;31;47mS[30melect Club  . . . . . . . . . . . . . . „§ ¢¦šã Club  [30m³ [40m
[47;1;37m ³                                                         [0;47;30m³ [40m
[47;1;37m ³ [0;30;47me[31mX[30mit  . . . . . . . . . . . . . . . . . . . . . „¥¦›¦ª  [30m³ [40m
[47;1;37m À[0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0;1m

€¤˜š¤à©«ã¨ ¦ €¨Ÿ¨à¤
˜¨˜¡˜¢é ›é©«œ «¤ œ§ ¢¦šã ©˜ª: [0m} T Bulletins main menu


SHMENU {[0;1m
€¤˜š¤à©«ã¨ ¦ €¨Ÿ¨à¤
!Wƒé©«œ «¤ œ§ ¢¦šã ©˜ª ([33mH[37m,[33mL[37m,[33mF[37m,[33mR[37m,[33mD[37m,[33mK[37m,[33mS[37m,[33mX[37m š ˜ â¥¦›¦, ã [33m?[37m š ˜ «¦ £œ¤¦ç): !)[0m} T Bulletins short menu


ERRSEL {[0;1;31m
Š¬§á£˜ , ›œ¤ ¬§á¨®œ   œ§ ¢¦šã "%c".
[0;1m} T Invalid option


NOAXES {[0;1;31m
!JŠ¬§á£˜ , ›œ¤ â®œ«œ §¨æ©™˜© ©œ ˜¬«ã «¤ œ§ ¢¦šã.!)
[0;1;31m} T User has no access to chosen area





SMENU {[2J[0m[47;1;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;30;47m¿ [40m
[47;1;37m ³  [0;47;30m                 €¤˜š¤à©«ã¨ ¦ €¨Ÿ¨à¤                   [0;47;30m³ [40m
[47;1;37m ³  [0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ  [0;47;30m³ [40m
[47;1;37m ³  [0;31;47mH[30melp . . . . . . . . . . . . . .  ‚œ¤ ¡âª ¢¨¦­¦¨åœª  [30m³ [40m
[47;1;37m ³  [0;31;47mL[30mist Bulletins  . . . . . . . . . .  ‰˜«á¢¦š¦ª á¨Ÿ¨à¤  [30m³ [40m
[47;1;37m ³  [0;31;47mF[30mull List  . . . . . . . . . . . . . ¢ã¨ª ¡˜«á¢¦š¦ª  [30m³ [40m
[47;1;37m ³  [0;31;47mR[30mead Bulletin . . . . . . . . . . . . €¤áš¤à© A¨Ÿ¨¦¬  [30m³ [40m
[47;1;37m ³  [0;31;47mD[30mownload Bulletin  . . . . . . . . . . .  Šã¯ €¨Ÿ¨¦¬  [30m³ [40m
[47;1;37m ³  [0;31;47mK[30meyword Scan  . . . . . . . . . . . . €¤œç¨œ© €¨Ÿ¨¦¬  [30m³ [40m
[47;1;37m ³  [0;31;47mS[30melect Club  . . . . . . . . . . . . . . „§ ¢¦šã Club  [30m³ [40m
[47;1;37m ³                                                         [0;47;30m³ [40m
[47;1;37m ³  [0;31;47mI[30mnsert Bulletin . . . . . . . . . . . . . . Œâ¦ €¨Ÿ¨¦  [30m³ [40m
[47;1;37m ³  [0;31;47mP[30murge (delete) Bulletin  . . . . . .  ƒ ˜š¨˜­ã €¨Ÿ¨¦¬  [30m³ [40m
[47;1;37m ³  [0;31;47mE[30mdit Bulletin . . . . . .  „¤£â¨à© ©«¦ ®œåà¤ €¨Ÿ¨¦¬  [30m³ [40m
[47;1;37m ³  [0;31;47mA[30mutomatic Insertion  . . . . . . .  €¬«æ£˜« œ ©˜šàšã  [30m³ [40m
[47;1;37m ³                                                         [0;47;30m³ [40m
[47;1;37m ³ [0;30;47me[31mX[30mit  . . . . . . . . . . . . . . . . . . . . . „¥¦›¦ª  [30m³ [40m
[47;1;37m À[0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0;1m

€¤˜š¤à©«ã¨ ¦ €¨Ÿ¨à¤
˜¨˜¡˜¢é ›é©«œ «¤ œ§ ¢¦šã ©˜ª: [0m} T Bulletins main menu for privileged users



SSHMENU {[0;1m
ƒé©«œ œ§ ¢¦šã ([33mH[37m,[33mL[37m,[33mF[37m,[33mR[37m,[33mD[37m,[33mK[37m,[33mS[37m,[33mI[37m,[33mP[37m,[33mE[37m,[33mA[37m,[33mX[37m ã [33m?[37m š ˜ £œ¤¦ç): } T Bulletin menu (short form) for privileged users


LEAVE {[0;1m
!J„¥¦›¦ª ˜§æ «¦ €¤˜š¤à©«ã¨ ¦ €¨Ÿ¨à¤.!)
[0;1m} T Leaving the bulletin reader




CURSIG {[0;1;32m
!J¨å©¡œ©«œ ©«¦ club [37m%s[32m.!)[0;1m} T Bulletin menu addition when selecting from a SIG


ABOUT {[0;1m
!J’¦ €¤˜š¤à©«ã¨ ¦ §œ¨ â®œ  æ¢˜ «˜ á¨Ÿ¨˜ §¦¬ â®¦¬¤ ›£¦© œ¬Ÿœå àª «é¨˜ ©«¤
@BBS@. ’˜ á¨Ÿ¨˜ œå¤˜  «˜¥ ¤¦££â¤˜ ¡˜«á club ›£¦©åœ¬©ª ¡˜ 
£œ¨¦£¤å˜ œ ©˜šàšãª ¡˜  ©¬¤¦›œç¦¤«˜  ˜§æ «¦ æ¤¦£˜ «¦¬ ©¬šš¨˜­â˜ «¦¬ª ¡˜ 
£ ˜ ©ç¤«¦£ §œ¨ š¨˜­ã ã «å«¢¦. “§á¨®¦¬¤ ¦  œ¥ãª œ¤«¦¢âª:!)

!J‹œ «¤ œ¤«¦¢ã [33mR[37mead, £§¦¨œå«œ ¤˜ › ˜™á©œ«œ â¤˜ á¨Ÿ¨¦ ›å¤¦¤«˜ª
œå«œ «¦¤ ˜¨ Ÿ£æ «¦¬, œå«œ «¦ æ¤¦£˜ ˜¨®œå¦¬ «¦¬. ‘£œ é©«œ æ«  ¦ ˜¨ Ÿ£æª œ¤æª
á¨Ÿ¨¦¬ £§¦¨œå ¤˜ ˜¢¢á¥œ  £œ «¦¤ ¡˜ ¨æ. † œ¤«¦¢ã [33mL[37mist ©˜ª ›å¤œ  «¦¤
¡˜«á¢¦š¦ «à¤ á¨Ÿ¨à¤ «ª ™á©ª. ‹œ [33mF[37mull List §˜å¨¤œ«œ §¢ã¨
¡˜«á¢¦š¦ §¦¬ §œ¨ â®œ  œ§ §¢â¦¤ §¢¨¦­¦¨åœª š ˜ ¡áŸœ á¨Ÿ¨¦ (æ§àª ˜¨ Ÿ£æ
˜¤˜š¤é©œà¤).!)

!J‹§¦¨œå«œ ¤˜ §œ¨ ¦¨å©œ«œ «˜ á¨Ÿ¨˜ §¦¬ Ÿ˜ ©˜ª ›œå®¤œ  «¦ ©ç©«£˜
£œ «¤ œ§ ¢¦šã [33mS[37melect club. ƒå¤¦¤«˜ª â¤˜ æ¤¦£˜ club, ©«¦ œ¥ãª Ÿ˜
™¢â§œ«œ £æ¤¦ «˜ á¨Ÿ¨˜ ˜¬«¦ç «¦¬ club. €¬«ã œå¤˜   ¡˜«á ©¬¤Ÿã¡ ¡˜«á©«˜©
æ«˜¤ £§˜å¤œ«˜  ©«¦ €¤˜š¤à©«ã¨ ¦ ˜§æ « ª „ › ¡âª œ¨ ¦®âª.!)

!J‹§¦¨œå«œ, «â¢¦ª, ¤˜ ˜¤ ®¤œç©œ«œ «˜ á¨Ÿ¨˜ š ˜ £å˜ ã §œ¨ ©©æ«œ¨œª ¢â¥œ ª
¡¢œ › á. † ˜¤å®¤œ¬© ®¨© £¦§¦ œå ­à¤« ¡ã ˜¤˜ã«©, â«©  Ÿœà¨œå å› œª « ª
¢â¥œ ª "Acro", "á¡¨¦" ¡˜  "€¡¨¦". „®œ«œ «¤ ›¬¤˜«æ««˜ ¤˜ ©«˜£˜«ã©œ«œ «¤
˜¤˜ã«© ˜¤á §á©˜ ©« š£ã, § â¦¤«˜ª [33mEnter[37m ã [33mCtrl-C[37m.!)

[0;1m} T About Bulletin Reader



SCASK {[0;1m
!Wƒé©«œ «¦ æ¤¦£˜ «¦¬ ¤â¦¬ Club ã [33m?[37m š ˜ ¡˜«á¢¦š¦, ã [33mEnter[37m š ˜ æ¢˜ «˜ Clubs:!)[0m } T Select new club, which club?


SCERR {[0;1;31m
!J‘¬šš¤é£, ›œ¤ ¬§á¨®œ  «â«¦ ¦ Club.!)
[0;1m} T Select new club, club does not exist


BLTCAN {[0;1;31m
!J† › ˜› ¡˜©å˜ «œ¨£˜«å©«¡œ.!)
[0;1m} T Cancelled



NBCLUB {[0;1m
Œâ¦ á¨Ÿ¨¦ š ˜ «¦ ˜¤˜š¤à©«ã¨ ¦.

!J‘œ §¦ ¦ club ¬§á¨®œ  «¦ á¨Ÿ¨¦; (E[[33mX[37m]it=â¥¦›¦ª, [33m?[37m=¡˜«á¢¦š¦ª):!) } T Add new Bulletin, ask for club name


DEFLTS {[Enter=%s][0m } T Default value for NBCLUB question


NBRCLB {[0;1;31m
!Jƒœ¤ ¬§á¨®œ  «¦ club "[37m%s[31m". ˜¤˜›¦¡ £á©«œ...!)
[0;1m} T Add new Bulletin, unknown club


NBCLUB1 {[0;1;32m
Œâ¦ á¨Ÿ¨¦ ©«¦ club [37m@CLUB@[32m.
[0;1m} T Add new Bulletin with club name already known


NBMSGN {[0;1m
!Wƒé©«œ «¦¤ ˜¨ Ÿ£æ £¤ç£˜«¦ª æ§¦¬ ™¨å©¡œ«˜  «¦ á¨Ÿ¨¦, ã [33mEnter[37m š ˜
¤˜ ©«œå¢œ«œ «é¨˜ «¦ á¨Ÿ¨¦ àª ˜¨®œå¦:!)[0m } T Add new Bulletin, Ask for message number


NBMSGNR {[0;1;31m
!JŠ¬§á£˜ , «¦ £ã¤¬£˜ [37m%s/%d[31m ›œ¤ ¬§á¨®œ .!)
[0;1m} T Add new Bulletin, message not found


NBFNXS {[0;1;31m
!J’¦ á¨Ÿ¨¦ [37m%s[31m ¬§á¨®œ  ã› ©«¦ ˜¤˜š¤à©«ã¨ ¦ «¦¬ club [37m%s[31m,
£œ ˜¨ Ÿ£æ [37m%d[31m.!)
[0;1m} T Add new Bulletin, article already exists


NBFNEX {[0;1;31m
!J’¦ ˜¨®œå¦ [37m%s[31m ¬§á¨®œ  ã› ©«¦ directory «¦¬ club [37m%s[31m.
† ˜¤« š¨˜­ã «¦¬ á¨Ÿ¨¦¬ ›œ¤ £§¦¨œå ¤˜ šå¤œ .
˜¨˜¡˜¢é œ ›¦§¦ ã©«œ «¦¤ •œ ¨ ©«ã ‘¬©«ã£˜«¦ª š ˜ ¤˜ ©™ã©œ  ã ¤˜
£œ«¦¤¦£á©œ  «¦ ¬§á¨®¦¤ ˜¨®œå¦.!)
[0;1m} T Add new Bulletin panic: target file already exists


NBIO {[0;1;31m
!J‘¬¤˜¤«ãŸ¡œ ¢áŸ¦ª ˜¤áš¤à©ª ¡˜«á «¤ ­æ¨«à© «¦¬ £¤ç£˜«¦ª [37m%s/%d[31m. ˜¨˜¡˜¢é
œ ›¦§¦ ã©«œ «¦¤ ®œ ¨ ©«ã ©¬©«ã£˜«¦ª š ˜ ˜¬«æ «¦ £ã¤¬£˜.!)
[0;1m} T Add new Bulletin, I/O error


NBATTR {[0;1;31m
!J’¦ ©¬¤££â¤¦ ˜¨®œå¦ «¦¬ £¤ç£˜«¦ª [37m%s/%d[31m ¢œå§œ !
˜¨˜¡˜¢é œ ›¦§¦ ã©«œ «¦¤ ®œ ¨ ©«ã ©¬©«ã£˜«¦ª š ˜ ˜¬«æ «¦ £ã¤¬£˜.!)
[0;1m} T Add new Bulletin, Unable to stat attachment


NBBODR {[0;1;31m
!J’¦ £ã¤¬£˜ [37m%s/%d[31m ¢œå§œ !
˜¨˜¡˜¢é œ ›¦§¦ ã©«œ «¦¤ ®œ ¨ ©«ã ©¬©«ã£˜«¦ª š ˜ ˜¬«æ «¦ £ã¤¬£˜.!)
[0;1m} T Add new Bulletin, Unable to stat message body


NBATT {[0;1m
!J’¦ £ã¤¬£˜ [32m%s/%d[37m â®œ  â¤˜ ©¬¤££â¤¦ ˜¨®œå¦ £œšâŸ¦¬ª [32m%d[37m bytes.!)

!J‹§¦¨œå«œ ¤˜ œ ©ášœ«œ ©«¦ €¤˜š¤à©«ã¨ ¦ œå«œ «¦ ©¬¤££â¤¦ ˜¨®œå¦ œå«œ «¦ ©é£˜ «¦¬ £¤ç£˜«¦ª.!)
[0;1m} T Add new Bulletin, size of message and attachment


NBBODATT {[0;1m
!W¦ ¦ «£ã£˜ «¦¬ £¤ç£˜«¦ª Ÿâ¢œ«œ ¤˜ œ ©ášœ«œ àª á¨Ÿ¨¦;!)

[[33mA[37m]attachment . . . .  ’¦ ©¬¤££â¤¦ ˜¨®œå¦
[[33mB[37m]ody . . . . . . . ’¦ ©é£˜ «¦¬ £¤ç£˜«¦ª

!W˜¨˜¡˜¢é ›é©«œ «¤ œ§ ¢¦šã ©˜ª ([33mA[37m,[33mB[37m,[33mX[37m š ˜ ˜¡ç¨à© ã [33m?[37m š ˜ ™¦ãŸœ ˜): } T Add new Bulletin, ask what to insert (body or attachment)


NBBAD {[Enter=[33m%c[37m][0m!) } T Add new Bulletin, default value for NBBODATT


NBBAR {[0;1;31m
!Jƒœ¤ ¬§á¨®œ  ˜¬«ã  œ§ ¢¦šã.!)
[0;1m} T Add new Bulletin, bad response to NBBODATT


NBCPR {[0;1;31m
!J‘¬¤˜¤«ãŸ¡œ ¢áŸ¦ª œšš¨˜­ãª/˜¤áš¤à©ª ¡˜«á «¤ œ ©˜šàšã «¦¬ á¨Ÿ¨¦¬. ˜¨˜¡˜¢é œ ›¦§¦ ã©«œ
«¦¤ ®œ ¨ ©«ã ©¬©«ã£˜«¦ª š ˜ ˜¬«æ «¦ á¨Ÿ¨¦.!)
[0;1m} T Add new Bulletin, I/O error while linking/copying.



BLTUPL2M {[0;1;33m
!J‘«œå¢˜«œ §á¤à ˜§æ â¤˜ ˜¨®œå¦. Š˜£™á¤œ«˜  ¬§'æ¯¤ £æ¤¦ «¦ ˜¨®œå¦ §¦¬
â­«˜©œ §¨é«¦.!)
[0;1m} T Add new Bulletin, more than one file uploaded 




NBUSER {[0;1m
!W¦ ¦ª œå¤˜  ¦ ©¬šš¨˜­â˜ª «¦¬ á¨Ÿ¨¦¬; (e[[33mX[37m]it=â¥¦›¦ª) } T Add new Bulletin, ask for author


NBUSERD {[Enter=%s]:!)[0m } T Add new Bulletin, default author


NBRRUID {[31;1m
‘¬šš¤é£, ›œ¤ ¬§á¨®œ  ®¨ã©«ª £œ ˜¬«æ «¦ ¯œ¬›é¤¬£¦.
} T Add new Bulletin rebuff unknown user id


NBCPER2 {[0;1;31m
!J† ˜¤«åš¨˜­ã «¦¬ ˜¨®œå¦¬ [37m%s[31m ©«¦ €¤˜š¤à©«ã¨ ¦ ›œ¤ ã«˜¤ œ­ ¡«ã.
˜¨˜¡˜¢é œ ›¦§¦ ã©«œ «¦¤ •œ ¨ ©«ã ‘¬©«ã£˜«¦ª.!)
[0;1m} T Add new Bulletin copy panic: cannot write to file.


NBDSCR {[0;1m
!J˜¨˜¡˜¢é ›é©«œ £ ˜ ©ç¤«¦£ §œ¨ š¨˜­ã «¦¬ á¨Ÿ¨¦¬ (£â®¨  63 ®˜¨˜¡«ã¨œª).
ƒé©«œ [33mX[37m š ˜ â¥¦›¦.!)

ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
} T Add new Bulletin, ask for description


NBERR {[0;1;31m
!J‘¬¤˜¤«ãŸ¡œ ¢áŸ¦ª ¡˜«á «¤ œ ©˜šàšã «¦¬ á¨Ÿ¨¦¬ ©«¤ ™á© ›œ›¦£â¤à¤. ˜¨˜¡˜¢é
œ ›¦§¦ ã©«œ «¦¤ ®œ ¨ ©«ã ©¬©«ã£˜«¦ª š ˜ ˜¬«æ «¦ £ã¤¬£˜.!)
[0;1m} T Add new Bulletin, database error


NBINFO {[0;1m
[0;36mÛÛ  [1mŒâ¦ €¨Ÿ¨¦  [46m[K[0;1m

!J’¦ §˜¨˜¡á«à á¨Ÿ¨¦ §¨¦©«âŸ¡œ ©«¦ ˜¤˜š¤à©«ã¨ ¦.!)

€¨Ÿ¨¦ . . . . . . [32m%d[37m
€¨®œå¦ . . . . .  [32m%s[37m
’å«¢¦ª  . . . . . !i!W[32m%s[37m!)
!0lClub . . . . . .  [32m%s[37m
‘¬šš¨˜­â˜ª  . . . [32m%s[37m

[46m[K[0;1m
} T Add new Bulletin added bulletin info


BLTNOBT {[0;1;31m
!Jƒœ¤ ¬§á¨®¦¬¤ á¨Ÿ¨˜ ©«¦ €¤˜š¤à©«ã¨ ¦.!)
[0;1m} T No articles in the database


CLBNOBT {[0;1;31m
!Jƒœ¤ ¬§á¨®¦¬¤ á¨Ÿ¨˜ ©«¦ club [37m/%s[31m.!)
[0;1m} T No articles in the selected club


BLTLSHD {[0;1m
!W‰˜«á¢¦š¦ª á¨Ÿ¨à¤ «¦¬ club [32m%s[37m.!)

[33m€¨Ÿ¨¦  ‘¬šš¨˜­â˜ª  œ¨ š¨˜­ã
[37m!FÄ
[0m} T Bulletin List Header


BLTLST {!W%4d   %-10s  !i%s!)
[0m!0l} T Bulletin List single line


LSTEND {[0;1m!FÄ

[0;1m} T Bulletin List footer


BLTLSHD2 {[0;1m
ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
³[0mŞ[7mClub: %-15s[0mİ[1m³
ÃÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÁÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄ¿
³ [33m#[37m ³[33m€¨®œå¦[37m      ³[33m€§¦©«¦¢â˜ª[37m³[33mœ¨ š¨˜­ã[37m                             ³[33m€¤˜š¤é©œ ª[37m³
ÃÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÂÄÄÄÄ´
} T Bulletin Full List Header


BLTLST2 {[0;1m³[0m%3d[1m³[0m%-12s[1m³[0m%-10s[1m³[0m%-44.44s[1m³[0m%4d[1m³
} T Bulletin Full List single line


LSTEND2 {[0;1mÀÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÙ
} T Bulletin Full List footer


LSTCAN {[0;1;31m!)
!0l!W’œ¨£˜« ©£æª ¡˜«˜¢æš¦¬.!)
[0;1m}  T Bulletin list/full list, aborted


READBLT {[0;1m
!W€¤áš¤à© á¨Ÿ¨¦¬.!)

!Wƒé©«œ «¦¤ ˜¨ Ÿ£æ «¦¬ á¨Ÿ¨¦¬ §¦¬ Ÿâ¢œ«œ ¤˜ ›œå«œ (›é©«œ [33m?[37m š ˜ ¡˜«á¢¦š¦, [33mX[37m š ˜ â¥¦›¦);!) [0m} T Read Bulletin, what filename?


DNLBLT {[0;1m
!WŠã¯ á¨Ÿ¨¦¬.!)

!Wƒé©«œ «¦¤ ˜¨ Ÿ£æ «¦¬ á¨Ÿ¨¦¬ §¦¬ Ÿâ¢œ«œ ¤˜ ¢á™œ«œ (›é©«œ [33m?[37m š ˜ ¡˜«á¢¦š¦, [33mX[37m š ˜ â¥¦›¦);!) [0m} T Download Bulletin, what filename?


UNKBLT {[0;1;31m
!JŠ¬§á£˜ , «¦ á¨Ÿ¨¦ ˜¬«æ ›œ¤ £§¦¨œå ¤˜ ™¨œŸœå.!)
[0;1m} T Unable to locate bulletin


UNKBLTC {[0;1;31m
!JŠ¬§á£˜ , «¦ á¨Ÿ¨¦ ˜¬«æ ›œ¤ £§¦¨œå ¤˜ ™¨œŸœå ©«¦ club [37m/%s[31m.!)
[0;1m} T Unable to locate bulletin in selected club


BLTAMB {[0;1;33m
!J’¦ æ¤¦£˜ ˜¨®œå¦¬ "[37m%s[33m" ˜¤ã¡œ  ©œ §á¤à ˜§æ â¤˜ á¨Ÿ¨¦.
˜¨˜¡˜¢é ®¨© £¦§¦ ã©«œ «¦¤ ˜¨ Ÿ£æ «¦¬ á¨Ÿ¨¦¬ š ˜ ¤˜ œ§ ¢â¥œ«œ «¦ á¨Ÿ¨¦ ˜¬«æ.
€¡¦¢¦¬Ÿœå â¤˜ª ¡˜«á¢¦š¦ª «à¤ á¨Ÿ¨à¤ §¦¬ £¦ ¨á¦¤«˜  «¦ å› ¦ æ¤¦£˜ ˜¨®œå¦¬:!)
[0;1m} T Ambiguous bulletin filename


AMBLSHD {[0;1m
[33m€¨Ÿ¨¦  Club             œ¨ š¨˜­ã
[37m!FÄ
[0m} T Ambiguous Bulletin List Header


AMBLST {!W%4d   %-15s  !i%s!)
[0m!0l} T Ambiguous Bulletin List single line


AMBEND {[0;1m!FÄ

[0;1m} T Ambiguous Bulletin List footer


BLTINFO {[0;1m
€¨Ÿ¨¦ . . . . . . [32m%d[37m
€¨®œå¦ . . . . .  [32m%s[37m
’å«¢¦ª  . . . . . !i!W[32m%s[37m!)
!0lClub . . . . . .  [32m%s[37m
‘¬šš¨˜­â˜ª  . . . [32m%s[37m
ƒ ˜™á©«¡œ . . .  [32m%d ­¦¨%s
[0;1m} T Bulletin information


TIMESSNG {á} T Times, singular
TIMESPLR {âª} T Times, plural


PANIC1 {[0;1m
!W[31;5mÛÛ[0;1;31m  ¨¦©¦®ã: !i’¦ ˜¨®œå¦ %s ›œ¤ £§æ¨œ©œ ¤˜ ˜¤¦ ®Ÿœå
š ˜ ˜¤áš¤à©. ˜¨˜¡˜¢¦ç£œ œ ›¦§¦ ã©«œ «¦¤ •œ ¨ ©«ã ‘¬©«ã£˜«¦ª.!)
!0l[0;1m
} T Read Bulletin panic: file open error


BLTHDR {[0;1m
!C‘•†
!)
!J’¦ §˜¨æ¤ á¨Ÿ¨¦ ¢ã­Ÿ¡œ ˜§æ «¤ @BBS@. „§ «¨â§œ«˜   ˜¤áš¤à©ã «¦¬, œ­'æ©¦¤
 §˜¨¦ç©˜ §˜¨˜«ã¨© ›œ¤ ˜­˜ ¨œŸœå. ’¦ á¨Ÿ¨¦ ˜§¦«œ¢œå §¤œ¬£˜« ¡ã  › ¦¡«©å˜
«ª @BBS@ ©ç£­à¤˜ £œ «¦ ¡˜«˜©«˜« ¡æ/©ç£™˜© £œ «¦ ®¨ã©«. (c) @BBS@!)

!F-

[0m} T Read Bulletin bulletin header / copyright notice


ENDBLT {[0;1m
!F-

[32m’â¢¦ª £œ«á›¦©ª «¦¬ á¨Ÿ¨¦¬.
[0;1m} T Read Bulletin end of bulletin transmission


ABORT {[31;1m
ƒ ˜¡æ§¡œ ˜§æ «¦¤ ®¨ã©«!
[0;1m} T Process aborted by the user


SRCHBLT {[0;1m
!J€¤å®¤œ¬© á¨Ÿ¨¦¬ š ˜ ¢â¥œ ª-¡¢œ › á.!)

!Wƒé©«œ £å˜ ã §œ¨ ©©æ«œ¨œª ¢â¥œ ª-¡¢œ › á, [33mX[37m š ˜ â¥¦›¦, ã
[33m?[37m š ˜ ™¦ãŸœ ˜:[0m } T Scan Bulletins for what keywords?


SRCHHLP {[0;1m
!J† œ§ ¢¦šã ˜¬«ã ˜¤ ®¤œçœ  æ¢˜ «˜ á¨Ÿ¨˜ ©«˜£˜«é¤«˜ª £æ¤¦ ©œ ˜¬«á
§¦¬ §œ¨ â®¦¬¤ « ª ¢â¥œ ª ¡¢œ › á §¦¬ ¦¨å©˜«œ. ‚ ˜ ¤˜ ¦¨å©œ«œ £æ¤¦ £å˜ ¢â¥
¡¢œ ›å, ˜§¢éª ›é©«œ « ¢â¥ ¡˜  §˜«ã©«œ [33mEnter[37m. ‚ ˜ §œ¨ ©©æ«œ¨œª ¢â¥œ ª
¡¢œ › á, › ˜®à¨ã©«œ « ª £œ ¡œ¤á. €¤ â®œ«œ £ ˜ ©ç¤Ÿœ« ¢â¥ ¡¢œ ›å §¦¬ §œ¨ â®œ 
¡œ¤á, ®¨© £¦§¦ ã©«œ £ ˜ §˜ç¢˜ ([33m-[37m):  §˜ç¢˜ ©£˜å¤œ  ¡œ¤æ, ©£œå¦ ©«å¥ª,
©ç£™¦¢¦ ã ¡˜  «˜ «¨å˜ £˜å.!)

!J† â¨œ¬¤˜ œå¤˜  ­à¤« ¡ã, é©«œ ¤˜ ¥œ§œ¨¤á ˜¤¦¨Ÿ¦š¨˜­åœª ¡˜  á¢¢˜ ¢áŸ.
ƒ¢˜›ã,  ¢â¥ ¡¢œ ›å "Sysop" «˜ ¨ áœ  £œ ¦§¦ ˜›ã§¦«œ ˜§æ « ª ¢â¥œ ª "©¬©¦§",
"©¬©à§", "‘“‘", "SYSOP".!)

!J‚ ˜ §˜¨á›œ š£˜, ˜¤ ›é©œ«œ àª ¢â¥œ ª ¡¢œ ›å˜ "demo system" š ˜ ¤˜ ˜¤ ®¤œç©œ«œ
«˜ á¨Ÿ¨˜ £œ « ª ¢â¥œ ª "demo" ¡˜  "system", «¦ ˜§¦«â¢œ©£˜ Ÿ˜ ©¬£§œ¨ ¢á™œ 
œ¥å©¦¬ «¤ ­¨á© "drugs [32msystem[37matically [32mdemo[37mlish your brain".!)

!J‚ ˜ ¤˜ ©¬š¡œ¡¨ £œ¤¦§¦ ã©œ«œ «¤ ˜¤å®¤œ¬© ©œ "DH Demo System",
›é©«œ "DH-demo-system". €¢¢á œå¤˜  ¡˜¢ç«œ¨˜ ¤˜ â®œ«œ £œ¨ ¡á á¨Ÿ¨˜ §˜¨˜§á¤à
§˜¨á ¤˜ ®á©œ«œ ¡á§¦ ˜ á¢¢˜ ©£˜¤« ¡á!!)
[0;1m} T Keyword scan, help on searching


KSCAN1 {[0;1m
!W€¤ ®¤œçà «¦ ˜¤˜š¤à©«ã¨ ¦ š ˜ «¤ ¢â¥ ¡¢œ ›å "[32m%s[37m"...
 â©«œ [33mEnter[37m š ˜ «œ¨£˜« ©£æ «ª › ˜› ¡˜©å˜ª.!)
[0;1m} T Keyword scan, start scanning (single keyword)


KSCAN2 {[0;1m
!W€¤ ®¤œçà «¦ ˜¤˜š¤à©«ã¨ ¦ š ˜ « ª ¢â¥œ ª ¡¢œ › á "[32m%s[37m"} T Keyword scan, start scanning (multiple keyword)


KSCAN3 {, "[32m%s[37m"} T Keyword scan, keyword


KSCAN4 { ¡˜  "[32m%s[37m"...  â©«œ [33mEnter[37m š ˜ «œ¨£˜« ©£æ «ª
› ˜› ¡˜©å˜ª.!)
[0;1m} T Keyword scan, last keyword


CURAREA {[0;1;32m

!W„¨œ¬¤˜ «¦¬ club [37m%s[32m...!)

[0;1m} T Scanning current club

CURBLT {!W[0;1m€¤ ®¤œçà «¦ á¨Ÿ¨¦ [33m%d. %s[0;1m...!) } T Scanning current Bulletin

SCNENDBLT {
} T Finished scanning current bulletin


KSIND0 {[s [0;30;40m[K[u} T Keyword scan, work indicator, begin

KSIND1 {[u[0m| %d[30m[K} T Keyword scan, work indicator, frame 1
KSIND2 {[u[0m/ %d[30m[K} T Keyword scan, work indicator, frame 2
KSIND3 {[u[0m- %d[30m[K} T Keyword scan, work indicator, frame 3
KSIND4 {[u[0m\ %d[30m[K} T Keyword scan, work indicator, frame 4
KSIND5 {[u[0m| %d[30m[K} T Keyword scan, work indicator, frame 5
KSIND6 {[u[0m/ %d[30m[K} T Keyword scan, work indicator, frame 6
KSIND7 {[u[0m- %d[30m[K} T Keyword scan, work indicator, frame 7
KSIND8 {[u[0m\ %d[30m[K} T Keyword scan, work indicator, frame 8

KSINDE {[u[0;1m[K} T Keyword scan, work indicator, end





SCANFND { [0;1;32m!W...™¨âŸ¡œ  ¢â¥ ¡¢œ ›å "[37m%s[32m"!!)
[0;1m} T Keyword found


PANIC2 {[0;1;31m

!J’¦ §˜¨˜§á¤à á¨Ÿ¨¦ ›œ¤ £§æ¨œ©œ ¤˜ ˜¤¦ ®Ÿœå š ˜ ˜¤áš¤à©.
˜¨˜¡˜¢¦ç£œ œ ›¦§¦ ã©«œ «¦¤ •œ ¨ ©«ã ‘¬©«ã£˜«¦ª š ˜ «¦ šœš¦¤æª.[37m!)

!J(‘¬¤œ®åà «¤ ˜¤å®¤œ¬©)!)

[0;1m} T Scan Bulletin panic: file open error


ASKREAD {[0;1m
!W‡â¢œ«œ ¤˜ › ˜™á©œ«œ ˜¬«æ «¦ á¨Ÿ¨¦
([[33mY[0;1m]es=¤˜  / [[33mN[0;1m]o=æ® );!) } T Read the scanned bulletin?


DEFLTC {[Enter=%c][0m } T Default value for ASKREAD/ASKINS questions



YNHUH {[0;1;31m
!J˜¨˜¡˜¢é ˜§˜¤«ã©«œ £œ [33mY[31m ã [33mN[31m, ã
[33mX[31m š ˜ «œ¨£˜« ©£æ «ª ˜¤å®¤œ¬©ª.!)
[0;1m} T Read scanned Bulletin rebuff invalid reply


SCNEND {[1;33m
’â¢¦ª ˜¤å®¤œ¬©ª.
} T End of Bulletin Scan


DELBLT {[0;1m
!Wƒ ˜š¨˜­ã á¨Ÿ¨¦¬.!)

!Wƒé©«œ ˜¨ Ÿ£æ ã æ¤¦£˜ ˜¨®œå¦¬ «¦¬ á¨Ÿ¨¦¬ §¦¬ Ÿâ¢œ«œ ¤˜ › ˜š¨á¯œ«œ (›é©«œ [33m?[37m š ˜ ¡˜«á¢¦š¦, [33mX[37m š ˜ â¥¦›¦);!) [0m} T Delete a Bulletin


DELNOAX {[0;1;31m
!J‘¬šš¤é£, ›œ¤ â®œ«œ › ¡˜åà£˜ ¤˜ › ˜š¨á¯œ«œ á¨Ÿ¨˜ «¦¬ club %s.!)
[0;1m}


ASKDEL {[0;1m
!W‡â¢œ«œ ¤˜ › ˜š¨á¯œ«œ ˜¬«æ «¦ á¨Ÿ¨¦ ˜§æ «¦ €¤˜š¤à©«ã¨ ¦;
([[33mY[37m]es=¤˜å / [[33mN[37m]o=æ® ) [0m!)} T Delete the bulletin?


ASKDELR {[0;1;31m
!J˜¨˜¡˜¢é ›é©«œ [33mY[31m ã [33mN[31m.!)
[0;1m} T Bad response to ASKDEL


ABODEL {[0;1;32m
!J’¦ á¨Ÿ¨¦ [37m%d[32m ›œ¤ ˜­˜ ¨âŸ¡œ ˜§æ «¦ €¤˜š¤à©«ã¨ ¦.!)
[0;1m} T Deletion aborted


CONFLICT {[0;1;31m
!J‰á§¦ ¦ª ®¨ã©«ª › ˜™áœ  ˜¬«æ «¦ á¨Ÿ¨¦.
˜¨˜¡˜¢¦ç£œ ¥˜¤˜›¦¡ £á©«œ ©œ ¢åš¦.!)
[0;1m} T Bulletin collision: user working on bulletin


DBDELOK {[32;1m
!J’¦ á¨Ÿ¨¦ ˜­˜ ¨âŸ¡œ ˜§æ «¦ €¤˜š¤à©«ã¨ ¦.!)
[0;1m} T Delete a Bulletin bulletin killed ok


DBERR {[31;1m
!J† › ˜š¨˜­ã «¦¬ á¨Ÿ¨¦¬ ›œ¤ ã«˜¤ œ­ ¡«ã.
˜¨˜¡˜¢é œ ›¦§¦ ã©«œ «¦¤ •œ ¨ ©«ã ‘¬©«ã£˜«¦ª š ˜ «¦ ¢áŸ¦ª.!)
[0;1m} T Delete a Bulletin panic: cannot delete file


EDTBLT {[0;1m
!J€¢¢˜šã ©«¦ ®œåà¤ á¨Ÿ¨¦¬ «¦¬ ˜¤˜š¤à©«¨å¦¬.!)

!W˜¨˜¡˜¢é ›é©«œ «¦ æ¤¦£˜ ã «¦¤ ˜¨ Ÿ£æ «¦¬ á¨Ÿ¨¦¬, ã [33mX[37m š ˜
â¥¦›¦:[0m!) } T Edit what Bulletin?


EDTNOAX {[0;1;31m
!J‘¬šš¤é£, ›œ¤ â®œ«œ › ¡˜åà£˜ ¤˜ £œ«˜™á¢¢œ«œ á¨Ÿ¨˜ «¦¬ club %s.!)
[0;1m}


EBLTVT {[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [34m€¢¢˜šã ©«¦ ®œåà¤ á¨Ÿ¨¦¬[0;30;47m ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  ‘¬šš¨˜­â˜ª   [1;44;37m@10;10;0s[0;1;47;37m                                               ³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  ’å«¢¦ª       [1;44;37m@64;55;0s[0;1;47;37m  ³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  Ctrl-R š ˜ ™¦ãŸœ ˜              [0;1;42;33m@14;"OK"b[0;47;30mÜ    [0;1;41;33m@14;"€¡¬¨¦"b[0;47;30mÜ  [0;1;47;37m³ [0m
[30;47m ³                                   ßßßßßßßßßßßßßßßß     ßßßßßßßßßßßßßßßß  [0;1;47;37m³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m} T Edit bulletin, visual template


EDITOK {[0;1;32m
!J’˜ ©«¦ ®œå˜ «¦¬ á¨Ÿ¨¦¬ œ¤£œ¨éŸ¡˜¤ œ§ «¬®éª:!)
[0;1m} T Edit bulletin, bulletin updated ok.


EDITERR {[0;1;31m
!J† œ¤£â¨à© «¦¬ á¨Ÿ¨¦¬ ›œ¤ ã«˜¤ œ­ ¡«ã. ˜¨˜¡˜¢é œ ›¦§¦ ã©«œ «¦¤
•œ ¨ ©«ã ‘¬©«ã£˜«¦ª š ˜ «¦ šœš¦¤æª.!)
[0;1m} T Edit bulletin, unable to update bulletin.


EBLTLT {[2J[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [34m€¢¢˜šã ©«¦ ®œåà¤ á¨Ÿ¨¦¬[0;30;47m ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³                                                                          [1;37m³ [0m
[30;47m ³ [31m1[30m. ‘¬šš¨˜­â˜ª . . [34m@10;10;0s[0;1;47;37m                                             ³ [0m
[30;47m ³                                                                          [1;37m³ [0m
[30;47m ³ [31m2[30m. ’å«¢¦ª  . . .  [34m@64;54;0s[0;1;47;37m ³ [0m
[30;47m ³                                                                          [1;37m³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0;1m
} T Modify message, linear template


EDTAUT {[0;1m
!Jƒé©«œ «¦ ¤â¦ ©¬šš¨˜­â˜ «¦¬ á¨Ÿ¨¦¬.!)
[0;1m} T Edit bulletin, enter author (linear template)


EDTTTL {[0;1m
!Jƒé©«œ «¦¤ ¤â¦ «å«¢¦ «¦¬ á¨Ÿ¨¦¬ (£â®¨  64 ®˜¨˜¡«ã¨œª)!)
[0;1m} T Edit bulletin, enter title


EDTAUTHR {[0;1;31m
!J’¦ ¯œ¬›é¤¬£¦ «¦¬ ©¬šš¨˜­â˜ ("[37m%s[31m") ›œ¤
¬§á¨®œ  ©«¤ ™á©. ˜¨˜¡˜¢é ¥˜¤˜›¦¡ £á©«œ.!)
[0;1m} T Edit bulletin, author does not exist


EDTAUTH {[0;1m
!Wƒé©«œ «¦ ¯œ¬›é¤¬£¦ «¦¬ ©¬šš¨˜­â˜, ã
[33mX[37m š ˜ ˜¡ç¨à©:!)[0m } T Edit bulletin, reenter author


AUTOINS {[0;1m
!J† ˜¬«æ£˜« œ ©˜šàšã ™¨å©¡œ  æ¢˜ «˜ á¨Ÿ¨˜ œ¤æª club §¦¬ â®¦¬¤ ©¬¤££â¤˜
˜¨®œå˜ ¡˜  ©˜ª §¨¦©­â¨œ  «˜ ©¬¤££â¤˜ ˜¨®œå˜ š ˜ œ ©˜šàšã ©«¦ ˜¤˜š¤à©«ã¨ ¦.!)
[0;1m} T Automatic insertion, information

AISIG {[0;1m
!Wƒé©«œ «¦ æ¤¦£˜ «¦¬ club §¦¬ Ÿ˜ ˜¤ ®¤œ¬Ÿœå,
[33m?[37m š ˜ ¡˜«á¢¦š¦, ã [33mX[37m š ˜ â¥¦›¦:!) } T Auto insertion asking for area name


AIDEF {[Enter=%s][0m } T Auto insertion, default area name


AISIGR {[0;1;31m
!J’¦ club "[37m%s[31m" ›œ¤ ¬§á¨®œ . ˜¤˜›¦¡ £á©«œ.!)
[0;1m} T Auto insertion, club does not exist


AIDIRR {[0;1;31m
!J’¦ club [37m%s[31m ›œ¤ £§æ¨œ©œ ¤˜ ˜¤¦ ®Ÿœå. ˜¨˜¡˜¢é œ ›¦§¦ ã©«œ «¦¤
•œ ¨ ©«ã ‘¬©«ã£˜«¦ª š ˜ « ª ©¬¤Ÿã¡œª §¦¬ ¦›ãš©˜¤ ©'˜¬«æ «¦ ¢áŸ¦ª.!)
[0;1m} T Auto insertion, failed to open the club's attachment directory


BGNAINS {[0;1;32m
!J€¤ ®¤œçà «¦ club [37m%s[32m š ˜ á¨Ÿ¨˜...!)
[0;1m} T Auto insertion scanning club


NOFILES {[0;1;31m
!JŠ¬§á£˜ , ›œ¤ ™¨âŸ¡˜¤ £¤ç£˜«˜ £œ ©¬¤££â¤˜ ˜¨®œå˜.!)
[0;1m} T Auto insertion no files found


FNDFILE {[0;1m
€¨®œå¦ %s (%d %s).} T Auto insertion found a file


BYTESNG {byte} T 'byte', singular form
BYTEPLR {bytes} T 'bytes', plural form


ALREXS {[1;31m  “§á¨®œ  ã›.
} T Auto insertion bulletin already exists


MSGDEL {[1;31m  ’¦ £ã¤¬£˜ â®œ  › ˜š¨˜­œå.
} T Auto insertion message body has been deleted


AIINFO {[0;1;32m  ¨âŸ¡œ «¦ §˜¨˜¡á«à á¨Ÿ¨¦:

[0;1m} T Auto insertion, bulletin information


ASKINS {[0;1;37m
!WŒ˜ «¦ œ ©ášà; ([[33mY[37m]es=¤˜å / [[33mN[37m]o=æ® )!) } T Auto insertion ask insert article


ASKERR {[0;1;31m
!J˜¨˜¡˜¢é ˜§˜¤«ã©«œ £œ [33mY[31m ã [33mN[31m, ã
[33mX[31m š ˜ «œ¨£˜« ©£æ «ª ˜¬«æ£˜«ª œ ©˜šàšãª.!)
[0;1m} T Auto insertion, please respond with Y or N


AIOK {[0;1;32m
’¦ á¨Ÿ¨¦ §¨¦©«âŸ¡œ œ§ «¬®éª ©«¦ ˜¤˜š¤à©«ã¨ ¦.
[0;1m} T Auto insertion, bulletin inserted ok.


AIERR {[0;1;31m
† œ ©˜šàšã «¦¬ á¨Ÿ¨¦¬ ›œ¤ ã«˜¤ œ­ ¡«ã. ˜¨˜¡˜¢é œ ›¦§¦ ã©«œ
«¦¤ •œ ¨ ©«ã ‘¬©«ã£˜«¦ª š ˜ «¦ ¢áŸ¦ª.!)
[0;1m} T Auto insertion, error inserting bulletin


ENDAINS {[0;1;33m

’â¢¦ª «ª ˜¤å®¤œ¬©ª.
} T Auto insertion end



LANG {}

DNLDESC {Article/Bulletin} S 50 Description for downloads



MENU {[2J[0m[47;1;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;30;47m¿ [40m
[47;1;37m ³  [0;47;30m                      Bulletins                        [0;47;30m³ [40m
[47;1;37m ³  [0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ  [0;47;30m³ [40m
[47;1;37m ³  [0;31;47mH[30melp . . . . . . . . . . . . . .  General Information  [30m³ [40m
[47;1;37m ³  [0;31;47mL[30mist  . . . . . . .  Brief list of articles/bulletins  [30m³ [40m
[47;1;37m ³  [0;31;47mF[30mull List  . . . . . . . . Detailed list of bulletins  [30m³ [40m
[47;1;37m ³  [0;31;47mR[30mead Bulletin . . . . . . . . . . Read a bulletin now  [30m³ [40m
[47;1;37m ³  [0;31;47mD[30mownload Bulletin  . . . . . .  Read a bulletin later  [30m³ [40m
[47;1;37m ³  [0;31;47mK[30meyword Scan  . . . . . . . . . Search for a bulletin  [30m³ [40m
[47;1;37m ³  [0;31;47mS[30melect Club  . . . . .  Only see one Club's bulletins  [30m³ [40m
[47;1;37m ³                                                         [0;47;30m³ [40m
[47;1;37m ³ [0;30;47me[31mX[30mit  . . . . . . . . . . .  Leave the bulletin reader  [30m³ [40m
[47;1;37m À[0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0;1m

Bulletins
Please enter your choice: [0m} T Bulletins main menu


SHMENU {[0;1m
Bulletins
!WEnter your choice ([33mH[37m,[33mL[37m,[33mF[37m,[33mR[37m,[33mD[37m,[33mK[37m,[33mS[37m,[33mX[37m to exit, or [33m?[37m for the menu): !)[0m} T Bulletins short menu


ERRSEL {[0;1;31m
Sorry, option "%c" is not available.
[0;1m} T Invalid option


NOAXES {[0;1;31m
!JSorry, you don't have access to this area.!)
[0;1;31m} T User has no access to chosen area





SMENU {[2J[0m[47;1;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;30;47m¿ [40m
[47;1;37m ³  [0;47;30m                      Bulletins                        [0;47;30m³ [40m
[47;1;37m ³  [0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ  [0;47;30m³ [40m
[47;1;37m ³  [0;31;47mH[30melp . . . . . . . . . . . . . .  General Information  [30m³ [40m
[47;1;37m ³  [0;31;47mL[30mist  . . . . . . .  Brief list of articles/bulletins  [30m³ [40m
[47;1;37m ³  [0;31;47mF[30mull List  . . . . . . . . Detailed list of bulletins  [30m³ [40m
[47;1;37m ³  [0;31;47mR[30mead Bulletin . . . . . . . . . . Read a bulletin now  [30m³ [40m
[47;1;37m ³  [0;31;47mD[30mownload Bulletin  . . . . . .  Read a bulletin later  [30m³ [40m
[47;1;37m ³  [0;31;47mK[30meyword Scan  . . . . . . . . . Search for a bulletin  [30m³ [40m
[47;1;37m ³  [0;31;47mS[30melect Club  . . . . .  Only see one Club's bulletins  [30m³ [40m
[47;1;37m ³                                                         [0;47;30m³ [40m
[47;1;37m ³  [0;31;47mI[30mnsert Bulletin . . . . . . . . .  Add a new bulletin  [30m³ [40m
[47;1;37m ³  [0;31;47mP[30murge (delete) Bulletin  . . . . .  Delete a bulletin  [30m³ [40m
[47;1;37m ³  [0;31;47mE[30mdit Bulletin . . . . . . .  Change/update a bulletin  [30m³ [40m
[47;1;37m ³  [0;31;47mA[30mutomatic Insertion  . . . Auto-insert club bulletins  [30m³ [40m
[47;1;37m ³                                                         [0;47;30m³ [40m
[47;1;37m ³ [0;30;47me[31mX[30mit  . . . . . . . . . . .  Leave the bulletin reader  [30m³ [40m
[47;1;37m À[0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0;1m

Bulletins
Please enter your choice: [0m} T Bulletins main menu for privileged users



SSHMENU {[0;1m
Enter your choice ([33mH[37m,[33mL[37m,[33mF[37m,[33mR[37m,[33mD[37m,[33mK[37m,[33mS[37m,[33mI[37m,[33mP[37m,[33mE[37m,[33mA[37m,[33mX[37m or [33m?[37m for the menu): } T Bulletin menu (short form) for privileged users


LEAVE {[0;1m
!JLeaving the bulletin reader.!)
[0;1m} T Leaving the bulletin reader




CURSIG {[0;1;32m
!JYou're in club [37m%s[32m.!)[0;1m} T Bulletin menu addition when selecting from a SIG


ABOUT {[0;1m

!JThe Bulletin Reader is a depository for user-contributed articles, textual
information and similar material. It differs from the clubs in that this is
one-way communication (i.e. there can be no replies or discussions). Usually,
articles are inserted into the article/bulletin reader from the Clubs, where
they were originally written. This is a good way to create digests of
discussions, or to keep permanent records of good, informative material that
has appeared in the clubs.!)

!JArticles are ordered by their club and date of creation and are accompanied
by the author's name and a short title or description. You can use the
following commands:!)

!JEnter [33mR[37 to read an article. You'll be asked for either the
article's number, or its filename. Please note that article numbers may change
as new articles are inserted. The [33mL[37mist command provides a short
catalogue of @BBS@ articles. With the [33mF[37mull List command you get a
detailed list, including such things as the number of times an articles has
been read, etc.!)

!JYou can limit the number of articles shown by the system by focusing on a
club with the [33mS[37melect club command. Give the name of a @BBS@ club and
you'll only see that club's bulletins in the future. This is the default
condition when you jump to the Bulletin reader from within a Club.!)

!JFinally, you can search for articles by one or more keywords. If the search
takes too long, you can stop it by pressing [33mEnter[37m or [33mCtrl-C[37m.!)

[0;1m} T About Bulletin Reader



SCASK {[0;1m
!WENter the name of the new Club, [33m?[37m for a list, or [33mEnter[37m
for all Clubs:!)[0m } T Select new club, which club?


SCERR {[0;1;31m
!JSorry, this Club doesn't exist.!)
[0;1m} T Select new club, club does not exist


BLTCAN {[0;1;31m
!JProcess terminated.!)
[0;1m} T Cancelled



NBCLUB {[0;1m
Add a new article.

!JWhich club is it in? (E[[33mX[37m]it=exit, [33m?[37m=list):!) } T Add new Bulletin, ask for club name


DEFLTS {[Enter=%s][0m } T Default value for NBCLUB question


NBRCLB {[0;1;31m
!JThere's no club "[37m%s[31m". Please try again...!)
[0;1m} T Add new Bulletin, unknown club


NBCLUB1 {[0;1;32m
Add a new article from club [37m@CLUB@[32m.
[0;1m} T Add new Bulletin with club name already known


NBMSGN {[0;1m
!WEnter the article's message number, or [33mEnter[37m to
upload a new article now:!)[0m } T Add new Bulletin, Ask for message number


NBMSGNR {[0;1;31m
!JSorry, message [37m%s/%d[31m doesn't exist.!)
[0;1m} T Add new Bulletin, message not found


NBFNXS {[0;1;31m
!JArticle [37m%s[31m already exists in club [37m%s[31m.
It's article number [37m%d[31m.!)
[0;1m} T Add new Bulletin, article already exists


NBFNEX {[0;1;31m
!JFIle [37m%s[31m already exists in the directory of club [37m%s[31m.
We can't copy the article there.
Please let the Sysop know so they can remove or rename the existing file.!)
[0;1m} T Add new Bulletin panic: target file already exists


NBIO {[0;1;31m
!JI/O error while reading message [37m%s/%d[31m. Please let the
Sysop know about this message.!)
[0;1m} T Add new Bulletin, I/O error


NBATTR {[0;1;31m
!JThe file attached to message [37m%s/%d[31m is missing!
Please let the Sysop know about this message.!)
[0;1m} T Add new Bulletin, Unable to stat attachment


NBBODR {[0;1;31m
!JMessage [37m%s/%d[31m is missing!
Please let the Sysop know about this message.!)
[0;1m} T Add new Bulletin, Unable to stat message body


NBATT {[0;1m
!JMessage [32m%s/%d[37m has a [32m%d[37m byte-long attached file.!)

!JYou can add to the Bulletin reader either the attached file or the message
body.!)
[0;1m} T Add new Bulletin, size of message and attachment


NBBODATT {[0;1m
!WWhat part of the message do you want to add?!)

[[33mA[37m]attachment
[[33mB[37m]ody

!WPlease make your choice ([33mA[37m,[33mB[37m,[33mX[37m to cancel, or [33m?[37m
for help): } T Add new Bulletin, ask what to insert (body or attachment)


NBBAD {[Enter=[33m%c[37m][0m!) } T Add new Bulletin, default value for NBBODATT


NBBAR {[0;1;31m
!JSorry, this choice isn't available.!)
[0;1m} T Add new Bulletin, bad response to NBBODATT


NBCPR {[0;1;31m
!JI/O error while inserting the article. Please notify the Sysop about this
article.!)
[0;1m} T Add new Bulletin, I/O error while linking/copying.



BLTUPL2M {[0;1;33m
!JYou've uploaded more than one file. We'll only use the first one.!)
[0;1m} T Add new Bulletin, more than one file uploaded 




NBUSER {[0;1m
!What's the username of the article's author? ([[33mX[37m] to cancel) } T Add new Bulletin, ask for author


NBUSERD {[Enter=%s]:!)[0m } T Add new Bulletin, default author


NBRRUID {[31;1m
Sorry, no such user exists.
} T Add new Bulletin rebuff unknown user id


NBCPER2 {[0;1;31m
!JThere was an error while copying file [37m%s[31m to the bulletin
reader. Please notify the Sysop about this.!)
[0;1m} T Add new Bulletin copy panic: cannot write to file.


NBDSCR {[0;1m
!JPlease enter a short description of the article (up to 63 characters).
Enter [33mX[37m to cancel.!)

ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
} T Add new Bulletin, ask for description


NBERR {[0;1;31m
!JThere was an error while adding this article to the database. Please
notify the Sysop.!)
[0;1m} T Add new Bulletin, database error


NBINFO {[0;1m
[0;36mÛÛ  [1mNew Article  [46m[K[0;1m

!JThe following article was added to the system.!)

Article . . . . . [32m%d[37m
Filename . . . .  [32m%s[37m
Title . . . . . . !i!W[32m%s[37m!)
!0lClub . . . . . .  [32m%s[37m
Author  . . . . . [32m%s[37m

[46m[K[0;1m
} T Add new Bulletin added bulletin info


BLTNOBT {[0;1;31m
!JThere are no articles in the Bulletin reader right now.!)
[0;1m} T No articles in the database


CLBNOBT {[0;1;31m
!JThere are no articles in club [37m/%s[31m right now.!)
[0;1m} T No articles in the selected club


BLTLSHD {[0;1m
!WBulletin/article list for club [32m%s[37m.!)

[33m   #   Author      Description
[37m!FÄ
[0m} T Bulletin List Header


BLTLST {!W%4d   %-10s  !i%s!)
[0m!0l} T Bulletin List single line


LSTEND {[0;1m!FÄ

[0;1m} T Bulletin List footer


BLTLSHD2 {[0;1m
ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
³[0mŞ[7mClub: %-15s[0mİ[1m³
ÃÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÁÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄ¿
³ [33m#[37m ³[33mFile  [37m      ³[33mAuthor    [37m³[33mDescription[37m                           ³[33mTimes read[37m³
ÃÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÂÄÄÄÄ´
} T Bulletin Full List Header


BLTLST2 {[0;1m³[0m%3d[1m³[0m%-12s[1m³[0m%-10s[1m³[0m%-44.44s[1m³[0m%4d[1m³
} T Bulletin Full List single line


LSTEND2 {[0;1mÀÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÙ
} T Bulletin Full List footer


LSTCAN {[0;1;31m!)
!0l!WListing terminated.!)
[0;1m}  T Bulletin list/full list, aborted


READBLT {[0;1m
!WRead an article.!)

!WPlease enter the bulletin's number or filename (enter [33m?[37m for a list, [33mX[37m to exit);!) [0m} T Read Bulletin, what filename?


DNLBLT {[0;1m
!WDownload a bulletin.!)

!WPlease enter the bulletin number of filename (enter [33m?[37m for a list, [33mX[37m to exit);!) [0m} T Download Bulletin, what filename?


UNKBLT {[0;1;31m
!JSorry, this article isn't in the database.!)
[0;1m} T Unable to locate bulletin


UNKBLTC {[0;1;31m
!JSorry, this article isn't in club [37m/%s[31m.!)
[0;1m} T Unable to locate bulletin in selected club


BLTAMB {[0;1;33m
!JThe filename "[37m%s[33m" belongs to more than one bulletin (in different clubs).
Please use the bulletin's number to select it. Here's a list of bulletins sharing this filename:!)
[0;1m} T Ambiguous bulletin filename


AMBLSHD {[0;1m
[33m   #   Club             Description
[37m!FÄ
[0m} T Ambiguous Bulletin List Header


AMBLST {!W%4d   %-15s  !i%s!)
[0m!0l} T Ambiguous Bulletin List single line


AMBEND {[0;1m!FÄ

[0;1m} T Ambiguous Bulletin List footer


BLTINFO {[0;1m
Bulletin  . . . . [32m%d[37m
Filename . . . .  [32m%s[37m
Title . . . . . . !i!W[32m%s[37m!)
!0lClub . . . . . .  [32m%s[37m
Author  . . . . . [32m%s[37m
Read . . . . . .  [32m%d tim%s
[0;1m} T Bulletin information


TIMESSNG {e} T Times, singular
TIMESPLR {es} T Times, plural


PANIC1 {[0;1m
!W[31;5mÛÛ[0;1;31m  Caution: !iFile %s couldn't be opened.
Please notify the Sysop about this event.!)
!0l[0;1m
} T Read Bulletin panic: file open error


BLTHDR {[0;1m
!CATTENTION
!)
!JThis bulletin was downloaded from @BBS@ and is copyright (C) by @BBS@.
By reading the text you agree to accept all rules of the system pertaining
to ownership and copyright of material. You can obtain a copy of the rules
governing this system by entering /RULES. You are reminded that holding an
account with this system is equivalent to accepting these rules.!)

!F-

[0m} T Read Bulletin bulletin header / copyright notice


ENDBLT {[0;1m
!F-

[32mEnd of bulletin transmission.
[0;1m} T Read Bulletin end of bulletin transmission


ABORT {[31;1m
Interrupted by the user!
[0;1m} T Process aborted by the user


SRCHBLT {[0;1m
!JSearch bulletins by keywords.!)

!WEnter one or more keywords, [33mX[37m to exit, or
[33m?[37m for help:[0m } T Scan Bulletins for what keywords?


SRCHHLP {[0;1m

!JThis command scans all articles and displays those that contain
the keywords you specify. Enter any number of keywords separated by
spaces, then press [33mEnter[37m. If one of your "keywords" includes
spaces or punctuation, substitute a dash ([33m-[37m). For example, 
"super-duper" will match "super duper", "super/duper", but not
"super" and "duper" separated from each other.!)

!JAs another example, entering "demo system" to scan for bulletins
with the words "demo" and "system", the search will match the phrase
"drugs [32msystem[37matically [32mdemo[37mlish your brain".!)

!JTo make the search more specific by looking for the phrase "DH Demo System",
you could enter "DH-demo-system". It's better to get a few more matches than
you need, though, than to miss some important matches!!)
[0;1m} T Keyword scan, help on searching


KSCAN1 {[0;1m
!WScanning the bulletins for the keyword "[32m%s[37m"...
Press [33mEnter[37m to abort the search.!)
[0;1m} T Keyword scan, start scanning (single keyword)


KSCAN2 {[0;1m
!W€¤ ®¤œçà «¦ ˜¤˜š¤à©«ã¨ ¦ š ˜ « ª ¢â¥œ ª ¡¢œ › á "[32m%s[37m"} T Keyword scan, start scanning (multiple keyword)


KSCAN3 {, "[32m%s[37m"} T Keyword scan, keyword


KSCAN4 { ¡˜  "[32m%s[37m"...  â©«œ [33mEnter[37m š ˜ «œ¨£˜« ©£æ «ª
› ˜› ¡˜©å˜ª.!)
[0;1m} T Keyword scan, last keyword


CURAREA {[0;1;32m

!W„¨œ¬¤˜ «¦¬ club [37m%s[32m...!)

[0;1m} T Scanning current club

CURBLT {!W[0;1m€¤ ®¤œçà «¦ á¨Ÿ¨¦ [33m%d. %s[0;1m...!) } T Scanning current Bulletin

SCNENDBLT {
} T Finished scanning current bulletin


KSIND0 {[s [0;30;40m[K[u} T Keyword scan, work indicator, begin

KSIND1 {[u[0m| %d[30m[K} T Keyword scan, work indicator, frame 1
KSIND2 {[u[0m/ %d[30m[K} T Keyword scan, work indicator, frame 2
KSIND3 {[u[0m- %d[30m[K} T Keyword scan, work indicator, frame 3
KSIND4 {[u[0m\ %d[30m[K} T Keyword scan, work indicator, frame 4
KSIND5 {[u[0m| %d[30m[K} T Keyword scan, work indicator, frame 5
KSIND6 {[u[0m/ %d[30m[K} T Keyword scan, work indicator, frame 6
KSIND7 {[u[0m- %d[30m[K} T Keyword scan, work indicator, frame 7
KSIND8 {[u[0m\ %d[30m[K} T Keyword scan, work indicator, frame 8

KSINDE {[u[0;1m[K} T Keyword scan, work indicator, end





SCANFND { [0;1;32m!W...keyword "[37m%s[32m" found!!)
[0;1m} T Keyword found


PANIC2 {[0;1;31m

!JThere was an I/O error while opening the article.
Please notify the Sysop about this event.[37m!)

!J(Will carry on scanning)!)

[0;1m} T Scan Bulletin panic: file open error


ASKREAD {[0;1m
!WWould you like to read this article
([[33mY[0;1m]es / [[33mN[0;1m]o);!) } T Read the scanned bulletin?


DEFLTC {[Enter=%c][0m } T Default value for ASKREAD/ASKINS questions



YNHUH {[0;1;31m
!JPlease answer with [33mY[31m or [33mN[31m, or
[33mX[31m to abort the search.!)
[0;1m} T Read scanned Bulletin rebuff invalid reply


SCNEND {[1;33m
End of search.
} T End of Bulletin Scan


DELBLT {[0;1m
!WDelete an article.!)

!WPlease enter the number or filename of the article to delete (enter [33m?[37m
for a list, [33mX[37m to exit);!) [0m} T Delete a Bulletin


DELNOAX {[0;1;31m
!JSorry, you don't have permission to delete articles from club %s.!)
[0;1m}


ASKDEL {[0;1m
!WWould you like to permanently delete this article?
([[33mY[37m]es / [[33mN[37m]o) [0m!)} T Delete the bulletin?


ASKDELR {[0;1;31m
!JPlease enter [33mY[31m or [33mN[31m.!)
[0;1m} T Bad response to ASKDEL


ABODEL {[0;1;32m
!JArticle [37m%d[32m was NOT deleted.!)
[0;1m} T Deletion aborted


CONFLICT {[0;1;31m
!JA user is currently accessing this article. Please try again later.!)
[0;1m} T Bulletin collision: user working on bulletin


DBDELOK {[32;1m
!JThe article has been permanently removed.!)
[0;1m} T Delete a Bulletin bulletin killed ok


DBERR {[31;1m
!JAn I/O error prevented deletion of this article.
Please notify the Sysop about this event.!)
[0;1m} T Delete a Bulletin panic: cannot delete file


EDTBLT {[0;1m
!JModify an article.!)

!WPlease enter article number of filename to modify, or [33mX[37m to
abort:[0m!) } T Edit what Bulletin?


EDTNOAX {[0;1;31m
!JSorry, you don't have permission to modify articles in club %s.!)
[0;1m}


EBLTVT {[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [34mModify an article[0;30;47m ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  Author   [1;44;37m@10;10;0s[0;1;47;37m                                               ³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  Title    [1;44;37m@64;55;0s[0;1;47;37m      ³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  Ctrl-R for help                 [0;1;42;33m@14;"OK"b[0;47;30mÜ    [0;1;41;33m@14;"Cancel"b[0;47;30mÜ  [0;1;47;37m³ [0m
[30;47m ³                                   ßßßßßßßßßßßßßßßß     ßßßßßßßßßßßßßßßß  [0;1;47;37m³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m} T Edit bulletin, visual template


EDITOK {[0;1;32m
!JArticle modified successfully:!)
[0;1m} T Edit bulletin, bulletin updated ok.


EDITERR {[0;1;31m
!JAn I/O error prevented us from updating article. Please
notify the Sysop about this event.!)
[0;1m} T Edit bulletin, unable to update bulletin.


EBLTLT {[2J[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [34mModify an article[0;30;47m ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³                                                                          [1;37m³ [0m
[30;47m ³ [31m1[30m. Author . . . . [34m@10;10;0s[0;1;47;37m                                             ³ [0m
[30;47m ³                                                                          [1;37m³ [0m
[30;47m ³ [31m2[30m. Title . . . .  [34m@64;54;0s[0;1;47;37m ³ [0m
[30;47m ³                                                                          [1;37m³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0;1m
} T Modify message, linear template


EDTAUT {[0;1m
!JPlease enter the updated user ID of this article's author.!)
[0;1m} T Edit bulletin, enter author (linear template)


EDTTTL {[0;1m
!JEnter the new title of the article (up to 64 characters)!)
[0;1m} T Edit bulletin, enter title


EDTAUTHR {[0;1;31m
!JUser "[37m%s[31m" does not exist on @BBS@.
Please try again.!)
[0;1m} T Edit bulletin, author does not exist


EDTAUTH {[0;1m
!WEnter the author's user ID, or
[33mX[37m to cancel:!)[0m } T Edit bulletin, reenter author


AUTOINS {[0;1m
!JAutomatic insertion finds club messages with attached files and offers
the attached files for insertion as bulletins or articles.!)
[0;1m} T Automatic insertion, information

AISIG {[0;1m
!WPlease enter the name of the club to scan,
[33m?[37m for a list, or [33mX[37m to exit:!) } T Auto insertion asking for area name


AIDEF {[Enter=%s][0m } T Auto insertion, default area name


AISIGR {[0;1;31m
!JClub "[37m%s[31m" does not exist. Please try again.!)
[0;1m} T Auto insertion, club does not exist


AIDIRR {[0;1;31m
!JClub [37m%s[31m could not be opened. Please notify the Sysop about
this event.!)
[0;1m} T Auto insertion, failed to open the club's attachment directory


BGNAINS {[0;1;32m
!JScanning club [37m%s[32m for articles...!)
[0;1m} T Auto insertion scanning club


NOFILES {[0;1;31m
!JSorry, there were no messages with attached files.!)
[0;1m} T Auto insertion no files found


FNDFILE {[0;1m
File %s (%d %s).} T Auto insertion found a file


BYTESNG {byte} T 'byte', singular form
BYTEPLR {bytes} T 'bytes', plural form


ALREXS {[1;31m  Already exists.
} T Auto insertion bulletin already exists


MSGDEL {[1;31m  The message has been deleted.
} T Auto insertion message body has been deleted


AIINFO {[0;1;32m  Found article:

[0;1m} T Auto insertion, bulletin information


ASKINS {[0;1;37m
!WInsert it? ([[33mY[37m]es / [[33mN[37m]o)!) } T Auto insertion ask insert article


ASKERR {[0;1;31m
!JPlease answer [33mY[31m or [33mN[31m, or
[33mX[31m to abort the aumatic insertion process.!)
[0;1m} T Auto insertion, please respond with Y or N


AIOK {[0;1;32m
The article was successfully inserted to the database.
[0;1m} T Auto insertion, bulletin inserted ok.


AIERR {[0;1;31m
An I/O error prevented us from adding the article. Please notify
the Sysop about this error.!)
[0;1m} T Auto insertion, error inserting bulletin


ENDAINS {[0;1;33m

End of scan.
} T Auto insertion end




LANGEND {}
