#!/bin/bash
#
# DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER
# DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER
# DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER
#
# THIS FILE  R E M O V E S  (DELETES) ALL FILES PASSED AS ARGUMENTS
# B E W A R E ! ! !   N O   W A R N I N G S   G I V E N ! ! !
#
# $Id$
#
# $Log$
# Revision 2.0  2004/09/13 19:44:54  alexios
# Stepped version to recover CVS repository after near-catastrophic disk
# crash.
#
#


# Security measure: This script will only run for BBS users. Please
# do not remove this constraint. You won't like it, I promise.

if [ -e ${PREFIX}/etc/online/$USERID ]; then
    ${PREFIX}/bin/protocols/listdownload -dfiMrw $*
    \rm -f $*
fi

# End of file.
