#!/bin/bash
#
# This program is free software; you  can redistribute it and/or modify
# it under the terms of the GNU  General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
#
# This program is distributed  in the hope  that it will be useful, but
# WITHOUT    ANY WARRANTY;   without  even  the    implied warranty  of
# MERCHANTABILITY or  FITNESS FOR  A PARTICULAR  PURPOSE.   See the GNU
# General Public License for more details.
#                                                                      
# You  should have received a copy   of the GNU  General Public License
# along with    this program;  if   not, write  to  the   Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.            
#
# $Id: bbsdeluser,v 2.0 2004/09/13 19:44:53 alexios Exp $
#
# $Log: bbsdeluser,v $
# Revision 2.0  2004/09/13 19:44:53  alexios
# Stepped version to recover CVS repository after near-catastrophic disk
# crash.
#
# Revision 1.1  2004/05/22 19:28:01  alexios
# Initial revision.
#

#
# This script calls various modules with the -cleanup argument.
#

# CAUTION CAUTION CAUTION CAUTION
#
# THIS SCRIPT DELETES A USER. USE WITH CARE.
# YOU HAVE BEEN WARNED. OOGAH.
# THE USER MUST *NOT* BE ON-LINE AT THE TIME OF DELETION.
# ONLY THE SUPER-USER MAY RUN OR ALTER THIS SCRIPT.

set -x
VICTIM=$1
victim=`echo $VICTIM | tr "[A-Z]" "[a-z]"`

dir=/bbs/data

# module user deletion stuff
for a in ${PREFIX}/etc/module.rc/userdel/[0-9]*; do
    [ -x $a ] && $a --userdel $VICTIM
done


#if [ ."$VICTIM" != ."" ]; then
#	/sbin/userdel $victim >&/dev/null ||    # Remove user's unix account
#	/sbin/deluser $victim >&/dev/null ||    # Try to use system's script
#	/bin/userdel $victim >&/dev/null ||     # Otherwise, if ALL else
#	/sbin/deluser $victim >&/dev/null ||	# fails, try our own compiled
#        userdel $victim >&/dev/null ||		# version of userdel.
#	deluser $victim >&/dev/null
#fi


# End of file.
