LEVEL2 {}

DEFATT {Default action for inclusion of attachments? NO} E NO YES ASK

DEFREQ {Default action for requested files? YES} E NO YES ASK

DEFHDR {Include full headers for messages by default? YES} B

OMCEML {EMail} S 16 Area name for email

ALLNAM {ALL} S 25 Name for 'All' recipients

UPDQSC {Update last read quickscan pointers after packet download? YES} B

USEPASS {Use password field for storing longer message subjects? YES} B

FIXETA {If using GREEKQWK, translate lower case accented eta? YES} B

ETAXLT {Character to translate lower case accented eta to: n} C

PRGIND {Use progress indicator while building packets? YES} B



LEVEL3 {}

ADMNAM {‘«â¢ ¦ª •˜£æ›¨˜¡˜ª, Sysop} S 60 Sysop's name as stored in CONTROL.DAT


OMMENU {[2J[0m[47;1;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;30;47m¿ [40m
[47;1;37m ³  [0;47;30m           ¨¦« £ã©œ ª †¢œ¡«¨¦¤ ¡¦ç «˜®¬›¨¦£œå¦¬ ¡˜  Clubs           [0;47;30m  ³ [40m
[47;1;37m ³  [0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ  [0;47;30m³ [40m
[47;1;37m ³                                                                         [0;47;30m³ [40m
[47;1;37m ³  [0;31;47mC[30mlubs included in packet  . . .  Clubs §¦¬ §œ¨ ¢˜£™á¤¦¤«˜  ©«¦ §˜¡â«¦  [30m³ [40m
[47;1;37m ³  [0;31;47mS[30metup preferences  . . . . . . . . . . . . . . .  çŸ£ © §¨¦« £ã©œà¤  [30m³ [40m
[47;1;37m ³                                                                         [0;47;30m³ [40m
[47;1;37m ³ [0;30;47me[31mX[30mit  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . „¥¦›¦ª  [30m³ [40m
[47;1;37m À[0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0;1m

çŸ£ © §¨¦« £ã©œà¤ †¢œ¡«¨¦¤ ¡¦ç «˜®¬›¨¦£œå¦¬ ¡˜  Clubs
˜¨˜¡˜¢é ›é©«œ «¤ œ§ ¢¦šã ©˜ª: [0m} T Setup, menu footer


OMSHORT {[0;1m
!Wƒé©«œ «¤ œ§ ¢¦šã ©˜ª, [33mX[37m š ˜ â¥¦›¦ ã [33m?[37m š ˜ «¦ £œ¤¦ç: [0m!)} T Setup, short menu


OMERR {[0;1;31m
!JŠ¬§á£˜ , ›œ¤ ¬§á¨®œ   œ§ ¢¦šã "%c".!)
[0;1m} T Setup, wrong selection


OMVT {[0m[30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [34m¬Ÿ£å©œ ª ›£ ¦¬¨šå˜ª §˜¡â«¦¬ £¤¬£á«à¤[0;30;47m ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  ‘¬¤££â¤˜ ˜¨®œå˜ ©«¦ §˜¡â«¦;    [0;30;46m @16;"® |Œ˜ |‰˜«æ§ ¤ „¨é«©ª"l [0;47;30m  (Space š ˜ ˜¢¢˜šã)  [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  ’˜ ˜¨®œå˜ §¦¬ â®œ«œ «ã©œ ;    [0;30;46m @16;"® |Œ˜ |‰˜«æ§ ¤ „¨é«©ª"l [0;47;30m  (Space š ˜ ˜¢¢˜šã)  [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  ¢ã¨ª header ©«˜ £¤ç£˜«˜;     [0;30;46m [@"X "t] [0;47;30m               (Space š ˜ ˜¢¢˜šã)  [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  Ctrl-O: ¦ãŸœ ˜ š ˜ §œ›å¦                                               [0;1;47;37m³ [0m
[30;47m ³  Ctrl-R: ¦ãŸœ ˜ š ˜ §¢ã¡«¨˜     [0;1;42;33m@14;"OK"b[0;47;30mÜ    [0;1;41;33m@14;"€¡¬¨¦"b[0;47;30mÜ  [0;1;47;37m³ [0m
[30;47m ³                                   ßßßßßßßßßßßßßßßß     ßßßßßßßßßßßßßßßß  [0;1;47;37m³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m} T Setup, Visual template


OMVTN {® } T Setup, string for NO
OMVTY {Œ˜ } T Setup, string for YES
OMVTA {‰˜«æ§ ¤ „¨é«©ª} T Setup, string for ASK



OMLT {[2J[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [34m¬Ÿ£å©œ ª ›£ ¦¬¨šå˜ª §˜¡â«¦¬ £¤¬£á«à¤[0;30;47m ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³                                                                          [1;37m³ [0m
[30;47m ³ [31m1[30m. ‘¬¤££â¤˜ ˜¨®œå˜ ©«¦ §˜¡â«¦ . . . . . . . . .  [34m@16;"® |Œ˜ |‰˜«æ§ ¤ „¨é«©ª"l[0;1;47;37m       ³ [0m
[30;47m ³                                                                          [1;37m³ [0m
[30;47m ³ [31m2[30m. ¨æš¨˜££˜ ˜§¦©¬£§åœ©ª . . . . . . . . . . . . [34m@16;"® |Œ˜ |‰˜«æ§ ¤ „¨é«©ª"l[0;1;47;37m       ³ [0m
[30;47m ³                                                                          [1;37m³ [0m
[30;47m ³ [31m3[30m. ¢ã¨ª header ©«˜ £¤ç£˜«˜  . . . . . . . . .  [34m@"X "t[0;1;47;37m                    ³ [0m
[30;47m ³                                                                          [1;37m³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0;1m
} T Setup QWK, Linear template


OMLTATT {[0;1m
!J‰á§¦ ˜ ˜§æ «˜ £¤ç£˜«˜ «¦¬ †¢œ¡«¨¦¤ ¡¦ç ’˜®¬›¨¦£œå¦¬ ¡˜  «à¤ Clubs â®¦¬¤
©¬¤££â¤˜ ˜¨®œå˜, «˜ ¦§¦å˜ «¦ ©ç©«£˜ ©˜ª §¨¦«¨â§œ  ¤˜ ¢á™œ«œ æ«˜¤ œå©«œ
on-line. €¬«ã  œ§ ¢¦šã ©˜ª ›å¤œ  «¤ œ¬¡˜ ¨å˜ ¤˜ ˜§¦­˜©å©œ«œ «  Ÿ˜ ¡á¤œ«œ £œ
«¬®æ¤ ©¬¤££â¤˜ ˜¨®œå˜. ‹§¦¨¦ç£œ ¤˜ £¤ «˜ œ ©áš¦¬£œ ¡˜Ÿæ¢¦¬ ©«¦ §˜¡â«¦ ©˜ª
(£§¦¨œå«œ ˜¨šæ«œ¨˜ ¤˜ «˜ «ã©œ«œ ˜§æ «¦¤ Mailer), ã ¤˜ œ ©áš¦¬£œ æ¢˜ «˜ ˜¨®œå˜.
‹§¦¨œå«œ œ§å©ª ¤˜ «ã©œ«œ ˜§æ «¦ ©ç©«£˜ ¤˜ ©˜ª ¨à«ã©œ  ˜¤ Ÿâ¢œ«œ ¤˜
œ ©ášœ«œ ¡áŸœ ˜¨®œå¦ ¥œ®à¨ ©«á, æ«˜¤ ›£ ¦¬¨šœå«œ «¦ §˜¡â«¦ £¤¬£á«à¤ ©˜ª.!)

!J€¤ ›œ¤ £§¦¨œå«œ ¤˜ ˜§¦­˜©å©œ«œ, ›é©«œ "æ® " œ›é. €¬«æ £œ é¤œ  «¦¤ æš¡¦ «à¤
§˜¡â«à¤ ©˜ª.!)
[0;1m} T Setup QWK, Linear template, set attachment policy


OMLTREQ {[0;1m
!J€¬«ã  œ§ ¢¦šã ›¦¬¢œçœ  æ§àª ¡˜   §¨¦š¦ç£œ¤, ˜¢¢á £§¦¨œå«œ ¤˜ œ¢âš¥œ«œ
«¤ ©¬£§œ¨ ­¦¨á «¦¬ Mailer §¨¦ª «˜ ˜¨®œå˜ §¦¬ â®œ«œ «ã©œ  £â©à «¦¬ off-line
reader ©˜ª (§œ¨ ©©æ«œ¨œª §¢¨¦­¦¨åœª š ˜ « ª ˜ «ã©œ ª ˜¨®œåà¤ ©« ª ¦›šåœª
®¨ã©ª «¦¬ Mailer).!)

!J€¤ ›œ¤ £§¦¨œå«œ ¤˜ ˜§¦­˜©å©œ«œ, ›é©«œ "¤˜ " œ›é. ‚œ¤ ¡á, æ«˜¤ «á«œ â¤˜
˜¨®œå¦, Ÿâ¢œ«œ ¤˜ «¦ ¢á™œ«œ ©«¦ œ§æ£œ¤¦ §˜¡â«¦ ©˜ª.!)
[0;1m} T Setup QWK, Linear template, set request policy


OMLTHDR {[0;1m
!J† œ§ ¡œ­˜¢å›˜ «à¤ £¤¬£á«à¤ æ§àª «¤ ™¢â§œ«œ ©«¦ †¢œ¡«¨¦¤ ¡æ ’˜®¬›¨¦£œå¦
¡˜  « ª „ › ¡âª œ¨ ¦®âª §¨¦©­â¨œ  §¦¢¢âª §¢¨¦­¦¨åœª ¦  ¦§¦åœª ›œ¤ £§¦¨¦ç¤
¤˜ ˜§¦Ÿ¡œ¬Ÿ¦ç¤ ©«¤ §¦¢ç §œ¨ ¦¨ ©£â¤ œ§ ¡œ­˜¢å›˜ «à¤ QWK £¤¬£á«à¤.
„¤œ¨š¦§¦ é¤«˜ª ˜¬«ã «¤ œ§ ¢¦šã, ¦ Mailer Ÿ˜ «¦§¦Ÿœ«œå «¤ §¢ã¨ œ§ ¡œ­˜¢å›˜
¡áŸœ £¤ç£˜«¦ª ˜£â©àª §¨ ¤ ˜§æ «¦ £ã¤¬£˜. €¬«æ Ÿ˜ ©˜ª œ§ «¨â§œ  ¤˜ ›œå«œ
«¦ §¢ã¨œª Ÿâ£˜ «ª ©¬ã«©ª («¦ QWK §¨à«æ¡¦¢¦ ¡æ™œ  «˜ Ÿâ£˜«˜), «¦¤ ˜¨ Ÿ£æ
˜§˜¤«ã©œà¤, ¡¢§.!)

!J€¤ ›œ¤ £§¦¨œå«œ ¤˜ ˜§¦­˜©å©œ«œ, œ¤œ¨š¦§¦ ã©«œ «¤ œ§ ¢¦šã.!)
[0;1m} T Setup QWK, Linear template, full header inclusion


OMSOK {[0;1;32m
!J  §¨¦« £ã©œ ª ©˜ª ˜§¦Ÿ¡œçŸ¡˜¤ œ§ «¬®éª.!)
[0;1m} T Setup QWK, changes stored successfully


OMSCAN {[0;1;31m
!J  ˜¢¢˜šâª ©˜ª £˜«˜ éŸ¡˜¤.!)
[0;1m} T Setup QWK, changes aborted



OMCMNU {[0;1m
   [33mV[37miew  . . . „£­á¤ © «à¤ §œ¨ ¢˜£™˜¤¦£â¤à¤ Club
   [33m+[37m  . . . . . . . . . . . .  ¨¦©Ÿâ©«œ â¤˜ Club
   [33m-[37m . . . . . . . . . . . . . €­˜ ¨â©«œ â¤˜ Club
   [33mR[37meset  . . . . . . €¢¢˜šã «œ¢œ¬«˜å¦¬ £¤ç£˜«¦ª
   [33mF[37mrom quickscan  . . . .  §àª ¡˜  «¦ Quickscan
   [33mT[37mo quickscan . . . . . . . „¤£â¨à© Quickscan
[0;1m} T Club config, menu


OMCMNUS {[0;1m
!Wƒé©«œ «¤ œ§ ¢¦šã ©˜ª ([33mV[37m,[33m+[37m,[33m-[37m,[33mR[37m,[33mF[37m,[33mT[37m,[33m?[37m š ˜ ™¦ãŸœ ˜, ã [33mX[37m š ˜ «â¢¦ª:!)[0m } T Club config, short menu



OMCHLP {[0;1m
!J„›é £§¦¨œå«œ ¤˜ ¦¨å©œ«œ §¦ ˜ clubs Ÿ˜ §œ¨ ¢˜£™á¤¦¤«˜  ©«˜ §˜¡â«˜ £¤¬£á«à¤ ©˜ª.
€¤ â®œ«œ ã› ¦¨å©œ  ¡á§¦ ˜ clubs š ˜ «¦ on-line Quickscan, «æ«œ ¥â¨œ«œ ã›
«¤ ¢œ «¦¬¨šå˜ «ª ™á©ª ©'˜¬«æ «¦ ©£œå¦.!)

!J€¨® ¡á æ¢˜ «˜ Clubs §œ¨ ¢˜£™á¤¦¤«˜  ©«¦ §˜¡â«¦ ©˜ª (¡˜  ©«¦ quickscan «à¤
clubs -- «¤ on-line ˜¤áš¤à©, ›¢˜›ã), ˜¢¢á £§¦¨œå«œ ¤˜
˜­˜ ¨â©œ«œ â¤˜ ›å¤¦¤«˜ª "[33m-/¤¦£˜Club[37m", ã ¤˜ §¨¦©Ÿâ©œ«œ â¤˜
›å¤¦¤«˜ª "[33m+/¤¦£˜Club[37m". ‚ ˜ ¤˜ ›œå«œ â¤˜ ¡˜«á¢¦š¦ æ¢à¤ «à¤ Clubs
£§¦¨œå«œ ¤˜ ›é©œ«œ "[33m+?[37m". ‚ ˜ ¤˜ ©¬£§œ¨ ¢á™œ«œ æ¢˜ «˜ Clubs ›é©«œ
"[33m+ALL[37m" ¡˜  š ˜ ¤˜ «˜ › ˜š¨á¯œ«œ æ¢˜, "[33m-ALL[37m".
‚ ˜ ¤˜ Ÿœà¨Ÿ¦ç¤ æ¢˜ «˜ £¤ç£˜«˜ œ¤æª Club ã› › ˜™˜©£â¤˜ ›é©«œ
"[33m+/O¤¦£˜Club[37m" ›ç¦ ­¦¨âª. ƒ¢˜›ã, ˜¤ ›é©œ«œ "[33m+ALL +ALL[37m",
«¦ ©ç©«£˜ Ÿ˜ Ÿœà¨ã©œ  æ¢˜ «˜ £¤ç£˜«˜ æ¢à¤ «à¤ Clubs ã› › ˜™˜©£â¤˜.
„«© , «¤ œ§æ£œ¤ ­¦¨á §¦¬ Ÿ˜ ¢á™œ«œ §˜¡â«¦, Ÿ˜ › ˜™á©œ«œ £æ¤¦ ¤â˜
£¤ç£˜«˜.!)

!J’¦ ©ç©«£˜ "Ÿ¬£á«˜ " «¦ «œ¢œ¬«˜å¦ £ã¤¬£˜ ¡áŸœ Club §¦¬ â®œ«œ ¢á™œ  ©œ §˜¡â«¦ QWK.
‹§¦¨œå«œ ¤˜ ˜¢¢á¥œ«œ «¦¤ ˜¨ Ÿ£æ ˜¬«æ £œ «¤ œ¤«¦¢ã [33mR[37m. €¬«ã  ›¬¤˜«æ««˜ ¬§á¨®œ 
š ˜ ¢æš¦¬ª ˜¨®œ ¦Ÿâ«©ª ¡˜  š ˜ ¤˜ ¡˜¢ç¯œ  ¦¨ ©£â¤œª ˜©¬¤ãŸ ©«œª ˜¤áš¡œª. [31m¨¦©â¥«œ[37m,
˜¢¢á¦¤«˜ª «¦¤ ˜¨ Ÿ£æ ˜¬«æ ®à¨åª ¤˜ ¥â¨œ«œ «  ¡á¤œ«œ £§¦¨œå ¤˜ › ¦š¡é©œ«œ ¡˜«á §¦¢ç «¦ §˜¡â«¦ ©˜ª,
ã ¤˜ ®á©œ«œ £¤ç£˜«˜ §¦¬ ›œ¤ â®œ«œ ˜¡æ£ ¢á™œ .!)

!J€¤ â®œ«œ ã› › ˜£¦¨­é©œ  â¤˜ ©ç¤¦¢¦ clubs ©«¦ Quickscan, £§¦¨œå«œ ¤˜ «¦
˜¤«¢ã©œ«œ £œ «¤ œ¤«¦¢ã [33mF[37m. † œ¤«¦¢ã ˜¬«ã ¦¨åœ  æ«  «˜ clubs §¦¬ Ÿ˜
¢˜£™á¤œ«œ ©«˜ §˜¡â«˜ ©˜ª Ÿ˜ œå¤˜  å› ˜ £œ ˜¬«á §¦¬ œå®˜«œ ©«¦ Quickscan ©˜ª
æ«˜¤ ›é©˜«œ «¤ œ¤«¦¢ã. ‹§¦¨œå«œ ¤˜ ¡á¤œ«œ ¡˜  «¦ ˜¤«åŸœ«¦, ¤˜ ©«œå¢œ«œ ›¢˜›ã
« ª œ›é ¨¬Ÿ£å©œ ª ©˜ª ©«¦ Quickscan, £œ «¤ œ¤«¦¢ã [33mT[33m.!)
[0;1m} T Club config, help


OMCHLP2 {[0;1m

!J‹ ˜ ¡˜  ˜¬«ã œå¤˜   §¨é« ­¦¨á §¦¬ › ˜£¦¨­é¤œ«œ «¦ §˜¡â«¦ £¤¬£á«à¤ ©˜ª,
æ¢˜ «˜ clubs §œ¨ ¢˜£™á¤¦¤«˜  ˜¬«æ£˜«˜ ˜§æ «¦ ©ç©«£˜. ’¦ §¨é«¦ §˜¡â«¦ ©˜ª Ÿ˜
§œ¨ â®œ  £æ¤¦ æ©˜ £¤ç£˜«˜ š¨˜­«¦ç¤ ˜§'˜¬«ã « ©« š£ã ¡˜  £œ«á (£§¦¨œå ›¢˜›ã
¡˜  ¤˜ £¤ §œ¨ â®œ  ¡˜Ÿæ¢¦¬ £¤ç£˜«˜). ‹§¦¨œå«œ œ¢œçŸœ¨˜ ¤˜ ˜¢¢á¥œ«œ «˜
clubs §¦¬ Ÿ˜ §œ¨ ¢˜£™á¤¦¤«˜  ©«˜ §˜¡â«˜ ©˜ª. ‚ ˜ §œ¨ ©©æ«œ¨œª §¢¨¦­¦¨åœª,
›é©«œ [33m?[37m ©«¦ §˜¨˜¡á«à £œ¤¦ç.!)
[0;1m} T Club config, help for users who already have a quickscan setup



OMCLH {[0;1;32m
  œ¥ãª §œ¨ ¦®âª £¤¬£á«à¤ §œ¨ ¢˜£™á¤¦¤«˜  ©«˜ §˜¡â«˜ ©˜ª:

[37mœ¨ ¦®ã            ‘«¦ Quickscan   ’œ¢œ¬«˜å¦ £ã¤¬£˜
!FÄ
[0m} T Club config, club list header


OMCL {%-16s        %3s              %6d
} T Club config, club list line


OMCLYES {Œ˜ } T Club config, club list, 'yes'
OMCLNO  {® } T Club config, club list, 'no'


OMCLF {[0;1m!FÄ
} T Club config, club list footer


OMCADD {[0;1m
!Wƒé©«œ Club §¦¬ Ÿ˜ ©¬£§œ¨ ¢á™œ«œ ©«˜ §˜¡â«˜ ©˜ª,
ã [33mALL[37m š ˜ æ¢˜ ([33m?[37m š ˜ ¡˜«á¢¦š¦):!)[0m } T Club config, add club


OMCCR {[0;1;31m
!Jƒœ¤ ¬§á¨®œ  ˜¬«æ «¦ Club.!)
} T Club config, add, unknown club


OMCDEL {[0;1m
!Wƒé©«œ Club §¦¬ Ÿ˜ œ¥˜ ¨â©œ«œ ˜§æ «˜ §˜¡â«˜ £¤¬£á«à¤ ©˜ª, ã
[33mALL[37m š ˜ æ¢˜ «˜ clubs ([33m?[37m š ˜ ¡˜«á¢¦š¦):!)[0m } T Club config, delete club


OMCDR {[0;1;31m
!Jƒœ¤ ¬§á¨®œ  «â«¦ ¦ Club ©«¦¤ ¡˜«á¢¦š¦ «à¤ ˜¤ ®¤œ¬¦£â¤à¤ Club.!)
} T Club config, delete, unknown club


OMCRES {[0;1m
!Wƒé©«œ Club «¦¬ ¦§¦å¦¬ Ÿ˜ ˜¢¢á¥œ«œ «¦ «œ¢œ¬«˜å¦ › ˜™˜©£â¤¦ £ã¤¬£˜,
[33mEMAIL[37m š ˜ «¦ †¢œ¡«¨¦¤ ¡æ ’˜®¬›¨¦£œå¦,
ã [33mALL[37m š ˜ æ¢˜ «˜ clubs ([33m?[37m š ˜ ¡˜«á¢¦š¦):!)[0m } T Club config, reset club


OMCRR {[0;1;31m
!Jƒœ¤ ¬§á¨®œ  «â«¦ ¦ Club ©«¦¤ ¡˜«á¢¦š¦ «à¤ ˜¤ ®¤œ¬¦£â¤à¤ Club.!)
} T Club config, reset, unknown club


OMCRN {[0;1m
!Jƒé©«œ «¦¤ ˜¨ Ÿ£æ «¦¬ «œ¢œ¬«˜å¦¬ £¤ç£˜«¦ª §¦¬ Ÿ˜ Ÿœà¨œå«˜  › ˜™˜©£â¤¦. €¤
›é©œ«œ ˜¨¤« ¡æ ˜¨ Ÿ£æ, ¦ ˜¨ Ÿ£æª £¤¬£á«à¤ «¦¬ club §¨¦©«åŸœ«˜  ©«¦¤ ˜¨ Ÿ£æ
©˜ª. „«© , ˜¤ â¤˜ club â®œ  100 £¤ç£˜«˜ ¡˜  ›é©œ«œ -10, «¦ «œ¢œ¬«˜å¦ £ã¤¬£˜
Ÿ˜ œå¤˜  «¦ 90. €¬«ã œå¤˜   [33m£æ¤[37m ©à©«ã £âŸ¦›¦ª š ˜ ¤˜ ˜¢¢á¥œ«œ «¦
«œ¢œ¬«˜å¦ › ˜™˜©£â¤¦ £ã¤¬£˜ ˜¤ £œ«˜™á¢¢œ«œ [33mæ¢˜[37m «˜ clubs.!)

!W€¨ Ÿ£æª «œ¢œ¬«˜å¦¬ £¤ç£˜«¦ª; ([33m%d[37m - [33m%d[37m, [33mX[37m š ˜ â¥¦›¦)!)[0m } T Club config, reset, asking for number


OMCRNR {[0;1;31m
!J€¨ Ÿ£æª œ¡«æª ¦¨åà¤.!)
[0;1m} T Club config, reset, number out of bounds


OMCFC {[0;1m
!J€¬«ã  œ¤«¦¢ã Ÿ˜ £œ«˜«¨â¯œ  «¤ › ˜£æ¨­à© «à¤ §˜¡â«¦¬ £¤¬£á«à¤ ©˜ª ©œ ˜¤«åš¨˜­¦ «ª › ˜£æ¨­à©ª š¨ãš¦¨ª
˜¤å®¤œ¬©ª. ƒ¢˜›ã, ©«¦ §˜¡â«¦ ©˜ª Ÿ˜ §œ¨ ¢˜£™á¤¦¤«˜  ˜¡¨ ™éª «˜ å› ˜ clubs §¦¬ › ˜™áœ«œ ¡˜  ©«¦ Quickscan,
¡˜  £œ «¦¬ª å› ¦¬ª ˜¨ Ÿ£¦çª «œ¢œ¬«˜åà¤ £¤¬£á«à¤.!)

!WŒ˜ §¨¦®à¨ã©¦¬£œ; ([[33mY[37m]es=¤˜å / [[33mN[37m]o=æ® )!)[0m } T Club config, From Quickscan, confirm?


OMCFCR {[0;1;31m
!J˜¨˜¡˜¢é ˜§˜¤«ã©«œ £œ [33mY[31m ã [33mN[31m.!)
[0;1m} T Club config, From Quickscan, invalid choice


OMCFOK {[0;1;32m
!J‰˜¢éª, ©«¦ §˜¡â«¦ ©˜ª Ÿ˜ §œ¨ ¢˜£™á¤¦¤«˜  §¢â¦¤ ˜¡¨ ™éª ¦  å› œª §œ¨ ¦®âª §¦¬ §œ¨ ¢˜£™á¤¦¤«˜  ¡˜ 
©«¤ š¨ãš¦¨ ˜¤å®¤œ¬©.!)
[0;1m} T Club config, From Quickscan, done


OMCFCAN {[0;1;31m
!J€¡¬¨éŸ¡œ.!)
[0;1m} T Club config, From Quickscan, aborted


OMCTC {[0;1m
!J€¬«ã  œ¤«¦¢ã Ÿ˜ £œ«˜«¨â¯œ  «¤ › ˜£æ¨­à© «ª š¨ãš¦¨ª ˜¤å®¤œ¬©ª ©œ ˜¤«åš¨˜­¦ «ª › ˜£æ¨­à©ª «¦¬
§˜¡â«¦¬ £¤¬£á«à¤ ©˜ª. ƒ¢˜›ã, ©«¦ Quickscan Ÿ˜ › ˜™áœ«œ ˜¡¨ ™éª «˜ å› ˜ clubs §¦¬ ¢˜£™á¤œ«œ ¡˜  ©«˜ §˜¡â«˜ ©˜ª,
¡˜  £œ «¦¬ª å› ¦¬ª ˜¨ Ÿ£¦çª «œ¢œ¬«˜åà¤ £¤¬£á«à¤.!)

!WŒ˜ §¨¦®à¨ã©¦¬£œ; ([[33mY[37m]es=¤˜å / [[33mN[37m]o=æ® )!)[0m } T Club config, To Quickscan, confirm?


OMCTCR {[0;1;31m
!J˜¨˜¡˜¢é ˜§˜¤«ã©«œ £œ [33mY[31m ã [33mN[31m.!)
[0;1m} T Club config, To Quickscan, invalid choice


OMCTOK {[0;1;32m
!J‰˜¢éª, ©«¤ š¨ãš¦¨ ˜¤å®¤œ¬© Ÿ˜ §œ¨ ¢˜£™á¤¦¤«˜  §¢â¦¤ ˜¡¨ ™éª ¦  å› œª §œ¨ ¦®âª §¦¬ §œ¨ ¢˜£™á¤¦¤«˜  ¡˜ 
©«˜ §˜¡â«˜ £¤¬£á«à¤ ©˜ª.!)
[0;1m} T Club config, To Quickscan, done


OMCTCAN {[0;1;31m
!J€¡¬¨éŸ¡œ.!)
[0;1m} T Club config, To Quickscan, aborted






OMDLHD {[0;1m                                                                 ‹¤ç£˜«˜
Club             œ¨ š¨˜­ã                                  ‘¬¤¦¢ ¡á  ‚ ˜ œ©áª
!FÄ
[0;1m} T Quickscan table: Header


OMDLEM {[0;1;32mE-Mail           †¢œ¡«¨¦¤ ¡æ ’˜®¬›¨¦£œå¦                    [37m} T Quickscan table: Email line


OMDLT1 {[0;1;32m%-16.16s %-42.42s [37m} T Quickscan table: SIG name and description


OMDLIND0 {[s [0;30;40m[K[u} T Keyword scan, work indicator, begin

OMDLIND1 {[u[0m|[30m[K} T Keyword scan, work indicator, frame 1
OMDLIND2 {[u[0m/[30m[K} T Keyword scan, work indicator, frame 2
OMDLIND3 {[u[0m-[30m[K} T Keyword scan, work indicator, frame 3
OMDLIND4 {[u[0m\[30m[K} T Keyword scan, work indicator, frame 4
OMDLIND5 {[u[0m|[30m[K} T Keyword scan, work indicator, frame 5
OMDLIND6 {[u[0m/[30m[K} T Keyword scan, work indicator, frame 6
OMDLIND7 {[u[0m-[30m[K} T Keyword scan, work indicator, frame 7
OMDLIND8 {[u[0m\[30m[K} T Keyword scan, work indicator, frame 8

OMDLINDE {[u[0;1m[K} T Keyword scan, work indicator, end


OMDLT2 {[0;1;33m%7d   %7d
} T Quickscan table: Number of messages found in SIG


MSGSTOT {[0;1m
¨âŸ¡˜¤ ©¬¤¦¢ ¡á:   [33m%4d[37m %s.
[0;1m} T Quickscan table: Total number of messages


MSGS4U {[0;1m‚ ˜ œ©áª:            [33m%4d[37m %s.
[0;1m} T Quickscan table: Number of messages for you


MSGSAT {[0;1m‹œ ©¬¤££â¤˜ ˜¨®œå˜: [33m%4d[37m %s.
[0;1m} T Quickscan table: Number of messages with attached files


MSGSNG {£ã¤¬£˜} S 'Message', singular
MSGPLR {£¤ç£˜«˜} S 'Messages', plural


QWKCOPY {[0;1m[2J[0;1m
„ ©˜šàšã ˜¨®œåà¤ ©«¦ §˜¡â«¦ £¤¬£á«à¤ ©˜ª...
[0;1m} T Copying attached/requested files


QWKCPPPN {[0;1;32m
€¨®œå˜ «à¤ ¦§¦åà¤  ¢ã¯ œå®œ ˜¤˜™¢Ÿœå:
[0;1m} T Dumping previously postponed files into your packet


QWKCPATT {[0;1;32m
€¨®œå˜ ©¬¤££â¤˜ ©œ ¤â˜ £¤ç£˜«˜:
[0;1m} T Dumping attached files into your packet


QWKCPREQ {[0;1;32m
‘¬¤££â¤˜ ˜¨®œå˜ §¦¬ â®œ«œ «ã©œ :
[0;1m} T Dumping requested files into your packet


QWKCPOTH {[0;1;32m
€¢¢˜ ˜¨®œå˜:
[0;1m} T Dumping all other files into your packet


ATTLEFT {[0;1;33m
!W¨¦œ ›¦§¦å©: !i…«ã©˜«œ «¤ œ ©˜šàšã ¡á§¦ ¦¬ ˜¨®œå¦¬ ã ˜¨®œåà¤ ©«¦
§˜¡â«¦ £¤¬£á«à¤ ©˜ª, ˜¢¢á â®œ«œ ¦¨å©œ  æ«  «˜ ˜¨®œå˜ ˜¬«á [37m›œ¤ Ÿ˜ œ ©áš¦¤«˜ 
§¦«â[33m ©«˜ §˜¡â«˜ ©˜ª! ‚ ˜ ¤˜ ¢á™œ«œ æ,«  ˜¨®œå˜ â®¦¬¤ «Ÿœå ©«¦ œ§æ£œ¤¦
§˜¡â«¦ ©˜ª, §š˜å¤œ«œ ©« ª ¨¬Ÿ£å©œ ª ¡˜  ˜¢¢á¥«œ «¤ œ§ ¢¦šã "€¨®œå˜ §¦¬
â®œ«œ «ã©œ " ©œ "Œ˜ " ã "‰˜«æ§ ¤ œ¨é«©ª".!)
!0l[0;1m} T Warning, requested files found but insertion of requests is off


QWKCPHD {[0;1;32m
¤¦£˜         œ¨ ¦®ã           ‹âšœŸ¦ª
!FÄ
[0;1m} T File copy: Header


QWKCPTB {
[A[0;1m%-12s  %-16s  %7d  [s} T File copy: Filename, area, and size


QWKCPAC {[0;1m!W[u[K„ ©˜šàšã; ([33mY[37m/[33mN[37m/[33mA[37m/[33mO[37m/[33mP[37m/[33mM[37m, [33m?[37m=™¦ãŸœ ˜)!) [0m} T File copy: Copy the file?


QWKCPER {[u} T File copy: bad choice in QWKCPAC menu


QWKASKH {[0;1m
!J’¦ ©ç©«£˜ ©˜ª ¨à«áœ  ˜¤ Ÿâ¢œ«œ ¤˜ œ ©ášœ  «¦ §˜¨˜§á¤à ˜¨®œå¦ ©«¦ §˜¡â«¦ £¤¬£á«à¤ ©˜ª.
€¬«æ ©¬£™˜å¤œ  š ˜«å «ã©˜«œ œ ©˜šàšã "‰˜«æ§ ¤ „¨é«©ª" œå«œ «à¤ ©¬¤££â¤à¤ ©œ £¤ç£˜«˜
˜¨®œåà¤, œå«œ «à¤ ˜¨®œåà¤ §¦¬ â®œ«œ «ã©œ  £â©à «¦¬ off-line reader ©˜ª.!)

!J‹§¦¨œå«œ ¤˜ ¡á¤œ«œ «˜ œ¥ãª:!)

!J!4l[[33mY[37m]es. Œ˜ , œ ©˜šàšã «¦¬ ˜¨®œå¦¬ ©«¦ §˜¡â«¦.!)
!0l
!J!4l[[33mN[37m]o. ® , «¦ ˜¨®œå¦ ›œ¤ Ÿ˜ œ ©˜®Ÿœå ©«¦ §˜¡â«¦ ¡˜  ›œ¤ Ÿ˜
©˜ª ¥˜¤˜§˜¨¦¬© ˜©«œå œ¡«æª ¡  ˜¤ «¦ «ã©œ«œ.!)
!0l
!J!4l[[33mA[37m]ll. ¢˜ «˜ ˜¨®œå˜ œ ©áš¦¤«˜  ©«¦ §˜¡â«¦ ©˜ª ®à¨åª á¢¢œª
œ¨à«ã©œ ª. ( ©¦›¬¤˜£œå £œ §¦¢¢á [33mY[37m)!)
!0l
!J!4lN[[33mO[37m]ne. ‰˜¤â¤˜ ˜¨®œå¦ ›œ¤ œ ©ášœ«˜  ©«¦ §˜¡â«¦ ©˜ª ®à¨åª
á¢¢œª œ¨à«ã©œ ª ( ©¦›¬¤˜£œå £œ §¦¢¢á [33mN[37m).!)
!0l
!J!4l[[33mP[37m]ostpone. €¤˜™¦¢ã ¢ã¯ª. ’¦ ˜¨®œå¦ ›œ¤ œ ©ášœ«˜  ©«¦ §˜¡â«¦,
˜¢¢á Ÿ˜ ©˜ª ¥˜¤˜§¨¦«˜Ÿœå š ˜ ¢ã¯ ©«¦ œ§æ£œ¤¦ §˜¡â«¦ £¤¬£á«à¤.!)
!0l
!J!4l[[33mM[37m]essage. ‹ã¤¬£˜. „£­˜¤åœ«˜   œ§ ¡œ­˜¢å›˜ «¦¬ £¤ç£˜«¦ª ©«¦ ¦§¦å¦ œå¤˜ 
©¬¤££â¤¦ «¦ ˜¨®œå¦. €¬«æ ©˜ª œ§ «¨â§œ  ¤˜ ›œå«œ «  §œ¨å§¦¬ œå¤˜  «¦ ˜¨®œå¦ ¡˜  ¤˜ §¨á¥œ«œ ˜¤á¢¦š˜.!)
!0l
[0;1m} T File copy: Help on deciding what to do with the file


QWKCPNF {[u[0;1;31m[Kƒœ¤ ™¨âŸ¡œ.
[0;1m} T File copy: Requested file not found


QWKCPAP {[u[0;1;31m[Kƒœ¤ â®œ  œš¡¨ Ÿœå ˜¡æ£˜.
[0;1m} T File copy: Can't copy unapproved files


QWKCPNA {[u[0;1;31m[Kƒœ¤ ©˜ª œ§ «¨â§œ«˜   ¢ã¯ «¦¬.
[0;1m} T File copy: This file is not available to you


QWKCPCP {[u[0;1;5;33m€¤« š¨á­œ«˜ ...[40;30m[K} T File copy: copying...


QWKCPIO {[u[0;1;31m[KŠáŸ¦ª ¡˜«á «¤ ˜¤« š¨˜­ã!
[0;1m} T File copy: I/O error while copying


QWKCPOK {[u[0;1;32m[K€¤« š¨˜­ã œ§ «¬®ãª.
[0;1m} T File copy: Copied ok


QWKCPPO {[u[0;1;33m[K† ¢ã¯ ˜¤˜™á¢¢œ«˜ .
[0;1m} T File copy: File skipped, request postponed


QWKCPCA {[u[0;1;33m[K† ¢ã¯ £˜«˜ é¤œ«˜ .
[0;1m} T File copy: File skipped, request cancelled


QWKCPHH {[0;1m
!J„§ ¡œ­˜¢å›˜ «¦¬ £¤ç£˜«¦ª ©«¦ ¦§¦å¦ œå¤˜  ©¬¤££â¤¦ «¦ ˜¨®œå¦:!)
[0;1m} T File copy: File header preview, header


QWKCPHF {} T File copy: File header preview, footer


MSGHDR1 {
%s/%d  %s
†‹/Œˆ€: %-38.38s  %31.31s
€:    %-42.42s  %s
‘:   %s%-48.48s  %21.21s
‡„‹€:   %-54.54s  %15.15s
} T Message header, top part


MSGHDR2 {€•„ˆ: %-52s  %17s
} T Message header, optional file attachment part


MSGHDR3 {ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

} T Message header, bottom part


MHFORU {} T Message header, message for you (clubs only)


MHALL {¢¦¬ª} T Message header, string for 'All'


MHDAY0 {‰¬¨ ˜¡ã} T Message header, string for Sunday
MHDAY1 {ƒœ¬«â¨˜} T Message header, string for Monday
MHDAY2 {’¨å«} T Message header, string for Tuesday
MHDAY3 {’œ«á¨«} T Message header, string for Wednesday
MHDAY4 {â£§«} T Message header, string for Thursday
MHDAY5 {˜¨˜©¡œ¬ã} T Message header, string for Friday
MHDAY6 {‘á™™˜«¦} T Message header, string for Saturday


MHJAN {ˆ˜¤¦¬˜¨å¦¬} T Message header, string for January
MHFEB {”œ™¨¦¬˜¨å¦¬} T Message header, string for February
MHMAR {‹˜¨«å¦¬} T Message header, string for March
MHAPR {€§¨ ¢å¦¬} T Message header, string for April
MHMAY {‹˜ä¦¬} T Message header, string for May
MHJUN {ˆ¦¬¤å¦¬} T Message header, string for June
MHJUL {ˆ¦¬¢å¦¬} T Message header, string for July
MHAUG {€¬š¦ç©«¦¬} T Message header, string for August
MHSEP {‘œ§«œ£™¨å¦¬} T Message header, string for September
MHOCT {¡«à™¨å¦¬} T Message header, string for October
MHNOV {Œ¦œ£™¨å¦¬} T Message header, string for November
MHDEC {ƒœ¡œ£™¨å¦¬} T Message header, string for December

MHPERIOD {œ¨ ¦› ¡æ, ˜¤á %d £â¨%s} T Message header, string for 'periodic'

MHXMPT {‹ › ˜š¨á¯ £¦} T Message header, string for 'exempt'

MHRRR {…«ãŸ¡œ ˜§æ›œ ¥ ˜¤áš¤à©ª} T Message header, string for 'return receipt requested'
        
MHTMRD {ƒ ˜™á©«¡œ %d ­¦¨%s} T Message header, string for 'read x times'

MHNREP {%d %s} T Message header, string for 'x replies'

MHNDNL {„¢ã­Ÿ %d ­¦¨%s} T Message header, string for 'downloaded x times'


TIMSNG {á} T 'Times', singular form
TIMPLR {âª} T 'Times', plural form

REPSNG {˜§á¤«©} T 'Reply', singular form
REPPLR {˜§˜¤«ã©œ ª} T 'Replies', plural form

DAYSNG {˜} T Days, singular form
DAYPLR {œª} T Days, plural form


ATTNOT1 {
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

€¬«æ «¦ £ã¤¬£˜ â®œ  ©¬¤££â¤¦ ˜¨®œå¦ £œ æ¤¦£˜ %s ¡˜  £âšœŸ¦ª
%d bytes.

’¦ ˜¨®œå¦ ƒ„Œ §œ¨ ¢˜£™á¤œ«˜  ©«¦ §˜¡â«¦ £¤¬£á«à¤ ©˜ª.
‘«œå¢«œ â¤˜ ¡œ¤æ £ã¤£˜ £œ §˜¨˜¢ã§« %s ¡˜  Ÿâ£˜
REQUEST %s/%ld š ˜ ¤˜ «¦ ¢á™œ«œ ©«¦ œ§æ£œ¤¦ §˜¡â«¦ ©˜ª.
} T Message text: File attachment not included in your packet


ATTNOT2 {
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

€¬«æ «¦ £ã¤¬£˜ â®œ  ©¬¤££â¤¦ ˜¨®œå¦ £œ æ¤¦£˜ %s ¡˜  £âšœŸ¦ª
%d bytes.
} T Message text: File attachment included in your packet


ATTNOT3 {
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

€¬«æ «¦ £ã¤¬£˜ â®œ  ©¬¤££â¤¦ ˜¨®œå¦ £œ æ¤¦£˜ %s ¡˜  £âšœŸ¦ª
%d bytes.

€¤ «¦ ˜¨®œå¦ ›œ¤ §œ¨ ¢˜£™á¤œ«˜  ©«¦ §˜¡â«¦ £¤¬£á«à¤ ©˜ª,
©«œå¢«œ â¤˜ ¡œ¤æ £ã¤£˜ £œ §˜¨˜¢ã§« %s ¡˜  Ÿâ£˜
REQUEST %s/%ld š ˜ ¤˜ «¦ ¢á™œ«œ ©«¦ œ§æ£œ¤¦ §˜¡â«¦ ©˜ª.
} T Message text: File attachment optionally included


ATTNOT4 {
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

€¬«æ «¦ £ã¤¬£˜ â®œ  ©¬¤££â¤¦ ˜¨®œå¦ £œ æ¤¦£˜ %s ¡˜  £âšœŸ¦ª
%d bytes, ˜¢¢á «¦ œ§å§œ›¦ §¨æ©™˜©ãª ©˜ª ©œ ˜¬«æ «¦ club ›œ¤
©˜ª œ§ «¨â§œ  ¤˜ «¦ ¢á™œ«œ.
} T Message text: File attachment not available to you


ATTNOT5 {
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

€¬«æ «¦ £ã¤¬£˜ â®œ  ©¬¤££â¤¦ ˜¨®œå¦ £œ æ¤¦£˜ %s ¡˜  £âšœŸ¦ª
%d bytes, ˜¢¢á ¦ ¦¨š˜¤à«ãª «¦¬ club ›œ¤ «¦ â®œ  ˜¡æ£˜ œš¡¨å¤œ .
} T Message text: File attachment not approved


ATTNOT6 {
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

€¬«æ «¦  £ã¤¬£˜ œå®œ  â¤˜ ©¬¤££â¤¦  ˜¨®œå¦, ˜¢¢á  «¦ ˜¨®œå¦  ›œ¤
™¨âŸ¡œ ©«¦ club. ˜¨˜¡˜¢¦ç£œ œ ›¦§¦ ã©«œ «¦¤ •œ ¨ ©«ã ‘¬©«ã£˜«¦ª
š ˜ «¦ šœš¦¤æª.
} T Message text: File not found or couldn't be opened


RRRINJ {[0;1m***

!J’¦ £â¢¦ª [32m%s[37m £æ¢ ª §œ¨ â¢˜™œ «¦ £¤¬£á ©˜ª
©œ §˜¡â«¦ QWK ¡˜  ›£ ¦¬¨šãŸ¡œ ˜§æ›œ ¥ §˜¨˜¢˜™ãª.!)
} T Return Receipt notification for receipt recipient



NOMSGS {[0;1;31m
!J’¦ §˜¡â«¦ ›œ¤ ­˜å¤œ«˜  ¤˜ §œ¨ â®œ  ˜¨®œå˜ ˜§˜¤«ã©œà¤ (.MSG).
”¬© ¦¢¦š ¡á, â¤˜ §˜¡â«¦ ˜§˜¤«ã©œà¤ §¨â§œ  ¤˜ §œ¨ â®œ  â¤˜ ˜¨®œå¦
£œ æ¤¦£˜ [37m%s.MSG[31m ã [37m%s.MSG[31m (£œ £ ¡¨á ã ¡œ­˜¢˜å˜ š¨á££˜«˜).!)
[0;1m} T Unable to find a .MSG file in the reply packet


BADID {[0;1;31m
!J’¦ §˜¡â«¦ ˜§˜¤«ã©œé¤ ©˜ª §¨¦¦¨åœ«˜  š ˜ ™á© £œ «¦¤ ¡à› ¡æ "[37m%s[31m".
’˜ §˜¡â«˜ «ª @BBS@ §¨â§œ  ¤˜ œå¤˜  ©­¨˜š ©£â¤˜ £œ «¦¤ ¡à› ¡æ
"[37m%s[31m". ƒœ¤ £§¦¨¦ç£œ ¤˜ ›œ®«¦ç£œ ˜¬«æ «¦ §˜¡â«¦.!)
[0;1m} T Reply packet is stamped with the wrong BBS ID.


REPHD {[0;1;32m
¨¦ª       Club             ‰˜«á©«˜©
!FÄ
} T Reply table: Header


REPTB {[0;1m%-10.10s %-16.16s } T Reply table: Recipient and SIG


REPTBALL {¢¦¬ª} T Reply table: string for 'All'


REPTBIN {[31m‹ œ¤œ¨šæ (› ˜šœš¨˜££â¤¦;) £ã¤¬£˜.
[0;1m} T Reply table: message is inactive (erased?)


REPTBNR {[31mƒœ¤ â®œ  ¦¨ ©«œå §˜¨˜¢ã§«ª.
[0;1m} T Reply table: no recipient specified


REPTBUU {[31m€š¤à©«¦ª §˜¨˜¢ã§«ª "%s".
[0;1m} T Reply table: unknown recipient


REPTBMF {[31m‰˜¡¦©®£˜« ©£â¤¦ £ã¤¬£˜!
[0;1m} T Reply table: malformed message


REPTBOK {[32m€§¦Ÿ¡œçŸ¡œ.
[0;1m} T Reply table: Message saved


REPTBAS {[33m€§¦Ÿ¡œçŸ¡œ, £œ æ¤¦£˜ ˜§¦©«¦¢â˜ "%s".
[0;1m} T Reply table: Saved, sender user-ID corrected


REPTBRR {[32m€§¦Ÿ¡œçŸ¡œ ¡˜  «ãŸ¡œ ˜§æ›œ ¥ §˜¨˜¢˜™ãª.
[0;1m} T Reply table: Saved, return receipt requested


REPTBUS {[31m€š¤à©«¦ club (å©àª ¤˜ ©™ã©«¡œ §¨æ©­˜«˜).
[0;1m} T Reply table: Unknown SIG number


REPTB2B {[31m’¦ £ã¤¬£˜ œå¤˜  £œš˜¢ç«œ¨¦ ˜§æ %d bytes.
[0;1m} T Reply table: Message too big


REPTBAG {[31m„®œ«œ ¥˜¤˜©«œå¢œ  ˜¬«æ «¦ £ã¤¬£˜.
[0;1m} T Reply table: This message has already been uploaded


REPTBAE {[31m‹ã¤¬£˜ §¨¦ª æ¢¦¬ª ©«¦ E-Mail.
[0;1m} T Reply table: E-Mail message to ALL


REPTBES {[31m¨¦©à§ ¡æ £ã¤¬£˜ ©œ club.
[0;1m} T Reply table: Recipient-only message in a SIG


REPTBPR {[31mƒ£æ© ¦ £ã¤¬£˜ £œ ˜å«© ˜§æ›œ ¥ª §˜¨˜¢˜™ãª.
[0;1m} T Reply table: Public message with return receipt


REPTBCR {[31mƒœ¤ â®œ«œ ˜¨¡œ«á credits.
[0;1m} T Reply table: Not enough credits to save


REPTBNA {[31m’¦ œ§å§œ›¦ ˜©­˜¢œå˜ª ©˜ª ›œ¤ «¦ œ§ «¨â§œ .
[0;1m} T Reply table: Club security restriction


REPTBCN {[33m€¡¬¨éŸ¡œ.
[0;1m} T Reply table: Message cancelled


DIRADD {[36mADD %s: } T Reply table: ADD directive


DIRDROP {[36mDROP %s: } T Reply table: DROP directive


DIRRESET {[36mRESET %s: } T Reply table: RESET directive


DIRRQST {[36mREQUEST %s: } T Reply table: REQUEST directive


DIRDONE {[32mƒœ¡«æ.
[0;1m} T Reply table: Directive processed


DIRFOR {[36m%s: [32m‡˜ «¦ œ§œ¥œ¨š˜©«¦ç£œ ©œ ¢åš¦.
[0;1m} T Reply table: Directive is foreign, will be processed in a bit


DIRERR1 {[31mŠáŸ¦ª ©«¤ œ¤«¦¢ã.
[0;1m} T Reply table: Error in directive


DIRERR2 {[31mŠáŸ¦ª œšš¨˜­ãª/˜¤áš¤à©ª
[0;1m} T Reply table: I/O Error in directive


DIRRQUS {[31m€š¤à©«¦ club.
[0;1m} T Reply table: REQUEST/ADD/DROP, unknown club


DIRCANT {[31mƒœ¤ œ§ «¨â§œ«˜ .
[0;1m} T Reply table: Can't manipulate E-Mail


DIRCNTR {[31m¨â§œ  ¤˜ â®œ  §¨¦šŸœå ADD.
[0;1m} T Reply table: Must ADD before RESETting


DIRNFND {[31mƒœ¤ ™¨âŸ¡œ  œ§ ©ç¤˜¯.
[0;1m} T Reply table: REQUESTed attachment not found


DIRNNEED {[33mƒœ¤ ®¨œ ˜æ«˜¤.
[0;1m} T Reply table: No need to do that


NOCFMSG {[31mƒœ¤ £§¦¨é ¤˜ œ§œ¥œ¨š˜©«é £¤ç£˜«˜ "CONFIG".
[0;1m} T Reply table: Can't process CONFIG messages


ENDUL {[0;1;32m!FÄ
%d[37m ˜§æ [32m%d[37m %s ˜§¦Ÿ¡œçŸ¡˜¤ œ§ «¬®éª.
[0;1m} T Reply table: Footer


ASKCLUB {[0;1m
!J˜¨˜¡˜¢é ›é©«œ «¦ æ¤¦£˜ «¦¬ club ©«¦ ¦§¦å¦ ¤˜ §¨¦àŸã©¦¬£œ
«¦ £ã¤¬£á ©˜ª, ã [33mEmail[37m š ˜ ¤˜ «¦ ©«œå¢¦¬£œ ©«¦ †¢œ¡«¨¦¤ ¡æ
’˜®¬›¨¦£œå¦ (§¨¦ª œ©áª ˜¤ œå¤˜  §¨¦ª æ¢¦¬ª), ã [33mX[37m š ˜ ˜¡ç¨à© «¦¬
£¤ç£˜«¦ª:[0m!) } T Re-enter club name


ASKCLBR {[0;1;31m
!J‘¬šš¤é£, ›œ¤ ¬§á¨®œ  ˜¬«æ «¦ club. ˜¤˜›¦¡ £á©«œ.!)
[0;1m} T Unknown club name


ASKERCP {[0;1m
!J˜¨˜¡˜¢é ›é©«œ «¦ æ¤¦£˜ «¦¬ §˜¨˜¢ã§«,
ã [33mX[37m š ˜ £˜«˜åà© ˜§¦©«¦¢ãª £¤ç£˜«¦ª:[0m!) } T Re-enter ID of unknown E-Mail message recipient


ASKSRCP {[0;1m
!J˜¨˜¡˜¢é ›é©«œ «¦ æ¤¦£˜ «¦¬ §˜¨˜¢ã§«,
[33mALL[37m š ˜ ˜§¦©«¦¢ã £¤ç£˜«¦ª ©œ Š“‘,
ã [33mX[37m š ˜ ˜¡ç¨à© £¤ç£˜«¦ª:[0m!) } T Re-enter ID of unknown SIG message recipient


UNKUSR {[0;1;31m
!J€¬«æ «¦ ¯œ¬›é¤¬£¦ ›œ¤ ¬§á¨®œ  ©«¤ ™á©. ˜¨˜¡˜¢é ¥˜¤˜§¨¦©§˜Ÿã©«œ...!)
[0;1m} T Unknown user ID, please re-enter


EMLALL {[0;1;31m
Š¬§á£˜ , ˜¢¢á ›œ¤ £§¦¨œå«œ ¤˜ ©«œå¢œ«œ £ã¤¬£˜ †¢œ¡«¨¦¤ ¡¦ç ’˜®¬›¨¦£œå¦¬
§¨¦ª æ¢¦¬ª.
[0;1m} T Can't supply "ALL" as E-Mail recipient


ASKEORS {[0;1m
!Jƒœ¤ £§¦¨œå«œ ¤˜ â®œ«œ §¨¦©à§ ¡æ £ã¤¬£˜ £â©˜ ©œ â¤˜ club. ‡â¢œ«œ:!)

[[33mE[37m]mail:  ¤˜ §¨¦àŸŸœå ©«¦ †¢œ¡«¨¦¤ ¡æ ’˜®¬›¨¦£œå¦,
[[33mP[37m]ublic: ¤˜ šå¤œ  ›£æ© ¦ ¡˜  ¤˜ §˜¨˜£œå¤œ  ©«¦ club, ã
[[33mC[37m]ancel: ¤˜ ˜¡¬¨àŸœå;

!J˜¨˜¡˜¢é ›é©«œ â¤˜ š¨á££˜ ([33mE[37m,[33mP[37m,[33mC[37m):!) [0m} T E-Mail message in a SIG: Make it private or public?


ASKRORS {[0;1m
!Jƒœ¤ £§¦¨œå«œ ¤˜ ¢á™œ«œ ˜§æ›œ ¥ §˜¨˜¢˜™ãª š ˜ ›£æ© ¦ £ã¤¬£˜. ‡â¢œ«œ:!)

[[33mE[37m]mail:  ¤˜ §¨¦àŸŸœå «¦ £ã¤¬£˜ ©«¦ †¢œ¡«¨¦¤ ¡æ ’˜®¬›¨¦£œå¦,
[[33mP[37m]ublic: ¤˜ £œå¤œ  ›£æ© ¦ ¡˜  ¤˜ ˜¡¬¨àŸœå  ˜å«© ˜§æ›œ ¥ª, ã
[[33mC[37m]ancel ¤˜ ˜¡¬¨àŸœå;

!J˜¨˜¡˜¢é ›é©«œ â¤˜ š¨á££˜ ([33mE[37m,[33mP[37m,[33mC[37m):!) [0m} T Public return receipt: Make it private or cancel?


ASKDUPL {[0;1m

!J„®œ«œ ¥˜¤˜©«œå¢œ  ˜¬«æ «¦ £ã¤¬£˜ ©« ™á©. €§˜¤«ã©«œ ¡˜«˜­˜« ¡á ©«¤
§˜¨˜¡á«à œ¨é«© ˜¤ «¦ £ã¤¬£˜ â®œ  ©™©«œå ˜§æ « ™á© ¡˜  Ÿâ¢œ«œ ¤˜ «¦
¥˜¤˜©«œå¢œ«œ.!)

!W‡â¢œ«œ ¤˜ ›œ®«¦ç£œ «¦ £ã¤¬£˜ ¦ç«àª ã á¢¢àª; ([[33mY[31m]es=¤˜å / [[33mN[31m]o=æ® ) [0m!)} T Duplicate message; accept it anyway?


ASKDUPD {[Enter=[33mN[37m][0m } T ASKDUPL default answer


ASKERR {[0;1;31m
!JŠ¬§á£˜ , ›œ¤ ¬§á¨®œ  ˜¬«ã  œ§ ¢¦šã.!)
[0;1m} T Unknown option error for ASKxxxx menus


SIGINJ {[0;1m***

!J’¦ £â¢¦ª [32m%s[37m £æ¢ ª ©˜ª â©«œ ¢œ £ã¤¬£˜ £œ Ÿâ£˜ "[32m%s[37m"
©«¦ club [32/%s[37m £â©à «¦¬ Off-line Mailer.
‹§¦¨œå«œ ¤˜ «¦ › ˜™á©œ«œ ›å¤¦¤«˜ª ˜§æ «¦ ¡œ¤«¨ ¡æ £œ¤¦ç:!)

([33mE[37m)mail = ¢œ¡«¨¦¤ ¡æ «˜®¬›¨¦£œå¦
([33mR[37m)ead  = ˜¤áš¤à©
([33mT[37m)o    = §¨æª œ©áª

!J'H š¨á­¦¤«˜ª [33m/GO ERT[37m ˜§æ ¦§¦¬›ã§¦«œ ©«¤ ™á©.!)
[0;1m} T Injected: You just got a SIG message through the Mailer


EMLINJ {[0;1m***

!J’¦ £â¢¦ª [32m%s[37m £æ¢ ª ©˜ª â©«œ ¢œ £ã¤¬£˜ £œ Ÿâ£˜ "[32m%s[37m"
©«¦ †¢œ¡«¨¦¤ ¡æ ’˜®¬›¨¦£œå¦ £â©à «¦¬ Off-line Mailer.
‹§¦¨œå«œ ¤˜ «¦ › ˜™á©œ«œ ›å¤¦¤«˜ª ˜§æ «¦ ¡œ¤«¨ ¡æ £œ¤¦ç:!)

([33mE[37m)mail = ¢œ¡«¨¦¤ ¡æ «˜®¬›¨¦£œå¦
([33mR[37m)ead  = ˜¤áš¤à©
([33mT[37m)o    = §¨æª œ©áª

!J'H š¨á­¦¤«˜ª [33m/GO ERT[37m ˜§æ ¦§¦¬›ã§¦«œ ©«¤ ™á©.!)
[0;1m} T Injected: You just got an E-Mail message through the Mailer


RQMUNS {[0;1;31m
!J  §˜¨˜¡á«à œ › ¡âª ˜ «ã©œ ª ›œ¤ ˜¤˜š¤à¨å©«¡˜¤:!)
[0;1;32m
¨¦ª       Club             ‰˜«á©«˜©
!FÄ
[0;1m} T The following requests were not satisfied


RQMTAB {[0;1m%-10.10s %-16.16s [36m%s: [31m† œ¤«¦¢ã ›œ¤ ˜¤˜š¤à¨å©«¡œ.
[0;1m} T Unsatisfied request table row


ENDRQM {[0;1;32m!FÄ
[0;1m} T End of unsatisfied request table




LANG {}


ADMNAM {Stelios Chamodrakas, Sysop} S 60 Sysop's name as stored in CONTROL.DAT


OMMENU {[2J[0m[47;1;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;30;47m¿ [40m
[47;1;37m ³  [0;47;30m    Mail Preferences    [0;47;30m  ³ [40m
[47;1;37m ³  [0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ  [0;47;30m³ [40m
[47;1;37m ³                            [0;47;30m³ [40m
[47;1;37m ³  [0;31;47mC[30mlubs included in packet  [30m³ [40m
[47;1;37m ³  [0;31;47mS[30metup preferences         [30m³ [40m
[47;1;37m ³                            [0;47;30m³ [40m
[47;1;37m ³ [0;30;47me[31mX[30mit                       [30m³ [40m
[47;1;37m À[0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0;1m

Offline mail preferences
Please enter your choice: [0m} T Setup, menu footer


OMSHORT {[0;1m
!WEnter your choice, [33mX[37m to exit or [33m?[37m for the menu: [0m!)} T Setup, short menu


OMERR {[0;1;31m
!JSorry, there is no option "%c".!)
[0;1m} T Setup, wrong selection


OMVT {[0m[30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [34mGeneral offline mail preferences[0;30;47m ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  Include file attachments?       [0;30;46m @6;"No|Yes|Ask me"l [0;47;30m             (Space to change)  [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  Include requested files?        [0;30;46m @6;"No|Yes|Ask me"l [0;47;30m             (Space to change)  [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  Add full message headers?       [0;30;46m [@"X "t] [0;47;30m                (Space to toggle)  [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  Ctrl-O: Help on preferences                                             [0;1;47;37m³ [0m
[30;47m ³  Ctrl-R: General help            [0;1;42;33m@14;"OK"b[0;47;30mÜ    [0;1;41;33m@14;"Cancel"b[0;47;30mÜ  [0;1;47;37m³ [0m
[30;47m ³                                   ßßßßßßßßßßßßßßßß     ßßßßßßßßßßßßßßßß  [0;1;47;37m³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m} T Setup, Visual template


OMVTN {No} T Setup, string for NO
OMVTY {Yes} T Setup, string for YES
OMVTA {Ask me} T Setup, string for ASK



OMLT {[2J[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [34mGeneral offline mail preferences[0;30;47m ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³                                                                          [1;37m³ [0m
[30;47m ³ [31m1[30m. Include file attachments? . . . . . . . . . . . . . . .  [34m@6;"Yes|No|Ask me"l[0;1;47;37m       ³ [0m
[30;47m ³                                                                          [1;37m³ [0m
[30;47m ³ [31m2[30m. Include requested files? . . . . . . . . . . . . . . . . [34m@6;"Yes|No|Ask me"l[0;1;47;37m       ³ [0m
[30;47m ³                                                                          [1;37m³ [0m
[30;47m ³ [31m3[30m. Add full message headers? . . . . . . . . . . . . . . .  [34m@"X "t[0;1;47;37m          ³ [0m
[30;47m ³                                                                          [1;37m³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0;1m
} T Setup QWK, Linear template


OMLTATT {[0;1m
!JSome email and club messages have files attached to them. This setting
controls what happens to such files when you generate an offline mail packet.
We can ignore them altogether (specify 'no') so you can request individual
files remotely (instructions are appended to messages with file attachments);
we can always include file attachments in your packets (specify 'yes'); or we can
ask you whether to include individual files during the packet generation
phase (specify 'ask me').!)

!JIf you can't decide, enter 'no'. This reduces the size of your QWK packets.!)
[0;1m} T Setup QWK, Linear template, set attachment policy


OMLTREQ {[0;1m
!JThis setting works just like the previous one, but it controls the system's
reaction to files you've requested yourself.!)

!JIf you can't decide, enter 'yes'. It will honour any and all requests
for file attachments that you make.!)
[0;1m} T Setup QWK, Linear template, set request policy


OMLTHDR {[0;1m
!JThe message header, as you see it online, offers a lot of information that's
not available to the QWK message header. Activate this setting and the system
will add a copy of the message header at the top of each message. This will
allow you to glean things like the full subject of the message
(normally truncated in QWK packet), the number of replies and downloads, and
so on.!)

!JIf you can't decide, leave this setting on. It's useful.!)
[0;1m} T Setup QWK, Linear template, full header inclusion


OMSOK {[0;1;32m
!JYour preferences were successfully saved.!)
[0;1m} T Setup QWK, changes stored successfully


OMSCAN {[0;1;31m
!JAborted.!)
[0;1m} T Setup QWK, changes aborted



OMCMNU {[0;1m
   [33mV[37miew  . . . . . . . . . . . View list of included clubs
   [33m+[37m  . . . . . . . . . . . . . . . Add a club to the list
   [33m-[37m . . . . . . . . . . . . . Remove a club from the list
   [33mR[37meset  . . . . . . . . . . . .  Reset last read message
   [33mF[37mrom quickscan  . . . . . . .  Read list from quiskscan
   [33mT[37mo quickscan . . . . . . . . . . Save list to quickscan
[0;1m} T Club config, menu


OMCMNUS {[0;1m
!WEnter your choice ([33mV[37m,[33m+[37m,[33m-[37m,[33mR[37m,[33mF[37m,[33mT[37m,[33m?[37m for help, or [33mX[37m to exit:!)[0m } T Club config, short menu



OMCHLP {[0;1m
!JThis allows you to set what clubs will be included in your message packets.
If you already have a Quickscan list, then you'll be familiar with this menu. In
fact, you can import your Quickscan list if you so wish.!)

!JInitially, all clubs are included in your packets, but you can remove one
by entering "[33m-/ClubName[37m". You can add one with
"[33m+/ClubName[37m". To see a list of all clubs, enter
"[33m+?[37m". To add all clubs, enter
"[33m+ALL[37m" and to remove all clubs enter "[33m-ALL[37m".
To mark all club messages as already read, enter
"[33m+/ClubName[37m" twice. Enter "[33m+ALL +ALL[37m",
to mark all messages read. The next time you generate a message packet,
only new messages since the reset will be included.!)

!JThe system remembers the last message of each club you've included in
your QWK packets. You can change this number with the [33mR[37m command.
Be aware that changing the last read pointers may result in massive
packets, or in missing messages you haven't read yet.!)

!JIf you already have a Quickscan list, you can import it with the [33mF[37m
command. You can also export your offline club list to your Quickscan list using the 
[33mT[33m command. This is done because Quickscan and offline mail are kept independent.
This allows users to make QWK packets for archival or later reading and still be able
to browse tha latest discussions online.!)
[0;1m} T Club config, help


OMCHLP2 {[0;1m

!JSince this is your first time here, we'll include all clubs in your
packets. Your first packet will contain only new messages written
after this moment (i.e. it may have no messages at all if you're in
a hurry). You may change the list of included clubs. For more information,
enter [33m?[37m at the prompt.!)
[0;1m} T Club config, help for users who already have a quickscan setup



OMCLH {[0;1;32m
The following clubs are included in your packets:

[37mClub               In Quickscan    Last message read
!FÄ
[0m} T Club config, club list header


OMCL {%-16s        %3s              %6d
} T Club config, club list line


OMCLYES {Yes} T Club config, club list, 'yes'
OMCLNO  {No} T Club config, club list, 'no'


OMCLF {[0;1m!FÄ
} T Club config, club list footer


OMCADD {[0;1m
!WPlease enter the name of a club to add to your packets,
or [33mALL[37m to add them all ([33m?[37m for a list):!)[0m } T Club config, add club


OMCCR {[0;1;31m
!JThat club doesn't exist.!)
} T Club config, add, unknown club


OMCDEL {[0;1m
!WPlease enter the name of a club to exclude from your packets, or
[33mALL[37m to remove them all ([33m?[37m for a list):!)[0m } T Club config, delete club


OMCDR {[0;1;31m
!JThat club isn't in your list of included clubs.!)
} T Club config, delete, unknown club


OMCRES {[0;1m
!WPlease enter the name of a club to reset its last read pointer,
[33mEMAIL[37m for the email area,
ã [33mALL[37m for all clubs ([33m?[37m for a list):!)[0m } T Club config, reset club


OMCRR {[0;1;31m
!JThere is no such club in your list of included clubs.!)
} T Club config, reset, unknown club


OMCRN {[0;1m
!JPlease enter the number of the last message to be considered read. If you
enter a negative number, the number is added to the number of the club's last
message. So, if a club's last message has numbe 100 and you enter -10, the
last read message will be 90. This is the [33monly[37m right way to change
the last read message on [33mALL[37m clubs simultaneously.!)

!WLast read message number: ([33m%d[37m - [33m%d[37m, [33mX[37m to exit)!)[0m } T Club config, reset, asking for number


OMCRNR {[0;1;31m
!JInvalid number.!)
[0;1m} T Club config, reset, number out of bounds


OMCFC {[0;1m
!JThis command imports the current status of your Quickscan
into the offline mail. Your QWK packets will include the same
clubs as your Quickscan, with the same messages marked read.!)

!WProceed? ([[33mY[37m]es / [[33mN[37m]o)!)[0m } T Club config, From Quickscan, confirm?


OMCFCR {[0;1;31m
!JPlease answer [33mY[31m or [33mN[31m.!)
[0;1m} T Club config, From Quickscan, invalid choice


OMCFOK {[0;1;32m
!JOK, your Quickscan configuration was imported.!)
[0;1m} T Club config, From Quickscan, done


OMCFCAN {[0;1;31m
!JAborted.!)
[0;1m} T Club config, From Quickscan, aborted


OMCTC {[0;1m
!JThis command exports the current status of the offline
mail to the Quickscan list. Your Quickscan state will be identical
to that of this area, with the same messages marked read.!)

!WProceed? ([[33mY[37m]es / [[33mN[37m]o)!)[0m } T Club config, To Quickscan, confirm?


OMCTCR {[0;1;31m
!JPlease answer [33mY[31m or [33mN[31m.!)
[0;1m} T Club config, To Quickscan, invalid choice


OMCTOK {[0;1;32m
!JOK, your configuration was exported to Quickscan.!)
[0;1m} T Club config, To Quickscan, done


OMCTCAN {[0;1;31m
!JAborted.!)
[0;1m} T Club config, To Quickscan, aborted






OMDLHD {[0;1m                                                                 Messages
Club             Description                                   Total   For you
!FÄ
[0;1m} T Quickscan table: Header


OMDLEM {[0;1;32mEmail            Electronic mail area                       [37m} T Quickscan table: Email line


OMDLT1 {[0;1;32m%-16.16s %-42.42s [37m} T Quickscan table: SIG name and description


OMDLIND0 {[s [0;30;40m[K[u} T Keyword scan, work indicator, begin

OMDLIND1 {[u[0m|[30m[K} T Keyword scan, work indicator, frame 1
OMDLIND2 {[u[0m/[30m[K} T Keyword scan, work indicator, frame 2
OMDLIND3 {[u[0m-[30m[K} T Keyword scan, work indicator, frame 3
OMDLIND4 {[u[0m\[30m[K} T Keyword scan, work indicator, frame 4
OMDLIND5 {[u[0m|[30m[K} T Keyword scan, work indicator, frame 5
OMDLIND6 {[u[0m/[30m[K} T Keyword scan, work indicator, frame 6
OMDLIND7 {[u[0m-[30m[K} T Keyword scan, work indicator, frame 7
OMDLIND8 {[u[0m\[30m[K} T Keyword scan, work indicator, frame 8

OMDLINDE {[u[0;1m[K} T Keyword scan, work indicator, end


OMDLT2 {[0;1;33m%7d   %7d
} T Quickscan table: Number of messages found in SIG


MSGSTOT {[0;1m
Total messages:      [33m%4d[37m %s.
[0;1m} T Quickscan table: Total number of messages


MSGS4U {[0;1mFor you:             [33m%4d[37m %s.
[0;1m} T Quickscan table: Number of messages for you


MSGSAT {[0;1mWith attachments:    [33m%4d[37m %s.
[0;1m} T Quickscan table: Number of messages with attached files


MSGSNG {message} S 'Message', singular
MSGPLR {messages} S 'Messages', plural


QWKCOPY {[0;1m[2J[0;1m
Copying files to your message packet...
[0;1m} T Copying attached/requested files


QWKCPPPN {[0;1;32m
Previously postponed files:
[0;1m} T Dumping previously postponed files into your packet


QWKCPATT {[0;1;32m
New attachments:
[0;1m} T Dumping attached files into your packet


QWKCPREQ {[0;1;32m
Previously requested files:
[0;1m} T Dumping requested files into your packet


QWKCPOTH {[0;1;32m
Other files:
[0;1m} T Dumping all other files into your packet


ATTLEFT {[0;1;33m
!WWarning: !iYou've requested one or more files, but
you've opted for requested files to [37mnot be included[33m
in your packets! To include requested files in your next packet,
go to the setup manu and change the "Include requested files"
setting to "yes" or "ask me".!)
!0l[0;1m} T Warning, requested files found but insertion of requests is off


QWKCPHD {[0;1;32m
Name          Club/area            Size
!FÄ
[0;1m} T File copy: Header


QWKCPTB {
[A[0;1m%-12s  %-16s  %7d  [s} T File copy: Filename, area, and size


QWKCPAC {[0;1m!W[u[KInclude? ([33mY[37m/[33mN[37m/[33mA[37m/[33mO[37m/[33mP[37m/[33mM[37m, [33m?[37m=help)!) [0m} T File copy: Copy the file?


QWKCPER {[u} T File copy: bad choice in QWKCPAC menu


QWKASKH {[0;1m
!JYou're being asked whether to copy the above file into your message packet.
This happened because you've opted for the system to ask you before
including files in your packets.!)

!JYou can say the following:!)

!J!4l[[33mY[37m]es. Include the file in your packet.!)
!0l
!J!4l[[33mN[37m]o. Don't include the file. Don't offer it again for inclusion
unless I explicitly request it.!)
!0l
!J!4l[[33mA[37m]ll. Include all remaining files (answers [33mY[37m to all remaining questions)!).
!0l
!J!4lN[[33mO[37m]ne. Include no other files (answers [33mN[37m to all remaining questions).!)
!0l
!J!4l[[33mP[37m]ostpone. Don't include this now. Offer it again next time.!)
!0l
!J!4l[[33mM[37m]essage. Shows the message header. This may help in determining whether
the file is useful or not.!)
!0l
[0;1m} T File copy: Help on deciding what to do with the file


QWKCPNF {[u[0;1;31m[KNot found.
[0;1m} T File copy: Requested file not found


QWKCPAP {[u[0;1;31m[KNot approved yet.
[0;1m} T File copy: Can't copy unapproved files


QWKCPNA {[u[0;1;31m[KDownload access denied.
[0;1m} T File copy: This file is not available to you


QWKCPCP {[u[0;1;5;33mCopying...[40;30m[K} T File copy: copying...


QWKCPIO {[u[0;1;31m[KI/O error while copying!
[0;1m} T File copy: I/O error while copying


QWKCPOK {[u[0;1;32m[KInclusion successful.
[0;1m} T File copy: Copied ok


QWKCPPO {[u[0;1;33m[KPostponed.
[0;1m} T File copy: File skipped, request postponed


QWKCPCA {[u[0;1;33m[KNot included.
[0;1m} T File copy: File skipped, request cancelled


QWKCPHH {[0;1m
!JMessage header:!)
[0;1m} T File copy: File header preview, header


QWKCPHF {} T File copy: File header preview, footer


MSGHDR1 {
%s/%d  %s
DATE:    %-38.38s  %31.31s
FROM:    %-42.42s  %s
TO:      %s%-48.48s  %21.21s
SUBJECT: %-54.54s  %15.15s
} T Message header, top part


MSGHDR2 {FILE:    %-52s  %17s
} T Message header, optional file attachment part


MSGHDR3 {ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

} T Message header, bottom part


MHFORU {} T Message header, message for you (clubs only)


MHALL {All} T Message header, string for 'All'


MHDAY0 {Sunday} T Message header, string for Sunday
MHDAY1 {Monday} T Message header, string for Monday
MHDAY2 {Tuesday} T Message header, string for Tuesday
MHDAY3 {Wednesday} T Message header, string for Wednesday
MHDAY4 {Thursday} T Message header, string for Thursday
MHDAY5 {Friday} T Message header, string for Friday
MHDAY6 {Saturday} T Message header, string for Saturday


MHJAN {January} T Message header, string for January
MHFEB {February} T Message header, string for February
MHMAR {March} T Message header, string for March
MHAPR {April} T Message header, string for April
MHMAY {May} T Message header, string for May
MHJUN {June} T Message header, string for June
MHJUL {July} T Message header, string for July
MHAUG {August} T Message header, string for August
MHSEP {September} T Message header, string for September
MHOCT {October} T Message header, string for October
MHNOV {November} T Message header, string for November
MHDEC {December} T Message header, string for December

MHPERIOD {Periodic, every %d day%s} T Message header, string for 'periodic'

MHXMPT {Exempt} T Message header, string for 'exempt'

MHRRR {Return receipte requested} T Message header, string for 'return receipt requested'
        
MHTMRD {Read %d time%s} T Message header, string for 'read x times'

MHNREP {%d %s} T Message header, string for 'x replies'

MHNDNL {Downloaded %d time%s} T Message header, string for 'downloaded x times'


TIMSNG {} T 'Times', singular form
TIMPLR {s} T 'Times', plural form

REPSNG {reply} T 'Reply', singular form
REPPLR {replies} T 'Replies', plural form


ATTNOT1 {
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

This message has an attached file named %s.
The file is %d bytes long.

The file is NOT included in your message packet.
To request it, send a blank message to %s and the keywords
REQUEST %s/%ld in the subject.
It'll be included in your next packet.
} T Message text: File attachment not included in your packet


ATTNOT2 {
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

This message has an attached file named %s.
The file is %d bytes long.
} T Message text: File attachment included in your packet


ATTNOT3 {
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

This message has an attached file named %s.
The file is %d bytes long.

If the file isn't in your message packet,
please send a blank message to %s and the keywords
REQUEST %s/%ld in the subject.
It'll be included in your next packet.
} T Message text: File attachment optionally included


ATTNOT4 {
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

This message has an attached file named %s.
The file is %d bytes long.
However, your access level does not allow the file to
be included in your packet.
} T Message text: File attachment not available to you


ATTNOT5 {
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

This message has an attached file named %s.
The file is %d bytes long.
However, the file hasn't yet been approved for download.
} T Message text: File attachment not approved


ATTNOT6 {
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

The message had an attached file, but the file couldn't be found.
Please notify the System Operator of this.
} T Message text: File not found or couldn't be opened


RRRINJ {[0;1m***

!J[32m%s[37m has just included your message in
an offline message packet. A return receipt has been
generated.!)
} T Return Receipt notification for receipt recipient



NOMSGS {[0;1;31m
!JThe packet doesn't seem to contain any reply files (.MSG).
Normally, a reply packet must include at least one file
named [37m%s.MSG[31m or [37m%s.MSG[31m (case doesn't matter).!)
[0;1m} T Unable to find a .MSG file in the reply packet


BADID {[0;1;31m
!JYour reply packet is for a BBS with codename "[37m%s[31m".
Packets intended for @BBS@ must be stamped with the codename
"[37m%s[31m". We can't accept this packet.!)
[0;1m} T Reply packet is stamped with the wrong BBS ID.


REPHD {[0;1;32m
To         Club             Status
!FÄ
} T Reply table: Header


REPTB {[0;1m%-10.10s %-16.16s } T Reply table: Recipient and SIG


REPTBALL {All} T Reply table: string for 'All'


REPTBIN {[31mInactive (erased?) message.
[0;1m} T Reply table: message is inactive (erased?)


REPTBNR {[31mNo recipient specified.
[0;1m} T Reply table: no recipient specified


REPTBUU {[31mUnknown recipient "%s".
[0;1m} T Reply table: unknown recipient


REPTBMF {[31mMalformed messsage!
[0;1m} T Reply table: malformed message


REPTBOK {[32mAccepted.
[0;1m} T Reply table: Message saved


REPTBAS {[33mAccepted, with "%s" as the sender.
[0;1m} T Reply table: Saved, sender user-ID corrected


REPTBRR {[32mAccepted. Return receipt requested.
[0;1m} T Reply table: Saved, return receipt requested


REPTBUS {[31mUnknown club. (recently deleted?)
[0;1m} T Reply table: Unknown SIG number


REPTB2B {[31mMessage longer than %d bytes.
[0;1m} T Reply table: Message too big


REPTBAG {[31mMessage already in BBS.
[0;1m} T Reply table: This message has already been uploaded


REPTBAE {[31mEmail message to ALL.
[0;1m} T Reply table: E-Mail message to ALL


REPTBES {[31mPrivate message in a club.
[0;1m} T Reply table: Recipient-only message in a SIG


REPTBPR {[31mPublic message with receipt request.
[0;1m} T Reply table: Public message with return receipt


REPTBCR {[31mNot enough credits.
[0;1m} T Reply table: Not enough credits to save


REPTBNA {[31mNot permitted by club security.
[0;1m} T Reply table: Club security restriction


REPTBCN {[33mAborted.
[0;1m} T Reply table: Message cancelled


DIRADD {[36mADD %s: } T Reply table: ADD directive


DIRDROP {[36mDROP %s: } T Reply table: DROP directive


DIRRESET {[36mRESET %s: } T Reply table: RESET directive


DIRRQST {[36mREQUEST %s: } T Reply table: REQUEST directive


DIRDONE {[32mAccepted.
[0;1m} T Reply table: Directive processed


DIRFOR {[36m%s: [32mWill process soon.
[0;1m} T Reply table: Directive is foreign, will be processed in a bit


DIRERR1 {[31mError in directive.
[0;1m} T Reply table: Error in directive


DIRERR2 {[31mI/O error.
[0;1m} T Reply table: I/O Error in directive


DIRRQUS {[31mUnknown club.
[0;1m} T Reply table: REQUEST/ADD/DROP, unknown club


DIRCANT {[31mNot allowed.
[0;1m} T Reply table: Can't manipulate E-Mail


DIRCNTR {[31mMust ADD before RESETting.
[0;1m} T Reply table: Must ADD before RESETting


DIRNFND {[31mREQUESTed file not found.
[0;1m} T Reply table: REQUESTed attachment not found


DIRNNEED {[33mNo need to do that.
[0;1m} T Reply table: No need to do that


NOCFMSG {[31mCan't process "CONFIG" messages.
[0;1m} T Reply table: Can't process CONFIG messages


ENDUL {[0;1;32m!FÄ
%d[37m of [32m%d[37m %s accepted.
[0;1m} T Reply table: Footer


ASKCLUB {[0;1m
!JPlease enter the name of a club to
forward your message, or [33mEmail[37m to store it in the Email area
(sent to you, if addressed to everyone), or [33mX[37m to drop
this message:[0m!) } T Re-enter club name


ASKCLBR {[0;1;31m
!JSorry, that club doesn't exist.!)
[0;1m} T Unknown club name


ASKERCP {[0;1m
!JPlease enter the name of the recipient,
or [33mX[37m to drop this message:[0m!) } T Re-enter ID of unknown E-Mail message recipient


ASKSRCP {[0;1m
!JPlease enter the name of the recipient,
[33mALL[37m to address it to everyone,
or [33mX[37m to drop this message:[0m!) } T Re-enter ID of unknown SIG message recipient


UNKUSR {[0;1;31m
!JThis user doesn't exist.!)
[0;1m} T Unknown user ID, please re-enter


EMLALL {[0;1;31m
Sorry, you can't address an email message to everyone.
[0;1m} T Can't supply "ALL" as E-Mail recipient


ASKEORS {[0;1m
!JYou can't send private messages to a club. Would you like to:!)

[[33mE[37m]mail:  forward the message to Email,
[[33mP[37m]ublic: make the message public and keep it in the club, or
[[33mC[37m]ancel: drop the message?

!JPlease enter your choice ([33mE[37m,[33mP[37m,[33mC[37m):!) [0m} T E-Mail message in a SIG: Make it private or public?


ASKRORS {[0;1m
!JYou can't request return receipts for public messages. Would you like to:!)

[[33mE[37m]mail:  forward the message to Email,
[[33mP[37m]ublic: remove the return receipt request, or
[[33mC[37m]ancel  drop the message?

!JPlease enter your choice ([33mE[37m,[33mP[37m,[33mC[37m):!) [0m} T Public return receipt: Make it private or cancel?


ASKDUPL {[0;1m

!JYou've sent this exact message before. Please answer 'yes' if you
know that the message has been deleted and you wish to send it again.!)

!WAccept the message anyway? ([[33mY[31m]es / [[33mN[31m]o) [0m!)} T Duplicate message; accept it anyway?


ASKDUPD {[Enter=[33mN[37m][0m } T ASKDUPL default answer


ASKERR {[0;1;31m
!JSorry, that isn't a valid choice at this point.!)
[0;1m} T Unknown option error for ASKxxxx menus


SIGINJ {[0;1m***

!J[32m%s[37m just sent you a message regarding "[32m%s[37m"
in club [32/%s[37m through the Off-line Mailer.
You can read it using the following commands (from the main menu):!)

([33mE[37m)mail ([33mR[37m)ead ([33mT[37m)o

!JOr enter [33m/GO ERT[37m wherever you are.!)
[0;1m} T Injected: You just got a SIG message through the Mailer


EMLINJ {[0;1m***

!J[32m%s[37m just sent you a message regarding "[32m%s[37m"
through the Off-line Mailer. You can read this message by
entering the following at the main menu:!)

([33mE[37m)mail ([33mR[37m)ead ([33mT[37m)o

!JOr enter [33m/GO ERT[37m wherever you are.!)
[0;1m} T Injected: You just got an E-Mail message through the Mailer


RQMUNS {[0;1;31m
!JThe following directives were not recognised:!)
[0;1;32m
To         Club             Status   
!FÄ
[0;1m} T The following requests were not satisfied


RQMTAB {[0;1m%-10.10s %-16.16s [36m%s: [31mUnknown directive.
[0;1m} T Unsatisfied request table row


ENDRQM {[0;1;32m!FÄ
[0;1m} T End of unsatisfied request table





LANGEND {}

