/*****************************************************************************\
 **                                                                         **
 **  FILE:     actions.h                                                    **
 **  AUTHORS:  Alexios                                                      **
 **  REVISION: A, August 96, Version 0.5                                    **
 **  PURPOSE:  Teleconferences, header file defining action data structs.   **
 **  NOTES:                                                                 **
 **  LEGALESE:                                                              **
 **                                                                         **
 **  This program is free software; you  can redistribute it and/or modify  **
 **  it under the terms of the GNU  General Public License as published by  **
 **  the Free Software Foundation; either version 2 of the License, or (at  **
 **  your option) any later version.                                        **
 **                                                                         **
 **  This program is distributed  in the hope  that it will be useful, but  **
 **  WITHOUT    ANY WARRANTY;   without  even  the    implied warranty  of  **
 **  MERCHANTABILITY or  FITNESS FOR  A PARTICULAR  PURPOSE.   See the GNU  **
 **  General Public License for more details.                               **
 **                                                                         **
 **  You  should have received a copy   of the GNU  General Public License  **
 **  along with    this program;  if   not, write  to  the   Free Software  **
 **  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.              **
 **                                                                         **
\*****************************************************************************/


/*
 * $Id$
 *
 * $Log$
 * Revision 1.1  2001/04/16 14:58:22  alexios
 * Initial revision
 *
 * Revision 0.2  1997/11/06 20:06:11  alexios
 * Added GPL legalese to the top of this file.
 *
 * Revision 0.1  1997/08/28 11:08:28  alexios
 * First registered revision. Adequate.
 *
 *
 */


#ifndef RCS_VER 
#define RCS_VER "$Id$"
#endif




#define ACTIONTYPES "SODAG"


#define TYPE_SIMPLE  'S'
#define TYPE_OBJECT  'O'
#define TYPE_DOUBLE  'D'
#define TYPE_ADVERB  'A'
#define TYPE_GENERIC 'G'


#define OBJ_NORMAL    0
#define OBJ_ALL       1
#define OBJ_SECRETLY  2


struct actionidx {
  char *verb;
  int  index;
};


#ifdef MKACTION

struct Saction {
  char *verb;
  char type;
  char *access;
  int  key;
  char *user[ML];
  char *simple[ML];
};


struct Oaction {
  char *verb;
  char type;
  char *access;
  int  key;
  char *user[ML];
  char *other[ML];
  char *all[ML];
  char *target[ML];
  char *secret[ML];
};


struct Daction {
  char *verb;
  char type;
  char *access;
  int  key;
  char *user[ML];
  char *simple[ML];
  char *other[ML];
  char *all[ML];
  char *target[ML];
  char *secret[ML];
};


struct Aaction {
  char *verb;
  char type;
  char *access;
  int  key;
  char *user[ML];
  char *simple[ML];
  char *adverb[ML];
};


struct Gaction {
  char *verb;
  char type;
  char *access;
  int  key;
  char *user[ML];
  char *generic[ML];
};


union action {
  struct Saction s;
  struct Oaction o;
  struct Daction d;
  struct Aaction a;
  struct Gaction g;
};


#define CODE_VERB      1
#define CODE_USER      2
#define CODE_SIMPLE    3
#define CODE_OTHER     4
#define CODE_ALL       5
#define CODE_TARGET    6
#define CODE_SECRET    7
#define CODE_ADVERB    8
#define CODE_GENERIC   9
#define CODE_ACCESS   10
#define CODE_KEY      11


struct keyword {
  char keyword[12];
  int  code;
} keywords[]={
  {"access",   CODE_ACCESS},
  {"adverb",   CODE_ADVERB},
  {"all",      CODE_ALL},
  {"generic",  CODE_GENERIC},
  {"key",      CODE_KEY},
  {"other",    CODE_OTHER},
  {"secret",   CODE_SECRET},
  {"simple",   CODE_SIMPLE},
  {"target",   CODE_TARGET},
  {"user",     CODE_USER},
  {"verb",     CODE_VERB},
  {"",-1}};


#define STRING(s) (s?s:"")

#define DUMP(f,v) for(n=0;n<ML;n++)fprintf(fout,f,i,n,STRING(v));


#define PREAMBLE \
"LEVEL2 {}\n\n"\
"WARNING {AUTOMATICALLY GENERATED BY mkaction. DO NOT EDIT.} "\
"T AUTOMATICALLY GENERATED BY mkaction. DO NOT EDIT.\n\n"\
"NUMVERBS {Number of action verbs following: %d} N 0 32767\n\n"\
"BEGNVERB {} T\n\n"

#define HEADER \
"A%03dVERB    {%s} T\n"\
"A%03dTYPE    {%c} T\n"\
"A%03dKEY     {%d} T\n"\
"A%03dACCS    {%s} T\n"

#define USER \
"A%03dUSER%02d  {%s} T\n"

#define SMPL \
"A%03dSMPL%02d  {%s} T\n"

#define OTHR \
"A%03dOTHR%02d  {%s} T\n"

#define SALL \
"A%03dSALL%02d  {%s} T\n"

#define TRGT \
"A%03dTRGT%02d  {%s} T\n"

#define SCRT \
"A%03dSCRT%02d  {%s} T\n"

#define ADVB \
"A%03dADVB%02d  {%s} T\n"

#define GNRC \
"A%03dGNRC%02d  {%s} T\n"

#define FOOTER \
"\n\n"

#endif /* MKACTION */
