LEVEL2 {}


ENTRYKEY {Key required to use notify: 2} N 0 129

INVKEY {Key required for notify invisibility: 8} N 0 129

SOPKEY {Key required to see through invisibility: 128} N 0 129

NUMUSR {Maximum number of users in notify list: 100} N 1 1000



LEVEL3 {}

NOENTRY {[0;1;31m
!JŠ¬§á£˜ , ›œ¤ â®œ«œ §¨æ©™˜© ©œ ˜¬«ã «¤ §œ¨ ¦®ã.!)
[0;1;31m} T User has no access to this module


MENU {[2J[0m[47;1;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;30;47m¿ [40m
[47;1;37m ³  [0;47;30m        €¬«æ£˜« œ ›¦§¦å© ©¬¤›â©œà¤ (Notify)         [0;47;30m³ [40m
[47;1;37m ³  [0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ  [0;47;30m³ [40m
[47;1;37m ³  [0;31;47mH[30melp  . . . . . . . . . . . . . . . .  ›šåœª ®¨ã©ª  [30m³ [40m
[47;1;37m ³  [0;31;47mL[30mist users . . . . . . . . . . . .  ‰˜«á¢¦š¦ª ®¨©«é¤  [30m³ [40m
[47;1;37m ³  [0;31;47mA[30mdd user  . . . . . . . . . . . . . . „ ©˜šàšã ®¨ã©«  [30m³ [40m
[47;1;37m ³  [0;31;47mD[30melete user  . . . . . . . . . . . .  ƒ ˜š¨˜­ã ®¨ã©«  [30m³ [40m
[47;1;37m ³                                                         [0;47;30m³ [40m
[47;1;37m ³ [0;30;47me[31mX[30mit  . . . . . . . . . . . . . . . . . . . . . „¥¦›¦ª  [30m³ [40m
[47;1;37m À[0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0;1m

€¬«æ£˜« œ ›¦§¦å© ©¬¤›â©œà¤ (notify)
˜¨˜¡˜¢é ›é©«œ «¤ œ§ ¢¦šã ©˜ª: [0m} T Notify menu


SHMENU {[0;1m
€¬«æ£˜« œ ›¦§¦å© ©¬¤›â©œà¤ (notify)
!Wƒé©«œ «¤ œ§ ¢¦šã ©˜ª ([33mH[37m,[33mL[37m,[33mA[37m,[33mD[37m,[33mX[37m š ˜ â¥¦›¦, ã [33m?[37m š ˜ «¦ £œ¤¦ç): !)[0m} T Notify short menu


ERRSEL {[0;1;31m
!WŠ¬§á£˜ , ›œ¤ ¬§á¨®œ   œ§ ¢¦šã "%c".!)
[0;1m} T Invalid option selection


LEAVE {[0;1m
!W„¥¦›¦ª ˜§æ «¤ €¬«æ£˜« œ ›¦§¦å©.!)
[0m} T Exiting to main menu


HELP {[0;1m
!J† ˜¬«æ£˜« œ ›¦§¦å© ©¬¤›â©œà¤ œå¤˜  â¤˜ª œç¡¦¢¦ª «¨æ§¦ª š ˜ ¤˜ ™¢â§œ«œ
§æ«œ ¡á§¦ ¦  ©¬š¡œ¡¨ £â¤¦  ®¨ã©«œª â®¦¬¤ ©¬¤›œŸœå ©«¤ @BBS@. ‹§¦¨œå«œ ¤˜ ¦¨å©œ«œ
£å˜ ¢å©«˜ ˜§æ £â®¨  [32m%d[37m ®¨ã©«œª. ‰áŸœ ­¦¨á §¦¬ â¤˜ª ˜§'˜¬«¦çª Ÿ˜ ©¬¤›âœ«˜ ,
«¦ ©ç©«£˜ Ÿ˜ ©˜ª œ ›¦§¦ œå. † ™á© ©˜ª œ ›¦§¦ œå œ§å©ª ¡˜«á « ©ç¤›œ©ã ©˜ª,
˜¤ ¡á§¦ ¦  ˜§æ «¦¬ª ®¨ã©«œª §¦¬ â®œ«œ ¦¨å©œ  œå¤˜  ã› ©¬¤›œ›œ£â¤¦ .!)

!J† ®¨ã© ˜¬«¦ç «¦¬ £œ¤¦ç œå¤˜  §¦¢ç ˜§¢ã. ‹œ «¤ œ¤«¦¢ã [[33mA[37m]dd
£§¦¨œå«œ ¤˜ §¨¦©Ÿâ©œ«œ â¤˜ ¯œ¬›é¤¬£¦ ©« ¢å©«˜ ©˜ª. ‹œ «¤ œ¤«¦¢ã
[[33mD[37m]elete ˜­˜ ¨œå«œ â¤˜ ¯œ¬›é¤¬£¦. ’â¢¦ª, £œ «¤ œ¤«¦¢ã
[[33mL[37m]ist £§¦¨œå«œ ¤˜ ›œå«œ « ¢å©«˜ ¯œ¬›à¤ç£à¤.!)

!J  ˜¢¢˜šâª ˜§¦Ÿ¡œç¦¤«˜  ¡˜   ©®ç¦¬¤ £œ «¤ â¥¦›æ ©˜ª ˜§æ «¦ £œ¤¦ç.!)
[0;1m} T Notify, help


ADDLIM {[0;1;31m
!J„®œ«œ ã› ­«á©œ  «¦ æ¨ ¦ «à¤ [37m%d[31m ¯œ¬›à¤ç£à¤ ©« ¢å©«˜ ©˜ª. €¤ Ÿâ¢œ«œ ¤˜
§¨¦©Ÿâ©œ«œ ¡á§¦ ¦ ¯œ¬›é¤¬£¦ Ÿ˜ §¨â§œ  ¤˜ ©™ã©œ«œ ¡á§¦ ¦ á¢¢¦.!)
[0;1m} T Add user, limit reached, can't add more users.


ADDLM2 {[0;1;31m
!J„®œ«œ [37m%d[31m ¯œ¬›é¤¬£˜ ©« ¢å©«˜ ©˜ª.  £âš ©«¦ª ˜¨ Ÿ£æª ¯œ¬›à¤ç£à¤
œå¤˜  [37m%d[31m (˜¬«æ ©¬¤â™œ  œ§œ ›ã ¦ •œ ¨ ©«ãª £œåà©œ «¦¤ £âš ©«¦ ˜¨ Ÿ£æ
¯œ¬›à¤ç£à¤). €¤ Ÿâ¢œ«œ ¤˜ §¨¦©Ÿâ©œ«œ ¡á§¦ ¦ ¯œ¬›é¤¬£¦ Ÿ˜ §¨â§œ  ¤˜ ­â¨œ«œ «¦¤
˜¨ Ÿ£æ ¯œ¬›à¤ç£à¤ ©« ¢å©«˜ ©˜ª ¡á«à ˜§æ «¦ æ¨ ¦.!)
[0;1m} T Add user, max number of users changed, too many users in list.


ADDASK {[0;1m
!Wƒé©«œ «¦ ¯œ¬›é¤¬£¦ «¦¬ £â¢¦¬ª §¦¬ Ÿâ¢œ«œ ¤˜ §¨¦©Ÿâ©œ«œ:!) [0m} T Add user, asking for ID


ADDHUH {[0;1;31m
!J‘˜ª ›å¤¦¬£œ «¦ ¢æš¦ £˜ª æ«  ›œ¤ ®¨œ áœ©«œ œ ›¦§¦å© æ«˜¤ ©¬¤›âœ©«œ ©«
™á©. ƒœ¤ â®œ  ¤æ£˜ ¤˜ â®œ«œ «¦ ¯œ¬›é¤¬£æ ©˜ª ©«¤ å› ˜ ©˜ª « ¢å©«˜!!)
[0;1m} T Won't add own username to list


ADDERR {[0;1;31m
!JŠ¬§á£˜ , ›œ¤ ¬§á¨®œ  ¯œ¬›é¤¬£¦ "[37m%s[31m" ©« ™á©.!)
[0;1m} T Add user, user ID does not exist


ADDEXS {[0;1;31m
!J’¦ ¯œ¬›é¤¬£¦ "[37m%s[31m" ¬§á¨®œ  ã› ©« ¢å©«˜ ©˜ª.!)
[0;1m} T add user, user ID is already on the list


ADDOK {[0;1;32m
!J%s [37m%s[32m §¨¦©«âŸ¡œ ©« ¢å©«˜ ©˜ª.!)
[0;1m} T Add user, all is well


ADDSEXM {} T Add user, male definite article
ADDSEXF {†} T Add user, female definite article


NOUSERS {[0;1;31m
!Jƒœ¤ ¬§á¨®¦¬¤ ¯œ¬›é¤¬£˜ ©« ¢å©«˜ ©˜ª.!)
[0;1m} T No users in the list


DELASK {[0;1m
!Wƒé©«œ «¦ ¯œ¬›é¤¬£¦ «¦¬ £â¢¦¬ª §¦¬ Ÿâ¢œ«œ ¤˜ ˜­˜ ¨â©œ«œ:!) [0m} T Delete user, asking for ID


DELERR {[0;1;31m
!JŠ¬§á£˜ , ›œ¤ ¬§á¨®œ  «¦ ¯œ¬›é¤¬£¦ "[37m%s[31m" ©« ¢å©«˜ ©˜ª.!)
[0;1m} T Delete user, user ID does isn't on the list


DELOK {[0;1;32m
!J’¦ ¯œ¬›é¤¬£¦ [37m%s[32m ˜­˜ ¨âŸ¡œ ˜§æ « ¢å©«˜ ©˜ª.!)
[0;1m} T Add user, all is well


LISTHD {[0;1;32m
‰˜«á¢¦š¦ª ¯œ¬›à¤ç£à¤ š ˜ «˜ ¦§¦å˜ Ÿ˜ ©˜ª œ ›¦§¦ œå «¦ ©ç©«£˜:
[0;1m
!FÄ
} T List users, header


LISTU {%s
} T List one single user


LISTFT {[0;1m!FÄ

[32m–œ¬›é¤¬£˜ ©« ¢å©«˜ ©˜ª: [37m%d[32m.
[0;1m} T List users, footer


INJMSG {[0;1;35m***
!J‹æ¢ ª ©¬¤›âŸ¡œ %s [37m%s[35m!!)
[0;1m} T Injoth notification message


SEXM {¦} T Male definite article
SEXF {} T Female definite article


LOGIN1 {[0;1;35m
!J„å¤˜  ã› ©¬¤›œ›œ£â¤%s } T Login message, part 1

CONM {¦ª} T 'connected', male form

CONF {} T 'connected', female form

CONP {¦ } T 'connected', plural form

LOGIN2 {%s [37m%s[35m} T Login message, user name.

LOGIN3 {, } T Login message, connective (comma)

LOGIN4 { ¡˜  } T Login message, connective (and)

LOGIN5 {.!)
[0;1m} T Login message, terminator (period and footer)
