/***********************************************************
 **                                                       **
 **  This header file generated by msgidx. Do not alter.  **
 **                                                       **
 ***********************************************************/

#ifndef __TELECON_BG_UNAMBIGUOUS__
#define	WAITACC 1
#define	HELP0 2
#define	HELP1 3
#define	UNKUID 4
#define	NOTSELF 5
#define	OKUID 6
#define	SEXM 7
#define	SEXF 8
#define	SEXML 9
#define	SEXFL 10
#define	BGREQ 11
#define	ACCPAT 12
#define	REQPAT 13
#define	BGALR 14
#define	ACCTMOUT 15
#define	REQTMOUT 16
#define	BOARD 17
#define	BDLINE 18
#define	BDCOL1 19
#define	BDCOL2 20
#define	BDSTN1 21
#define	BDSTN2 22
#define	BDSTNN 23
#define	BDEMPT 24
#define	ANNOUNCE 25
#define	ROLL1WIN 26
#define	ROLL1LOS 27
#define	ROL13RD 28
#else
#define	TELECON_BG_WAITACC 1
#define	TELECON_BG_HELP0 2
#define	TELECON_BG_HELP1 3
#define	TELECON_BG_UNKUID 4
#define	TELECON_BG_NOTSELF 5
#define	TELECON_BG_OKUID 6
#define	TELECON_BG_SEXM 7
#define	TELECON_BG_SEXF 8
#define	TELECON_BG_SEXML 9
#define	TELECON_BG_SEXFL 10
#define	TELECON_BG_BGREQ 11
#define	TELECON_BG_ACCPAT 12
#define	TELECON_BG_REQPAT 13
#define	TELECON_BG_BGALR 14
#define	TELECON_BG_ACCTMOUT 15
#define	TELECON_BG_REQTMOUT 16
#define	TELECON_BG_BOARD 17
#define	TELECON_BG_BDLINE 18
#define	TELECON_BG_BDCOL1 19
#define	TELECON_BG_BDCOL2 20
#define	TELECON_BG_BDSTN1 21
#define	TELECON_BG_BDSTN2 22
#define	TELECON_BG_BDSTNN 23
#define	TELECON_BG_BDEMPT 24
#define	TELECON_BG_ANNOUNCE 25
#define	TELECON_BG_ROLL1WIN 26
#define	TELECON_BG_ROLL1LOS 27
#define	TELECON_BG_ROL13RD 28
#endif /* __TELECON_BG_UNAMBIGUOUS__ */
