/***********************************************************
 **                                                       **
 **  This header file generated by msgidx. Do not alter.  **
 **                                                       **
 ***********************************************************/

#ifndef __BBSDIALOG_UNAMBIGUOUS__
#define	VHELP 1
#define	FHHDR 2
#define	FHBUTN 3
#define	FHFTR 4
#define	NO 5
#define	YES 6
#define	PROMPT 7
#define	ERRSEL 8
#define	FIELD 9
#define	NERR 10
#define	DERR 11
#define	UERR 12
#define	CERR 13
#define	CLSLSTHDR 14
#define	CLSLSTTAB 15
#define	CLSLSTEND 16
#define	FCAN 17
#define	LISTMHDR 18
#define	LISTMENU 19
#define	LISTMFTR 20
#define	LIST 21
#define	TOGON 22
#define	TOGOFF 23
#define	CONFIRM 24
#define	CONFERR 25
#else
#define	BBSDIALOG_VHELP 1
#define	BBSDIALOG_FHHDR 2
#define	BBSDIALOG_FHBUTN 3
#define	BBSDIALOG_FHFTR 4
#define	BBSDIALOG_NO 5
#define	BBSDIALOG_YES 6
#define	BBSDIALOG_PROMPT 7
#define	BBSDIALOG_ERRSEL 8
#define	BBSDIALOG_FIELD 9
#define	BBSDIALOG_NERR 10
#define	BBSDIALOG_DERR 11
#define	BBSDIALOG_UERR 12
#define	BBSDIALOG_CERR 13
#define	BBSDIALOG_CLSLSTHDR 14
#define	BBSDIALOG_CLSLSTTAB 15
#define	BBSDIALOG_CLSLSTEND 16
#define	BBSDIALOG_FCAN 17
#define	BBSDIALOG_LISTMHDR 18
#define	BBSDIALOG_LISTMENU 19
#define	BBSDIALOG_LISTMFTR 20
#define	BBSDIALOG_LIST 21
#define	BBSDIALOG_TOGON 22
#define	BBSDIALOG_TOGOFF 23
#define	BBSDIALOG_CONFIRM 24
#define	BBSDIALOG_CONFERR 25
#endif /* __BBSDIALOG_UNAMBIGUOUS__ */
