/***********************************************************
 **                                                       **
 **  This header file generated by msgidx. Do not alter.  **
 **                                                       **
 ***********************************************************/

#ifndef __MOLBBSX_UNAMBIGUOUS__
#define	FILE01                                     1
#define	XGRASTT                                    2
#define	XGRAFN                                     3
#define	XNEWSTT                                    4
#define	XNEWFN                                     5
#define	XBLTSTT                                    6
#define	XBLTFN                                     7
#define	XBLTLST                                    8
#define	XDUNCP                                     9
#define	XGRAOPT                                   10
#define	XGRAASKL                                  11
#define	XGRANERR                                  12
#define	XGRAASKA                                  13
#define	XGRADHDR                                  14
#define	XGRADMT                                   15
#define	XGRAWRH                                   16
#define	XGRAWMT                                   17
#define	XGRAWRT                                   18
#define	XGRANWR                                   19
#define	XNEWOPT                                   20
#define	XNEWDHDR                                  21
#define	XNEWDMT                                   22
#define	XBLTOPT                                   23
#define	XBLTDRQL                                  24
#define	XBLTDHDR                                  25
#define	XBLTDMT                                   26
#define	XBLTLS0                                   27
#define	XBLTLS1                                   28
#define	XBLTLS2                                   29
#define	XBLTLS3                                   30
#define	XBLTULS                                   31
#define	XBLTURT                                   32
#define	XBLTREQ                                   33
#define	XBLTNFD                                   34
#define	XBLTUOK                                   35
#else
#define	MOLBBSX_FILE01                             1
#define	MOLBBSX_XGRASTT                            2
#define	MOLBBSX_XGRAFN                             3
#define	MOLBBSX_XNEWSTT                            4
#define	MOLBBSX_XNEWFN                             5
#define	MOLBBSX_XBLTSTT                            6
#define	MOLBBSX_XBLTFN                             7
#define	MOLBBSX_XBLTLST                            8
#define	MOLBBSX_XDUNCP                             9
#define	MOLBBSX_XGRAOPT                           10
#define	MOLBBSX_XGRAASKL                          11
#define	MOLBBSX_XGRANERR                          12
#define	MOLBBSX_XGRAASKA                          13
#define	MOLBBSX_XGRADHDR                          14
#define	MOLBBSX_XGRADMT                           15
#define	MOLBBSX_XGRAWRH                           16
#define	MOLBBSX_XGRAWMT                           17
#define	MOLBBSX_XGRAWRT                           18
#define	MOLBBSX_XGRANWR                           19
#define	MOLBBSX_XNEWOPT                           20
#define	MOLBBSX_XNEWDHDR                          21
#define	MOLBBSX_XNEWDMT                           22
#define	MOLBBSX_XBLTOPT                           23
#define	MOLBBSX_XBLTDRQL                          24
#define	MOLBBSX_XBLTDHDR                          25
#define	MOLBBSX_XBLTDMT                           26
#define	MOLBBSX_XBLTLS0                           27
#define	MOLBBSX_XBLTLS1                           28
#define	MOLBBSX_XBLTLS2                           29
#define	MOLBBSX_XBLTLS3                           30
#define	MOLBBSX_XBLTULS                           31
#define	MOLBBSX_XBLTURT                           32
#define	MOLBBSX_XBLTREQ                           33
#define	MOLBBSX_XBLTNFD                           34
#define	MOLBBSX_XBLTUOK                           35
#endif /* __MOLBBSX_UNAMBIGUOUS__ */
