/***********************************************************
 **                                                       **
 **  This header file generated by msgidx. Do not alter.  **
 **                                                       **
 ***********************************************************/

#ifndef __MENUMAN_UNAMBIGUOUS__
#define	DEFCCR 1
#define	TOPPAG 2
#define	EXTPAG 3
#define	USESHM 4
#define	RETMENU 5
#define	EXTMENU 6
#define	RELOGSTG 7
#define	KEYREL 8
#define	DEFDESCR 9
#define	XITDESCR 10
#define	MENPRO 11
#define	MENEPI 12
#define	SHMBEG 13
#define	SHMOPT 14
#define	SHMLOP 15
#define	SHMEND 16
#define	SHMPRM 17
#define	ERRSEL 18
#define	NOAXES1 19
#define	NOAXES2 20
#define	CANTXEC 21
#define	RUSXITN 22
#define	RUSXITL 23
#else
#define	MENUMAN_DEFCCR 1
#define	MENUMAN_TOPPAG 2
#define	MENUMAN_EXTPAG 3
#define	MENUMAN_USESHM 4
#define	MENUMAN_RETMENU 5
#define	MENUMAN_EXTMENU 6
#define	MENUMAN_RELOGSTG 7
#define	MENUMAN_KEYREL 8
#define	MENUMAN_DEFDESCR 9
#define	MENUMAN_XITDESCR 10
#define	MENUMAN_MENPRO 11
#define	MENUMAN_MENEPI 12
#define	MENUMAN_SHMBEG 13
#define	MENUMAN_SHMOPT 14
#define	MENUMAN_SHMLOP 15
#define	MENUMAN_SHMEND 16
#define	MENUMAN_SHMPRM 17
#define	MENUMAN_ERRSEL 18
#define	MENUMAN_NOAXES1 19
#define	MENUMAN_NOAXES2 20
#define	MENUMAN_CANTXEC 21
#define	MENUMAN_RUSXITN 22
#define	MENUMAN_RUSXITL 23
#endif /* __MENUMAN_UNAMBIGUOUS__ */
