/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "metaservices.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif
#include "parallelism.h"

static void
metabbs_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		registration_package_t metabbs_register_1_arg;
		registration_package_t metabbs_register_non_megistos_1_arg;
		char *metabbs_request_info_1_arg;
		club_list_request_t distclub_request_list_1_arg;
		club_header_request_t distclub_request_header_1_arg;
		ihave_request_t distclub_request_ihave_1_arg;
		message_request_t distclub_request_message_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case metabbs_register:
		_xdr_argument = (xdrproc_t) xdr_registration_package_t;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) metabbs_register_1_svc;
		break;

	case metabbs_register_non_megistos:
		_xdr_argument = (xdrproc_t) xdr_registration_package_t;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) metabbs_register_non_megistos_1_svc;
		break;

	case metabbs_request_info:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_info_package_p;
		local = (char *(*)(char *, struct svc_req *)) metabbs_request_info_1_svc;
		break;

	case distclub_request_list:
		_xdr_argument = (xdrproc_t) xdr_club_list_request_t;
		_xdr_result = (xdrproc_t) xdr_club_list;
		local = (char *(*)(char *, struct svc_req *)) distclub_request_list_1_svc;
		break;

	case distclub_request_header:
		_xdr_argument = (xdrproc_t) xdr_club_header_request_t;
		_xdr_result = (xdrproc_t) xdr_club_header;
		local = (char *(*)(char *, struct svc_req *)) distclub_request_header_1_svc;
		break;

	case distclub_request_ihave:
		_xdr_argument = (xdrproc_t) xdr_ihave_request_t;
		_xdr_result = (xdrproc_t) xdr_ihave_list;
		local = (char *(*)(char *, struct svc_req *)) distclub_request_ihave_1_svc;
		break;

	case distclub_request_message:
		_xdr_argument = (xdrproc_t) xdr_message_request_t;
		_xdr_result = (xdrproc_t) xdr_club_message;
		local = (char *(*)(char *, struct svc_req *)) distclub_request_message_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (METABBS_PROG, METABBS_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, METABBS_PROG, METABBS_VERS, metabbs_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (METABBS_PROG, METABBS_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, METABBS_PROG, METABBS_VERS, metabbs_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (METABBS_PROG, METABBS_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
