/* Automatically generated by mkversion.sh , do NOT edit. */

#define BJ_MAJORVERSION "0"
#define BJ_MINORVERSION "7"
#define BJ_COMPILED_BY  "bbs@vennea"
#define BJ_MAKE_NUMBER  "291"
#define BJ_DATE         "00-11-28 19:35"
