LEVEL2 {}

UNIXSH {/bin/bash -login} S 30 Full name of shell?

SXFDESC {Remote Sysop transfer request} S 50 File upload description

KEYCHU {Key required to show users' names in channel listings: 128} N 0 129

KYDNAM {Key required to show NAME field in DETAIL INFO: 0} N 0 129

KYDCOM {Key required to show COMPANY field in DETAIL INFO: 0} N 0 129

KYDADR {Key required to show ADDRESS field in DETAIL INFO: 0} N 0 129

KYDPHO {Key required to show PHONE field in DETAIL INFO: 0} N 0 129

KYDAGE {Key required to show AGE field in DETAIL INFO: 0} N 0 129

KYDSEX {Key required to show SEX field in DETAIL INFO: 0} N 0 129

KYDPSS {Key required to show PASSWORD field in DETAIL INFO: 129} N 0 129

HIDEPASS {Hide passwords from DETAIL VIEW, regardless of key? NO} B

DFWARN {Free disk space needs attention at what capacity percentage? 75} N 0 100

DFCRIT {Free disk space is critical at what capacity percentage? 90} N 0 100

PGSTMO {Sysop page notification stays blinking for how long (mins)? 5} N 1 9999


LEVEL3 {}




NARSOP {[0;1;31m
‘¬šš¤é£, ›œ¤ â®œ«œ §¨æ©™˜© ©œ ˜¬«ã «¤ œ§ ¢¦šã.
[0;1m
} T You don't have access to this service


EXITRS {[0;1m
„¥¦›¦ª ˜§æ « ª œ§ ¢¦šâª ®œ ¨ ©«é¤...
} T Remote Sysop exit to main menu


RSHDR {[0;1;33m!Z ©œ™˜©£æª æ¢à¤ «à¤ •¨©«é¤ œå¤˜   ˜¨®ã «à¤ œ¡¢œ¡«é¤ «ª @BBS@.
 
} T Remote Sysop menu header


RSCOM01 {[31m%sCHANGE . . Change/view channel status  „£­á¤ ©/˜¢¢˜šã ¡˜«á©«˜©ª ¡˜¤˜¢ é¤
} T Remote sysop command description


RSCOM02 {[31m%sEMULATE  . Inspect a channel  . . . . . . . . . . . .  ˜¨˜«ã¨© ¡˜¤˜¢ ¦ç
} T Remote sysop command description


RSCOM03 {[31m%sMONITOR  . Inspect channel input  . . . . . .  ˜¨˜«ã¨© œ ©æ›¦¬ ¡˜¤˜¢ é¤
} T Remote sysop command description


RSCOM04 {[31m%sSEND . . . Send a message to user(s)  . .  €§¦©«¦¢ã £¤ç£˜«¦ª ©œ ®¨ã©«/œª
} T Remote sysop command description


RSCOM05 {[32m%sDELETE . . Delete a user's account  . . . . .  ƒ ˜š¨˜­ã ¢¦š˜¨ ˜©£¦ç ®¨ã©«
} T Remote sysop command description


RSCOM06 {[32m%sDETAIL . . Get info about user  . . . . . .  ¢¨¦­¦¨åœª š ˜ ¡á§¦ ¦ ®¨ã©«
} T Remote sysop command description


RSCOM07 {[32m%sEXEMPT . . (Un)protect user from deletion . . . . (‹)-› ˜š¨á¯ £¦ª ®¨ã©«ª
} T Remote sysop command description


RSCOM08 {[32m%sHANGUP . . Disconnect a user  . . . . . . . . . . . . .  €§¦©ç¤›œ© ®¨ã©«
} T Remote sysop command description


RSCOM09 {[32m%sPOST . . . Give credits to a user . . . . . . .  €§æ›¦© £¦¤á›à¤ ©œ ®¨ã©«
} T Remote sysop command description


RSCOM10 {[32m%sSEARCH . . Search user database . . . . „¨œ¬¤˜ «ª ™á©ª ›œ›¦£â¤à¤ ®¨©«é¤
} T Remote sysop command description


RSCOM11 {[32m%sSUSPEND  . Toggle user's lockout flag . €¢¢˜šã › ¡˜ é£˜«¦ª ©ç¤›œ©ª ®¨ã©«
} T Remote sysop command description


RSCOM12 {[33m%sAUDIT  . . Inspect system log file  . . „§ Ÿœé¨© «à¤ logs «¦¬ ©¬©«ã£˜«¦ª
} T Remote sysop command description


RSCOM13 {[33m%sCLEANUP  . Inspect cleanup log file . . .  „§ Ÿœé¨© «à¤ logs «¦¬ cleanup
} T Remote sysop command description


RSCOM14 {[33m%sEVENT  . . Schedule and cancel events . . ¨¦š¨˜££˜« ©£æª œ › ¡é¤ œ¨š˜© é¤
} T Remote sysop command description


RSCOM15 {[33m%sFILTAUD  . Search the Audit Trail . . . . . . . . . –á¥ £¦ «¦¬ Audit Trail
} T Remote sysop command description


RSCOM16 {[33m%sLOGON  . . Change login message . . . . . . .  €¢¢˜šã œ ©˜šàš ¡¦ç ¡œ £â¤¦¬
} T Remote sysop command description


RSCOM17 {[33m%sSECURITY . Security logs  . . . . . . . .  „§ Ÿœé¨© ˜©­˜¢œå˜ª ©¬©«ã£˜«¦ª
} T Remote sysop command description


RSCOM18 {[33m%sSIGNUPS  . View recent signups  . . . . . .  „§ Ÿœé¨© §¨æ©­˜«à¤ œšš¨˜­é¤
} T Remote sysop command description


RSCOM19 {[34m%sAGESTATS . System demographics  . . . . .  ƒ£¦š¨˜­ ¡á ©«¦ ®œå˜ ©¬©«ã£˜«¦ª
} T Remote sysop command description


RSCOM20 {[34m%sCLSSTATS . Class statistics . . . . . . ‘«˜« ©« ¡á ©«¦ ®œå˜ š ˜ «˜ classes
} T Remote sysop command description


RSCOM21 {[34m%sGENSTATS . Generic statistics . . . . . .  ‚œ¤ ¡œ¬£â¤˜ ©«˜« ©« ¡á ©«¦ ®œå˜
} T Remote sysop command description


RSCOM22 {[34m%sLINSTATS . Linux statistics . . . . . . ‘«˜« ©« ¡á ¢œ «¦¬¨š ¡¦ç ©¬©«ã£˜«¦ª
} T Remote sysop command description


RSCOM23 {[34m%sMODSTATS . Module statistics  . . . . . ‘«˜« ©« ¡á ©«¦ ®œå˜ š ˜ «˜ modules
} T Remote sysop command description


RSCOM24 {[34m%sSYSTATS  . System statistics  . . . . . . . . . ‚œ¤ ¡á ©«˜« ©« ¡á ©«¦ ®œå˜
} T Remote sysop command description


RSCOM25 {[34m%sTOP  . . . User TOP lists . . . . . . . . . . .  ¦©¦« ¡ã ¡˜«á«˜¥ ®¨©«é¤
} T Remote sysop command description


RSCOM26 {[35m%sCLASSED  . Class Editor . . . . . . . . . . . . . .  •œ ¨ ©£æª «à¤ classes
} T Remote sysop command description


RSCOM27 {[35m%sKEYS . . . Edit user's key list . . €¢¢˜šã «ª ¢å©«˜ª ¡¢œ › é¤ œ¤æª ®¨ã©«
} T Remote sysop command description


RSCOM28 {[35m%sUSERCLASS  Change a user's class  . . . . . . €¢¢˜šã «¦¬ class œ¤æª ®¨ã©«
} T Remote sysop command description


RSCOM29 {[36m%sCOPY . . . Copy a file  . . . . . . . . . . . . . . . .  €¤« š¨˜­ã ˜¨®œå¦¬
} T Remote sysop command description


RSCOM30 {[36m%sDIR  . . . File directory . . . . . . . . . . . . . . .  ‰˜«á¢¦š¦ª ˜¨®œåà¤
} T Remote sysop command description


RSCOM31 {[36m%sEDITOR . . Invoke the editor  . . . . . . . . .  ‰¢ã© «¦¬ editor ¡œ £â¤¦¬
} T Remote sysop command description


RSCOM32 {[36m%sREN  . . . Rename or move a file  . . . . ‹œ«¦¤¦£˜©å˜ ã £œ«˜¡å¤© ˜¨®œå¦¬
} T Remote sysop command description


RSCOM33 {[36m%sRM . . . . Delete a file  . . . . . . . . . . . . . . . . ƒ ˜š¨˜­ã ˜¨®œå¦¬
} T Remote sysop command description


RSCOM34 {[36m%sRUN  . . . Execute a Unix command . . . . . . . . .  „¡«â¢œ© œ¤«¦¢ãª Unix
} T Remote sysop command description


RSCOM35 {[36m%sSHELL  . . Jump to a Unix shell . . . . .  ¨¦©à¨ ¤ã â¥¦›¦ª ©«¦ Unix shell
} T Remote sysop command description


RSCOM36 {[36m%sTRANSFER . Upload/download files  . . . . . . . . .  €§¦©«¦¢ã/¢ã¯ ˜¨®œåà¤
} T Remote sysop command description


RSCOM37 {[36m%sTYPE . . . Display a text file  . . . . . . „£­á¤ © œ¤æª ˜¨®œå¦¬ ¡œ £â¤¦¬
} T Remote sysop command description


RSCOM38 {[37m%sGDET  . .  Global DETAIL (/L)  . . . . . . . . . . . . . . . . . „¤«¦¢ã /L
} T Remote sysop command description


RSCOM39 {[37m%sINVIS . .  Invisible Sysop (/invis)  . . . . .  €æ¨˜«¦ª ®œ ¨ ©«ãª (/invis)
} T Remote sysop command description


RSCOM40 {[37m%sPAGEAUDIT  Global Audit Notification . . „ ›¦§¦å© š ˜ Audit ¡˜«˜®à¨ã©œ ª
} T Remote sysop command description


RSCOM41 {[37m%sSYSOP  . . System Operator privileges . . . . ¨¦¤æ£ ˜ ®œ ¨ ©«ã ©¬©«ã£˜«¦ª
} T Remote sysop command description


OPTSEP {
} T Remote Sysop menu option separator


OPTON {=> } T Remote Sysop menu option enabled


OPTOFF {   } T Remote Sysop menu option disabled


RSSMNU {[1;37m
„ˆŠ‚„‘ •„ˆˆ‘’—Œ
ƒé©«œ «¤ œ¤«¦¢ã ©˜ª (ã ? š ˜ menu): [0m} T Remote Sysop short prompt


ERRCOM {[0;1;31m
€¬«ã  œ¤«¦¢ã ›œ¤ ¬§á¨®œ . €¡æ£˜ ¤˜ «¦ £áŸœ ª «¦ £œ¤¦ç;;; 8-)
[0;1m} T Remote Sysop generic invalid option


MORCHR {[0;1;31m
’¦ "%s" «˜ ¨ áœ  ©œ §á¤à ˜§æ £å˜ œ¤«¦¢ã...
} T Remote Sysop need more characters to distinguish commands


NUMERR {[0;1;31m
˜¨˜¡˜¢é ›é©«œ â¤˜¤ ˜¨ Ÿ£æ ˜§æ %d àª %d.
[0;1m} T Remote Sysop generic numeric error


UNKUID {[0;1;31m
’©¡ «©¡ «©¡... ƒœ¤ ¬§á¨®œ  ®¨ã©«ª "%s".
[0;1m} T Generic error: no such user


NOAXES {[0;1;31m
‘¬šš¤é£, ›œ¤ â®œ«œ §¨æ©™˜© ©«¤ œ§ ¢¦šã %s.
[0;1m
} T Remote Sysop no access to that option


EXECERR {[0;1;31m
ƒœ¤ £§æ¨œ©œ ¤˜ œ¡«œ¢œ©«œå  œ¤«¦¢ã ©˜ª...
[0;1m} T Couldn't exec external program


CRDSING {} T "Credit" singular form
CRDPLUR {s} T "Credits" plural form

MSCACC {¦¤} T Male user accusative
FEMACC {¤} T Female user accusative


NOTIFIED {[0;1;32m
’¦ £â¢¦ª %s œå¤˜  ©¬¤›œ›œ£â¤¦ ¡˜  œ ›¦§¦ ãŸ¡œ.
} T User on-line and notifed




RSCHANGEWHT {[0;1m
!W‹œ §¦ ¦ ¡˜¤á¢  Ÿ˜ §˜å¥¦¬£œ, ˜­œ¤« ¡æ; ƒé©œ ˜¨ Ÿ£æ ¡˜¤˜¢ ¦ç,
æ¤¦£˜ unix tty (§® ttyS1), ALL ã * š ˜ æ¢˜ «˜ ¡˜¤á¢ ˜, ã ? š ˜ ¡˜«á¢¦š¦:!) [0m} T Change channel status: Which one?


RSCHANGEERR {[0;1;31m
“§á¨®œ  ¡á§¦ ¦ª ®¨ã©«ª ©'˜¬«ã «¤ š¨˜££ã. €§¦©¬¤›â©«œ «¦¤ ¡˜  ¥˜¤˜§¨¦©§˜Ÿã©«œ.
[0;1m} T Change channel status: There's a user in that channel


RSCHANGELMN {[0;1;37m
¦ ˜ œå¤˜   ¤â˜ ¡˜«á©«˜©;

[37mR[32mESET (NORMAL) . . . . . . . . . . . ‰˜¤¦¤ ¡ã,  š¨˜££ã ›â®œ«˜  ®¨ã©«œª.
[37mB[32mUSY-OUT  . . . . . . . . ‰˜«â™˜©£˜ ˜¡¦¬©« ¡¦ç,  š¨˜££ã £ ¢áœ  ©¬¤œ®éª.
[37mN[32mO-ANSWER  . . . . . . . . . . . . . † š¨˜££ã ›œ¤ ˜§˜¤«áœ  ©« ª ¡¢ã©œ ª.
[37mO[32mFF-LINE . . † š¨˜££ã ˜§˜¤«áœ , «¬§é¤œ  â¤˜ ©ç¤«¦£¦ £ã¤¬£˜, ¡˜  ¡¢œå¤œ .
[0;1m} T Change channel status: Long menu

RSCHANGESMN {[0;1m
ƒé©«œ «¤ œ§ ¢¦šã ©˜ª ([33mR[37m,[33mB[37m,[33mN[37m,[33mO[37m, ? š ˜ £œ¤¦ç, ã X š ˜ â¥¦›¦): [0m} T Change channel status: Short menu


RSCHANGEBAD {[0;1;31m
Š¬§á£˜ , ˜¬«ã  œ§ ¢¦šã ›œ¤ œå¤˜  ›¬¤˜«ã.
[0;1m} T Change channel status: Wrong selection


RSCHANGEOK {[0;1;32m
!J‰˜¢éª,  ˜¢¢˜šã ¡˜«á©«˜©ª «ãŸ¡œ ˜§æ «¦ ©ç©«£˜ ¡˜  ¨¬Ÿ£åœ«˜ .!)
} T Change channel status: Done, submitting new status
 


RSEMUWHO {[0;1m
!W¦ ¦¤ Ÿ˜ œ£¦¬¢á¨œ ª §á¢ , ©«¬šœ¨â ©ç©¦§˜;
ƒé©œ ˜¨ Ÿ£æ ¡˜¤˜¢ ¦ç, æ¤¦£˜ unix tty (§® ttyS1), ¯œ¬›é¤¬£¦, ã ? š ˜ ¡˜«á¢¦š¦:!) [0m} T Emulate channel: Which one?


RSEMUSLF {[0;1;31m
ƒœ¤ â®œ  ¡˜  §¦¢ç ¤æ£˜ ¤˜ ¡á¤œ ª emulate «¦¤ œ˜¬«æ ©¦¬!
[0;1m} T Emulate channel: can't emulate self


RSEMUHAHA {[0;1;31m
!J„, æ® ! ’  ©¦¬ œå¤˜  ˜¬«¦å ¦  ©«˜¢ ¤ ¡¦å. ¨¦©§˜Ÿœåª ¤˜ œ£¦¬¢á¨œ ª
¡á§¦ ¦¤ §¦¬ ©œ œ£¦¬¢á¨œ  ã›.  œ£¦¬¢á¨à¤ «¦¬ œ£¦¬¢á¨¦¤«¦ª. :-)!)
[0;1m} T Emulate channel: attempt to establish circular emulation


RSEMUNUS {[0;1;31m
!J•££... ˜¬«æ «¦ ¡˜¤á¢  ›œ¤ œå¤˜  ›˜ £¦¤ ©£â¤¦ ˜§æ «¦¤ emulation daemon
(emud), ¡  â«©  ›œ¤ £§¦¨œåª ¤˜ «¦ ¡á¤œ ª emulate. ¨¦©§˜Ÿœåª £á¢¢¦¤ ¤˜
emulá¨œ ª â¤˜ ˜›¨˜¤âª ©œ ¨ ˜¡æ ¡˜¤á¢ .!)
[0;1m} T Emulate channel: can't emulate 'emud'-less channel


RSEMUGO {
[0;47;30m[K Emulating... [1;33mCtrl-Q[0;47;30m = â¥¦›¦ª, [1;33mCtrl-C[0;47;30m = SYSOP CHAT, [1;33mCtrl-Z[0;47;30m = HANGUP !F-
[0;1m[K} T Emulate channel: beginning emulation


RSEMUEND {
[0;47;30m[K ’â¢¦ª Emulation !F-
[0;1m[K} T Emulate channel: end of emulation


RSEMUHUP {
[0;1;45;37m[K  ®¨ã©«ª ˜§¦©¬¤›âŸ¡œ.
[0;1m[K} T Emulate channel: user zapped out


RSEMUNOE {
!J[0;1m ®¨ã©«ª ˜§¦©¬¤›âŸ¡œ (ã «¨â®œ  ¡á«  §¦¬ ›œ¤ ›â®œ«˜ 
emulation).!)
[0;1m} T Emulate channel: user disconnected.


RSEMUCHT {[0;1m
!W[0;1;33;5mÛÛ[0;1;33m  ¨¦œ ›¦§¦å©: !i ®¨ã©«ª â®œ  œš¡˜«˜¢­Ÿœå ©«¦
sysop chat mode, ˜§'æ§¦¬ ›œ¤ £§¦¨œå ¤˜ ™šœ  ®à¨åª « ™¦ãŸœ á ©˜ª.!)
!0l[0;1m} T Emulate channel: user abandoned in sysop chat mode


RSMONITORHDR {[0;1m[2J
‰€Œ€Šˆ      ‰„ˆ‹„Œ
!F-
[0m} T Monitor Channel: Header


RSMONITORTAB {[0m[0;1;33m%-12s[0m!i!W%s!)
!0l!1r} T Monitor Channel: Table line


RSMONITOREND {[0;1m!F-

[0;1m’â¢¦ª §˜¨˜¡¦¢¦çŸ©ª ¡˜¤˜¢ é¤.

} T Monitor Channel: End of monitoring


RSMONITORERR {[0;1;31m
!JŠáŸ¦ª ¡˜«á «¤ › á¨¡œ ˜ «ª §˜¨˜¡¦¢¦çŸ©ª «à¤ ¡˜¤˜¢ é¤!!)
[0;1m} T Monitor Channel: Error occured




RSSENDWHO {[0;1m
!W‘œ §¦ ¦¤ Ÿ˜ ©«œå¢¦¬£œ ©¬©¦§ ¡æ £ã¤¬£˜;
ƒé©œ ˜¨ Ÿ£æ ¡˜¤˜¢ ¦ç, æ¤¦£˜ unix tty (§® ttyS1), ¯œ¬›é¤¬£¦,
[33mall[37m š ˜ ˜§¦©«¦¢ã §¨¦ª æ¢¦¬ª,
ã ? š ˜ ¡˜«á¢¦š¦:!) [0m} T Send message to channel: Which one?


RSSENDR {[0;1;31m
€¬«æ «¦ ¡˜¤á¢  ›œ¤ â®œ  ®¨ã©«, ®˜¨ «à£â¤œ.
[0;1m} T Send message to channel: no user in that channel


RSSENDD {[0;1;31m
!JŠ¬§á£˜ , ¦ ®¨ã©«ª ˜§¦©¬¤›âŸ¡œ æ©¦ ©¬¤«á©˜«œ «¦ ¡œå£œ¤¦ «¦¬
£¤ç£˜«¦ª.!)
[0;1m} T Send message to channel: user disconnected


RSSEND1 {[0;1;32m
„¤«á¥œ , «¦ £ã¤¬£˜ ©«á¢Ÿ¡œ ©«¦ ¡˜¤á¢  [37m%x[32m.
[0;1m} T Send message to channel: message sent to one channel


RSSENDX {[0;1;31m
!WŠ¬§á£˜ , «¦ £â¢¦ª [37m%s[31m ›œ¤ £§¦¨œå ¤˜ œ¤¦®¢Ÿœå.!)
[0;1m} T Send message to channel: message not send, user was BUSY


RSSEND2 {[0;1;32m
!J„¤«á¥œ , «¦ £ã¤¬£˜ ©«á¢Ÿ¡œ §¨¦ª [32mæ¢¦¬ª[37m.!)
[0;1m} T Send message to channel: message sent to all users


RSSEND2A {[0;1;33m
!J’¦ £ã¤¬£˜ ›œ¤ £§æ¨œ©œ ¤˜ ©«˜¢œå §¨¦ª [32mæ¢¦¬ª[37m.!)
[0;1m} T Send message to channel: couldn't send to ALL users


RSSEND2B {[0;1;31m
!JŠ¬§á£˜ , «¦ £ã¤¬£˜ ›œ¤ £§æ¨œ©œ ¤˜ ©«˜¢œå §¨¦ª ¡˜¤â¤˜ ®¨ã©«.!)
[0;1m} T Send message to channel: couldn't send to ANY users


RSSENDCAN {[0;1;31m
† ˜§¦©«¦¢ã «¦¬ £¤ç£˜«¦ª ˜¡¬¨éŸ¡œ.
[0;1m } T Send message to channel: canceled


RSSENDINH {[0m



[36;5mÛÛ  [0;1m€ ’Œ •„ˆˆ‘’† ‘“‘’†‹€’‘:

} T Send message to channel: message header




RSDELETEWHO {
!W[0;1;31;5mÛÛ[0;1;31m  ‘•†: !i ®¨ã©«ª §¦¬ Ÿ˜ ¦¤¦£á©œ«œ Ÿ˜
› ˜š¨˜­œå. ‡˜ «¦¬ ˜­˜ ¨œŸœå «¦ › ¡˜åà£˜ §¨æ©™˜©ª £â®¨  «¦ œ§æ£œ¤¦ cleanup,
¦§æ«œ ¡˜  Ÿ˜ › ˜š¨˜­œå ˜¤œ§ ©«¨œ§«å ¦ ¢¦š˜¨ ˜©£æª «¦¬. ‹â®¨  «æ«œ, £§¦¨œå«œ
¤˜ ˜¤˜ ¨â©œ«œ «¤ › ˜š¨˜­ã «¦¬ £œ «¤ å› ˜ œ¤«¦¢ã (DELETE).!)
!0l[0;1m
!W‹œ §¦ ˜¤¦ç «˜ ˜å£˜«˜ Ÿ˜ ¢œ¨é©¦¬£œ «¤ ¡¦¤©æ¢˜, ˜­œ¤« ¡æ; !)[0m} T Delete a user: who?


RSDELETEERR {
!J[0;1;31m’¦ ¯œ¬›é¤¬£¦ [37m%s[31m œå¤˜  §¨¦©«˜«œ¬£â¤¦. ƒ„Œ £§¦¨œå ¤˜
› ˜š¨˜­œå.!)
[0;1m} T Delete a user: user is exempt


RSDELETEOK {
!J[0;1;32m„¤«á¥œ , «¦ ¯œ¬›é¤¬£¦ [37m%s[32m ©£œ éŸ¡œ š ˜ › ˜š¨˜­ã. €¤
Ÿâ¢œ«œ ¤˜ á¨œ«œ «¤ › ˜š¨˜­ã «¦¬, ®¨© £¦§¦ ã©«œ «¤ å› ˜ œ¤«¦¢ã ‹„•ˆ ’
„•‹„Œ CLEANUP.!)
[0;1m} T Delete a user: ok


RSDELETEUNDO {
!J[0;1;32m„¤«á¥œ , «¦ ¯œ¬›é¤¬£¦ [37m%s[32m ƒ„Œ Ÿ˜ › ˜š¨˜­œå ©«¦ œ¨®æ£œ¤¦
cleanup.!)
[0;1m} T Delete a user: undeleted



RSDETAILWHO {[0;1m
!Wƒé©«œ «¦ ¯œ¬›é¤¬£¦ §¦¬ Ÿâ¢œ«œ ¤˜ ›œå«œ: !)[0m} T Datailed info: About whom?


RSDETAILNAX {<ƒœ¤ œ£­˜¤åœ«˜ >} T Detailed info: field contents withheld

RSDETAILSUSP {[31mşSUSPENDEDş} T Detailed info: 'suspended' string

RSDETAILXMPT {[32mşEXEMPTş} T Detailed info: 'exempt' string

RSDETAILDEL {[31mşDELETEDş} T Detailed info: 'deleted' string

RSDETAILOP {[32mşOPERATORş} T Detailed info: 'operator' string

RSDETAILM {€¤›¨˜ª} T Detailed info: 'male' string
RSDETAILF {‚¬¤˜å¡˜} T Detailed info: 'female' string

RSDETAILS1 {IBM PC ã ©¬£™˜«æª} T Detailed info: system #1
RSDETAILS2 {Apple Macintosh} T Detailed info: system #2
RSDETAILS3 {Apple II/II+/IIe, ¡¢§} T Detailed info: system #3
RSDETAILS4 {Amiga} T Detailed info: system #4
RSDETAILS5 {Atari} T Detailed info: system #5
RSDETAILS6 {Archimedes} T Detailed info: system #6
RSDETAILS7 {Amstrad CPC 464/664/6128} T Detailed info: system #7
RSDETAILS8 {€š¤à©«¦} T Detailed info: system #8
RSDETAILS9 {} T Detailed info: system #9

RSDETAILNST {(®à¨åª §˜ç©œ ª)} T Detailed info: 'non-stop' string

RSDETAILL1 {„¢¢¤ ¡á} T Detailed info: language #1
RSDETAILL2 {€šš¢ ¡á} T Detailed info: language #2
RSDETAILL3 {} T Detailed info: language #3
RSDETAILL4 {} T Detailed info: language #4
RSDETAILL5 {} T Detailed info: language #5
RSDETAILL6 {} T Detailed info: language #6
RSDETAILL7 {} T Detailed info: language #7
RSDETAILL8 {} T Detailed info: language #8
RSDETAILL9 {} T Detailed info: language #9
RSDETAILL0 {} T Detailed info: language #10


RSDETAIL {[0;1m
[0;36mÛÛ  [1m‘«¦ ®œå˜ «¦¬ ¯œ¬›à¤ç£¦¬ %s  [46m[K[0;1m

[32mƒ£ ¦¬¨šãŸ¡œ . . . .  [37m%-9s  %s %s
[32m’œ¢œ¬«˜å˜ ©ç¤›œ©  . . [37m%-9s  %s %s

[32m¤¦£˜«œ§é¤¬£¦ . . . .  [37m%s
[32m„«˜ ¨œå˜ . . . . . . . [37m%s
[32mƒ œçŸ¬¤© (1/2) . . .  [37m%s
[32mƒ œçŸ¬¤© (2/2)  . . . [37m%s
[32m’¢â­à¤¦  . . . . . .  [37m%s
[32m†¢ ¡å˜ . . . . . . . . [37m%s
[32m”ç¢¦  . . . . . . . .  [37m%s
[32m“§¦¢¦š ©«ãª  . . . . . [37m%s
[32mƒ ˜©«á©œ ª ¦Ÿæ¤ª . .  [37m%d x %d %s
[32m‚¢é©©˜ . . . . . . . . [37m%s
[32mClass . . . . . . . .  [37m%s
[32m‘ç¤Ÿ£˜  . . . . . . . [37m%s
[32m‹¦¤á›œª . . . . . . .  [37m%d (%d PAID àª «é¨˜)

[46m[K[0;1m
} T Detailed info: template



RSEXEMPTWHO {[0;1m
!W¦ ¦¤ ®¨ã©« Ÿâ¢œ«œ ¤˜ §¨¦©«œ«œç©œ«œ ˜§æ › ˜š¨˜­ã; !)[0m} T Exempt a user: who?


RSEXEMPTERR {[0;1;31m
!W Sysop œå¤˜  §á¤«˜ §¨¦©«˜«œ¬£â¤¦ª ˜§æ › ˜š¨˜­ã.!)
[0;1m} T Exempt a user: can't unexempt sysop.


RSEXEMPTOK {
!J[0;1;32m„¤«á¥œ , «¦ ¯œ¬›é¤¬£¦ [37m%s[32m œå¤˜  §¢â¦¤ £ › ˜š¨á¯ £¦.!)
[0;1m} T Exempt a user: ok


RSEXEMPTUNDO {
!J[0;1;32m„¤«á¥œ , «¦ ¯œ¬›é¤¬£¦ [37m%s[32m ƒ„Œ œå¤˜  § ˜ §¨¦©«˜«œ¬£â¤¦
˜§æ › ˜š¨˜­âª.!)
[0;1m} T Exempt a user: unexempted




RSSUSPWHO {[0;1m
!W¦ ¦¤ Ÿ˜ ¡á¤¦¬£œ (un)suspend; !)[0m} T Suspend a user: who?


RSSUSPERR {
!J[0;1;31m’¦ ¯œ¬›é¤¬£¦ [37m%s[31m œå¤˜  §¨¦©«˜«œ¬£â¤¦. ƒ„Œ £§¦¨œå ¤˜
šå¤œ  suspend.!)
[0;1m} T Suspend a user: user is exempt


RSSUSPOK {
!J[0;1;32m„¤«á¥œ , «¦ ¯œ¬›é¤¬£¦ [37m%s[32m ›œ¤ Ÿ˜ £§¦¨œå §¢â¦¤ ¤˜
©¬¤›œŸœå ©«¤ ™á©.!)
[0;1m} T Suspend a user: ok


RSSUSPUNDO {
!J[0;1;32m„¤«á¥œ , «¦ ¯œ¬›é¤¬£¦ [37m%s[32m £§¦¨œå ¤˜ £§œ  ¡˜  §á¢  ©«¤
™á©.!)
[0;1m} T Suspend a user: unsuspended




RSPOSTWHO {[0;1m
‘œ §¦ ¦¤ ®¨ã©« Ÿ˜ ›é©¦¬£œ credits; [0m} T Post credits: To whom?


RSPOSTAMT {[0;1m              æ©˜ credits ¤˜ ›é©à; [0m} T Post credits: How many?


RSPOSTFOP {[0;1m  ’˜ credits œå¤˜  (F)ree ã (P)aid; [0m} T Post credits: Free or Paid?


RSPOSTERR {[0;1;31m
˜¨˜¡˜¢é ›é©«œ F š ˜ FREE credits ã P š ˜ PAID credits.
[0;1m} T Post credits: Please enter F or P


RSPOSTCNF {[0;1;32m
!W¨æ¡œ «˜  ¤˜ ›é©œ«œ %d %s credit%s ©«%s %s. Œ˜ §¨¦®à¨ã©à;!)[0m } T Post credits: Do you confirm?


RSPOSTDEL {[0;1;31m
!J”«¦¬! ©¦ œ©ç â§˜ œª £œ «˜ spells ©¦¬, ¡á§¦ ¦ª â©™©œ «¦¤ ®¨ã©«.!)

!J‘åš¦¬¨˜ ›œ¤ ¡á¤œ  §¢˜¡å«©œª ¦ ‹§¢áŸ¨˜ª;;;!)
[0;1m} T Post credits: User has been deleted


RSPOSTNOT1 {[0;1;32m
***
 •œ ¨ ©«ãª ‘¬©«ã£˜«¦ª £æ¢ ª ©˜ª §¨¦©â­œ¨œ [37m%d credit%s ›à¨œá¤ ®¨ã©ª[32m.
} T Post credits: User notification, free credits


RSPOSTNOT2 {[0;1;32m
***
 •œ ¨ ©«ãª ‘¬©«ã£˜«¦ª £æ¢ ª ©˜ª â›à©œ [37m%d credit%s[32m §¦¬ â®œ«œ ˜š¦¨á©œ .
} T Post credits: User notification, paid credits


RSPOSTNOT3 {[0;1;32m
***
 •œ ¨ ©«ãª ‘¬©«ã£˜«¦ª £æ¢ ª ©˜ª â›à©œ [37m%d credit%s[32m §¦¬ â®œ«œ
˜š¦¨á©œ . ‹œ«˜­œ¨Ÿã¡˜«œ ˜¬«æ£˜«˜ ©«¦ class [37m%s[32m. ƒé©«œ [33mAV[32m
˜§æ «¦ ¡œ¤«¨ ¡æ £œ¤¦ç š ˜ ¤˜ ›œå«œ «  á¢¢˜¥œ ©«¦¤ ¢¦š˜¨ ˜©£æ ©˜ª.!)
} T Post credits: User notification, paid credits with class change


RSPOSTOK {[0;1;32m
† £œ«˜­¦¨á âš ¤œ.
[0;1m} T Post credits: Transfer ok.



RSPOSTOK2 {[0;1;32m
† £œ«˜­¦¨á âš ¤œ.  ®¨ã©«ª £œ«˜­â¨Ÿ¡œ ˜¬«æ£˜«˜ ©«¦ class [37m%s[32m.
[0;1m} T Post credits: Transfer ok with class change



RSHANGUPWHO {[0;1m
!W¦ ¦¤ Ÿ˜ §œ«á¥¦¬£œ, ˜­œ¤« ¡æ;
ƒé©œ ˜¨ Ÿ£æ ¡˜¤˜¢ ¦ç, æ¤¦£˜ unix tty (§® ttyS1), ¯œ¬›é¤¬£¦, ã ? š ˜ ¡˜«á¢¦š¦:!) [0m} T Hangup User: Who?


RSHANGUPERR {[0;1;31m
ƒœ¤ ¬§á¨®œ  ®¨ã©«ª ©'˜¬«æ «¦ ¡˜¤á¢ ... ¥˜¤˜§¨¦©§áŸ©œ.
[0;1m} T Hangup User: No user in that channel.


RSHANGUPOK {[0;1;32m
„¤«á¥œ , ¦ ®¨ã©«ª ˜§¦©¬¤›âŸ¡œ.
[0;1m} T Hangup User: User kicked out.


RSSRCHVT {[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [34m„¨œ¬¤˜ ™á©ª ›œ›¦£â¤à¤ ®¨©«é¤[0;30;47m ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  –œ¬›é¤¬£¦ . . . . . . . . . [0;30;46m @2;" |<|<=|=|>=|>|IN"l [47m  [1;44;37m@23;23;0s[47;37m             ³ [0m
[30;47m ³  ‘ç¤Ÿ£˜  . . . . . . . . .  [0;30;46m @2;" |<|<=|=|>=|>|IN"l [47m  [1;44;37m@15;15;2s[47;37m                     ³ [0m
[30;47m ³  ¤¦£˜«œ§é¤¬£¦ . . . . . . . [0;30;46m @2;" |<|<=|=|>=|>|IN"l [47m  [1;44;37m@30;30;0s[47;37m      ³ [0m
[30;47m ³  „«˜ ¨œå˜ . . . . . . . . .  [0;30;46m @2;" |<|<=|=|>=|>|IN"l [47m  [1;44;37m@30;30;0s[47;37m      ³ [0m
[30;47m ³  ƒ œçŸ¬¤© (1/2) . . . . . . [0;30;46m @2;" |<|<=|=|>=|>|IN"l [47m  [1;44;37m@30;30;0s[47;37m      ³ [0m
[30;47m ³  ƒ œçŸ¬¤© (2/2)  . . . . .  [0;30;46m @2;" |<|<=|=|>=|>|IN"l [47m  [1;44;37m@30;30;0s[47;37m      ³ [0m
[30;47m ³  ’¢â­à¤¦  . . . . . . . . . [0;30;46m @2;" |<|<=|=|>=|>|IN"l [47m  [1;44;37m@23;23;0s[47;37m             ³ [0m
[30;47m ³  “§¦¢¦š ©«ãª  . . . . . . .  [0;30;46m @2;" |="l [47m  [0;30;46m @14;"IBM compatible|Apple Mac|Old Apple|Amiga|Atari|Archimedes|Amstrad CPC|€š¤à©«¦"l [1;47;37m                      ³ [0m
[30;47m ³  †¢ ¡å˜  . . . . . . . . . . [0;30;46m @2;" |<|<=|=|>=|>"l [47m  [1;44;37m@2;0;99;0n[47;37m                                  ³ [0m
[30;47m ³  ”ç¢¦ . . . . . . . . . . .  [0;30;46m @2;" |="l [47m  [46m @7;"€¤›¨˜ª|‚¬¤˜å¡˜"l [1;47;37m                             ³ [0m
[30;47m ³  Credits › ˜Ÿâ© £˜ «é¨˜  . . [0;30;46m @2;" |<|<=|=|>=|>"l [47m  [1;44;37m@9;0;999999999;0n[47;37m                           ³ [0m
[30;47m ³  PAID credits àª «é¨˜ . . .  [0;30;46m @2;" |<|<=|=|>=|>"l [47m  [1;44;37m@9;0;999999999;0n[47;37m                           ³ [0m
[30;47m ³  Class . . . . . . . . . . . [0;30;46m @2;" |="l [47m  [1;44;37m@9;9;1s[47;37m                           ³ [0m
[30;47m ³  †£œ¨¦£¤å˜ œšš¨˜­ãª  . . .  [0;30;46m @2;" |<|<=|=|>=|>"l [47m  [1;44;37m@10;10;4s[0;30;47m            (dd/mm/yyyy)[1;37m  ³ [0m
[30;47m ³  ’œ¢œ¬«˜å˜ ©ç¤›œ© . . . . . [0;30;46m @2;" |<|<=|=|>=|>"l [47m  [1;44;37m@10;10;4s[0;30;47m            (dd/mm/yyyy)[1;37m  ³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  ' '=don't-care  'IN'=§œ¨ â®œ                                            [0;1;47;37m³ [0m
[30;47m ³                                  [0;1;42;33m@14;"OK"b[0;47;30mÜ    [0;1;41;33m@14;"Cancel"b[0;47;30mÜ  [0;1;47;37m³ [0m
[30;47m ³  Ctrl-R: ¦ãŸœ ˜                  ßßßßßßßßßßßßßßßß     ßßßßßßßßßßßßßßßß  [0;1;47;37m³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m} T Search: visual template


RSSRCHM {€¤›¨˜ª} T String for 'male' in edit templates
RSSRCHF {‚¬¤˜å¡˜} T String for 'female' in edit templates

RSSRCHS1 {IBM compatible} T String for system type #1 in edit templates
RSSRCHS2 {Apple Mac} T String for system type #2 in edit templates
RSSRCHS3 {Old Apple} T String for system type #3 in edit templates
RSSRCHS4 {Amiga} T String for system type #4 in edit templates
RSSRCHS5 {Atari} T String for system type #5 in edit templates
RSSRCHS6 {Archimedes} T String for system type #6 in edit templates
RSSRCHS7 {Amstrad CPC} T String for system type #7 in edit templates
RSSRCHS8 {€š¤à©«¦} T String for system type #8 (unknown) in edit templates


RSSRCHLT {[2J[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³ „¨œ¬¤˜ ™á©ª ›œ›¦£â¤à¤ ®¨©«é¤                                           [0;1;47;37m³ [0m
[30;47m ³ ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [0;1;47;37m³ [0m
[30;47m ³ –œ¬›é¤¬£¦ . . . . . . . . . [31m 1[30m. [34m@2;" |<|<=|=|>=|>|IN"l  [31m 2[30m. [34m@23;23;0s[1;47;37m          ³ [0m
[30;47m ³ ‘ç¤Ÿ£˜  . . . . . . . . .  [31m 3[30m. [34m@2;" |<|<=|=|>=|>|IN"l  [31m 4[30m. [34m@15;15;2s[1;47;37m                  ³ [0m
[30;47m ³ ¤¦£˜«œ§é¤¬£¦ . . . . . . . [31m 5[30m. [34m@2;" |<|<=|=|>=|>|IN"l  [31m 6[30m. [34m@30;30;0s[1;47;37m   ³ [0m
[30;47m ³ „«˜ ¨œå˜ . . . . . . . . .  [31m 7[30m. [34m@2;" |<|<=|=|>=|>|IN"l  [31m 8[30m. [34m@30;30;0s[1;47;37m   ³ [0m
[30;47m ³ ƒ œçŸ¬¤© (1/2) . . . . . . [31m 9[30m. [34m@2;" |<|<=|=|>=|>|IN"l  [31m10[30m. [34m@30;30;0s[1;47;37m   ³ [0m
[30;47m ³ ƒ œçŸ¬¤© (2/2)  . . . . .  [31m11[30m. [34m@2;" |<|<=|=|>=|>|IN"l  [31m12[30m. [34m@30;30;0s[1;47;37m   ³ [0m
[30;47m ³ ’¢â­à¤¦  . . . . . . . . . [31m13[30m. [34m@2;" |<|<=|=|>=|>|IN"l  [31m14[30m. [34m@23;23;0s[1;47;37m          ³ [0m
[30;47m ³ “§¦¢¦š ©«ãª  . . . . . . .  [31m15[30m. [34m@2;" |="l  [31m16[30m. [34m@14;"IBM compatible|Apple Mac|Old Apple|Amiga|Atari|Archimedes|Amstrad CPC|€š¤à©«¦"l[1;47;37m                   ³ [0m
[30;47m ³ †¢ ¡å˜  . . . . . . . . . . [31m17[30m. [34m@2;" |<|<=|=|>=|>"l  [31m18[30m. [34m@2;0;99;0n[1;47;37m                               ³ [0m
[30;47m ³ ”ç¢¦ . . . . . . . . . . .  [31m19[30m. [34m@2;" |="l  [31m20[30m. [34m@7;"€¤›¨˜ª|‚¬¤˜å¡˜"l[1;47;37m                          ³ [0m
[30;47m ³ Credits › ˜Ÿâ© £˜ «é¨˜  . . [31m21[30m. [34m@2;" |<|<=|=|>=|>"l  [31m22[30m. [34m@9;0;999999999;0n[1;47;37m                        ³ [0m
[30;47m ³ PAID credits àª «é¨˜ . . .  [31m23[30m. [34m@2;" |<|<=|=|>=|>"l  [31m24[30m. [34m@9;0;999999999;0n[1;47;37m                        ³ [0m
[30;47m ³ Class . . . . . . . . . . . [31m25[30m. [34m@2;" |="l  [31m26[30m. [34m@9;9;1s[1;47;37m                        ³ [0m
[30;47m ³ †£œ¨¦£¤å˜ œšš¨˜­ãª  . . .  [31m27[30m. [34m@2;" |<|<=|=|>=|>"l  [31m28[30m. [34m@10;10;4s[1;37;47m                       ³ [0m
[30;47m ³ ’œ¢œ¬«˜å˜ ©ç¤›œ© . . . . . [31m29[30m. [34m@2;" |<|<=|=|>=|>"l  [31m30[30m. [34m@10;10;4s[1;37;47m                       ³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m} T Search: Linear template


RSSRCH1 {} T Search: help for field #1
RSSRCH2 {} T Search: help for field #2
RSSRCH3 {} T Search: help for field #3
RSSRCH4 {} T Search: help for field #4
RSSRCH5 {} T Search: help for field #5
RSSRCH6 {} T Search: help for field #6
RSSRCH7 {} T Search: help for field #7
RSSRCH8 {} T Search: help for field #8
RSSRCH9 {} T Search: help for field #9
RSSRCH10 {} T Search: help for field #10
RSSRCH11 {} T Search: help for field #11
RSSRCH12 {} T Search: help for field #12
RSSRCH13 {} T Search: help for field #13
RSSRCH14 {} T Search: help for field #14
RSSRCH15 {} T Search: help for field #15
RSSRCH16 {} T Search: help for field #16
RSSRCH17 {} T Search: help for field #17
RSSRCH18 {} T Search: help for field #18
RSSRCH19 {} T Search: help for field #19
RSSRCH20 {} T Search: help for field #20
RSSRCH21 {} T Search: help for field #21
RSSRCH22 {} T Search: help for field #22
RSSRCH23 {} T Search: help for field #23
RSSRCH24 {} T Search: help for field #24
RSSRCH25 {} T Search: help for field #25
RSSRCH26 {} T Search: help for field #26
RSSRCH27 {} T Search: help for field #27
RSSRCH28 {} T Search: help for field #28
RSSRCH29 {} T Search: help for field #29
RSSRCH30 {} T Search: help for field #30


RSSRCHC {[0;1;31m
† › ˜› ¡˜©å˜ ˜¡¬¨éŸ¡œ.
[0;1m} T Search: canceled


RSSRCHR {[0;1;31m
!Wƒœ¤ â®œ  ¤æ£˜ ¤˜ ¯á¥¦¬£œ ©«¤ ™á© ›œ›¦£â¤à¤ ˜¤ ›œ¤ ¦¨å©œ«œ
«¦¬¢á® ©«¦¤ â¤˜ ¡¨ «ã¨ ¦. :-) !)
[0;1m} T Search: no query


RSSRCHB {[0;1m
( â©«œ [33mEnter[37m š ˜ «œ¨£˜« ©£æ «ª â¨œ¬¤˜ª)

•¨ã©«œª §¦¬ ™¨âŸ¡˜¤:

–„“ƒ—Œ“‹    €‚‹€’ˆ‰ Œ‹€
!F-
[0m} T Search: header


RSSRCHL {%-13s%s
} T Search: found user


RSCLASSWHO {[0;1m
¦ ¦¤ ®¨ã©« Ÿâ¢œ ª ¤˜ £œ«˜¡ ¤ã©œ ª ©œ á¢¢¦ class; [0m} T Change User's Class: Whose?


RSCLASSREP {[0;1;32m
•¨ã©«ª . . . . . . . . [37m%s[32m
’¨â®¦¤ class  . . . . . [37m%s
[0;1m} T Change User's Class: Current class report


RSCLASSCLS {[0;1m
‘œ §¦ ¦ class ¤˜ £œ«˜­œ¨Ÿœå ¦ ®¨ã©«ª; (? š ˜ ¡˜«á¢¦š¦) [0m} T Change User's Class: Which class?


RSCLASSERR {[0;1;31m
’©¡ «©¡ «©¡... ›œ¤ ¬§á¨®œ  ˜¬«æ «¦ class. ƒé©œ ? š ˜ ¡˜«á¢¦š¦.
[0;1m} T Change User's Class: Class does not exist


RSCLASSDEL {[0;1;31m
!J”«¦¬! ©¦ œ©ç á¢¢˜œª «¦ class, ¡á§¦ ¦ª â©™©œ «¦¤ ®¨ã©«.
† ˜¢¢˜šã class ›œ¤  ©®çœ  §¢â¦¤.!)

!J‘åš¦¬¨˜ ›œ¤ ¡á¤œ  §¢˜¡å«©œª ¦ ‹§¢áŸ¨˜ª;;;!)
[0;1m} T Change Class: User has been deleted


RSCLASSNOT {[0;1;32m
***
!J •œ ¨ ©«ãª ‘¬©«ã£˜«¦ª £æ¢ ª ©˜ª £œ«â­œ¨œ ©«¦ class [37m%s[32m. ƒé©«œ
[33mAV[32m ˜§æ «¦ ¡œ¤«¨ ¡æ £œ¤¦ç š ˜ ¤˜
›œå«œ «  á¢¢˜¥œ ©«¦¤ ¢¦š˜¨ ˜©£æ ©˜ª.!)
[0;1m} T Change Class: User notification


RSCLASSOK {[0;1;32m
„¤«á¥œ ,  ˜¢¢˜šã âš ¤œ £œ œ§ «¬®å˜.

[0;1m} T Change Class: Finished successfully





RSKEYSWHO {[0;1m
‹œ §¦ ¦¤ ®¨ã©« Ÿ˜ §˜å¥œ ª §á¢ , ˜­œ¤« ¡æ; [0m} T Change User's Keys: Whose?


RSKEYSSYS {[0;1;31m
® , ƒ„Œ Ÿ˜ §˜å¥œ ª £œ «˜ ¡¢œ › á «¦¬ ©ç©¦§˜. €¬«æª «˜ â®œ  æ¢˜ £¦¤å£àª.

[0;1m} T Change User's Keys: Won't change Sysop's keys


RSKEYSTAB {[0;1;32m
ÉÍÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÍ»
º 0   ³    1    ³    2    ³    3    ³    4    ³    5    ³    6   6 º
º 12 4 6 8 0 2 4 6 8 0 2 4 6 8 0 2 4 6 8 0 2 4 6 8 0 2 4 6 8 0 2 4 º
º [37m%s[32m º
ÌÍØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØÍ¹
º ³         ³         ³         ³    1    ³    1    ³    1    ³  1 º
º 6    7    ³    8    ³    9    ³    0    ³    1    ³    2    ³  2 º
º 56 8 0 2 4 6 8 0 2 4 6 8 0 2 4 6 8 0 2 4 6 8 0 2 4 6 8 0 2 4 6 8 º
º [37m%s[32m º
ÈÍÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÍ¼
[0;1m} T Change User's Keys: Key Editor Template


RSKEYSASK {
[0;1m!Wƒé©«œ «¦¤ ˜¨ Ÿ£æ «¦¬ ¡¢œ › ¦ç (1-128, ? š ˜ œ£­á¤ © ¡¢œ › é¤, 
ON=æ¢˜, OFF=¡˜¤â¤˜, OK š ˜ «â¢¦ª, X š ˜ ˜¡ç¨à©): !)[0m} T Change User's Keys: Key Editor, enter key


RSKEYSON {[0;1;32m
’¦ ¡¢œ ›å %d §¨¦©«âŸ¡œ ©«¦ ©ç¤¦¢¦.
[0;1m} T Change User's Keys: Key Editor, added key


RSKEYSOFF {[0;1;32m
’¦ ¡¢œ ›å %d ˜­˜ ¨âŸ¡œ ˜§æ «¦ ©ç¤¦¢¦.
[0;1m} T Change User's Keys: Key Editor, deleted key


RSKEYSDEL {[0;1;31m
!J”«¦¬! ©¦ œ©ç â§˜ œª £œ «˜ ¡¢œ › á, ¡á§¦ ¦ª â©™©œ «¦¤ ®¨ã©«.
† ˜¢¢˜šã ›œ¤  ©®çœ  §¢â¦¤.!)
[0;1m} T Change User's Keys: User has been deleted


RSKEYSOK {[0;1;32m
„¤«á¥œ ,  ˜¢¢˜šã âš ¤œ £œ œ§ «¬®å˜.

[0;1m} T Change User's Keys: Finished successfully




RSTYPEASK {[0;1;32m!W‡¬£åà æ«  ©«¦ linux š¨á­¦¬£œ «˜ directories £œ '/' ¡˜  æ®  £œ '\'! :-)!)

[0;1m¡, «é¨˜, §¦ ¦ ˜¨®œå¦ Ÿâ¢œ ª ¤˜ ›œ ª; [0m} T Type file: What file?


RSTYPEERR {[0;1;31m
!J’¦ ˜¨®œå¦ %s ›œ¤ ™¨âŸ¡œ ã ›œ¤ £§¦¨œå ¤˜ ˜¤¦ ®Ÿœå.!)

[0;1m} T Type file: File not found




RSCOPYSRC {[0;1;32m!W‡¬£åà æ«  ©«¦ linux š¨á­¦¬£œ «˜ directories £œ '/' ¡˜  æ®  £œ '\'! :-)!)

[0;1m¡, «é¨˜, §¦ ¦ ˜¨®œå¦ Ÿâ¢œ ª ¤˜ ˜¤« š¨á¯œ ª; [0m} T Copy file: Enter source file


RSCOPYTRG {
[0;1m‰˜  §¦ç Ÿâ¢œ ª ¤˜ «¦ ˜¤« š¨á¯œ ª;            [0m} T Copy file: Enter destination


RSCOPYERR {[0;1;31m
!J† ˜¤« š¨˜­ã ©«˜£á«©œ ¢æšà ¢áŸ¦¬ª.!)

[0;1m} T Copy file: cp returned error


RSCOPYOK {[0;1;31m
!J† ˜¤« š¨˜­ã «â¢œ à©œ œ§ «¬®éª.!)

[0;1m} T Copy file: ok!




RSRENSRC {[0;1;32m!W‡¬£åà æ«  ©«¦ linux š¨á­¦¬£œ «˜ directories £œ '/' ¡˜  æ®  £œ '\'! :-)!)

[0;1m¡, «é¨˜, §¦ ¦ ˜¨®œå¦ Ÿâ¢œ ª ¤˜ £œ«¦¤¦£á©œ ª; [0m} T Rename/move file: Enter file


RSRENTRG {
[0;1m‰˜  §¦ ¦ œå¤˜  «¦ ¡˜ ¤¦ç¨ ¦ æ¤¦£á «¦¬;        [0m} T Rename/move file: Enter new name/dir


RSRENERR {[0;1;31m
!J† › ˜› ¡˜©å˜ ©«˜£á«©œ ¢æšà ¢áŸ¦¬ª.!)

[0;1m} T Rename/move file: mv returned error


RSRENOK {[0;1;31m
!J† › ˜› ¡˜©å˜ «â¢œ à©œ œ§ «¬®éª.!)

[0;1m} T Rename/move file: ok!




RSDIRASK {[0;1;32m!W‡¬£åà æ«  ©«¦ linux š¨á­¦¬£œ «˜ directories £œ '/' ¡˜  æ®  £œ '\'! :-)!)

[0;1m¡, «é¨˜, §¦ ¦ directory/˜¨®œå¦ Ÿâ¢œ ª ¤˜ ¡á¤œ ª DIR; [0m} T DIR: what directory?


RSDIRERR {[0;1;31m
!J’¦ %s ›œ¤ ™¨âŸ¡œ ã ›œ¤ £§¦¨œå ¤˜ ˜¤¦ ®Ÿœå.!)

[0;1m} T DIR: can't open directory/file




RSDELASK {
!W[0;1;31;5m‘•†: !i[0;1;31m¨æ¡œ «˜  ¤˜ › ˜š¨á¯œ«œ â¤˜
˜¨®œå¦. [5mƒ„Œ[0;1;31m Ÿ˜ ¬§á¨¥œ  á¢¢ œ¨é«©, ¡˜  «¦ ˜¨®œå¦
[5mƒ„Œ[0;1;31m £§¦¨œå ¤˜ ˜¤˜¡«Ÿœå £œ ¡˜¤â¤˜ «¨æ§¦. ¨¦©â¥«œ «  ¡á¤œ«œ.!)
!0l
[0;1m¦ ¦ ˜¨®œå¦ Ÿâ¢œ«œ ¤˜ › ˜š¨á¯œ«œ; [0m} T DEL: what file?


RSDELERR {[0;1;31m
!J’¦ %s ›œ¤ ™¨âŸ¡œ ã ›œ¤ £§¦¨œå ¤˜ › ˜š¨˜­œå.!)

[0;1m} T DEL: can't remove directory/file




RSSYSASK {[0;1;32m!W‡¬£åà æ«  ©«¦ linux š¨á­¦¬£œ «˜ directories £œ '/' ¡˜  æ®  £œ '\'! :-)!)

[0;1m¡, «é¨˜, §¦ ˜ œ¤«¦¢ã Ÿâ¢œ ª ¤˜ «¨â¥œ ª; [0m} T SYS: Enter command to run



RSXFERDIR {[0;1m
¦ ˜ œå¤˜   › œçŸ¬¤© «ª £œ«˜­¦¨áª ˜¨®œåà¤;

[33mU[37m . . . €¤œ™á¦¬£œ ®¨ã© £¦ ˜¨®œå¦ (§® ¤â¦ "™œ¢« à£â¤¦" kernel)
[33mD[37m  . .  ‰˜«œ™á¦¬£œ ˜§˜¨˜å««˜ utilities (cindy???.gif)
} T Transfer files: Up or down?


RSXFERSHRT {
[0;1m˜¨˜¡˜¢é ›é©«œ «¤ œ§ ¢¦šã ©˜ª (œšé ¤å§«à «˜ª virtual ®œå¨˜ª £¦¬): [0m} T Transfer files: Up or down, short menu


RSXFERRSEL {[0;1;31m
˜¨˜¡˜¢é ›é©«œ [33mU[31m, [33mD[31m, [33m?[31m š ˜ «¦ £œ¤¦ç, ã [33mX[31m š ˜ â¥¦›¦.
[0;1m} T Transfer files: Wrong selection


RSXFERWHD {
[0;1;32m!W‡¬£åà æ«  ©«¦ linux š¨á­¦¬£œ «˜ directories £œ '/' ¡˜  æ®  £œ '\'! :-)!)[37m

!W¦ ¦ ˜¨®œå¦ Ÿâ¢œ«œ ¤˜ ¢á™œ«œ; ˜¨˜¡˜¢é ›é©«œ «¦ æ¤¦£˜ «¦¬ ˜¨®œå¦¬
(wildcards œ§ «¨â§¦¤«˜ ):!) [0m} T Transfer files: Enter filename


RSXFERERR {[0;1;31m
!J’¦ %s ›œ¤ ™¨âŸ¡œ ã ›œ¤ £§¦¨œå ¤˜ ˜¤¦ ®Ÿœå.!)

[0;1m} T Transfer files: Can't open file


RSXFERWHU {
[0;1;32m!W‡¬£åà æ«  ©«¦ linux š¨á­¦¬£œ «˜ directories £œ '/' ¡˜  æ®  £œ '\'! :-)!)

[32m€¨®œå˜ §¦¬ ©«œå¢˜«œ: [37m%d

!W‘œ §¦ ¦ directory ¤˜ «˜ ©«œå¢¦¬£œ;!) [0m} T Transfer files: Enter directory


RSXFERER2 {[0;1;31m
!J’¦ %s ›œ¤ œå¤˜  directory! ’©¡ «©¡ «©¡...!)

[0;1m} T Transfer files: File is not a directory


RSXFERER3 {[0;1;31m
!J€¡ç¨à© £œ«˜­¦¨áª.!)

[0;1m} T Transfer files: transfer aborted.



RSEDITWHF {
[0;1;32m!W‡¬£åà æ«  ©«¦ linux š¨á­¦¬£œ «˜ directories £œ '/' ¡˜  æ®  £œ '\'! :-)!)[37m

!W¦ ¦ ˜¨®œå¦ Ÿâ¢œ«œ ¤˜ ­â¨œ«œ ©«¦¤ editor; ˜¨˜¡˜¢é ›é©«œ «¦ æ¤¦£˜ «¦¬ ˜¨®œå¦¬:!) [0m} T Edit a file: Enter filename


RSEDITERR {[0;1;31m
!J’¦ %s ›œ¤ ™¨âŸ¡œ ã ›œ¤ £§¦¨œå ¤˜ ˜¤¦ ®Ÿœå.!)

[0;1m} T Edit a file: Can't open file







RSAUDIT1 {[0;1m
„£­á¤ © «¦¬ Audit Trail.

!W‡â¢œ«œ ¤˜ ›œå«œ «¦ Audit Trail ˜§æ «¤ ˜¨®ã ([[33mB[37m]eginning) ã «¦ «â¢¦ª
([[33mE[37m]nd);!)[0m } T Audit: Beginning or end?


RSAUDITR {[0;1;31m
!Wƒœ¤ ¬§á¨®œ  ˜¬«ã  œ§ ¢¦šã.!)
[0m} T Audit: No such option


RSAUDIT2 {[0;1;32m

(§ â©«œ Enter š ˜ › ˜¡¦§ã «ª œ£­á¤ ©ª)

AUDIT TRAIL
!F-
[0m} T Audit: Listing audit trail


RSAUDITI {!W[0;1m%s!)
!26l!W[0m%s!)
!0l} T Audit: single audit entry, informational


RSAUDITC {!W[0;1;33m%s!)
!26l!W[0m%s!)
!0l} T Audit: single audit entry, cautionary


RSAUDITE {!W[0;1;31m%s!)
!26l!W[0m%s!)
!0l} T Audit: single audit entry, emergency


RSAUDIT3 {!0l[0;1;31m

!W† › ˜› ¡˜©å˜ «œ¨£˜«å©«¡œ §¨æà¨˜.!)
[0;1m} T Audit: Listing terminated




RSCLEANUP1 {[0;1m
„£­á¤ © «¦¬ Cleanup Audit Trail.

!W‡â¢œ«œ ¤˜ ›œå«œ «¦ Cleanup Audit Trail ˜§æ «¤ ˜¨®ã ([[33mB[37m]eginning) ã «¦ «â¢¦ª
([[33mE[37m]nd);!)[0m } T Audit: Beginning or end?


RSCLEANUPR {[0;1;31m
!Wƒœ¤ ¬§á¨®œ  ˜¬«ã  œ§ ¢¦šã.!)
[0m} T Audit: No such option


RSCLEANUP2 {[0;1;32m

(§ â©«œ Enter š ˜ › ˜¡¦§ã «ª œ£­á¤ ©ª)

CLEANUP AUDIT TRAIL
!F-
[0m} T Audit: Listing audit trail


RSCLEANUP3 {[0;1;31m

!W† › ˜› ¡˜©å˜ «œ¨£˜«å©«¡œ §¨æà¨˜.!)
[0;1m} T Audit: Listing terminated



RSLOGONH {[0;1m

€¢¢˜šã ¡œ £â¤¦¬ œ ©æ›¦¬ (logon message).

!J“§á¨®¦¬¤ ›ç¦ œå› ¡œ £â¤à¤: «¦ šœ¤ ¡æ, §¦¬ œ£­˜¤åœ«˜  ©œ æ¢˜ «˜ ¡˜¤á¢ ˜,
¡˜  «¦ œ › ¡æ, §¦¬ œ£­˜¤åœ«˜  £æ¤¦ ©œ â¤˜ ¡˜¤á¢ . ‰áŸœ ¡˜¤á¢  £§¦¨œå ¤˜
â®œ  «¦ › ¡æ «¦¬ ¡œå£œ¤¦, §¦¬ œ£­˜¤åœ«˜  ‹€…ˆ £œ «¦ šœ¤ ¡æ ¡œå£œ¤¦ ˜£â©àª
§¨ ¤ ¦ ®¨ã©«ª ›é©œ  «¦ ¯œ¬›é¤¬£æ «¦¬.!)
[0;1m} T Logon message: help


RSLOGONP {[0;1m
!W¦ ¦ ˜¨®œå¦ Ÿâ¢œ«œ ¤˜ ˜¢¢á¥œ«œ; ƒé©«œ [33m*[37m š ˜ «¦ šœ¤ ¡æ £ã¤¬£˜, ã
˜¨ Ÿ£æ ¡˜¤˜¢ ¦ç/unix tty š ˜ ¤˜ ˜¢¢á¥œ«œ «¦ ¡œå£œ¤¦ £æ¤¦ œ¤æª ¡˜¤˜¢ ¦ç, ã
[33m?[37m š ˜ ¡˜«á¢¦š¦ ¬§˜¨®æ¤«à¤ £¤¬£á«à¤:!) [0m} T Logon message: prompt


RSLOGONL1 {[0;1m
‰˜«á¢¦š¦ª ã› ¬§˜¨®æ¤«à¤ ¡œ £â¤à¤ œ ©æ›¦¬

 ‰˜¤á¢   ‹âšœŸ¦ª
-----------------
[0m} T Logon message: message list header


RSLOGONL2A {    *     %5d
} T Logon message: message list, global message


RSLOGONL2B {   %02x     %5d
} T Logon message: message list


RSLOGONL3 {[0;1m-----------------

} T Logon message: message list footer


RSLOGOND {[0;1m
!W€¬«æ «¦ ¡œå£œ¤¦ œ ©æ›¦¬ ¬§á¨®œ  ã›. ‡â¢œ«œ ¤˜ «¦ ˜¢¢á¥œ«œ, ã ¤˜ «¦ › ˜š¨á¯œ«œ;
ƒé©«œ [[33mD[37m]elete=› ˜š¨˜­ã, ã [[33mE[37m]dit=˜¢¢˜šã: [Enter=Edit]!) [0m} T Logon message: delete or edit?


RSLOGONDR {[0;1;31m
€¬«ã  œ§ ¢¦šã› ›œ¤ ¬§á¨®œ .
[0;1m} T Logon message: invalid selection


RSLOGONDD {[0;1;32m
‰˜¢éª, «¦ ¡œå£œ¤¦ œ ©æ›¦¬ › œš¨á­.
[0;1m} T Logon message: logon message deleted




RSCLSSTR {[0;1;31m
!JŠ¬§á£˜ , ›œ¤ ­˜å¤œ«˜  ¤˜ ¬§á¨®œ  «¦ ˜¨®œå¦ ©«˜« ©« ¡é¤ š ˜ «˜ classes.
ˆ©àª ¤˜ ›£ ¦¬¨šœå«˜  ˜¬«ã «¤ ©« š£ã, ã ¤˜ £¤ â®œ  ›£ ¦¬¨šŸœå ˜¡æ£˜.!)
[0;1m} T Class statistics: error


RSCLSST1 {[0;1m
ÚÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄ¿
³ Class     ³ •¨ã©«œª ³ Credits ³ Šœ§«á   ³
ÃÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄ´
} T Class statistics: table header


RSCLSST2 {[0;1m³ [32m%-9s[37m ³ [33m%7d[37m ³ [33m%7d[37m ³ [33m%7d[37m ³
} T Class statistics: table line


RSCLSST3 {[0;1mÀÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÙ

(œ£­˜¤å¦¤«˜  £æ¤¦ classes ©«˜ ¦§¦å˜ â®œ  ¡˜«˜¤˜¢àŸœå ®¨æ¤¦ª)
[0;1m
} T Class statistics: table footer




RSMODSTR {[0;1;31m
!JŠ¬§á£˜ , ›œ¤ ­˜å¤œ«˜  ¤˜ ¬§á¨®œ  «¦ ˜¨®œå¦ ©«˜« ©« ¡é¤ š ˜ «˜ classes.
ˆ©àª ¤˜ ›£ ¦¬¨šœå«˜  ˜¬«ã «¤ ©« š£ã, ã ¤˜ £¤ â®œ  ›£ ¦¬¨šŸœå ˜¡æ£˜.!)
[0;1m} T Module statistics: error


RSMODST1 {[0;1m
ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
³ ¤¦£˜ module                               ³ Credits     %% ³ Šœ§«á       %% ³
ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
} T Class statistics: table header


RSMODST2 {[0;1m³ [32m%-43s[37m³ [33m%7d %5.1f[37m ³ [33m%7d %5.1f [37m³
} T Module statistics: table line


RSMODST3 {[0;1mÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
[0;1m
} T Module statistics: table footer



RSSYSTATS {[0;1m

[32m¤¦£˜ ©¬©«ã£˜«¦ª . . . . . . [37m@BBS@
[32m„¡›¦© §¨¦š¨á££˜«¦ª . . . .  [37m@VERSION@
[32m€¨ Ÿ£æª ¡˜¤˜¢ é¤ . . . . . . [37m%d

[32m„®¦¬¤ ›àŸœå ©¬¤¦¢ ¡á  . . .  [37m%7d [32mcredit(s)
[32m€§'˜¬«á, PAID œå¤˜   . . . . [37m%7d [32mcredit(s)
[32m‘¬¤¦¢ ¡æª on-line ®¨æ¤¦ª  .  [37m%7d [32m¢œ§«á
[32m‘¬¤›â©œ ª  . . . . . . . . . [37m%7d

[32mUploads . . . . . . . . . .  [37m%7d [32m˜¨®œå˜   [37m%7d [32mkbytes
[32mDownloads  . . . . . . . . . [37m%7d [32m˜¨®œå˜   [37m%7d [32mkbytes

[32m‹¤ç£˜«˜ ©œ clubs . . . . .  [37m%7d[32m ©¬¤¦¢ ¡á, [37m%7d[32m ¬§á¨®¦¤«˜
[32m‹¤ç£˜«˜ email . . . . . . . [37m%7d[32m ©¬¤¦¢ ¡á, [37m%7d[32m ¬§á¨®¦¤«˜
[32m‹¤ç£˜«˜ net-mail . . . . .  [37m%7d[32m œ¥œ¨®æ£œ¤˜
[32m‹¤ç£˜«˜ net-mail  . . . . . [37m%7d[32m œ ©œ¨®æ£œ¤˜

[0;1m} T System statistics



RSLINST1 {[0;1m
[32m¤¦£˜ £®˜¤ã£˜«¦ª  . . . [37m%s
[32m!W„¡›¦© ¢œ «¦¬¨š ¡¦ç . .  [37m!i%s!)
[32m!0l„§œ¥œ¨š˜©«ãª  . . . . .  [37m%s %s (%s BogoMips)
[32mUptime . . . . . . . . . [37m%02d:%02d:%02d
[32m”æ¨«¦ª ©¬©«ã£˜«¦ª . . .  [37m%s

ÚÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄ¿
³ ‹Œ†‹† ³  Total  ³   Used  ³   Free  ³ Shared  ³ Buffers ³  Cache  ³
ÃÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄ´
³ RAM   ³  [32m%5d  [37m³  [32m%5d  [37m³  [33m%5d  [37m³  [32m%5d  [37m³  [32m%5d  [37m³  [32m%5d  [37m³
³ Swap  ³  [32m%5d  [37m³  [32m%5d  [37m³  [33m%5d  [37mÃÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÙ
ÀÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÙ
[0;1m} T Linux statistics 1


RSLINSTW {[0;1;32;5m[s!J˜¨˜¡˜¢é §œ¨ £â¤œ«œ...!)[0;1m} T Linux statistics, please wait


RSLINST2 {[0;1m[u[K[0;1m
ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
³ ƒå©¡¦ª          ³ Size (K) ³ Used (K) ³ Free (K) ³ Mounted on               ³
ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
} T Linux statistics 2


RSLINST3 {³ %s%-16s[37m³ %s%8d [37m³ %s%8d [37m³ %s%8d [0;1m³ %s%-25s[37m³
} T Linux statistics 3

RSLINST4 {ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
³ ‘ç¤¦¢¦          ³ [32m%8d [37m³ [32m%8d [37m³ [32m%8d [0;1m³                          ³
ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÙ
³ [32mÛÛ  [37m¢˜ ¡˜¢á    [33mÛÛ  [37m‰˜ ¨æª š ˜ ¡˜Ÿá¨ ©£˜    [31mÛÛ  [37m ƒˆ‘‰‘ ‚„‹ˆ‘„ ³
ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
[0;1m} T Linux statistics 4


RSLINST5 {[32m} T Linux statistics 5 (disk free space is ok)

RSLINST6 {[33m} T Linux statistics 6 (disk free space needs attention)

RSLINST7 {[31m} T Linux statistics 7 (disk free space is critical)


RSGENST1 {[0;1;32m
!J€¬«ã  œ¤«¦¢ã §˜¨â®œ  £ ˜ £œšá¢ ©œ ¨á ©«˜« ©« ¡é¤ ©«¦ ®œåà¤
š ˜ › á­¦¨˜ «£ã£˜«˜ «ª ™á©ª. ‡˜ ®¨œ ˜©«œå ¤˜ ¦¨å©œ«œ §¦ ˜ ©«¦ ®œå˜
Ÿâ¢œ«œ ¤˜ ›œå«œ, ¡˜  £œ §¦ ˜ £¦¨­ã.!)

[37m!W„¨é«© 1 ˜§æ 4: ‡â¢œ«œ ¤˜ ›œå«œ ©ç¤¦¢˜ ã £â©¦¬ª æ¨¦¬ª;
ƒé©«œ [[33mT[37m]otal=‘ç¤¦¢¦, [[33mA[37m]verage=‹â©¦ª æ¨¦ª, ã [33mX[37m š ˜ â¥¦›¦:!) [0m} T Generic statistics 1


RSGENST2 {[0;1m
!W„¨é«© 2 ˜§æ 4: ‡â¢œ«œ  ˜¤á¢¬© ¤˜ šå¤œ  §á¤à ©œ!)

  [33mC[37m. ‰˜«˜¤á¢à© Credits
  [33mM[37m. Šœ§«á (Minutes) on-line
  [33mL[37m. €¨ Ÿ£æ ¡¢ã©œà¤ (CaLls)

!Wƒé©«œ «¤ œ§ ¢¦šã ©˜ª ([33mC[37m,[33mM[37m,[33mL[37m, ã [33mX[37m š ˜ «¤ §¨¦š¦ç£œ¤ œ¨é«©:!) [0m} T Generic statistics 2


RSGENST3 {[0;1m
!W„¨é«© 3 ˜§æ 4: ’  œå›¦¬ª ©«˜« ©« ¡ã Ÿâ¢œ«œ;!)

  [33mB[37m. BaudStats . . . . . . . . . ’˜®ç««œª ©ç¤›œ©ª
  [33mC[37m. ClassStats . . . . . . . . ‰¢á©œ ª ®¨©«é¤ (*)
  [33mD[37m. DayStats  . . . . . . . .  †£œ¨ã© ˜ ¡å¤© (*)
  [33mM[37m. ModStats . . .  ‘«˜« ©« ¡âª š ˜ «˜ modules (*)
  [33mT[37m. TTYstats  . . . . . . . . . . . •¨ã© ¡˜¤˜¢ é¤

!W(*) !iƒœ¤ ¬§¦©«¨åœ«˜  ˜¤á¢¬© ˜¨ Ÿ£¦ç ¡¢ã©œà¤ (™¢. §¨¦š¦ç£œ¤ œ¨é«©).!)[B
!0l
!Wƒé©«œ «¤ œ§ ¢¦šã ©˜ª ([33mB[37m,[33mC[37m,[33mD[37m,[33mM[37m,[33mT[37m,
ã [33mX[37m š ˜ «¤ §¨¦š¦ç£œ¤ œ¨é«©:!) [0m} T Generic statistics 3


RSGENSTR {[0;1;31m
!J„®œ«œ «ã©œ  ˜¤á¢¬© ˜¨ Ÿ£¦ç ¡¢ã©œà¤, ¡˜  «¦ œå›¦ª ©«˜« ©« ¡ãª §¦¬ £æ¢ ª › ˜¢â¥˜«œ
›œ¤ «¦ ¬§¦©«¨åœ  ˜¬«æ. ‰˜  ©«¦ ¡á«à ¡á«à, ˜¤ ›œ¤ ©¦¬ ˜¨¡¦ç¤ ¡á§¦¬ 120 › ˜­¦¨œ« ¡á
š¨˜­ã£˜«˜ ¡˜  Ÿâ¢œ ª ¡  á¢¢˜, ¤˜ §˜ª ¤˜ «˜ ­« á¥œ ª £æ¤¦ª ©¦¬. :-) !)
[0;1m} T Generic statistics, impossible combination


RSGENST4 {[0;1m
!W„¨é«© 4 ˜§æ 4: ’  ®¨¦¤ ¡æ §œ¨ ¦¨ ©£æ ¤˜ Ÿâ©¦¬£œ;!)

  [33mD[37m. Day . . . . . . . . . . ‹æ¤¦ ©£œ¨ ¤á ©«˜« ©« ¡á ©«¦ ®œå˜
  [33mM[37m. Month  . . . . . . . . . . ‘«˜« ©« ¡ã ˜¬«¦ç «¦¬ £ã¤˜ £æ¤¦
  [33mY[37m. Year  . . . . . . . . . . ‘«˜« ©« ¡ã ˜¬«¦ç «¦¬ â«¦¬ª £æ¤¦
  [33mE[37m. Ever . .  ‰˜¤â¤˜ª ®¨¦¤ ¡æª §œ¨ ¦¨ ©£æª, ©¬¤¦¢ ¡á ©«¦ ®œå˜

!Wƒé©«œ «¤ œ§ ¢¦šã ©˜ª ([33mD[37m,[33mM[37m,[33mY[37m,[33mE[37m,
ã [33mX[37m š ˜ «¤ §¨¦š¦ç£œ¤ œ¨é«©:!) [0m} T Generic statistics 4




RSTOPSM {[0;1m
[32m¦ ¦ TOP-30 Ÿâ¢œ«œ ¤˜ ›œå«œ;

[33mA[37m  . . . . . . . . . . . . . . . . . €¨ Ÿ£æª ©¬¤›â©œà¤
[33mB[37m . . . . . . . . . . . . . . . . . ˜¢ æ«œ¨˜ accounts
[33mC[37m  . . . . . . . . . . . . . . . . . . €¨ Ÿ£æª credits
[33mD[37m . . . . . . . . . . . . . . . . €¨ Ÿ£æª paid credits
[33mE[37m  . . . . . . . .  €¨ Ÿ£æª credits §¦¬ â®¦¬¤ ¥¦›œ¬«œå
[33mF[37m . . . . . . . . . . . . . . . . . . . •¨æ¤¦ª on-line
[33mG[37m  . . . . . . . . €¨ Ÿ£æª £¤¬£á«à¤ §¦¬ â®¦¬¤ š¨˜­«œå
[33mH[37m . . . . . .   ¡˜¢ç«œ¨¦  uploaders (˜¨ Ÿ£æª ˜¨®œåà¤)
[33mI[37m  . . . . . .    ¡˜¢ç«œ¨¦  uploaders (˜¨ Ÿ£æª bytes)
[33mJ[37m . . .    ¡˜¢ç«œ¨¦ (;) downloaders (˜¨ Ÿ£æª ˜¨®œåà¤)
[33mK[37m  . . . .   ¡˜¢ç«œ¨¦ (;) downloaders (˜¨ Ÿ£æª bytes)
[33mL[37m . . . . . . . .  ’˜ clubs £œ «˜ §œ¨ ©©æ«œ¨˜ £¤ç£˜«˜
[33mM[37m  . . . . . . . . . ’˜ clubs £œ «˜ §œ¨ ©©æ«œ¨˜ ˜¨®œå˜
[33mN[37m . . . . . . . . . . ’˜ clubs £œ «˜ §œ¨ ©©æ«œ¨˜ á¨Ÿ¨˜
[33mO[37m  . ’˜ clubs £œ « ª §œ¨ ©©æ«œ¨œª ˜¤˜š¤é©œ ª £¤¬£á«à¤
[33mP[37m . . . .  ’˜ clubs £œ « ª §œ¨ ©©æ«œ¨œª ¢ã¯œ ª ˜¨®œåà¤
[0;1m} T TOP-Ns, long menu


RSTOPSS {[0;1m
!Wƒé©«œ «¤ œ§ ¢¦šã ©˜ª ([33mA[37m-[33mP[37m, ã [33mX[37m š ˜ â¥¦›¦)!) [0m} T TOP-Ns, short menu

RSTOPSTA {€¨ Ÿ£æª ©¬¤›â©œà¤} T TOP-Ns, chart title 1
RSTOPSTB {˜¢ æ«œ¨˜ accounts} T TOP-Ns, chart title 2
RSTOPSTC {€¨ Ÿ£æª credits} T TOP-Ns, chart title 3
RSTOPSTD {€¨ Ÿ£æª paid credits} T TOP-Ns, chart title 4
RSTOPSTE {€¨ Ÿ£æª credits §¦¬ â®¦¬¤ ¥¦›œ¬«œå} T TOP-Ns, chart title 5
RSTOPSTF {•¨æ¤¦ª on-line} T TOP-Ns, chart title 6
RSTOPSTG {€¨ Ÿ£æª £¤¬£á«à¤ §¦¬ â®¦¬¤ š¨˜­«œå} T TOP-Ns, chart title 7
RSTOPSTH {  ¡˜¢ç«œ¨¦  uploaders (˜¨ Ÿ£æª ˜¨®œåà¤)} T TOP-Ns, chart title 8
RSTOPSTI {  ¡˜¢ç«œ¨¦  uploaders (˜¨ Ÿ£æª bytes)} T TOP-Ns, chart title 9
RSTOPSTJ {  ¡˜¢ç«œ¨¦ (;) downloaders (˜¨ Ÿ£æª ˜¨®œåà¤)} T TOP-Ns, chart title 10
RSTOPSTK {  ¡˜¢ç«œ¨¦ (;) downloaders (˜¨ Ÿ£æª bytes)} T TOP-Ns, chart title 11
RSTOPSTL {’˜ clubs £œ «˜ §œ¨ ©©æ«œ¨˜ £¤ç£˜«˜} T TOP-Ns, chart title 12
RSTOPSTM {’˜ clubs £œ «˜ §œ¨ ©©æ«œ¨˜ ˜¨®œå˜} T TOP-Ns, chart title 13
RSTOPSTN {’˜ clubs £œ «˜ §œ¨ ©©æ«œ¨˜ á¨Ÿ¨˜} T TOP-Ns, chart title 14
RSTOPSTO {’˜ clubs £œ « ª §œ¨ ©©æ«œ¨œª ˜¤˜š¤é©œ ª £¤¬£á«à¤} T TOP-Ns, chart title 15
RSTOPSTP {’˜ clubs £œ « ª §œ¨ ©©æ«œ¨œª ¢ã¯œ ª ˜¨®œåà¤} T TOP-Ns, chart title 16


RSTOPS1 {

[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[0;30;47m ³  %-50s  [1;37m³ [0m
[0;30;47m ³  ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ  [1;37m³ [0m
} T TOP-Ns, top of chart


RSTOPS2 {[0;30;47m ³  %02d. %11s  %-33s  [1;37m³ [0m
} T TOP-Ns, chart entry


RSTOPS3 {[0;30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0;1m

} T TOP-Ns, chart bottom




RSGDET {[0;1;32m
!J† ç§˜¨¥ ˜¬«ãª «ª œ¤«¦¢ãª ˜§¢á ©£˜å¤œ  æ«  â®œ«œ «¤ œ¤«¦¢ã /L
(global detail). ƒé©«œ [33m/L <¯œ¬›é¤¬£¦>[32m ˜§'¦§¦¬›ã§¦«œ £â©˜ ©«¤ ™á©
š ˜ ¤˜ §á¨œ«œ §¢¨¦­¦¨åœª š ˜ «¦ ¯œ¬›é¤¬£¦ ˜¬«æ.!)
[0;1m} T Global Detail:[A information




RSSYSOPWHO {[0;1m
¦ ¦¤ ¡˜¡¦£¦å¨ Ÿ˜ ¡˜«˜¨˜©«œåª £œ ©¬©¦§ ¡á §¨¦¤æ£ ˜, ˜­œ¤« ¡æ; [0m} T Change Sysop Permissions: Whose?


RSSYSOPNSY {[0;1;31m
!J„ ¦®  ¤˜ ¡á¤¦¬£œ ¡˜  ©ç©¦§˜ æ§¦ ¦¤ ¡˜  æ§¦ ¦¤. €¬«á «˜ ¡˜¤¦¤åœ  ¦ £œšá¢¦ª...!)

!J(€¬«ã  œ¤«¦¢ã ›å¤œ  §¨¦¤æ£ ˜ ©œ ¡á§¦ ¦¤, ˜¤ œ¡«œ¢œ©«œå ˜§æ «¦¤ Sysop. €¢¢ éª,
©˜ª ›œå®¤œ  æ«  â®œ«œ §¨¦¤æ£ ˜ ®œ ¨ ©«ã ©¬©«ã£˜«¦ª.!)

[0;1m} T Remote Sysop can't make person a Sysop


RSSYSOPHDR {[0;1m€¢¢˜šã §¨æ©™˜©ª «¦¬ %s... («¦¤ á£¦ ¨¦)

} T Change Sysop Permissions: Menu header


RSSYSOPMNU {[0;1m
!W„§ ¢¦šã š ˜ ˜¢¢˜šã, ON=æ¢˜, OFF=¡˜¤â¤˜, X š ˜ â¥¦›¦, ã ?: !)[0m} T Change Sysop Permissions: Menu prompt


RSSYSOPON {[0;1m
† œ¤«¦¢ã %s §¨¦©«âŸ¡œ ©«¦ ©ç¤¦¢¦.
} T Change Sysop Permissions: Option turned on


RSSYSOPOFF {[0;1m
† œ¤«¦¢ã %s ˜­˜ ¨âŸ¡œ ˜§æ «¦ ©ç¤¦¢¦.
} T Change Sysop Permissions: Option turned off


RSSYSOPSOP {[0;1;31m
!J’  ˜¤˜©­á¢œ œª œå¤˜  ˜¬«âª, ˜­œ¤« ¡æ; „å©˜  ¦ ¡¦¤©¦¢ â¨ª, ¡˜  ¦ ¡¦¤©¦¢ â¨ª
â®œ  §¨æ©™˜© §á¤«˜ ¡˜  §˜¤«¦ç. ƒœ¤ £§¦¨œåª ¤˜ ˜¢¢á¥œ ª «¤ §¨æ©™˜©ã ©¦¬.!)

[0;1m} T Change Sysop Permissions: Can't change Sysop's access


RSSYSOPUPD {[0;1;32m
€¤«œ, á¢¢¦ª â¤˜ª ©«¦ Club «à¤ ‡œé¤...
} T Change Sysop Permissions: User's permissions updated


RSSYSOPDEL {[0;1;31m
!J’¤ §á«©œª á©®£˜, £á©«¦¨á £¦¬... ‰˜Ÿéª â› ¤œª §¨¦¤æ£ ˜ ©«¦ Ÿç£--,
œœœ, œ¤¤¦é ©«¦¤ ®¨ã©«, ¡á§¦ ¦ª «¦¤ â©™©œ. † §¨æ©™˜© §¦¬ «¦¬ â›à©œª ›œ¤
 ©®çœ  §¢œæ¤.!)

!J‘¬£™¦¬¢ã: ¡¦å«˜ ¡˜¢á £ã§àª œå¤˜  ©«¤ ™á© ¦ ˜ššâ¢ª...!)
[0;1m} T Change Sysop Permissions: User has been deleted


RSSYSOPNOT {[0;1;32m
***
!J •œ ¨ ©«ãª ‘¬©«ã£˜«¦ª £æ¢ ª á¢¢˜¥œ « ª œ › ¡âª §¨¦©™á©œ ª ©˜ª.
„¢á«œ ©œ œ§˜­ã £˜å «¦¬ š ˜ ¤˜ £áŸœ«œ §¦ ˜ ˜¡¨ ™éª ã«˜¤  ˜¢¢˜šã.!)	
[0;1m} T Change Sysop Permissions: User notification






CLSLSTHDR {[0;1;32m
“§á¨®¦¤«˜ classes:

!W} T List of classes: Header

CLSLSTTAB {%-20s} T List of classes: Tabulation

CLSLSTEND {!)
[0;1m} T List of classes: Footer


GCHANBCH {[0;1;31m
!W’©¡ «©¡ «©¡... §á¢  §˜å¦¬£œ; ƒœ¤ ¬§á¨®œ  «â«¦ ¦ ¡˜¤á¢ , ®˜¨ «à£â¤œ!!)
[0;1m} T Get channel: bad channel number


GCHANBDV {[0;1;31m
!W„£ ™â™˜ ˜, á¤«œ ¤˜ ›é©œ ª ©à©«á «¦ tty... :-)
ƒœ¤ £§¦¨é ¤˜ ˜¤¦å¥à ˜¬«æ «¦ tty. ‘åš¦¬¨˜ «¦ â›à©œª ©«¤ £¦¨­ã tty*;
’¦ ¦ç¤ ® §¨¦©â®œ  «˜ ¡œ­˜¢˜å˜ ¡˜  «˜ £ ¡¨á š¨á££˜«˜. „©ç;!)
[0;1m} T Get channel: bad device name


GCHANBID {[0;1;31m
!W€«ç®©œª, ¤œ˜¨â ©ç©¦§˜. €¬«æ «¦ á«¦£¦ ›œ¤ œå¤˜  ©¬›œ›œ£â¤¦.
‰  ˜¤ ›œ¤ £œ § ©«œçœ ª, ¡á¤œ â¤˜ /#. :-)!)
[0;1m} T Get channel: bad user ID


GCHANHUH {[0;1;31m
!Wƒœ¤ ¡˜«˜¢˜™˜å¤à «¤ ¢â¥ "%s". €¤ œå¤˜  æ¤¦£˜ ®¨ã©«, ˜¬«æª ¦ ®¨ã©«ª
›œ¤ ¬§á¨®œ  ©«¤ ™á©. €¢¢ éª, ¡á¤˜«œ £á¢¢¦¤ ¡á§¦ ¦ ¢áŸ¦ª.!)
[0;1m} T Get channel: can't figure out what input is


CHNLSTHDR {[0m
ÚÄÄÄÄÂÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
³ [1;33m##[0m ³  [1;33mBAUD[0m  ³ [1;33m•†‘’†‘ (‰€’€‘’€‘† ‚€‹‹†‘)[0m               ³
ÃÄÄÄÄÅÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
} T Channel list: header

CHNLSTTBQ {[0m³ [1;32m%02x[0m ³        ³ [0;37m¨¦©à¨ ¤á ˜¤œ¤œ¨šã š¨˜££ã (LOGOUT)       [0m ³
} T Channel list: line, QUIT state

CHNLSTTBI {[0m³ [1;32m%02x[0m ³        ³ [0;1;33mReset modem ©«¤ ¡˜«á©«˜© %-14s[0m ³
} T Channel list: line, INIT state

CHNLSTTBR {[0m³ [1;32m%02x[0m ³        ³ [0;1;34m„ ©œ¨®æ£œ¤ «¢œ­à¤ ¡ã ¡¢ã© (RING)      [0m ³
} T Channel list: line, RING state

CHNLSTTBA {[0m³ [1;32m%02x[0m ³        ³ [0;1;36m€§˜¤«é ©œ œ ©œ¨®æ£œ¤ ¡¢ã© (ANSWER)     [0m ³
} T Channel list: line, ANSWER state

CHNLSTTBM {[0m³ [1;32m%02x[0m ³ [1;32m%6s[0m ³ [0;1;32mMetaBBS: %-32.32s[0m ³
} T Channel list: line, METABBS state

CHNLSTTBL {[0m³ [1;32m%02x[0m ³ [1;32m%6s[0m ³ [0;1;37m‘ç¤›œ© £œ «¤ ™á© (LOGIN)              [0m ³
} T Channel list: line, LOGIN state

CHNLSTTBG {[0m³ [1;32m%02x[0m ³        ³ [0;1;37m‘ç¤›œ© ¤â¦¬ ®¨ã©« (RELOGON)            [0m ³
} T Channel list: line, RELOG state

CHNLSTTBU {[0m³ [1;32m%02x[0m ³ [1;32m%6s[0m ³ [0;1m%-31.31s%-10s[0m ³
} T Channel list: line, USER state

CHNLSTPGS {[32;5m(/p sysop)} T Channel list: list, USER state, used has paged the Sysop

CHNLSTTBU2 {[0m³ [1;32m%02x[0m ³ [1;32m%6s[0m ³ [0;1m† š¨˜££ã œå¤˜  ¡˜«œ ¢££â¤.             [0m ³
} T Channel list: line, USER state (unnamed)

CHNLSTTBO {[0m³ [1;32m%02x[0m ³        ³ [0;1;32m‰˜«á©«˜© š¨˜££ãª: %-22s[0m ³
} T Channel list: line, OK state

CHNLSTTBF {[0m³ [1;32m%02x[0m ³        ³ [0;1;31;5m€§¦«¬®å˜ «¦¬ reset! ‰˜«á©«˜©: %-10s[0m ³
} T Channel list: line, FAIL state

CHNLSTTBE {[0m³ [1;32m%02x[0m ³        ³ ¨¦©à¨ ¤á áš¤à©« ¡˜«á©«˜©               ³
} T Channel list: line, error reading line state

CHNLSTFTR {[0mÀÄÄÄÄÁÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
[0;1m} T Channel list: footer







RSAPGVT {[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [34m”å¢«¨¦ ¡˜«˜®à¨ã©œà¤ Audit Trail[0;30;47m ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  „›é £§¦¨œå«œ  ¤˜ œ¢âš¥œ«œ §¦ ˜  œå› ¡˜«˜®à¨ã©œà¤  «¦¬ audit  trail Ÿ˜  [0;1;47;37m³ [0m
[30;47m ³  ©˜ª  ›œå®¤œ  «¦ ©ç©«£˜.  † ©¦™˜¨æ««˜  ¡˜«˜®à¨ã©œà¤ £§¦¨œå ¤˜ ˜¢¢á¥œ   [0;1;47;37m³ [0m
[30;47m ³  ¡˜  £œ «¤ œ¤«¦¢ã /audit. ƒé©«œ Ctrl-O ©œ ¡á§¦ ¦ §œ›å¦ š ˜ ™¦ãŸœ ˜.     [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  „£­á¤ © . . . . . . . . [0;30;46m @23;"‰˜££å˜ ¡˜«˜®é¨©|„§œåš¦¬©œª ¡˜«˜®à¨ã©œ ª|„§œåš¦¬©œª & ‘£˜¤« ¡âª|¢œª ¦  ¡˜«˜®à¨ã©œ ª"l [0;30;47m  (space š ˜ ˜¢¢˜šã)  [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  „å› ¡˜«˜®à¨ã©œà¤ §¦¬ Ÿâ¢œ«œ ¤˜ ™¢â§œ«œ:            (space š ˜ ˜¢¢˜šã)  [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  •¨œé©œ ª/‘«˜« ©« ¡á/Š¦š ©« ¡âª ¡˜«˜®à¨ã©œ ª . . . . . . . . . .  [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³  „ › ¡âª «˜¡« ¡âª › œ¨š˜©åœª (cleanup, events)  . . . . . . . . . [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³  ‰˜«˜®à¨ã©œ ª ®œ ¨ ©£¦ç ©¬©«ã£˜«¦ª . . . . . . . . . . . . . . .  [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³  €©­á¢œ ˜ ©¬©«ã£˜«¦ª, ®¨©«é¤ ¡˜  ˜¨®œåà¤ . . . . . . . . . . . . [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³  ‹œ«˜­¦¨âª/˜¤˜š¤é©œ ª ˜¨®œåà¤  . . . . . . . . . . . . . . . . .  [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³  ‰å¤© ®¨©«é¤ (©¬¤›â©œ ª, ˜§¦©¬¤›â©œ ª, ¡¢§)  . . . . . . . . . [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³  €¢¢œª ¡˜«˜®à¨ã©œ ª  . . . . . . . . . . . . . . . . . . . . . .  [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  ¨¦©¦®ã: ¦  ˜¢¢˜šâª  ©®ç¦¬¤ š ˜ Š„‘ « ª £œ«â§œ «˜ ©¬¤›â©œ ª ©˜ª.       [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³                                  [0;1;42;33m@14;"OK"b[0;47;30mÜ    [0;1;41;33m@14;"Cancel"b[0;47;30mÜ  [0;1;47;37m³ [0m
[30;47m ³  Ctrl-R: ¦ãŸœ ˜                  ßßßßßßßßßßßßßßßß     ßßßßßßßßßßßßßßßß  [0;1;47;37m³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m} T Audit paging: visual template


SEVO {‰˜££å˜ ¡˜«˜®é¨©} T Filtering: show nothing (off)
SEVE {„§œåš¦¬©œª ¡˜«˜®à¨ã©œ ª} T Filtering: show emergency entries only
SEVC {„§œåš¦¬©œª & ‘£˜¤« ¡âª} T Filtering: show emergency and cautionary
SEVI {¢œª ¦  ¡˜«˜®à¨ã©œ ª} T Filtering: show everything



RSAPGLT {[2J[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³ ”å¢«¨¦ ¡˜«˜®à¨ã©œà¤ Audit Trail                                          [0;1;47;37m³ [0m
[30;47m ³ ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [0;1;47;37m³ [0m
[30;47m ³ „›é £§¦¨œå«œ ¤˜  œ¢âš¥œ«œ §¦ ˜ œå› ¡˜«˜®à¨ã©œà¤ «¦¬  audit trail Ÿ˜ ©˜ª [0;1;47;37m³ [0m
[30;47m ³ ›œå®¤œ  «¦ ©ç©«£˜.  † ©¦™˜¨æ««˜  ¡˜«˜®à¨ã©œà¤ £§¦¨œå ¤˜ ˜¢¢á¥œ  ¡˜  £œ [0;1;47;37m³ [0m
[30;47m ³ «¤ œ¤«¦¢ã /audit.                                                       [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³ [31m1[30m. „£­á¤ © . . . . . . . . . . . . . . . . . .  [34m@23;"‰˜££å˜ ¡˜«˜®é¨©|„§œåš¦¬©œª ¡˜«˜®à¨ã©œ ª|„§œåš¦¬©œª & ‘£˜¤« ¡âª|¢œª ¦  ¡˜«˜®à¨ã©œ ª"l [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³ [31m2[30m. •¨œé©œ ª/‘«˜« ©« ¡á/Š¦š ©« ¡âª ¡˜«˜®à¨ã©œ ª . . . . . . . . . . . [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³ [31m3[30m. „ › ¡âª «˜¡« ¡âª › œ¨š˜©åœª (cleanup, events)  . . . . . . . . .  [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³ [31m4[30m. ‰˜«˜®à¨ã©œ ª ®œ ¨ ©£¦ç ©¬©«ã£˜«¦ª . . . . . . . . . . . . . . . . [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³ [31m5[30m. €©­á¢œ ˜ ©¬©«ã£˜«¦ª, ®¨©«é¤ ¡˜  ˜¨®œåà¤ . . . . . . . . . . . .  [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³ [31m6[30m. ‹œ«˜­¦¨âª/˜¤˜š¤é©œ ª ˜¨®œåà¤  . . . . . . . . . . . . . . . . . . [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³ [31m7[30m. ‰å¤© ®¨©«é¤ (©¬¤›â©œ ª, ˜§¦©¬¤›â©œ ª, ¡¢§)  . . . . . . . . .  [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³ [31m8[30m. €¢¢œª ¡˜«˜®à¨ã©œ ª  . . . . . . . . . . . . . . . . . . . . . . . [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  ¨¦©¦®ã: ¦  ˜¢¢˜šâª  ©®ç¦¬¤ š ˜ Š„‘ « ª £œ«â§œ «˜ ©¬¤›â©œ ª ©˜ª.       [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m
} T Audit paging: Linear template


RSAPGH0 {[0;1m
!J  ¡˜«˜®à¨ã©œ ª «¦¬ Audit Trail ®à¨å¦¤«˜  ©œ «¨œ ª £œšá¢œª ¡˜«š¦¨åœª
©¦™˜¨æ««˜ª.   §¢¨¦­¦¨ ˜¡âª ¡˜«˜®à¨ã©œ ª œå¤˜  ¦  § ¦ ¡¦ ¤âª. ‰˜«˜®à¨¦ç¤
­¬© ¦¢¦š ¡âª › œ¨š˜©åœª.   ©£˜¤« ¡âª ¡˜«˜®à¨ã©œ ª œ£­˜¤å¦¤«˜  ©œ ¡æ¡¡ ¤¦
®¨é£˜. ¤¦£á¦¤«˜  ©£˜¤« ¡âª š ˜«å £§¦¨œå ¤˜ ›¢é¤¦¬¤ ¡˜«˜©«á©œ ª §¦¬
˜§˜ «¦ç¤ «¤ §¨¦©¦®ã ©˜ª (æ§àª œšš¨˜­âª ¤âà¤ ®¨©«é¤, hack tries ¡¢§). ’â¢¦ª,
¦  œ§œåš¦¬©œª ¡˜«˜®à¨ã©œ ª œå¤˜  ¦  § ¦ ©§á¤ œª ¡˜  ›¢é¤¦¬¤ ©¦™˜¨á §¨¦™¢ã£˜«˜
©« ™á©. á¤«¦«œ §¨â§œ  ¤˜ «¦¬ª ›å¤œ«˜   ˜§˜¨˜å«« §¨¦©¦®ã. „›é £§¦¨œå«œ ¤˜
¦¨å©œ«œ «¦ ¡˜«é­¢  ©¦™˜¨æ««˜ª «à¤ ¡˜«˜®à¨ã©œà¤ §¦¬ Ÿ˜ ™¢â§œ«œ ˜¤á §á©˜
©« š£ã.!)
} T Audit paging: field help 0

RSAPGH1 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«æ «¦ œå›¦ª ¡˜«˜®é¨©ª, «¦ ©ç©«£˜ Ÿ˜ ©˜ª œ ›¦§¦ œå ¡áŸœ
­¦¨á §¦¬ Ÿ˜ ¡˜«˜š¨á­œ«˜  ¡á«  §¦¬ â®œ  ¤˜ ¡á¤œ  £œ ®¨œé©œ ª credits,
©«˜« ©« ¡âª ¡˜«˜®à¨ã©œ ª ¡˜  šœ¤ ¡éª ¢¦š ©« ¡âª ¡˜«˜®à¨ã©œ ª.!)
[0;1m} T Audit paging: field help 1


RSAPGH2 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«æ «¦ œå›¦ª ¡˜«˜®é¨©ª, «¦ ©ç©«£˜ Ÿ˜ ©˜ª œ ›¦§¦ œå ¡áŸœ
­¦¨á §¦¬ Ÿ˜ ¡˜«˜š¨á­œ«˜  ¡á«  §¦¬ â®œ  ¤˜ ¡á¤œ  £œ « ª «˜¡« ¡âª › œ¨š˜©åœª
«ª ™á©ª (§® cleanup).!)
[0;1m} T Audit paging: field help 2


RSAPGH3 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«æ «¦ œå›¦ª ¡˜«˜®é¨©ª, «¦ ©ç©«£˜ Ÿ˜ ©˜ª œ ›¦§¦ œå ¡áŸœ
­¦¨á §¦¬ Ÿ˜ ¡˜«˜š¨á­œ«˜   œ¡«â¢œ© ¡á§¦ ˜ª œ¤«¦¢ãª ®œ ¨ ©«ã ©¬©«ã£˜«¦ª ã
§˜¨æ£¦ ˜ œ¤â¨šœ ˜.!)
[0;1m} T Audit paging: field help 3


RSAPGH4 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«æ «¦ œå›¦ª ¡˜«˜®é¨©ª, «¦ ©ç©«£˜ Ÿ˜ ©˜ª œ ›¦§¦ œå ¡áŸœ
­¦¨á §¦¬ Ÿ˜ ¡˜«˜š¨á­œ«˜  ¡á«  §¦¬ â®œ  ¤˜ ¡á¤œ  £œ «¤ ˜©­á¢œ ˜ «¦¬
©¬©«ã£˜«¦ª: §¨¦©§áŸœ œª ©§˜©å£˜«¦ª ¢¦š˜¨ ˜©£é¤ ¡¢§.!)
[0;1m} T Audit paging: field help 4


RSAPGH5 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«æ «¦ œå›¦ª ¡˜«˜®é¨©ª, «¦ ©ç©«£˜ Ÿ˜ ©˜ª œ ›¦§¦ œå ¡áŸœ
­¦¨á §¦¬ Ÿ˜ ¡˜«˜š¨á­¦¤«˜  £œ«˜­¦¨âª ˜¨®œåà¤, ˜¤˜š¤é©œ ª ˜¨®œåà¤ ã §˜¨æ£¦ œª
œ¤â¨šœ œª.!)
[0;1m} T Audit paging: field help 5


RSAPGH6 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«æ «¦ œå›¦ª ¡˜«˜®é¨©ª, «¦ ©ç©«£˜ Ÿ˜ ©˜ª œ ›¦§¦ œå ¡áŸœ
­¦¨á §¦¬ Ÿ˜ ¡˜«˜š¨á­¦¤«˜  ©¬¤›â©œ ª ¡˜  ˜§¦©¬¤›â©œ ª ®¨©«é¤ (¡˜  ©®œ« ¡âª
¡˜«˜®à¨ã©œ ª).!)
[0;1m} T Audit paging: field help 6


RSAPGH7 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«æ «¦ œå›¦ª ¡˜«˜®é¨©ª, «¦ ©ç©«£˜ Ÿ˜ ©˜ª œ ›¦§¦ œå ¡áŸœ
­¦¨á §¦¬ Ÿ˜ ¡˜«˜š¨á­œ«˜  ¡á§¦ ˜ œ¤â¨šœ ˜ §¦¬ ›œ¤ ˜¤ã¡œ  ©« ª á¢¢œª
¡˜«š¦¨åœª ¡˜«˜®à¨ã©œà¤.!)
[0;1m} T Audit paging: field help 7


RSAPGCAN {[0;1;31m
  ˜¢¢˜šâª ©˜ª £˜«˜ éŸ¡˜¤.
[0;1m} T Audit paging: filtering changes aborted


RSAPGOK {[0;1;32m
„¤«á¥œ , «¦ ­å¢«¨¦ «à¤ ¡˜«˜®à¨ã©œà¤ ¨¬Ÿ£å©«¡œ.
[0;1m} T Audit paging: filtering changes set



RSFLTVT {[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [34m„¨œ¬¤˜ «¦¬ Audit Trail[0;30;47m ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  „¨œ¬¤˜ š ˜ . . . [1;44;37m@80;51;0s[0;1;47;37m  [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  „¨œ¬¤˜ §¢¨¦­¦¨ ˜¡é¤ ¡˜«˜®à¨ã©œà¤ . . . . . . . . . . . . . . .  [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³  „¨œ¬¤˜ ©£˜¤« ¡é¤ ¡˜«˜®à¨ã©œà¤ . . . . . . . . . . . . . . . . . [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³  „¨œ¬¤˜ œ§œåš¦¬©à¤ ¡˜«˜®à¨ã©œà¤  . . . . . . . . . . . . . . . .  [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  „¨œ¬¤˜ ®¨œé©œà¤/©«˜« ©« ¡é¤/¢¦š ©« ¡é¤ ¡˜«˜®à¨ã©œà¤  . . . . . . [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³  „¨œ¬¤˜ œ › ¡é¤ «˜¡« ¡é¤ › œ¨š˜© é¤ (cleanup, events)  . . . . .  [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³  „¨œ¬¤˜ ‰˜«˜®à¨ã©œà¤ ®œ ¨ ©£¦ç ©¬©«ã£˜«¦ª . . . . . . . . . . . . [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³  „¨œ¬¤˜ €©­á¢œ ˜ª ©¬©«ã£˜«¦ª, ®¨©«é¤ ¡˜  ˜¨®œåà¤  . . . . . . .  [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³  „¨œ¬¤˜ ‹œ«˜­¦¨é¤/˜¤˜š¤é©œà¤ ˜¨®œåà¤  . . . . . . . . . . . . . . [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³  „¨œ¬¤˜ ‰ ¤ã©œà¤ ®¨©«é¤ (©¬¤›â©œà¤, ˜§¦©¬¤›â©œà¤, ¡¢§)  . . . .  [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³  „¨œ¬¤˜ €¢¢à¤ ¡˜«˜®à¨ã©œà¤  . . . . . . . . . . . . . . . . . . . [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  „£­á¤ © ˜§æ «¦ «â¢¦ª (¤âœª ¡˜«˜®à¨ã©œ ª) §¨¦ª «¤ ˜¨®ã . . . .  [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³                                  [0;1;42;33m@14;"OK"b[0;47;30mÜ    [0;1;41;33m@14;"Cancel"b[0;47;30mÜ  [0;1;47;37m³ [0m
[30;47m ³  Ctrl-R: ¦ãŸœ ˜                  ßßßßßßßßßßßßßßßß     ßßßßßßßßßßßßßßßß  [0;1;47;37m³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m} T Audit search: visual template



RSFLTLT {[2J[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³ „¨œ¬¤˜ «¦¬ Audit Trail                                                   [0;1;47;37m³ [0m
[30;47m ³ ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³ [31m1[30m.  „¨œ¬¤˜ š ˜ . . . [34m@80;51;0s [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³ [31m2[30m.  „¨œ¬¤˜ §¢¨¦­¦¨ ˜¡é¤ ¡˜«˜®à¨ã©œà¤ . . . . . . . . . . . . . . .  [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³ [31m3[30m.  „¨œ¬¤˜ ©£˜¤« ¡é¤ ¡˜«˜®à¨ã©œà¤ . . . . . . . . . . . . . . . . . [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³ [31m4[30m.  „¨œ¬¤˜ œ§œåš¦¬©à¤ ¡˜«˜®à¨ã©œà¤  . . . . . . . . . . . . . . . .  [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³ [31m5[30m.  „¨œ¬¤˜ •¨œé©œà¤/‘«˜« ©« ¡é¤/Š¦š ©« ¡é¤ ¡˜«˜®à¨ã©œà¤ . . . . . .  [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³ [31m6[30m.  „¨œ¬¤˜ „ › ¡é¤ «˜¡« ¡é¤ › œ¨š˜© é¤ (cleanup, events) . . . . . . [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³ [31m7[30m.  „¨œ¬¤˜ ‰˜«˜®à¨ã©œà¤ ®œ ¨ ©£¦ç ©¬©«ã£˜«¦ª  . . . . . . . . . . .  [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³ [31m8[30m.  „¨œ¬¤˜ €©­á¢œ ˜ª ©¬©«ã£˜«¦ª, ®¨©«é¤ ¡˜  ˜¨®œåà¤ . . . . . . . . [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³ [31m9[30m.  „¨œ¬¤˜ ‹œ«˜­¦¨é¤/˜¤˜š¤é©œà¤ ˜¨®œåà¤ . . . . . . . . . . . . . .  [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³ [31m10[30m. „¨œ¬¤˜ ‰å¤©ª ®¨©«é¤ (©¬¤›â©œ ª, ˜§¦©¬¤›â©œ ª, ¡¢§)  . . . . . [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³ [31m11[30m. „¨œ¬¤˜ €¢¢à¤ ¡˜«˜®à¨ã©œà¤ . . . . . . . . . . . . . . . . . . .  [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³ [31m12[30m. „£­á¤ © ˜§æ «¦ «â¢¦ª (¤âœª ¡˜«˜®à¨ã©œ ª) §¨¦ª «¤ ˜¨®ã . . . .  [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m
} T Audit search: linear template


RSFLT1 {[0;1m
!J„›é £§¦¨œå«œ ¤˜ ›é©œ«œ £å˜ ¢â¥ ã ­¨á© ¡¢œ ›å «¤ ¦§¦å˜ Ÿ˜ ¯á¥¦¬£œ ©«¦ 
Audit Trail. €¤ ˜­ã©œ«œ ˜¬«æ «¦ §œ›å¦ ¡œ¤æ, æ¢œª ¦  ¡˜«˜®à¨ã©œ ª «¦¬ Audit
Trail Ÿ˜ œ£­˜¤ ©«¦ç¤ (˜­¦ç ­ ¢«¨˜¨ ©«¦ç¤ ¡˜  ˜§æ « ª ¨¬Ÿ£å©œ ª «à¤ ¬§æ¢¦ §à¤
§œ›åà¤!).
[0;1m} T Audit search: field help 1


RSFLT2 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«ã «¤ œ§ ¢¦šã, «¦ ©ç©«£˜ Ÿ˜ ¯á¥œ  š ˜ §¢¨¦­¦¨ ˜¡âª ¡˜«˜®à¨ã©œ ª.
‹§¦¨œå«œ ¤˜ œ£­˜¤å©œ«œ ¡  á¢¢œª ¡˜«˜®à¨ã©œ ª œ¤œ¨š¦§¦ é¤«˜ª «˜ ˜¤«å©«¦ ®˜ §œ›å˜.!)
[0;1m} T Audit search: field help 2


RSFLT3 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«ã «¤ œ§ ¢¦šã, «¦ ©ç©«£˜ Ÿ˜ ¯á¥œ  š ˜ ©£˜¤« ¡âª ¡˜«˜®à¨ã©œ ª.
‹§¦¨œå«œ ¤˜ œ£­˜¤å©œ«œ ¡  á¢¢œª ¡˜«˜®à¨ã©œ ª œ¤œ¨š¦§¦ é¤«˜ª «˜ ˜¤«å©«¦ ®˜ §œ›å˜.!)
[0;1m} T Audit search: field help 3


RSFLT4 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«ã «¤ œ§ ¢¦šã, «¦ ©ç©«£˜ Ÿœ ¯á¥œ  š ˜ œ§œåš¦¬©œª ¡˜«˜®à¨ã©œ ª.
‹§¦¨œå«œ ¤˜ œ£­˜¤å©œ«œ ¡  á¢¢œª ¡˜«˜®à¨ã©œ ª œ¤œ¨š¦§¦ é¤«˜ª «˜ ˜¤«å©«¦ ®˜ §œ›å˜.!)
[0;1m} T Audit search: field help 4

RSFLTH5 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«æ «¦ œå›¦ª ¡˜«˜®é¨©ª, «¦ ©ç©«£˜ Ÿ˜ ¯á¥œ  š ˜
¡˜«˜®à¨ã©œ ª §¦¬ â®¦¬¤ ¤˜ ¡á¤¦¬¤ £œ ®¨œé©œ ª credits,
©«˜« ©« ¡âª ¡˜«˜®à¨ã©œ ª ¡˜  šœ¤ ¡éª ¢¦š ©« ¡âª ¡˜«˜®à¨ã©œ ª.!)
[0;1m} T Audit paging: field help 5


RSFLTH6 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«æ «¦ œå›¦ª ¡˜«˜®é¨©ª, «¦ ©ç©«£˜ Ÿ˜ ¯á¥œ  š ˜
¡˜«˜®à¨ã©œ ª §¦¬ â®¦¬¤ ¤˜ ¡á¤¦¬¤ £œ « ª «˜¡« ¡âª › œ¨š˜©åœª
«ª ™á©ª (§® cleanup).!)
[0;1m} T Audit paging: field help 6


RSFLTH7 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«æ «¦ œå›¦ª ¡˜«˜®é¨©ª, «¦ ©ç©«£˜ Ÿ˜ ¯á¥œ  š ˜
¡˜«˜®à¨ã©œ ª §¦¬ â®¦¬¤ ¤˜ ¡á¤¦¬¤ £œ «¤ œ¡«â¢œ© œ¤«¦¢é¤ ®œ ¨ ©«ã ©¬©«ã£˜«¦ª ã
§˜¨æ£¦ œª œ¤â¨šœ œª.!)
[0;1m} T Audit paging: field help 7


RSFLTH8 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«æ «¦ œå›¦ª ¡˜«˜®é¨©ª, «¦ ©ç©«£˜ Ÿ˜ ¯á¥œ  š ˜
¡˜«˜®à¨ã©œ ª §¦¬ â®¦¬¤ ¤˜ ¡á¤¦¬¤ £œ «¤ ˜©­á¢œ ˜ «¦¬
©¬©«ã£˜«¦ª: §¨¦©§áŸœ œª ©§˜©å£˜«¦ª ¢¦š˜¨ ˜©£é¤ ¡¢§.!)
[0;1m} T Audit paging: field help 8


RSFLTH9 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«æ «¦ œå›¦ª ¡˜«˜®é¨©ª, «¦ ©ç©«£˜ Ÿ˜ ¯á¥œ  š ˜ 
¡˜«˜®à¨ã©œ ª §¦¬ â®¦¬¤ ¤˜ ¡á¤¦¬¤ £œ £œ«˜­¦¨âª ˜¨®œåà¤, ˜¤˜š¤é©œ ª ˜¨®œåà¤ ã §˜¨æ£¦ œª
œ¤â¨šœ œª.!)
[0;1m} T Audit paging: field help 9


RSFLTH10 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«æ «¦ œå›¦ª ¡˜«˜®é¨©ª, «¦ ©ç©«£˜ Ÿ˜ ¯á¥œ  š ˜
¡˜«˜®à¨ã©œ ª §¦¬ â®¦¬¤ ¤˜ ¡á¤¦¬¤ £œ ©¬¤›â©œ ª ¡˜  ˜§¦©¬¤›â©œ ª ®¨©«é¤.!)
[0;1m} T Audit paging: field help 10


RSFLTH11 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«æ «¦ œå›¦ª ¡˜«˜®é¨©ª, «¦ ©ç©«£˜ Ÿ˜ ¯á¥œ 
š ˜ ¡˜«˜®à¨ã©œ ª §¦¬ ›œ¤ ˜¤ã¡¦¬¤ ©« ª ¬§æ¢¦ §œª ¡˜«š¦¨åœª.!)
[0;1m} T Audit paging: field help 11



RSFLTH12 {[0;1m
!J‹œ ˜¬«ã «¤ œ§ ¢¦šã œ¤œ¨šã, ¦  ¡˜«˜®à¨ã©œ ª ©˜ª §˜¨¦¬© á¦¤«˜  £œ ˜¤«å©«¨¦­ ®¨¦¤ ¡ã ©œ ¨á: ¦  § ¦ §¨æ©­˜«œª
œ£­˜¤å¦¤«˜  §¨é«œª. €¬«ã œå¤˜  ¡˜   § ¦ §¨˜¡« ¡ã ¢œ «¦¬¨šå˜ ¡˜«á ¡˜¤æ¤˜.!)
[0;1m} T Audit paging: field help 12











AUDSRCH {[0;1;32m
„¨œ¬¤˜ «¦¬ Audit Trail...
!FÄ
[0;1m} T Searching Audit Trail


AUDSEND {!0l[0;1;32m!FÄ

’â¢¦ª â¨œ¬¤˜ª.
[0;1m} T Searching Audit Trail, end of search


AUDNF {[0;1;31m
!J‘¬šš¤é£, ›œ¤ ™¨âŸ¡œ «å§¦«˜ ©®œ« ¡æ.!)
[0;1m} T Searching Audit Trail, nothing found


AUDSCAN {[0;1;31m!0l
† â¨œ¬¤˜ «œ¨£˜«å©«¡œ.
[0;1m} T Audit Trail search terminated.


LANG {}



NARSOP {[0;1;31m
Sorry, you don't have access to this area.
[0;1m
} T You don't have access to this service


EXITRS {[0;1m
Leaving the operator menu...
} T Remote Sysop exit to main menu


RSHDR {[0;1;33m!Z@BBS@ Operator Menu
 
} T Remote Sysop menu header


RSCOM01 {[31m%sCHANGE . . . . . . . . . Change/view channel status
} T Remote sysop command description


RSCOM02 {[31m%sEMULATE  . . . . . . . . . . . .  Inspect a channel
} T Remote sysop command description


RSCOM03 {[31m%sMONITOR  . . . . . . . . . .  Inspect channel input
} T Remote sysop command description


RSCOM04 {[31m%sSEND . . . . . . . . . .  Send a message to user(s)
} T Remote sysop command description


RSCOM05 {[32m%sDELETE . . . . . . . . . .  Delete a user's account
} T Remote sysop command description


RSCOM06 {[32m%sDETAIL . . . . . . . . . . . .  Get info about user
} T Remote sysop command description


RSCOM07 {[32m%sEXEMPT . . . . . . . (Un)protect user from deletion
} T Remote sysop command description


RSCOM08 {[32m%sHANGUP . . . . . . . . . . . . .  Disconnect a user
} T Remote sysop command description


RSCOM09 {[32m%sPOST . . . . . . . . . . . . Give credits to a user
} T Remote sysop command description


RSCOM10 {[32m%sSEARCH . . . . . . . . . . . . Search user database
} T Remote sysop command description


RSCOM11 {[32m%sSUSPEND  . . . . . . . . Toggle user's lockout flag
} T Remote sysop command description


RSCOM12 {[33m%sAUDIT  . . . . . . . . . .  Inspect system log file
} T Remote sysop command description


RSCOM13 {[33m%sCLEANUP  . . . . . . . . . Inspect cleanup log file
} T Remote sysop command description


RSCOM14 {[33m%sEVENT  . . . . . . . . . Schedule and cancel events
} T Remote sysop command description


RSCOM15 {[33m%sFILTAUD  . . . . . . . . . . Search the Audit Trail
} T Remote sysop command description


RSCOM16 {[33m%sLOGON  . . . . . . . . . . . . Change login message
} T Remote sysop command description


RSCOM17 {[33m%sSECURITY . . . . . . . . . . . . . .  Security logs
} T Remote sysop command description


RSCOM18 {[33m%sSIGNUPS  . . . . . . . . . . .  View recent signups
} T Remote sysop command description


RSCOM19 {[34m%sAGESTATS . . . . . . . . . . .  System demographics
} T Remote sysop command description


RSCOM20 {[34m%sCLSSTATS . . . . . . . . . . . . . Class statistics
} T Remote sysop command description


RSCOM21 {[34m%sGENSTATS . . . . . . . . . . . . Generic statistics
} T Remote sysop command description


RSCOM22 {[34m%sLINSTATS . . . . . . . . . . . . . Linux statistics
} T Remote sysop command description


RSCOM23 {[34m%sMODSTATS . . . . . . . . . . . .  Module statistics
} T Remote sysop command description


RSCOM24 {[34m%sSYSTATS  . . . . . . . . . . . .  System statistics
} T Remote sysop command description


RSCOM25 {[34m%sTOP  . . . . . . . . . . . . . . . . User TOP lists
} T Remote sysop command description


RSCOM26 {[35m%sCLASSED  . . . . . . . . . . . . . . . Class Editor
} T Remote sysop command description


RSCOM27 {[35m%sKEYS . . . . . . . . . . . . . Edit user's key list
} T Remote sysop command description


RSCOM28 {[35m%sUSERCLASS  . . . . . . . . .  Change a user's class
} T Remote sysop command description


RSCOM29 {[36m%sCOPY . . . . . . . . . . . . . . . . .  Copy a file
} T Remote sysop command description


RSCOM30 {[36m%sDIR  . . . . . . . . . . . . . . . . File directory
} T Remote sysop command description


RSCOM31 {[36m%sEDITOR . . . . . . . . . . . . .  Invoke the editor
} T Remote sysop command description


RSCOM32 {[36m%sREN  . . . . . . . . . . . .  Rename or move a file
} T Remote sysop command description


RSCOM33 {[36m%sRM . . . . . . . . . . . . . . . . .  Delete a file
} T Remote sysop command description


RSCOM34 {[36m%sRUN  . . . . . . . . . . . . Execute a Unix command
} T Remote sysop command description


RSCOM35 {[36m%sSHELL  . . . . . . . . . . . . Jump to a Unix shell
} T Remote sysop command description


RSCOM36 {[36m%sTRANSFER . . . . . . . . . .  Upload/download files
} T Remote sysop command description


RSCOM37 {[36m%sTYPE . . . . . . . . . . . . .  Display a text file
} T Remote sysop command description


RSCOM38 {[37m%sGDET  . . . . . . . . . . . . .  Global DETAIL (/L)
} T Remote sysop command description


RSCOM39 {[37m%sINVIS . . . . . . . . . .  Invisible Sysop (/invis)
} T Remote sysop command description


RSCOM40 {[37m%sPAGEAUDIT . . . . . . . . Global Audit Notification
} T Remote sysop command description


RSCOM41 {[37m%sSYSOP . . . . . . . . .  System Operator privileges
} T Remote sysop command description


OPTSEP {
} T Remote Sysop menu option separator


OPTON {=> } T Remote Sysop menu option enabled


OPTOFF {   } T Remote Sysop menu option disabled


RSSMNU {[1;37m
OPERATOR MENU
Enter command (or ? for the menu): [0m} T Remote Sysop short prompt


ERRCOM {[0;1;31m
Unknown command.
[0;1m} T Remote Sysop generic invalid option


MORCHR {[0;1;31m
Ambiguous abbreviation "%s" (try adding one or two letters).
} T Remote Sysop need more characters to distinguish commands


NUMERR {[0;1;31m
Enter a number in the range %d - %d.
[0;1m} T Remote Sysop generic numeric error


UNKUID {[0;1;31m
User "%s" does not exist.
[0;1m} T Generic error: no such user


NOAXES {[0;1;31m
Sorry, you don't have access to command %s.
[0;1m
} T Remote Sysop no access to that option


EXECERR {[0;1;31m
Your command couldn't be executed.
[0;1m} T Couldn't exec external program


CRDSING {} T "Credit" singular form
CRDPLUR {s} T "Credits" plural form

MSCACC {} T Male user accusative
FEMACC {} T Female user accusative


NOTIFIED {[0;1;32m
%s is online and has been notified.
} T User on-line and notifed




RSCHANGEWHT {[0;1m
!WWhat channel do we change? Enter channel number, UNIX tty name
(e.g. ttyS1), ALL or * for all channels, or ? for a list:!) [0m} T Change channel status: Which one?


RSCHANGEERR {[0;1;31m
!JThere's already a user on that channel. Disconnect them and try again.!)
[0;1m} T Change channel status: There's a user in that channel


RSCHANGELMN {[0;1;37m
What's the new status of the channel to be?

[37mR[32mESET (NORMAL) . . . . . . . . . The line accepts connections as usual.
[37mB[32mUSY-OUT  . . . . . . . . . . . . The line goes off hook (busy signal).
[37mN[32mO-ANSWER  . . . . . . . . . . . . . . . .  Incoming calls are ignored.
[37mO[32mFF-LINE . . . . .  Answers calls, issues a brief message and hangs up.
[0;1m} T Change channel status: Long menu

RSCHANGESMN {[0;1m
!WEnter the new status ([33mR[37m,[33mB[37m,[33mN[37m,[33mO[37m, ? for
the menu, or X to exit):!) [0m} T Change channel status: Short menu


RSCHANGEBAD {[0;1;31m
Sorry, that's not a valid choice.
[0;1m} T Change channel status: Wrong selection


RSCHANGEOK {[0;1;32m
!JFine, the status change has been requested.!)
} T Change channel status: Done, submitting new status
 


RSEMUWHO {[0;1m
!WWhom do you want to emulate?
Enter channel number, UNIX tty (§® ttyS1), user ID, or ? for a list:!) [0m} T Emulate channel: Which one?


RSEMUSLF {[0;1;31m
There's no sense in emulating yourself!
[0;1m} T Emulate channel: can't emulate self


RSEMUHAHA {[0;1;31m
!JErm, you're trying to emulate someone who's already emulating
you. You're a paranoid lot, aren't you?!)
[0;1m} T Emulate channel: attempt to establish circular emulation


RSEMUNUS {[0;1;31m
!JThat channel doesn't have a resident emulation daemon (emud), so
it can't be emulated. Maybe you're trying to emulate an inactive
channel.!)
[0;1m} T Emulate channel: can't emulate 'emud'-less channel


RSEMUGO {
[0;47;30m[K Emulating... [1;33mCtrl-Q[0;47;30m = QUIT, [1;33mCtrl-C[0;47;30m = SYSOP CHAT, [1;33mCtrl-Z[0;47;30m = HANGUP !F-
[0;1m[K} T Emulate channel: beginning emulation


RSEMUEND {
[0;47;30m[K END OF EMULATION !F-
[0;1m[K} T Emulate channel: end of emulation


RSEMUHUP {
[0;1;45;37m[K User disconnected.
[0;1m[K} T Emulate channel: user zapped out


RSEMUNOE {
!J[0;1mThe user has disconnected (or is running something very
strange).!)
[0;1m} T Emulate channel: user disconnected.


RSEMUCHT {[0;1m
!W[0;1;33;5mÛÛ[0;1;33m  Warning: !iThe user has been abandoned in
Sysop Chat Mode. Only you can take them out of it (emulate the user
again and press Ctrl-C for Sysop Chat).!)
!0l[0;1m} T Emulate channel: user abandoned in sysop chat mode


RSMONITORHDR {[0;1m[2J
CHANNEL     TEXT
!F-
[0m} T Monitor Channel: Header


RSMONITORTAB {[0m[0;1;33m%-12s[0m!i!W%s!)
!0l!1r} T Monitor Channel: Table line


RSMONITOREND {[0;1m!F-

[0;1mEnd of channel monitoring.

} T Monitor Channel: End of monitoring


RSMONITORERR {[0;1;31m
!JError while monitoring channels!!)
[0;1m} T Monitor Channel: Error occured




RSSENDWHO {[0;1m
!WWhom do we send a sysop page to?
Enter channel number, UNIX tty (e.g. ttyS1), user ID,
[33mALL[37m to send to everyone, or
? for a list:!) [0m} T Send message to channel: Which one?


RSSENDR {[0;1;31m
There's no-one on that channel.
[0;1m} T Send message to channel: no user in that channel


RSSENDD {[0;1;31m
!JSorry, the user disconnected while you were editing the text
of the message.!)
[0;1m} T Send message to channel: user disconnected


RSSEND1 {[0;1;32m
OK, the message was sent to channel [37m%x[32m.
[0;1m} T Send message to channel: message sent to one channel


RSSENDX {[0;1;31m
!WSorry, [37m%s[31m is in the BUSY state and can't be paged.!)
[0;1m} T Send message to channel: message not send, user was BUSY


RSSEND2 {[0;1;32m
!JThe message was sent to [32mall users[37m.!)
[0;1m} T Send message to channel: message sent to all users


RSSEND2A {[0;1;33m
!JThe message couldn't be sent to [32mall users[37m.!)
[0;1m} T Send message to channel: couldn't send to ALL users


RSSEND2B {[0;1;31m
!JSorry, the message couldn't be sent to any user at all.!)
[0;1m} T Send message to channel: couldn't send to ANY users


RSSENDCAN {[0;1;31m
Aborted.
[0;1m } T Send message to channel: canceled


RSSENDINH {[0m



[36;5mÛÛ  [0;1mFROM THE SYSTEM OPERATOR:

} T Send message to channel: message header




RSDELETEWHO {
!W[0;1;31;5mÛÛ[0;1;31m  ATTENTION: !iThe user account
you are about to name will be deleted. They will be unable to
login until the coming cleanup, at which point all user account
data will be irretrievably removed from the system. Until then, you
can undo the deletion using the same command (DELETE).!)
!0l[0;1m
!WWhose blood should we spray all over the console, boss? !)[0m} T Delete a user: who?


RSDELETEERR {
!J[0;1;31m[37m%s[31m is exempt from deletion. The account cannot be
deleted unless the exemption is removed.!)
[0;1m} T Delete a user: user is exempt


RSDELETEOK {
!J[0;1;32mOkay, [37m%s[32m was tagged for deletion. To undo this,
you may issue the same command (DELETE) BEFORE THE COMING CLEANUP.!)
[0;1m} T Delete a user: ok


RSDELETEUNDO {
!J[0;1;32mOkay, [37m%s[32m is now reinstated. The account will
NOT be deleted at the coming cleanup.!)
[0;1m} T Delete a user: undeleted



RSDETAILWHO {[0;1m
!WUser ID to view detailed information on: !)[0m} T Datailed info: About whom?


RSDETAILNAX {<Suppressed>} T Detailed info: field contents withheld

RSDETAILSUSP {[31mşSUSPENDEDş} T Detailed info: 'suspended' string

RSDETAILXMPT {[32mşEXEMPTş} T Detailed info: 'exempt' string

RSDETAILDEL {[31mşDELETEDş} T Detailed info: 'deleted' string

RSDETAILOP {[32mşOPERATORş} T Detailed info: 'operator' string

RSDETAILM {Male} T Detailed info: 'male' string
RSDETAILF {Female} T Detailed info: 'female' string

GDETS1 {IBM PC compatible} T Detailed info: system #1
GDETS2 {Apple Macintosh} T Detailed info: system #2
GDETS3 {Apple II/II+/IIe, ¡¢§} T Detailed info: system #3
GDETS4 {Amiga} T Detailed info: system #4
GDETS5 {Atari} T Detailed info: system #5
GDETS6 {Archimedes} T Detailed info: system #6
GDETS7 {Amstrad CPC 464/664/6128} T Detailed info: system #7
GDETS8 {Unknown} T Detailed info: system #8
GDETS9 {} T Detailed info: system #9

GDETNST {(non-stop)} T Detailed info: 'non-stop' string

GDETL1 {Ellhnika} T Detailed info: language #1
GDETL2 {English} T Detailed info: language #2
GDETL3 {} T Detailed info: language #3
GDETL4 {} T Detailed info: language #4
GDETL5 {} T Detailed info: language #5
GDETL6 {} T Detailed info: language #6
GDETL7 {} T Detailed info: language #7
GDETL8 {} T Detailed info: language #8
GDETL9 {} T Detailed info: language #9
GDETL0 {} T Detailed info: language #10


RSDETAIL {[0;1m
[0;36mÛÛ  [1mDetailed account info for %s  [46m[K[0;1m

[32mCreation date . . . .  [37m%-9s  %s %s
[32mLast online  . . . . . [37m%-9s  %s %s

[32mName  . . . . . . . .  [37m%s
[32mCompany  . . . . . . . [37m%s
[32mAddress (1/2) . . . .  [37m%s
[32mAddress (2/2)  . . . . [37m%s
[32mTelephone . . . . . .  [37m%s
[32mAge  . . . . . . . . . [37m%s
[32mSex . . . . . . . . .  [37m%s
[32mComputer type  . . . . [37m%s
[32mScreen size . . . . .  [37m%d x %d %s
[32mLanguage . . . . . . . [37m%s
[32mClass . . . . . . . .  [37m%s
[32mPassword . . . . . . . [37m%s
[32mCredits . . . . . . .  [37m%d (%d PAID)

[46m[K[0;1m
} T Detailed info: template



RSEXEMPTWHO {[0;1m
!WThis (un)tags users as exempt from deletion. User ID: !)[0m} T Exempt a user: who?


RSEXEMPTERR {[0;1;31m
!WSysop is always exempt from deletion.!)
[0;1m} T Exempt a user: can't unexempt sysop.


RSEXEMPTOK {
!J[0;1;32mDone, [37m%s[32m is now exempt from deletion.!)
[0;1m} T Exempt a user: ok


RSEXEMPTUNDO {
!J[0;1;32mDone, [37m%s[32m is no longer exempt and can be deleted.!)
[0;1m} T Exempt a user: unexempted




RSSUSPWHO {[0;1m
!WWhom do we (un)suspend? !)[0m} T Suspend a user: who?


RSSUSPERR {
!J[0;1;31m[37m%s[31m is tagged exempt. The account can't be suspended.!)
[0;1m} T Suspend a user: user is exempt


RSSUSPOK {
!J[0;1;32mDone, [37m%s[32m will no longer be able to login
until taken out of suspension or deleted.!)
[0;1m} T Suspend a user: ok


RSSUSPUNDO {
!J[0;1;32mDone, [37m%s[32m is no longer suspended.!)
[0;1m} T Suspend a user: unsuspended




RSPOSTWHO {[0;1m
Whom do we post credist to? [0m} T Post credits: To whom?


RSPOSTAMT {[0;1m
How many credits? [0m} T Post credits: How many?


RSPOSTFOP {[0;1m
Are these (F)ree or (P)aid credits? [0m} T Post credits: Free or Paid?


RSPOSTERR {[0;1;31m
Enter [33mF[31m for free credits or [33mP[31m for paid credits.
[0;1m} T Post credits: Please enter F or P


RSPOSTCNF {[0;1;32m
!WYou are about to post %d %s credit%s to%s %s. Proceed?!)[0m } T Post credits: Do you confirm?


RSPOSTDEL {[0;1;31m
!JWhoops, the user no longer exists.!)
[0;1m} T Post credits: User has been deleted


RSPOSTNOT1 {[0;1;32m
***
!JThe System Operator has just posted you [37m%d free credit%s[32m.!)
} T Post credits: User notification, free credits


RSPOSTNOT2 {[0;1;32m
***
!JThe System Operator has just posted you [37m%d credit%s[32m that you've paid for.!)
} T Post credits: User notification, paid credits


RSPOSTNOT3 {[0;1;32m
***
!JThe System Operator has just posted you [37m%d credit%s[32m
that you've paid for. You have been moved to the [37m%s[32m class.
Enter [33mAV[32m at the main menu to review your new status.!)
} T Post credits: User notification, paid credits with class change


RSPOSTOK {[0;1;32m
Credits posted.
[0;1m} T Post credits: Transfer ok.



RSPOSTOK2 {[0;1;32m
Credits posted. The user was moved to the [37m%s[32m class.
[0;1m} T Post credits: Transfer ok with class change



RSHANGUPWHO {[0;1m
!WWhom do we kick out, boss?
Enter channel number, UNIX tty (e.g. ttyS1), username, or ? for a list:!) [0m} T Hangup User: Who?


RSHANGUPERR {[0;1;31m
!JThat channel is currently unused.!)
[0;1m} T Hangup User: No user in that channel.


RSHANGUPOK {[0;1;32m
User disconnected.
[0;1m} T Hangup User: User kicked out.


RSSRCHVT {[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [34m„¨œ¬¤˜ ™á©ª ›œ›¦£â¤à¤ ®¨©«é¤[0;30;47m ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  –œ¬›é¤¬£¦ . . . . . . . . . [0;30;46m @2;" |<|<=|=|>=|>|IN"l [47m  [1;44;37m@23;23;0s[47;37m             ³ [0m
[30;47m ³  ‘ç¤Ÿ£˜  . . . . . . . . .  [0;30;46m @2;" |<|<=|=|>=|>|IN"l [47m  [1;44;37m@15;15;2s[47;37m                     ³ [0m
[30;47m ³  ¤¦£˜«œ§é¤¬£¦ . . . . . . . [0;30;46m @2;" |<|<=|=|>=|>|IN"l [47m  [1;44;37m@30;30;0s[47;37m      ³ [0m
[30;47m ³  „«˜ ¨œå˜ . . . . . . . . .  [0;30;46m @2;" |<|<=|=|>=|>|IN"l [47m  [1;44;37m@30;30;0s[47;37m      ³ [0m
[30;47m ³  ƒ œçŸ¬¤© (1/2) . . . . . . [0;30;46m @2;" |<|<=|=|>=|>|IN"l [47m  [1;44;37m@30;30;0s[47;37m      ³ [0m
[30;47m ³  ƒ œçŸ¬¤© (2/2)  . . . . .  [0;30;46m @2;" |<|<=|=|>=|>|IN"l [47m  [1;44;37m@30;30;0s[47;37m      ³ [0m
[30;47m ³  ’¢â­à¤¦  . . . . . . . . . [0;30;46m @2;" |<|<=|=|>=|>|IN"l [47m  [1;44;37m@23;23;0s[47;37m             ³ [0m
[30;47m ³  “§¦¢¦š ©«ãª  . . . . . . .  [0;30;46m @2;" |="l [47m  [0;30;46m @14;"IBM compatible|Apple Mac|Old Apple|Amiga|Atari|Archimedes|Amstrad CPC|€š¤à©«¦"l [1;47;37m                      ³ [0m
[30;47m ³  †¢ ¡å˜  . . . . . . . . . . [0;30;46m @2;" |<|<=|=|>=|>"l [47m  [1;44;37m@2;0;99;0n[47;37m                                  ³ [0m
[30;47m ³  ”ç¢¦ . . . . . . . . . . .  [0;30;46m @2;" |="l [47m  [46m @7;"€¤›¨˜ª|‚¬¤˜å¡˜"l [1;47;37m                             ³ [0m
[30;47m ³  Credits › ˜Ÿâ© £˜ «é¨˜  . . [0;30;46m @2;" |<|<=|=|>=|>"l [47m  [1;44;37m@9;0;999999999;0n[47;37m                           ³ [0m
[30;47m ³  PAID credits àª «é¨˜ . . .  [0;30;46m @2;" |<|<=|=|>=|>"l [47m  [1;44;37m@9;0;999999999;0n[47;37m                           ³ [0m
[30;47m ³  Class . . . . . . . . . . . [0;30;46m @2;" |="l [47m  [1;44;37m@9;9;1s[47;37m                           ³ [0m
[30;47m ³  †£œ¨¦£¤å˜ œšš¨˜­ãª  . . .  [0;30;46m @2;" |<|<=|=|>=|>"l [47m  [1;44;37m@10;10;4s[0;30;47m            (dd/mm/yyyy)[1;37m  ³ [0m
[30;47m ³  ’œ¢œ¬«˜å˜ ©ç¤›œ© . . . . . [0;30;46m @2;" |<|<=|=|>=|>"l [47m  [1;44;37m@10;10;4s[0;30;47m            (dd/mm/yyyy)[1;37m  ³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  ' '=don't-care  'IN'=§œ¨ â®œ                                            [0;1;47;37m³ [0m
[30;47m ³                                  [0;1;42;33m@14;"OK"b[0;47;30mÜ    [0;1;41;33m@14;"Cancel"b[0;47;30mÜ  [0;1;47;37m³ [0m
[30;47m ³  Ctrl-R: ¦ãŸœ ˜                  ßßßßßßßßßßßßßßßß     ßßßßßßßßßßßßßßßß  [0;1;47;37m³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m} T Search: visual template


RSSRCHM {€¤›¨˜ª} T String for 'male' in edit templates
RSSRCHF {‚¬¤˜å¡˜} T String for 'female' in edit templates

RSSRCHS1 {IBM compatible} T String for system type #1 in edit templates
RSSRCHS2 {Apple Mac} T String for system type #2 in edit templates
RSSRCHS3 {Old Apple} T String for system type #3 in edit templates
RSSRCHS4 {Amiga} T String for system type #4 in edit templates
RSSRCHS5 {Atari} T String for system type #5 in edit templates
RSSRCHS6 {Archimedes} T String for system type #6 in edit templates
RSSRCHS7 {Amstrad CPC} T String for system type #7 in edit templates
RSSRCHS8 {€š¤à©«¦} T String for system type #8 (unknown) in edit templates


RSSRCHLT {[2J[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³ „¨œ¬¤˜ ™á©ª ›œ›¦£â¤à¤ ®¨©«é¤                                           [0;1;47;37m³ [0m
[30;47m ³ ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [0;1;47;37m³ [0m
[30;47m ³ –œ¬›é¤¬£¦ . . . . . . . . . [31m 1[30m. [34m@2;" |<|<=|=|>=|>|IN"l  [31m 2[30m. [34m@23;23;0s[1;47;37m          ³ [0m
[30;47m ³ ‘ç¤Ÿ£˜  . . . . . . . . .  [31m 3[30m. [34m@2;" |<|<=|=|>=|>|IN"l  [31m 4[30m. [34m@15;15;2s[1;47;37m                  ³ [0m
[30;47m ³ ¤¦£˜«œ§é¤¬£¦ . . . . . . . [31m 5[30m. [34m@2;" |<|<=|=|>=|>|IN"l  [31m 6[30m. [34m@30;30;0s[1;47;37m   ³ [0m
[30;47m ³ „«˜ ¨œå˜ . . . . . . . . .  [31m 7[30m. [34m@2;" |<|<=|=|>=|>|IN"l  [31m 8[30m. [34m@30;30;0s[1;47;37m   ³ [0m
[30;47m ³ ƒ œçŸ¬¤© (1/2) . . . . . . [31m 9[30m. [34m@2;" |<|<=|=|>=|>|IN"l  [31m10[30m. [34m@30;30;0s[1;47;37m   ³ [0m
[30;47m ³ ƒ œçŸ¬¤© (2/2)  . . . . .  [31m11[30m. [34m@2;" |<|<=|=|>=|>|IN"l  [31m12[30m. [34m@30;30;0s[1;47;37m   ³ [0m
[30;47m ³ ’¢â­à¤¦  . . . . . . . . . [31m13[30m. [34m@2;" |<|<=|=|>=|>|IN"l  [31m14[30m. [34m@23;23;0s[1;47;37m          ³ [0m
[30;47m ³ “§¦¢¦š ©«ãª  . . . . . . .  [31m15[30m. [34m@2;" |="l  [31m16[30m. [34m@14;"IBM compatible|Apple Mac|Old Apple|Amiga|Atari|Archimedes|Amstrad CPC|€š¤à©«¦"l[1;47;37m                   ³ [0m
[30;47m ³ †¢ ¡å˜  . . . . . . . . . . [31m17[30m. [34m@2;" |<|<=|=|>=|>"l  [31m18[30m. [34m@2;0;99;0n[1;47;37m                               ³ [0m
[30;47m ³ ”ç¢¦ . . . . . . . . . . .  [31m19[30m. [34m@2;" |="l  [31m20[30m. [34m@7;"€¤›¨˜ª|‚¬¤˜å¡˜"l[1;47;37m                          ³ [0m
[30;47m ³ Credits › ˜Ÿâ© £˜ «é¨˜  . . [31m21[30m. [34m@2;" |<|<=|=|>=|>"l  [31m22[30m. [34m@9;0;999999999;0n[1;47;37m                        ³ [0m
[30;47m ³ PAID credits àª «é¨˜ . . .  [31m23[30m. [34m@2;" |<|<=|=|>=|>"l  [31m24[30m. [34m@9;0;999999999;0n[1;47;37m                        ³ [0m
[30;47m ³ Class . . . . . . . . . . . [31m25[30m. [34m@2;" |="l  [31m26[30m. [34m@9;9;1s[1;47;37m                        ³ [0m
[30;47m ³ †£œ¨¦£¤å˜ œšš¨˜­ãª  . . .  [31m27[30m. [34m@2;" |<|<=|=|>=|>"l  [31m28[30m. [34m@10;10;4s[1;37;47m                       ³ [0m
[30;47m ³ ’œ¢œ¬«˜å˜ ©ç¤›œ© . . . . . [31m29[30m. [34m@2;" |<|<=|=|>=|>"l  [31m30[30m. [34m@10;10;4s[1;37;47m                       ³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m} T Search: Linear template


RSSRCH1 {} T Search: help for field #1
RSSRCH2 {} T Search: help for field #2
RSSRCH3 {} T Search: help for field #3
RSSRCH4 {} T Search: help for field #4
RSSRCH5 {} T Search: help for field #5
RSSRCH6 {} T Search: help for field #6
RSSRCH7 {} T Search: help for field #7
RSSRCH8 {} T Search: help for field #8
RSSRCH9 {} T Search: help for field #9
RSSRCH10 {} T Search: help for field #10
RSSRCH11 {} T Search: help for field #11
RSSRCH12 {} T Search: help for field #12
RSSRCH13 {} T Search: help for field #13
RSSRCH14 {} T Search: help for field #14
RSSRCH15 {} T Search: help for field #15
RSSRCH16 {} T Search: help for field #16
RSSRCH17 {} T Search: help for field #17
RSSRCH18 {} T Search: help for field #18
RSSRCH19 {} T Search: help for field #19
RSSRCH20 {} T Search: help for field #20
RSSRCH21 {} T Search: help for field #21
RSSRCH22 {} T Search: help for field #22
RSSRCH23 {} T Search: help for field #23
RSSRCH24 {} T Search: help for field #24
RSSRCH25 {} T Search: help for field #25
RSSRCH26 {} T Search: help for field #26
RSSRCH27 {} T Search: help for field #27
RSSRCH28 {} T Search: help for field #28
RSSRCH29 {} T Search: help for field #29
RSSRCH30 {} T Search: help for field #30


RSSRCHC {[0;1;31m
† › ˜› ¡˜©å˜ ˜¡¬¨éŸ¡œ.
[0;1m} T Search: canceled


RSSRCHR {[0;1;31m
!Wƒœ¤ â®œ  ¤æ£˜ ¤˜ ¯á¥¦¬£œ ©«¤ ™á© ›œ›¦£â¤à¤ ˜¤ ›œ¤ ¦¨å©œ«œ
«¦¬¢á® ©«¦¤ â¤˜ ¡¨ «ã¨ ¦. :-) !)
[0;1m} T Search: no query


RSSRCHB {[0;1m
( â©«œ [33mEnter[37m š ˜ «œ¨£˜« ©£æ «ª â¨œ¬¤˜ª)

•¨ã©«œª §¦¬ ™¨âŸ¡˜¤:

–„“ƒ—Œ“‹    €‚‹€’ˆ‰ Œ‹€
!F-
[0m} T Search: header


RSSRCHL {%-13s%s
} T Search: found user


RSCLASSWHO {[0;1m
¦ ¦¤ ®¨ã©« Ÿâ¢œ ª ¤˜ £œ«˜¡ ¤ã©œ ª ©œ á¢¢¦ class; [0m} T Change User's Class: Whose?


RSCLASSREP {[0;1;32m
•¨ã©«ª . . . . . . . . [37m%s[32m
’¨â®¦¤ class  . . . . . [37m%s
[0;1m} T Change User's Class: Current class report


RSCLASSCLS {[0;1m
‘œ §¦ ¦ class ¤˜ £œ«˜­œ¨Ÿœå ¦ ®¨ã©«ª; (? š ˜ ¡˜«á¢¦š¦) [0m} T Change User's Class: Which class?


RSCLASSERR {[0;1;31m
’©¡ «©¡ «©¡... ›œ¤ ¬§á¨®œ  ˜¬«æ «¦ class. ƒé©œ ? š ˜ ¡˜«á¢¦š¦.
[0;1m} T Change User's Class: Class does not exist


RSCLASSDEL {[0;1;31m
!J”«¦¬! ©¦ œ©ç á¢¢˜œª «¦ class, ¡á§¦ ¦ª â©™©œ «¦¤ ®¨ã©«.
† ˜¢¢˜šã class ›œ¤  ©®çœ  §¢â¦¤.!)

!J‘åš¦¬¨˜ ›œ¤ ¡á¤œ  §¢˜¡å«©œª ¦ ‹§¢áŸ¨˜ª;;;!)
[0;1m} T Change Class: User has been deleted


RSCLASSNOT {[0;1;32m
***
!J •œ ¨ ©«ãª ‘¬©«ã£˜«¦ª £æ¢ ª ©˜ª £œ«â­œ¨œ ©«¦ class [37m%s[32m. ƒé©«œ
[33mAV[32m ˜§æ «¦ ¡œ¤«¨ ¡æ £œ¤¦ç š ˜ ¤˜
›œå«œ «  á¢¢˜¥œ ©«¦¤ ¢¦š˜¨ ˜©£æ ©˜ª.!)
[0;1m} T Change Class: User notification


RSCLASSOK {[0;1;32m
„¤«á¥œ ,  ˜¢¢˜šã âš ¤œ £œ œ§ «¬®å˜.

[0;1m} T Change Class: Finished successfully





RSKEYSWHO {[0;1m
‹œ §¦ ¦¤ ®¨ã©« Ÿ˜ §˜å¥œ ª §á¢ , ˜­œ¤« ¡æ; [0m} T Change User's Keys: Whose?


RSKEYSSYS {[0;1;31m
® , ƒ„Œ Ÿ˜ §˜å¥œ ª £œ «˜ ¡¢œ › á «¦¬ ©ç©¦§˜. €¬«æª «˜ â®œ  æ¢˜ £¦¤å£àª.

[0;1m} T Change User's Keys: Won't change Sysop's keys


RSKEYSTAB {[0;1;32m
ÉÍÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÍ»
º 0   ³    1    ³    2    ³    3    ³    4    ³    5    ³    6   6 º
º 12 4 6 8 0 2 4 6 8 0 2 4 6 8 0 2 4 6 8 0 2 4 6 8 0 2 4 6 8 0 2 4 º
º [37m%s[32m º
ÌÍØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØÍ¹
º ³         ³         ³         ³    1    ³    1    ³    1    ³  1 º
º 6    7    ³    8    ³    9    ³    0    ³    1    ³    2    ³  2 º
º 56 8 0 2 4 6 8 0 2 4 6 8 0 2 4 6 8 0 2 4 6 8 0 2 4 6 8 0 2 4 6 8 º
º [37m%s[32m º
ÈÍÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÍ¼
[0;1m} T Change User's Keys: Key Editor Template


RSKEYSASK {
[0;1m!Wƒé©«œ «¦¤ ˜¨ Ÿ£æ «¦¬ ¡¢œ › ¦ç (1-128, ? š ˜ œ£­á¤ © ¡¢œ › é¤, 
ON=æ¢˜, OFF=¡˜¤â¤˜, OK š ˜ «â¢¦ª, X š ˜ ˜¡ç¨à©): !)[0m} T Change User's Keys: Key Editor, enter key


RSKEYSON {[0;1;32m
’¦ ¡¢œ ›å %d §¨¦©«âŸ¡œ ©«¦ ©ç¤¦¢¦.
[0;1m} T Change User's Keys: Key Editor, added key


RSKEYSOFF {[0;1;32m
’¦ ¡¢œ ›å %d ˜­˜ ¨âŸ¡œ ˜§æ «¦ ©ç¤¦¢¦.
[0;1m} T Change User's Keys: Key Editor, deleted key


RSKEYSDEL {[0;1;31m
!J”«¦¬! ©¦ œ©ç â§˜ œª £œ «˜ ¡¢œ › á, ¡á§¦ ¦ª â©™©œ «¦¤ ®¨ã©«.
† ˜¢¢˜šã ›œ¤  ©®çœ  §¢â¦¤.!)
[0;1m} T Change User's Keys: User has been deleted


RSKEYSOK {[0;1;32m
„¤«á¥œ ,  ˜¢¢˜šã âš ¤œ £œ œ§ «¬®å˜.

[0;1m} T Change User's Keys: Finished successfully




RSTYPEASK {[0;1;32m!W‡¬£åà æ«  ©«¦ linux š¨á­¦¬£œ «˜ directories £œ '/' ¡˜  æ®  £œ '\'! :-)!)

[0;1m¡, «é¨˜, §¦ ¦ ˜¨®œå¦ Ÿâ¢œ ª ¤˜ ›œ ª; [0m} T Type file: What file?


RSTYPEERR {[0;1;31m
!J’¦ ˜¨®œå¦ %s ›œ¤ ™¨âŸ¡œ ã ›œ¤ £§¦¨œå ¤˜ ˜¤¦ ®Ÿœå.!)

[0;1m} T Type file: File not found




RSCOPYSRC {[0;1;32m!W‡¬£åà æ«  ©«¦ linux š¨á­¦¬£œ «˜ directories £œ '/' ¡˜  æ®  £œ '\'! :-)!)

[0;1m¡, «é¨˜, §¦ ¦ ˜¨®œå¦ Ÿâ¢œ ª ¤˜ ˜¤« š¨á¯œ ª; [0m} T Copy file: Enter source file


RSCOPYTRG {
[0;1m‰˜  §¦ç Ÿâ¢œ ª ¤˜ «¦ ˜¤« š¨á¯œ ª;            [0m} T Copy file: Enter destination


RSCOPYERR {[0;1;31m
!J† ˜¤« š¨˜­ã ©«˜£á«©œ ¢æšà ¢áŸ¦¬ª.!)

[0;1m} T Copy file: cp returned error


RSCOPYOK {[0;1;31m
!J† ˜¤« š¨˜­ã «â¢œ à©œ œ§ «¬®éª.!)

[0;1m} T Copy file: ok!




RSRENSRC {[0;1;32m!W‡¬£åà æ«  ©«¦ linux š¨á­¦¬£œ «˜ directories £œ '/' ¡˜  æ®  £œ '\'! :-)!)

[0;1m¡, «é¨˜, §¦ ¦ ˜¨®œå¦ Ÿâ¢œ ª ¤˜ £œ«¦¤¦£á©œ ª; [0m} T Rename/move file: Enter file


RSRENTRG {
[0;1m‰˜  §¦ ¦ œå¤˜  «¦ ¡˜ ¤¦ç¨ ¦ æ¤¦£á «¦¬;        [0m} T Rename/move file: Enter new name/dir


RSRENERR {[0;1;31m
!J† › ˜› ¡˜©å˜ ©«˜£á«©œ ¢æšà ¢áŸ¦¬ª.!)

[0;1m} T Rename/move file: mv returned error


RSRENOK {[0;1;31m
!J† › ˜› ¡˜©å˜ «â¢œ à©œ œ§ «¬®éª.!)

[0;1m} T Rename/move file: ok!




RSDIRASK {[0;1;32m!W‡¬£åà æ«  ©«¦ linux š¨á­¦¬£œ «˜ directories £œ '/' ¡˜  æ®  £œ '\'! :-)!)

[0;1m¡, «é¨˜, §¦ ¦ directory/˜¨®œå¦ Ÿâ¢œ ª ¤˜ ¡á¤œ ª DIR; [0m} T DIR: what directory?


RSDIRERR {[0;1;31m
!J’¦ %s ›œ¤ ™¨âŸ¡œ ã ›œ¤ £§¦¨œå ¤˜ ˜¤¦ ®Ÿœå.!)

[0;1m} T DIR: can't open directory/file




RSDELASK {
!W[0;1;31;5m‘•†: !i[0;1;31m¨æ¡œ «˜  ¤˜ › ˜š¨á¯œ«œ â¤˜
˜¨®œå¦. [5mƒ„Œ[0;1;31m Ÿ˜ ¬§á¨¥œ  á¢¢ œ¨é«©, ¡˜  «¦ ˜¨®œå¦
[5mƒ„Œ[0;1;31m £§¦¨œå ¤˜ ˜¤˜¡«Ÿœå £œ ¡˜¤â¤˜ «¨æ§¦. ¨¦©â¥«œ «  ¡á¤œ«œ.!)
!0l
[0;1m¦ ¦ ˜¨®œå¦ Ÿâ¢œ«œ ¤˜ › ˜š¨á¯œ«œ; [0m} T DEL: what file?


RSDELERR {[0;1;31m
!J’¦ %s ›œ¤ ™¨âŸ¡œ ã ›œ¤ £§¦¨œå ¤˜ › ˜š¨˜­œå.!)

[0;1m} T DEL: can't remove directory/file




RSSYSASK {[0;1;32m!W‡¬£åà æ«  ©«¦ linux š¨á­¦¬£œ «˜ directories £œ '/' ¡˜  æ®  £œ '\'! :-)!)

[0;1m¡, «é¨˜, §¦ ˜ œ¤«¦¢ã Ÿâ¢œ ª ¤˜ «¨â¥œ ª; [0m} T SYS: Enter command to run



RSXFERDIR {[0;1m
¦ ˜ œå¤˜   › œçŸ¬¤© «ª £œ«˜­¦¨áª ˜¨®œåà¤;

[33mU[37m . . . €¤œ™á¦¬£œ ®¨ã© £¦ ˜¨®œå¦ (§® ¤â¦ "™œ¢« à£â¤¦" kernel)
[33mD[37m  . .  ‰˜«œ™á¦¬£œ ˜§˜¨˜å««˜ utilities (cindy???.gif)
} T Transfer files: Up or down?


RSXFERSHRT {
[0;1m˜¨˜¡˜¢é ›é©«œ «¤ œ§ ¢¦šã ©˜ª (œšé ¤å§«à «˜ª virtual ®œå¨˜ª £¦¬): [0m} T Transfer files: Up or down, short menu


RSXFERRSEL {[0;1;31m
˜¨˜¡˜¢é ›é©«œ [33mU[31m, [33mD[31m, [33m?[31m š ˜ «¦ £œ¤¦ç, ã [33mX[31m š ˜ â¥¦›¦.
[0;1m} T Transfer files: Wrong selection


RSXFERWHD {
[0;1;32m!W‡¬£åà æ«  ©«¦ linux š¨á­¦¬£œ «˜ directories £œ '/' ¡˜  æ®  £œ '\'! :-)!)[37m

!W¦ ¦ ˜¨®œå¦ Ÿâ¢œ«œ ¤˜ ¢á™œ«œ; ˜¨˜¡˜¢é ›é©«œ «¦ æ¤¦£˜ «¦¬ ˜¨®œå¦¬
(wildcards œ§ «¨â§¦¤«˜ ):!) [0m} T Transfer files: Enter filename


RSXFERERR {[0;1;31m
!J’¦ %s ›œ¤ ™¨âŸ¡œ ã ›œ¤ £§¦¨œå ¤˜ ˜¤¦ ®Ÿœå.!)

[0;1m} T Transfer files: Can't open file


RSXFERWHU {
[0;1;32m!W‡¬£åà æ«  ©«¦ linux š¨á­¦¬£œ «˜ directories £œ '/' ¡˜  æ®  £œ '\'! :-)!)

[32m€¨®œå˜ §¦¬ ©«œå¢˜«œ: [37m%d

!W‘œ §¦ ¦ directory ¤˜ «˜ ©«œå¢¦¬£œ;!) [0m} T Transfer files: Enter directory


RSXFERER2 {[0;1;31m
!J’¦ %s ›œ¤ œå¤˜  directory! ’©¡ «©¡ «©¡...!)

[0;1m} T Transfer files: File is not a directory


RSXFERER3 {[0;1;31m
!J€¡ç¨à© £œ«˜­¦¨áª.!)

[0;1m} T Transfer files: transfer aborted.



RSEDITWHF {
[0;1;32m!W‡¬£åà æ«  ©«¦ linux š¨á­¦¬£œ «˜ directories £œ '/' ¡˜  æ®  £œ '\'! :-)!)[37m

!W¦ ¦ ˜¨®œå¦ Ÿâ¢œ«œ ¤˜ ­â¨œ«œ ©«¦¤ editor; ˜¨˜¡˜¢é ›é©«œ «¦ æ¤¦£˜ «¦¬ ˜¨®œå¦¬:!) [0m} T Edit a file: Enter filename


RSEDITERR {[0;1;31m
!J’¦ %s ›œ¤ ™¨âŸ¡œ ã ›œ¤ £§¦¨œå ¤˜ ˜¤¦ ®Ÿœå.!)

[0;1m} T Edit a file: Can't open file







RSAUDIT1 {[0;1m
„£­á¤ © «¦¬ Audit Trail.

!W‡â¢œ«œ ¤˜ ›œå«œ «¦ Audit Trail ˜§æ «¤ ˜¨®ã ([[33mB[37m]eginning) ã «¦ «â¢¦ª
([[33mE[37m]nd);!)[0m } T Audit: Beginning or end?


RSAUDITR {[0;1;31m
!Wƒœ¤ ¬§á¨®œ  ˜¬«ã  œ§ ¢¦šã.!)
[0m} T Audit: No such option


RSAUDIT2 {[0;1;32m

(§ â©«œ Enter š ˜ › ˜¡¦§ã «ª œ£­á¤ ©ª)

AUDIT TRAIL
!F-
[0m} T Audit: Listing audit trail


RSAUDITI {!W[0;1m%s!)
!26l!W[0m%s!)
!0l} T Audit: single audit entry, informational


RSAUDITC {!W[0;1;33m%s!)
!26l!W[0m%s!)
!0l} T Audit: single audit entry, cautionary


RSAUDITE {!W[0;1;31m%s!)
!26l!W[0m%s!)
!0l} T Audit: single audit entry, emergency


RSAUDIT3 {!0l[0;1;31m

!W† › ˜› ¡˜©å˜ «œ¨£˜«å©«¡œ §¨æà¨˜.!)
[0;1m} T Audit: Listing terminated




RSCLEANUP1 {[0;1m
„£­á¤ © «¦¬ Cleanup Audit Trail.

!W‡â¢œ«œ ¤˜ ›œå«œ «¦ Cleanup Audit Trail ˜§æ «¤ ˜¨®ã ([[33mB[37m]eginning) ã «¦ «â¢¦ª
([[33mE[37m]nd);!)[0m } T Audit: Beginning or end?


RSCLEANUPR {[0;1;31m
!Wƒœ¤ ¬§á¨®œ  ˜¬«ã  œ§ ¢¦šã.!)
[0m} T Audit: No such option


RSCLEANUP2 {[0;1;32m

(§ â©«œ Enter š ˜ › ˜¡¦§ã «ª œ£­á¤ ©ª)

CLEANUP AUDIT TRAIL
!F-
[0m} T Audit: Listing audit trail


RSCLEANUP3 {[0;1;31m

!W† › ˜› ¡˜©å˜ «œ¨£˜«å©«¡œ §¨æà¨˜.!)
[0;1m} T Audit: Listing terminated



RSLOGONH {[0;1m

€¢¢˜šã ¡œ £â¤¦¬ œ ©æ›¦¬ (logon message).

!J“§á¨®¦¬¤ ›ç¦ œå› ¡œ £â¤à¤: «¦ šœ¤ ¡æ, §¦¬ œ£­˜¤åœ«˜  ©œ æ¢˜ «˜ ¡˜¤á¢ ˜,
¡˜  «¦ œ › ¡æ, §¦¬ œ£­˜¤åœ«˜  £æ¤¦ ©œ â¤˜ ¡˜¤á¢ . ‰áŸœ ¡˜¤á¢  £§¦¨œå ¤˜
â®œ  «¦ › ¡æ «¦¬ ¡œå£œ¤¦, §¦¬ œ£­˜¤åœ«˜  ‹€…ˆ £œ «¦ šœ¤ ¡æ ¡œå£œ¤¦ ˜£â©àª
§¨ ¤ ¦ ®¨ã©«ª ›é©œ  «¦ ¯œ¬›é¤¬£æ «¦¬.!)
[0;1m} T Logon message: help


RSLOGONP {[0;1m
!W¦ ¦ ˜¨®œå¦ Ÿâ¢œ«œ ¤˜ ˜¢¢á¥œ«œ; ƒé©«œ [33m*[37m š ˜ «¦ šœ¤ ¡æ £ã¤¬£˜, ã
˜¨ Ÿ£æ ¡˜¤˜¢ ¦ç/unix tty š ˜ ¤˜ ˜¢¢á¥œ«œ «¦ ¡œå£œ¤¦ £æ¤¦ œ¤æª ¡˜¤˜¢ ¦ç, ã
[33m?[37m š ˜ ¡˜«á¢¦š¦ ¬§˜¨®æ¤«à¤ £¤¬£á«à¤:!) [0m} T Logon message: prompt


RSLOGONL1 {[0;1m
‰˜«á¢¦š¦ª ã› ¬§˜¨®æ¤«à¤ ¡œ £â¤à¤ œ ©æ›¦¬

 ‰˜¤á¢   ‹âšœŸ¦ª
-----------------
[0m} T Logon message: message list header


RSLOGONL2A {    *     %5d
} T Logon message: message list, global message


RSLOGONL2B {   %02x     %5d
} T Logon message: message list


RSLOGONL3 {[0;1m-----------------

} T Logon message: message list footer


RSLOGOND {[0;1m
!W€¬«æ «¦ ¡œå£œ¤¦ œ ©æ›¦¬ ¬§á¨®œ  ã›. ‡â¢œ«œ ¤˜ «¦ ˜¢¢á¥œ«œ, ã ¤˜ «¦ › ˜š¨á¯œ«œ;
ƒé©«œ [[33mD[37m]elete=› ˜š¨˜­ã, ã [[33mE[37m]dit=˜¢¢˜šã: [Enter=Edit]!) [0m} T Logon message: delete or edit?


RSLOGONDR {[0;1;31m
€¬«ã  œ§ ¢¦šã› ›œ¤ ¬§á¨®œ .
[0;1m} T Logon message: invalid selection


RSLOGONDD {[0;1;32m
‰˜¢éª, «¦ ¡œå£œ¤¦ œ ©æ›¦¬ › œš¨á­.
[0;1m} T Logon message: logon message deleted




RSCLSSTR {[0;1;31m
!JŠ¬§á£˜ , ›œ¤ ­˜å¤œ«˜  ¤˜ ¬§á¨®œ  «¦ ˜¨®œå¦ ©«˜« ©« ¡é¤ š ˜ «˜ classes.
ˆ©àª ¤˜ ›£ ¦¬¨šœå«˜  ˜¬«ã «¤ ©« š£ã, ã ¤˜ £¤ â®œ  ›£ ¦¬¨šŸœå ˜¡æ£˜.!)
[0;1m} T Class statistics: error


RSCLSST1 {[0;1m
ÚÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄ¿
³ Class     ³ •¨ã©«œª ³ Credits ³ Šœ§«á   ³
ÃÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄ´
} T Class statistics: table header


RSCLSST2 {[0;1m³ [32m%-9s[37m ³ [33m%7d[37m ³ [33m%7d[37m ³ [33m%7d[37m ³
} T Class statistics: table line


RSCLSST3 {[0;1mÀÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÙ

(œ£­˜¤å¦¤«˜  £æ¤¦ classes ©«˜ ¦§¦å˜ â®œ  ¡˜«˜¤˜¢àŸœå ®¨æ¤¦ª)
[0;1m
} T Class statistics: table footer




RSMODSTR {[0;1;31m
!JŠ¬§á£˜ , ›œ¤ ­˜å¤œ«˜  ¤˜ ¬§á¨®œ  «¦ ˜¨®œå¦ ©«˜« ©« ¡é¤ š ˜ «˜ classes.
ˆ©àª ¤˜ ›£ ¦¬¨šœå«˜  ˜¬«ã «¤ ©« š£ã, ã ¤˜ £¤ â®œ  ›£ ¦¬¨šŸœå ˜¡æ£˜.!)
[0;1m} T Module statistics: error


RSMODST1 {[0;1m
ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
³ ¤¦£˜ module                               ³ Credits     %% ³ Šœ§«á       %% ³
ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
} T Class statistics: table header


RSMODST2 {[0;1m³ [32m%-43s[37m³ [33m%7d %5.1f[37m ³ [33m%7d %5.1f [37m³
} T Module statistics: table line


RSMODST3 {[0;1mÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
[0;1m
} T Module statistics: table footer



RSSYSTATS {[0;1m

[32m¤¦£˜ ©¬©«ã£˜«¦ª . . . . . . [37m@BBS@
[32m„¡›¦© §¨¦š¨á££˜«¦ª . . . .  [37m@VERSION@
[32m€¨ Ÿ£æª ¡˜¤˜¢ é¤ . . . . . . [37m%d

[32m„®¦¬¤ ›àŸœå ©¬¤¦¢ ¡á  . . .  [37m%7d [32mcredit(s)
[32m€§'˜¬«á, PAID œå¤˜   . . . . [37m%7d [32mcredit(s)
[32m‘¬¤¦¢ ¡æª on-line ®¨æ¤¦ª  .  [37m%7d [32m¢œ§«á
[32m‘¬¤›â©œ ª  . . . . . . . . . [37m%7d

[32mUploads . . . . . . . . . .  [37m%7d [32m˜¨®œå˜   [37m%7d [32mkbytes
[32mDownloads  . . . . . . . . . [37m%7d [32m˜¨®œå˜   [37m%7d [32mkbytes

[32m‹¤ç£˜«˜ ©œ clubs . . . . .  [37m%7d[32m ©¬¤¦¢ ¡á, [37m%7d[32m ¬§á¨®¦¤«˜
[32m‹¤ç£˜«˜ email . . . . . . . [37m%7d[32m ©¬¤¦¢ ¡á, [37m%7d[32m ¬§á¨®¦¤«˜
[32m‹¤ç£˜«˜ net-mail . . . . .  [37m%7d[32m œ¥œ¨®æ£œ¤˜
[32m‹¤ç£˜«˜ net-mail  . . . . . [37m%7d[32m œ ©œ¨®æ£œ¤˜

[0;1m} T System statistics



RSLINST1 {[0;1m
[32m¤¦£˜ £®˜¤ã£˜«¦ª  . . . [37m%s
[32m!W„¡›¦© ¢œ «¦¬¨š ¡¦ç . .  [37m!i%s!)
[32m!0l„§œ¥œ¨š˜©«ãª  . . . . .  [37m%s %s (%s BogoMips)
[32mUptime . . . . . . . . . [37m%02d:%02d:%02d
[32m”æ¨«¦ª ©¬©«ã£˜«¦ª . . .  [37m%s

ÚÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄ¿
³ ‹Œ†‹† ³  Total  ³   Used  ³   Free  ³ Shared  ³ Buffers ³  Cache  ³
ÃÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄ´
³ RAM   ³  [32m%5d  [37m³  [32m%5d  [37m³  [33m%5d  [37m³  [32m%5d  [37m³  [32m%5d  [37m³  [32m%5d  [37m³
³ Swap  ³  [32m%5d  [37m³  [32m%5d  [37m³  [33m%5d  [37mÃÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÙ
ÀÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÙ
[0;1m} T Linux statistics 1


RSLINSTW {[0;1;32;5m[s!J˜¨˜¡˜¢é §œ¨ £â¤œ«œ...!)[0;1m} T Linux statistics, please wait


RSLINST2 {[0;1m[u[K[0;1m
ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
³ ƒå©¡¦ª          ³ Size (K) ³ Used (K) ³ Free (K) ³ Mounted on               ³
ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
} T Linux statistics 2


RSLINST3 {³ %s%-16s[37m³ %s%8d [37m³ %s%8d [37m³ %s%8d [0;1m³ %s%-25s[37m³
} T Linux statistics 3

RSLINST4 {ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
³ ‘ç¤¦¢¦          ³ [32m%8d [37m³ [32m%8d [37m³ [32m%8d [0;1m³                          ³
ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÙ
³ [32mÛÛ  [37m¢˜ ¡˜¢á    [33mÛÛ  [37m‰˜ ¨æª š ˜ ¡˜Ÿá¨ ©£˜    [31mÛÛ  [37m ƒˆ‘‰‘ ‚„‹ˆ‘„ ³
ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
[0;1m} T Linux statistics 4


RSLINST5 {[32m} T Linux statistics 5 (disk free space is ok)

RSLINST6 {[33m} T Linux statistics 6 (disk free space needs attention)

RSLINST7 {[31m} T Linux statistics 7 (disk free space is critical)


RSGENST1 {[0;1;32m
!J€¬«ã  œ¤«¦¢ã §˜¨â®œ  £ ˜ £œšá¢ ©œ ¨á ©«˜« ©« ¡é¤ ©«¦ ®œåà¤
š ˜ › á­¦¨˜ «£ã£˜«˜ «ª ™á©ª. ‡˜ ®¨œ ˜©«œå ¤˜ ¦¨å©œ«œ §¦ ˜ ©«¦ ®œå˜
Ÿâ¢œ«œ ¤˜ ›œå«œ, ¡˜  £œ §¦ ˜ £¦¨­ã.!)

[37m!W„¨é«© 1 ˜§æ 4: ‡â¢œ«œ ¤˜ ›œå«œ ©ç¤¦¢˜ ã £â©¦¬ª æ¨¦¬ª;
ƒé©«œ [[33mT[37m]otal=‘ç¤¦¢¦, [[33mA[37m]verage=‹â©¦ª æ¨¦ª, ã [33mX[37m š ˜ â¥¦›¦:!) [0m} T Generic statistics 1


RSGENST2 {[0;1m
!W„¨é«© 2 ˜§æ 4: ‡â¢œ«œ  ˜¤á¢¬© ¤˜ šå¤œ  §á¤à ©œ!)

  [33mC[37m. ‰˜«˜¤á¢à© Credits
  [33mM[37m. Šœ§«á (Minutes) on-line
  [33mL[37m. €¨ Ÿ£æ ¡¢ã©œà¤ (CaLls)

!Wƒé©«œ «¤ œ§ ¢¦šã ©˜ª ([33mC[37m,[33mM[37m,[33mL[37m, ã [33mX[37m š ˜ «¤ §¨¦š¦ç£œ¤ œ¨é«©:!) [0m} T Generic statistics 2


RSGENST3 {[0;1m
!W„¨é«© 3 ˜§æ 4: ’  œå›¦¬ª ©«˜« ©« ¡ã Ÿâ¢œ«œ;!)

  [33mB[37m. BaudStats . . . . . . . . . ’˜®ç««œª ©ç¤›œ©ª
  [33mC[37m. ClassStats . . . . . . . . ‰¢á©œ ª ®¨©«é¤ (*)
  [33mD[37m. DayStats  . . . . . . . .  †£œ¨ã© ˜ ¡å¤© (*)
  [33mM[37m. ModStats . . .  ‘«˜« ©« ¡âª š ˜ «˜ modules (*)
  [33mT[37m. TTYstats  . . . . . . . . . . . •¨ã© ¡˜¤˜¢ é¤

!W(*) !iƒœ¤ ¬§¦©«¨åœ«˜  ˜¤á¢¬© ˜¨ Ÿ£¦ç ¡¢ã©œà¤ (™¢. §¨¦š¦ç£œ¤ œ¨é«©).!)[B
!0l
!Wƒé©«œ «¤ œ§ ¢¦šã ©˜ª ([33mB[37m,[33mC[37m,[33mD[37m,[33mM[37m,[33mT[37m,
ã [33mX[37m š ˜ «¤ §¨¦š¦ç£œ¤ œ¨é«©:!) [0m} T Generic statistics 3


RSGENSTR {[0;1;31m
!J„®œ«œ «ã©œ  ˜¤á¢¬© ˜¨ Ÿ£¦ç ¡¢ã©œà¤, ¡˜  «¦ œå›¦ª ©«˜« ©« ¡ãª §¦¬ £æ¢ ª › ˜¢â¥˜«œ
›œ¤ «¦ ¬§¦©«¨åœ  ˜¬«æ. ‰˜  ©«¦ ¡á«à ¡á«à, ˜¤ ›œ¤ ©¦¬ ˜¨¡¦ç¤ ¡á§¦¬ 120 › ˜­¦¨œ« ¡á
š¨˜­ã£˜«˜ ¡˜  Ÿâ¢œ ª ¡  á¢¢˜, ¤˜ §˜ª ¤˜ «˜ ­« á¥œ ª £æ¤¦ª ©¦¬. :-) !)
[0;1m} T Generic statistics, impossible combination


RSGENST4 {[0;1m
!W„¨é«© 4 ˜§æ 4: ’  ®¨¦¤ ¡æ §œ¨ ¦¨ ©£æ ¤˜ Ÿâ©¦¬£œ;!)

  [33mD[37m. Day . . . . . . . . . . ‹æ¤¦ ©£œ¨ ¤á ©«˜« ©« ¡á ©«¦ ®œå˜
  [33mM[37m. Month  . . . . . . . . . . ‘«˜« ©« ¡ã ˜¬«¦ç «¦¬ £ã¤˜ £æ¤¦
  [33mY[37m. Year  . . . . . . . . . . ‘«˜« ©« ¡ã ˜¬«¦ç «¦¬ â«¦¬ª £æ¤¦
  [33mE[37m. Ever . .  ‰˜¤â¤˜ª ®¨¦¤ ¡æª §œ¨ ¦¨ ©£æª, ©¬¤¦¢ ¡á ©«¦ ®œå˜

!Wƒé©«œ «¤ œ§ ¢¦šã ©˜ª ([33mD[37m,[33mM[37m,[33mY[37m,[33mE[37m,
ã [33mX[37m š ˜ «¤ §¨¦š¦ç£œ¤ œ¨é«©:!) [0m} T Generic statistics 4




RSTOPSM {[0;1m
[32m¦ ¦ TOP-30 Ÿâ¢œ«œ ¤˜ ›œå«œ;

[33mA[37m  . . . . . . . . . . . . . . . . . €¨ Ÿ£æª ©¬¤›â©œà¤
[33mB[37m . . . . . . . . . . . . . . . . . ˜¢ æ«œ¨˜ accounts
[33mC[37m  . . . . . . . . . . . . . . . . . . €¨ Ÿ£æª credits
[33mD[37m . . . . . . . . . . . . . . . . €¨ Ÿ£æª paid credits
[33mE[37m  . . . . . . . .  €¨ Ÿ£æª credits §¦¬ â®¦¬¤ ¥¦›œ¬«œå
[33mF[37m . . . . . . . . . . . . . . . . . . . •¨æ¤¦ª on-line
[33mG[37m  . . . . . . . . €¨ Ÿ£æª £¤¬£á«à¤ §¦¬ â®¦¬¤ š¨˜­«œå
[33mH[37m . . . . . .   ¡˜¢ç«œ¨¦  uploaders (˜¨ Ÿ£æª ˜¨®œåà¤)
[33mI[37m  . . . . . .    ¡˜¢ç«œ¨¦  uploaders (˜¨ Ÿ£æª bytes)
[33mJ[37m . . .    ¡˜¢ç«œ¨¦ (;) downloaders (˜¨ Ÿ£æª ˜¨®œåà¤)
[33mK[37m  . . . .   ¡˜¢ç«œ¨¦ (;) downloaders (˜¨ Ÿ£æª bytes)
[33mL[37m . . . . . . . .  ’˜ clubs £œ «˜ §œ¨ ©©æ«œ¨˜ £¤ç£˜«˜
[33mM[37m  . . . . . . . . . ’˜ clubs £œ «˜ §œ¨ ©©æ«œ¨˜ ˜¨®œå˜
[33mN[37m . . . . . . . . . . ’˜ clubs £œ «˜ §œ¨ ©©æ«œ¨˜ á¨Ÿ¨˜
[33mO[37m  . ’˜ clubs £œ « ª §œ¨ ©©æ«œ¨œª ˜¤˜š¤é©œ ª £¤¬£á«à¤
[33mP[37m . . . .  ’˜ clubs £œ « ª §œ¨ ©©æ«œ¨œª ¢ã¯œ ª ˜¨®œåà¤
[0;1m} T TOP-Ns, long menu


RSTOPSS {[0;1m
!Wƒé©«œ «¤ œ§ ¢¦šã ©˜ª ([33mA[37m-[33mP[37m, ã [33mX[37m š ˜ â¥¦›¦)!) [0m} T TOP-Ns, short menu

RSTOPSTA {€¨ Ÿ£æª ©¬¤›â©œà¤} T TOP-Ns, chart title 1
RSTOPSTB {˜¢ æ«œ¨˜ accounts} T TOP-Ns, chart title 2
RSTOPSTC {€¨ Ÿ£æª credits} T TOP-Ns, chart title 3
RSTOPSTD {€¨ Ÿ£æª paid credits} T TOP-Ns, chart title 4
RSTOPSTE {€¨ Ÿ£æª credits §¦¬ â®¦¬¤ ¥¦›œ¬«œå} T TOP-Ns, chart title 5
RSTOPSTF {•¨æ¤¦ª on-line} T TOP-Ns, chart title 6
RSTOPSTG {€¨ Ÿ£æª £¤¬£á«à¤ §¦¬ â®¦¬¤ š¨˜­«œå} T TOP-Ns, chart title 7
RSTOPSTH {  ¡˜¢ç«œ¨¦  uploaders (˜¨ Ÿ£æª ˜¨®œåà¤)} T TOP-Ns, chart title 8
RSTOPSTI {  ¡˜¢ç«œ¨¦  uploaders (˜¨ Ÿ£æª bytes)} T TOP-Ns, chart title 9
RSTOPSTJ {  ¡˜¢ç«œ¨¦ (;) downloaders (˜¨ Ÿ£æª ˜¨®œåà¤)} T TOP-Ns, chart title 10
RSTOPSTK {  ¡˜¢ç«œ¨¦ (;) downloaders (˜¨ Ÿ£æª bytes)} T TOP-Ns, chart title 11
RSTOPSTL {’˜ clubs £œ «˜ §œ¨ ©©æ«œ¨˜ £¤ç£˜«˜} T TOP-Ns, chart title 12
RSTOPSTM {’˜ clubs £œ «˜ §œ¨ ©©æ«œ¨˜ ˜¨®œå˜} T TOP-Ns, chart title 13
RSTOPSTN {’˜ clubs £œ «˜ §œ¨ ©©æ«œ¨˜ á¨Ÿ¨˜} T TOP-Ns, chart title 14
RSTOPSTO {’˜ clubs £œ « ª §œ¨ ©©æ«œ¨œª ˜¤˜š¤é©œ ª £¤¬£á«à¤} T TOP-Ns, chart title 15
RSTOPSTP {’˜ clubs £œ « ª §œ¨ ©©æ«œ¨œª ¢ã¯œ ª ˜¨®œåà¤} T TOP-Ns, chart title 16


RSTOPS1 {

[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[0;30;47m ³  %-50s  [1;37m³ [0m
[0;30;47m ³  ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ  [1;37m³ [0m
} T TOP-Ns, top of chart


RSTOPS2 {[0;30;47m ³  %02d. %11s  %-33s  [1;37m³ [0m
} T TOP-Ns, chart entry


RSTOPS3 {[0;30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0;1m

} T TOP-Ns, chart bottom




RSGDET {[0;1;32m
!J† ç§˜¨¥ ˜¬«ãª «ª œ¤«¦¢ãª ˜§¢á ©£˜å¤œ  æ«  â®œ«œ «¤ œ¤«¦¢ã /L
(global detail). ƒé©«œ [33m/L <¯œ¬›é¤¬£¦>[32m ˜§'¦§¦¬›ã§¦«œ £â©˜ ©«¤ ™á©
š ˜ ¤˜ §á¨œ«œ §¢¨¦­¦¨åœª š ˜ «¦ ¯œ¬›é¤¬£¦ ˜¬«æ.!)
[0;1m} T Global Detail:[A information




RSSYSOPWHO {[0;1m
¦ ¦¤ ¡˜¡¦£¦å¨ Ÿ˜ ¡˜«˜¨˜©«œåª £œ ©¬©¦§ ¡á §¨¦¤æ£ ˜, ˜­œ¤« ¡æ; [0m} T Change Sysop Permissions: Whose?


RSSYSOPNSY {[0;1;31m
!J„ ¦®  ¤˜ ¡á¤¦¬£œ ¡˜  ©ç©¦§˜ æ§¦ ¦¤ ¡˜  æ§¦ ¦¤. €¬«á «˜ ¡˜¤¦¤åœ  ¦ £œšá¢¦ª...!)

!J(€¬«ã  œ¤«¦¢ã ›å¤œ  §¨¦¤æ£ ˜ ©œ ¡á§¦ ¦¤, ˜¤ œ¡«œ¢œ©«œå ˜§æ «¦¤ Sysop. €¢¢ éª,
©˜ª ›œå®¤œ  æ«  â®œ«œ §¨¦¤æ£ ˜ ®œ ¨ ©«ã ©¬©«ã£˜«¦ª.!)

[0;1m} T Remote Sysop can't make person a Sysop


RSSYSOPHDR {[0;1m€¢¢˜šã §¨æ©™˜©ª «¦¬ %s... («¦¤ á£¦ ¨¦)

} T Change Sysop Permissions: Menu header


RSSYSOPMNU {[0;1m
!W„§ ¢¦šã š ˜ ˜¢¢˜šã, ON=æ¢˜, OFF=¡˜¤â¤˜, X š ˜ â¥¦›¦, ã ?: !)[0m} T Change Sysop Permissions: Menu prompt


RSSYSOPON {[0;1m
† œ¤«¦¢ã %s §¨¦©«âŸ¡œ ©«¦ ©ç¤¦¢¦.
} T Change Sysop Permissions: Option turned on


RSSYSOPOFF {[0;1m
† œ¤«¦¢ã %s ˜­˜ ¨âŸ¡œ ˜§æ «¦ ©ç¤¦¢¦.
} T Change Sysop Permissions: Option turned off


RSSYSOPSOP {[0;1;31m
!J’  ˜¤˜©­á¢œ œª œå¤˜  ˜¬«âª, ˜­œ¤« ¡æ; „å©˜  ¦ ¡¦¤©¦¢ â¨ª, ¡˜  ¦ ¡¦¤©¦¢ â¨ª
â®œ  §¨æ©™˜© §á¤«˜ ¡˜  §˜¤«¦ç. ƒœ¤ £§¦¨œåª ¤˜ ˜¢¢á¥œ ª «¤ §¨æ©™˜©ã ©¦¬.!)

[0;1m} T Change Sysop Permissions: Can't change Sysop's access


RSSYSOPUPD {[0;1;32m
€¤«œ, á¢¢¦ª â¤˜ª ©«¦ Club «à¤ ‡œé¤...
} T Change Sysop Permissions: User's permissions updated


RSSYSOPDEL {[0;1;31m
!J’¤ §á«©œª á©®£˜, £á©«¦¨á £¦¬... ‰˜Ÿéª â› ¤œª §¨¦¤æ£ ˜ ©«¦ Ÿç£--,
œœœ, œ¤¤¦é ©«¦¤ ®¨ã©«, ¡á§¦ ¦ª «¦¤ â©™©œ. † §¨æ©™˜© §¦¬ «¦¬ â›à©œª ›œ¤
 ©®çœ  §¢œæ¤.!)

!J‘¬£™¦¬¢ã: ¡¦å«˜ ¡˜¢á £ã§àª œå¤˜  ©«¤ ™á© ¦ ˜ššâ¢ª...!)
[0;1m} T Change Sysop Permissions: User has been deleted


RSSYSOPNOT {[0;1;32m
***
!J •œ ¨ ©«ãª ‘¬©«ã£˜«¦ª £æ¢ ª á¢¢˜¥œ « ª œ › ¡âª §¨¦©™á©œ ª ©˜ª.
„¢á«œ ©œ œ§˜­ã £˜å «¦¬ š ˜ ¤˜ £áŸœ«œ §¦ ˜ ˜¡¨ ™éª ã«˜¤  ˜¢¢˜šã.!)	
[0;1m} T Change Sysop Permissions: User notification






CLSLSTHDR {[0;1;32m
“§á¨®¦¤«˜ classes:

!W} T List of classes: Header

CLSLSTTAB {%-20s} T List of classes: Tabulation

CLSLSTEND {!)
[0;1m} T List of classes: Footer


GCHANBCH {[0;1;31m
!W’©¡ «©¡ «©¡... §á¢  §˜å¦¬£œ; ƒœ¤ ¬§á¨®œ  «â«¦ ¦ ¡˜¤á¢ , ®˜¨ «à£â¤œ!!)
[0;1m} T Get channel: bad channel number


GCHANBDV {[0;1;31m
!W„£ ™â™˜ ˜, á¤«œ ¤˜ ›é©œ ª ©à©«á «¦ tty... :-)
ƒœ¤ £§¦¨é ¤˜ ˜¤¦å¥à ˜¬«æ «¦ tty. ‘åš¦¬¨˜ «¦ â›à©œª ©«¤ £¦¨­ã tty*;
’¦ ¦ç¤ ® §¨¦©â®œ  «˜ ¡œ­˜¢˜å˜ ¡˜  «˜ £ ¡¨á š¨á££˜«˜. „©ç;!)
[0;1m} T Get channel: bad device name


GCHANBID {[0;1;31m
!W€«ç®©œª, ¤œ˜¨â ©ç©¦§˜. €¬«æ «¦ á«¦£¦ ›œ¤ œå¤˜  ©¬›œ›œ£â¤¦.
‰  ˜¤ ›œ¤ £œ § ©«œçœ ª, ¡á¤œ â¤˜ /#. :-)!)
[0;1m} T Get channel: bad user ID


GCHANHUH {[0;1;31m
!Wƒœ¤ ¡˜«˜¢˜™˜å¤à «¤ ¢â¥ "%s". €¤ œå¤˜  æ¤¦£˜ ®¨ã©«, ˜¬«æª ¦ ®¨ã©«ª
›œ¤ ¬§á¨®œ  ©«¤ ™á©. €¢¢ éª, ¡á¤˜«œ £á¢¢¦¤ ¡á§¦ ¦ ¢áŸ¦ª.!)
[0;1m} T Get channel: can't figure out what input is


CHNLSTHDR {[0m
ÚÄÄÄÄÂÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
³ [1;33m##[0m ³  [1;33mBAUD[0m  ³ [1;33m•†‘’†‘ (‰€’€‘’€‘† ‚€‹‹†‘)[0m               ³
ÃÄÄÄÄÅÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
} T Channel list: header

CHNLSTTBQ {[0m³ [1;32m%02x[0m ³        ³ [0;37m¨¦©à¨ ¤á ˜¤œ¤œ¨šã š¨˜££ã (LOGOUT)       [0m ³
} T Channel list: line, QUIT state

CHNLSTTBI {[0m³ [1;32m%02x[0m ³        ³ [0;1;33mReset modem ©«¤ ¡˜«á©«˜© %-14s[0m ³
} T Channel list: line, INIT state

CHNLSTTBR {[0m³ [1;32m%02x[0m ³        ³ [0;1;34m„ ©œ¨®æ£œ¤ «¢œ­à¤ ¡ã ¡¢ã© (RING)      [0m ³
} T Channel list: line, RING state

CHNLSTTBA {[0m³ [1;32m%02x[0m ³        ³ [0;1;36m€§˜¤«é ©œ œ ©œ¨®æ£œ¤ ¡¢ã© (ANSWER)     [0m ³
} T Channel list: line, ANSWER state

CHNLSTTBM {[0m³ [1;32m%02x[0m ³ [1;32m%6s[0m ³ [0;1;32mMetaBBS: %-32.32s[0m ³
} T Channel list: line, METABBS state

CHNLSTTBL {[0m³ [1;32m%02x[0m ³ [1;32m%6s[0m ³ [0;1;37m‘ç¤›œ© £œ «¤ ™á© (LOGIN)              [0m ³
} T Channel list: line, LOGIN state

CHNLSTTBG {[0m³ [1;32m%02x[0m ³        ³ [0;1;37m‘ç¤›œ© ¤â¦¬ ®¨ã©« (RELOGON)            [0m ³
} T Channel list: line, RELOG state

CHNLSTTBU {[0m³ [1;32m%02x[0m ³ [1;32m%6s[0m ³ [0;1m%-31.31s%-10s[0m ³
} T Channel list: line, USER state

CHNLSTPGS {[32;5m(/p sysop)} T Channel list: list, USER state, used has paged the Sysop

CHNLSTTBU2 {[0m³ [1;32m%02x[0m ³ [1;32m%6s[0m ³ [0;1m† š¨˜££ã œå¤˜  ¡˜«œ ¢££â¤.             [0m ³
} T Channel list: line, USER state (unnamed)

CHNLSTTBO {[0m³ [1;32m%02x[0m ³        ³ [0;1;32m‰˜«á©«˜© š¨˜££ãª: %-22s[0m ³
} T Channel list: line, OK state

CHNLSTTBF {[0m³ [1;32m%02x[0m ³        ³ [0;1;31;5m€§¦«¬®å˜ «¦¬ reset! ‰˜«á©«˜©: %-10s[0m ³
} T Channel list: line, FAIL state

CHNLSTTBE {[0m³ [1;32m%02x[0m ³        ³ ¨¦©à¨ ¤á áš¤à©« ¡˜«á©«˜©               ³
} T Channel list: line, error reading line state

CHNLSTFTR {[0mÀÄÄÄÄÁÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
[0;1m} T Channel list: footer







RSAPGVT {[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [34m”å¢«¨¦ ¡˜«˜®à¨ã©œà¤ Audit Trail[0;30;47m ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  „›é £§¦¨œå«œ  ¤˜ œ¢âš¥œ«œ §¦ ˜  œå› ¡˜«˜®à¨ã©œà¤  «¦¬ audit  trail Ÿ˜  [0;1;47;37m³ [0m
[30;47m ³  ©˜ª  ›œå®¤œ  «¦ ©ç©«£˜.  † ©¦™˜¨æ««˜  ¡˜«˜®à¨ã©œà¤ £§¦¨œå ¤˜ ˜¢¢á¥œ   [0;1;47;37m³ [0m
[30;47m ³  ¡˜  £œ «¤ œ¤«¦¢ã /audit. ƒé©«œ Ctrl-O ©œ ¡á§¦ ¦ §œ›å¦ š ˜ ™¦ãŸœ ˜.     [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  „£­á¤ © . . . . . . . . [0;30;46m @23;"‰˜££å˜ ¡˜«˜®é¨©|„§œåš¦¬©œª ¡˜«˜®à¨ã©œ ª|„§œåš¦¬©œª & ‘£˜¤« ¡âª|¢œª ¦  ¡˜«˜®à¨ã©œ ª"l [0;30;47m  (space š ˜ ˜¢¢˜šã)  [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  „å› ¡˜«˜®à¨ã©œà¤ §¦¬ Ÿâ¢œ«œ ¤˜ ™¢â§œ«œ:            (space š ˜ ˜¢¢˜šã)  [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  •¨œé©œ ª/‘«˜« ©« ¡á/Š¦š ©« ¡âª ¡˜«˜®à¨ã©œ ª . . . . . . . . . .  [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³  „ › ¡âª «˜¡« ¡âª › œ¨š˜©åœª (cleanup, events)  . . . . . . . . . [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³  ‰˜«˜®à¨ã©œ ª ®œ ¨ ©£¦ç ©¬©«ã£˜«¦ª . . . . . . . . . . . . . . .  [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³  €©­á¢œ ˜ ©¬©«ã£˜«¦ª, ®¨©«é¤ ¡˜  ˜¨®œåà¤ . . . . . . . . . . . . [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³  ‹œ«˜­¦¨âª/˜¤˜š¤é©œ ª ˜¨®œåà¤  . . . . . . . . . . . . . . . . .  [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³  ‰å¤© ®¨©«é¤ (©¬¤›â©œ ª, ˜§¦©¬¤›â©œ ª, ¡¢§)  . . . . . . . . . [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³  €¢¢œª ¡˜«˜®à¨ã©œ ª  . . . . . . . . . . . . . . . . . . . . . .  [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  ¨¦©¦®ã: ¦  ˜¢¢˜šâª  ©®ç¦¬¤ š ˜ Š„‘ « ª £œ«â§œ «˜ ©¬¤›â©œ ª ©˜ª.       [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³                                  [0;1;42;33m@14;"OK"b[0;47;30mÜ    [0;1;41;33m@14;"Cancel"b[0;47;30mÜ  [0;1;47;37m³ [0m
[30;47m ³  Ctrl-R: ¦ãŸœ ˜                  ßßßßßßßßßßßßßßßß     ßßßßßßßßßßßßßßßß  [0;1;47;37m³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m} T Audit paging: visual template


SEVO {‰˜££å˜ ¡˜«˜®é¨©} T Filtering: show nothing (off)
SEVE {„§œåš¦¬©œª ¡˜«˜®à¨ã©œ ª} T Filtering: show emergency entries only
SEVC {„§œåš¦¬©œª & ‘£˜¤« ¡âª} T Filtering: show emergency and cautionary
SEVI {¢œª ¦  ¡˜«˜®à¨ã©œ ª} T Filtering: show everything



RSAPGLT {[2J[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³ ”å¢«¨¦ ¡˜«˜®à¨ã©œà¤ Audit Trail                                          [0;1;47;37m³ [0m
[30;47m ³ ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [0;1;47;37m³ [0m
[30;47m ³ „›é £§¦¨œå«œ ¤˜  œ¢âš¥œ«œ §¦ ˜ œå› ¡˜«˜®à¨ã©œà¤ «¦¬  audit trail Ÿ˜ ©˜ª [0;1;47;37m³ [0m
[30;47m ³ ›œå®¤œ  «¦ ©ç©«£˜.  † ©¦™˜¨æ««˜  ¡˜«˜®à¨ã©œà¤ £§¦¨œå ¤˜ ˜¢¢á¥œ  ¡˜  £œ [0;1;47;37m³ [0m
[30;47m ³ «¤ œ¤«¦¢ã /audit.                                                       [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³ [31m1[30m. „£­á¤ © . . . . . . . . . . . . . . . . . .  [34m@23;"‰˜££å˜ ¡˜«˜®é¨©|„§œåš¦¬©œª ¡˜«˜®à¨ã©œ ª|„§œåš¦¬©œª & ‘£˜¤« ¡âª|¢œª ¦  ¡˜«˜®à¨ã©œ ª"l [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³ [31m2[30m. •¨œé©œ ª/‘«˜« ©« ¡á/Š¦š ©« ¡âª ¡˜«˜®à¨ã©œ ª . . . . . . . . . . . [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³ [31m3[30m. „ › ¡âª «˜¡« ¡âª › œ¨š˜©åœª (cleanup, events)  . . . . . . . . .  [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³ [31m4[30m. ‰˜«˜®à¨ã©œ ª ®œ ¨ ©£¦ç ©¬©«ã£˜«¦ª . . . . . . . . . . . . . . . . [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³ [31m5[30m. €©­á¢œ ˜ ©¬©«ã£˜«¦ª, ®¨©«é¤ ¡˜  ˜¨®œåà¤ . . . . . . . . . . . .  [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³ [31m6[30m. ‹œ«˜­¦¨âª/˜¤˜š¤é©œ ª ˜¨®œåà¤  . . . . . . . . . . . . . . . . . . [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³ [31m7[30m. ‰å¤© ®¨©«é¤ (©¬¤›â©œ ª, ˜§¦©¬¤›â©œ ª, ¡¢§)  . . . . . . . . .  [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³ [31m8[30m. €¢¢œª ¡˜«˜®à¨ã©œ ª  . . . . . . . . . . . . . . . . . . . . . . . [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  ¨¦©¦®ã: ¦  ˜¢¢˜šâª  ©®ç¦¬¤ š ˜ Š„‘ « ª £œ«â§œ «˜ ©¬¤›â©œ ª ©˜ª.       [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m
} T Audit paging: Linear template


RSAPGH0 {[0;1m
!J  ¡˜«˜®à¨ã©œ ª «¦¬ Audit Trail ®à¨å¦¤«˜  ©œ «¨œ ª £œšá¢œª ¡˜«š¦¨åœª
©¦™˜¨æ««˜ª.   §¢¨¦­¦¨ ˜¡âª ¡˜«˜®à¨ã©œ ª œå¤˜  ¦  § ¦ ¡¦ ¤âª. ‰˜«˜®à¨¦ç¤
­¬© ¦¢¦š ¡âª › œ¨š˜©åœª.   ©£˜¤« ¡âª ¡˜«˜®à¨ã©œ ª œ£­˜¤å¦¤«˜  ©œ ¡æ¡¡ ¤¦
®¨é£˜. ¤¦£á¦¤«˜  ©£˜¤« ¡âª š ˜«å £§¦¨œå ¤˜ ›¢é¤¦¬¤ ¡˜«˜©«á©œ ª §¦¬
˜§˜ «¦ç¤ «¤ §¨¦©¦®ã ©˜ª (æ§àª œšš¨˜­âª ¤âà¤ ®¨©«é¤, hack tries ¡¢§). ’â¢¦ª,
¦  œ§œåš¦¬©œª ¡˜«˜®à¨ã©œ ª œå¤˜  ¦  § ¦ ©§á¤ œª ¡˜  ›¢é¤¦¬¤ ©¦™˜¨á §¨¦™¢ã£˜«˜
©« ™á©. á¤«¦«œ §¨â§œ  ¤˜ «¦¬ª ›å¤œ«˜   ˜§˜¨˜å«« §¨¦©¦®ã. „›é £§¦¨œå«œ ¤˜
¦¨å©œ«œ «¦ ¡˜«é­¢  ©¦™˜¨æ««˜ª «à¤ ¡˜«˜®à¨ã©œà¤ §¦¬ Ÿ˜ ™¢â§œ«œ ˜¤á §á©˜
©« š£ã.!)
} T Audit paging: field help 0

RSAPGH1 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«æ «¦ œå›¦ª ¡˜«˜®é¨©ª, «¦ ©ç©«£˜ Ÿ˜ ©˜ª œ ›¦§¦ œå ¡áŸœ
­¦¨á §¦¬ Ÿ˜ ¡˜«˜š¨á­œ«˜  ¡á«  §¦¬ â®œ  ¤˜ ¡á¤œ  £œ ®¨œé©œ ª credits,
©«˜« ©« ¡âª ¡˜«˜®à¨ã©œ ª ¡˜  šœ¤ ¡éª ¢¦š ©« ¡âª ¡˜«˜®à¨ã©œ ª.!)
[0;1m} T Audit paging: field help 1


RSAPGH2 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«æ «¦ œå›¦ª ¡˜«˜®é¨©ª, «¦ ©ç©«£˜ Ÿ˜ ©˜ª œ ›¦§¦ œå ¡áŸœ
­¦¨á §¦¬ Ÿ˜ ¡˜«˜š¨á­œ«˜  ¡á«  §¦¬ â®œ  ¤˜ ¡á¤œ  £œ « ª «˜¡« ¡âª › œ¨š˜©åœª
«ª ™á©ª (§® cleanup).!)
[0;1m} T Audit paging: field help 2


RSAPGH3 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«æ «¦ œå›¦ª ¡˜«˜®é¨©ª, «¦ ©ç©«£˜ Ÿ˜ ©˜ª œ ›¦§¦ œå ¡áŸœ
­¦¨á §¦¬ Ÿ˜ ¡˜«˜š¨á­œ«˜   œ¡«â¢œ© ¡á§¦ ˜ª œ¤«¦¢ãª ®œ ¨ ©«ã ©¬©«ã£˜«¦ª ã
§˜¨æ£¦ ˜ œ¤â¨šœ ˜.!)
[0;1m} T Audit paging: field help 3


RSAPGH4 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«æ «¦ œå›¦ª ¡˜«˜®é¨©ª, «¦ ©ç©«£˜ Ÿ˜ ©˜ª œ ›¦§¦ œå ¡áŸœ
­¦¨á §¦¬ Ÿ˜ ¡˜«˜š¨á­œ«˜  ¡á«  §¦¬ â®œ  ¤˜ ¡á¤œ  £œ «¤ ˜©­á¢œ ˜ «¦¬
©¬©«ã£˜«¦ª: §¨¦©§áŸœ œª ©§˜©å£˜«¦ª ¢¦š˜¨ ˜©£é¤ ¡¢§.!)
[0;1m} T Audit paging: field help 4


RSAPGH5 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«æ «¦ œå›¦ª ¡˜«˜®é¨©ª, «¦ ©ç©«£˜ Ÿ˜ ©˜ª œ ›¦§¦ œå ¡áŸœ
­¦¨á §¦¬ Ÿ˜ ¡˜«˜š¨á­¦¤«˜  £œ«˜­¦¨âª ˜¨®œåà¤, ˜¤˜š¤é©œ ª ˜¨®œåà¤ ã §˜¨æ£¦ œª
œ¤â¨šœ œª.!)
[0;1m} T Audit paging: field help 5


RSAPGH6 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«æ «¦ œå›¦ª ¡˜«˜®é¨©ª, «¦ ©ç©«£˜ Ÿ˜ ©˜ª œ ›¦§¦ œå ¡áŸœ
­¦¨á §¦¬ Ÿ˜ ¡˜«˜š¨á­¦¤«˜  ©¬¤›â©œ ª ¡˜  ˜§¦©¬¤›â©œ ª ®¨©«é¤ (¡˜  ©®œ« ¡âª
¡˜«˜®à¨ã©œ ª).!)
[0;1m} T Audit paging: field help 6


RSAPGH7 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«æ «¦ œå›¦ª ¡˜«˜®é¨©ª, «¦ ©ç©«£˜ Ÿ˜ ©˜ª œ ›¦§¦ œå ¡áŸœ
­¦¨á §¦¬ Ÿ˜ ¡˜«˜š¨á­œ«˜  ¡á§¦ ˜ œ¤â¨šœ ˜ §¦¬ ›œ¤ ˜¤ã¡œ  ©« ª á¢¢œª
¡˜«š¦¨åœª ¡˜«˜®à¨ã©œà¤.!)
[0;1m} T Audit paging: field help 7


RSAPGCAN {[0;1;31m
  ˜¢¢˜šâª ©˜ª £˜«˜ éŸ¡˜¤.
[0;1m} T Audit paging: filtering changes aborted


RSAPGOK {[0;1;32m
„¤«á¥œ , «¦ ­å¢«¨¦ «à¤ ¡˜«˜®à¨ã©œà¤ ¨¬Ÿ£å©«¡œ.
[0;1m} T Audit paging: filtering changes set



RSFLTVT {[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [34m„¨œ¬¤˜ «¦¬ Audit Trail[0;30;47m ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  „¨œ¬¤˜ š ˜ . . . [1;44;37m@80;51;0s[0;1;47;37m  [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  „¨œ¬¤˜ §¢¨¦­¦¨ ˜¡é¤ ¡˜«˜®à¨ã©œà¤ . . . . . . . . . . . . . . .  [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³  „¨œ¬¤˜ ©£˜¤« ¡é¤ ¡˜«˜®à¨ã©œà¤ . . . . . . . . . . . . . . . . . [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³  „¨œ¬¤˜ œ§œåš¦¬©à¤ ¡˜«˜®à¨ã©œà¤  . . . . . . . . . . . . . . . .  [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  „¨œ¬¤˜ ®¨œé©œà¤/©«˜« ©« ¡é¤/¢¦š ©« ¡é¤ ¡˜«˜®à¨ã©œà¤  . . . . . . [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³  „¨œ¬¤˜ œ › ¡é¤ «˜¡« ¡é¤ › œ¨š˜© é¤ (cleanup, events)  . . . . .  [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³  „¨œ¬¤˜ ‰˜«˜®à¨ã©œà¤ ®œ ¨ ©£¦ç ©¬©«ã£˜«¦ª . . . . . . . . . . . . [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³  „¨œ¬¤˜ €©­á¢œ ˜ª ©¬©«ã£˜«¦ª, ®¨©«é¤ ¡˜  ˜¨®œåà¤  . . . . . . .  [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³  „¨œ¬¤˜ ‹œ«˜­¦¨é¤/˜¤˜š¤é©œà¤ ˜¨®œåà¤  . . . . . . . . . . . . . . [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³  „¨œ¬¤˜ ‰ ¤ã©œà¤ ®¨©«é¤ (©¬¤›â©œà¤, ˜§¦©¬¤›â©œà¤, ¡¢§)  . . . .  [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³  „¨œ¬¤˜ €¢¢à¤ ¡˜«˜®à¨ã©œà¤  . . . . . . . . . . . . . . . . . . . [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  „£­á¤ © ˜§æ «¦ «â¢¦ª (¤âœª ¡˜«˜®à¨ã©œ ª) §¨¦ª «¤ ˜¨®ã . . . .  [0;30;46m [@"X "t] [0;1;47;37m  ³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³                                  [0;1;42;33m@14;"OK"b[0;47;30mÜ    [0;1;41;33m@14;"Cancel"b[0;47;30mÜ  [0;1;47;37m³ [0m
[30;47m ³  Ctrl-R: ¦ãŸœ ˜                  ßßßßßßßßßßßßßßßß     ßßßßßßßßßßßßßßßß  [0;1;47;37m³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m} T Audit search: visual template



RSFLTLT {[2J[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³ „¨œ¬¤˜ «¦¬ Audit Trail                                                   [0;1;47;37m³ [0m
[30;47m ³ ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³ [31m1[30m.  „¨œ¬¤˜ š ˜ . . . [34m@80;51;0s [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³ [31m2[30m.  „¨œ¬¤˜ §¢¨¦­¦¨ ˜¡é¤ ¡˜«˜®à¨ã©œà¤ . . . . . . . . . . . . . . .  [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³ [31m3[30m.  „¨œ¬¤˜ ©£˜¤« ¡é¤ ¡˜«˜®à¨ã©œà¤ . . . . . . . . . . . . . . . . . [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³ [31m4[30m.  „¨œ¬¤˜ œ§œåš¦¬©à¤ ¡˜«˜®à¨ã©œà¤  . . . . . . . . . . . . . . . .  [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³ [31m5[30m.  „¨œ¬¤˜ •¨œé©œà¤/‘«˜« ©« ¡é¤/Š¦š ©« ¡é¤ ¡˜«˜®à¨ã©œà¤ . . . . . .  [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³ [31m6[30m.  „¨œ¬¤˜ „ › ¡é¤ «˜¡« ¡é¤ › œ¨š˜© é¤ (cleanup, events) . . . . . . [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³ [31m7[30m.  „¨œ¬¤˜ ‰˜«˜®à¨ã©œà¤ ®œ ¨ ©£¦ç ©¬©«ã£˜«¦ª  . . . . . . . . . . .  [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³ [31m8[30m.  „¨œ¬¤˜ €©­á¢œ ˜ª ©¬©«ã£˜«¦ª, ®¨©«é¤ ¡˜  ˜¨®œåà¤ . . . . . . . . [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³ [31m9[30m.  „¨œ¬¤˜ ‹œ«˜­¦¨é¤/˜¤˜š¤é©œà¤ ˜¨®œåà¤ . . . . . . . . . . . . . .  [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³ [31m10[30m. „¨œ¬¤˜ ‰å¤©ª ®¨©«é¤ (©¬¤›â©œ ª, ˜§¦©¬¤›â©œ ª, ¡¢§)  . . . . . [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³ [31m11[30m. „¨œ¬¤˜ €¢¢à¤ ¡˜«˜®à¨ã©œà¤ . . . . . . . . . . . . . . . . . . .  [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³ [31m12[30m. „£­á¤ © ˜§æ «¦ «â¢¦ª (¤âœª ¡˜«˜®à¨ã©œ ª) §¨¦ª «¤ ˜¨®ã . . . .  [34m@"X "t [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m
} T Audit search: linear template


RSFLT1 {[0;1m
!J„›é £§¦¨œå«œ ¤˜ ›é©œ«œ £å˜ ¢â¥ ã ­¨á© ¡¢œ ›å «¤ ¦§¦å˜ Ÿ˜ ¯á¥¦¬£œ ©«¦ 
Audit Trail. €¤ ˜­ã©œ«œ ˜¬«æ «¦ §œ›å¦ ¡œ¤æ, æ¢œª ¦  ¡˜«˜®à¨ã©œ ª «¦¬ Audit
Trail Ÿ˜ œ£­˜¤ ©«¦ç¤ (˜­¦ç ­ ¢«¨˜¨ ©«¦ç¤ ¡˜  ˜§æ « ª ¨¬Ÿ£å©œ ª «à¤ ¬§æ¢¦ §à¤
§œ›åà¤!).
[0;1m} T Audit search: field help 1


RSFLT2 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«ã «¤ œ§ ¢¦šã, «¦ ©ç©«£˜ Ÿ˜ ¯á¥œ  š ˜ §¢¨¦­¦¨ ˜¡âª ¡˜«˜®à¨ã©œ ª.
‹§¦¨œå«œ ¤˜ œ£­˜¤å©œ«œ ¡  á¢¢œª ¡˜«˜®à¨ã©œ ª œ¤œ¨š¦§¦ é¤«˜ª «˜ ˜¤«å©«¦ ®˜ §œ›å˜.!)
[0;1m} T Audit search: field help 2


RSFLT3 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«ã «¤ œ§ ¢¦šã, «¦ ©ç©«£˜ Ÿ˜ ¯á¥œ  š ˜ ©£˜¤« ¡âª ¡˜«˜®à¨ã©œ ª.
‹§¦¨œå«œ ¤˜ œ£­˜¤å©œ«œ ¡  á¢¢œª ¡˜«˜®à¨ã©œ ª œ¤œ¨š¦§¦ é¤«˜ª «˜ ˜¤«å©«¦ ®˜ §œ›å˜.!)
[0;1m} T Audit search: field help 3


RSFLT4 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«ã «¤ œ§ ¢¦šã, «¦ ©ç©«£˜ Ÿœ ¯á¥œ  š ˜ œ§œåš¦¬©œª ¡˜«˜®à¨ã©œ ª.
‹§¦¨œå«œ ¤˜ œ£­˜¤å©œ«œ ¡  á¢¢œª ¡˜«˜®à¨ã©œ ª œ¤œ¨š¦§¦ é¤«˜ª «˜ ˜¤«å©«¦ ®˜ §œ›å˜.!)
[0;1m} T Audit search: field help 4

RSFLTH5 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«æ «¦ œå›¦ª ¡˜«˜®é¨©ª, «¦ ©ç©«£˜ Ÿ˜ ¯á¥œ  š ˜
¡˜«˜®à¨ã©œ ª §¦¬ â®¦¬¤ ¤˜ ¡á¤¦¬¤ £œ ®¨œé©œ ª credits,
©«˜« ©« ¡âª ¡˜«˜®à¨ã©œ ª ¡˜  šœ¤ ¡éª ¢¦š ©« ¡âª ¡˜«˜®à¨ã©œ ª.!)
[0;1m} T Audit paging: field help 5


RSFLTH6 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«æ «¦ œå›¦ª ¡˜«˜®é¨©ª, «¦ ©ç©«£˜ Ÿ˜ ¯á¥œ  š ˜
¡˜«˜®à¨ã©œ ª §¦¬ â®¦¬¤ ¤˜ ¡á¤¦¬¤ £œ « ª «˜¡« ¡âª › œ¨š˜©åœª
«ª ™á©ª (§® cleanup).!)
[0;1m} T Audit paging: field help 6


RSFLTH7 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«æ «¦ œå›¦ª ¡˜«˜®é¨©ª, «¦ ©ç©«£˜ Ÿ˜ ¯á¥œ  š ˜
¡˜«˜®à¨ã©œ ª §¦¬ â®¦¬¤ ¤˜ ¡á¤¦¬¤ £œ «¤ œ¡«â¢œ© œ¤«¦¢é¤ ®œ ¨ ©«ã ©¬©«ã£˜«¦ª ã
§˜¨æ£¦ œª œ¤â¨šœ œª.!)
[0;1m} T Audit paging: field help 7


RSFLTH8 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«æ «¦ œå›¦ª ¡˜«˜®é¨©ª, «¦ ©ç©«£˜ Ÿ˜ ¯á¥œ  š ˜
¡˜«˜®à¨ã©œ ª §¦¬ â®¦¬¤ ¤˜ ¡á¤¦¬¤ £œ «¤ ˜©­á¢œ ˜ «¦¬
©¬©«ã£˜«¦ª: §¨¦©§áŸœ œª ©§˜©å£˜«¦ª ¢¦š˜¨ ˜©£é¤ ¡¢§.!)
[0;1m} T Audit paging: field help 8


RSFLTH9 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«æ «¦ œå›¦ª ¡˜«˜®é¨©ª, «¦ ©ç©«£˜ Ÿ˜ ¯á¥œ  š ˜ 
¡˜«˜®à¨ã©œ ª §¦¬ â®¦¬¤ ¤˜ ¡á¤¦¬¤ £œ £œ«˜­¦¨âª ˜¨®œåà¤, ˜¤˜š¤é©œ ª ˜¨®œåà¤ ã §˜¨æ£¦ œª
œ¤â¨šœ œª.!)
[0;1m} T Audit paging: field help 9


RSFLTH10 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«æ «¦ œå›¦ª ¡˜«˜®é¨©ª, «¦ ©ç©«£˜ Ÿ˜ ¯á¥œ  š ˜
¡˜«˜®à¨ã©œ ª §¦¬ â®¦¬¤ ¤˜ ¡á¤¦¬¤ £œ ©¬¤›â©œ ª ¡˜  ˜§¦©¬¤›â©œ ª ®¨©«é¤.!)
[0;1m} T Audit paging: field help 10


RSFLTH11 {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«æ «¦ œå›¦ª ¡˜«˜®é¨©ª, «¦ ©ç©«£˜ Ÿ˜ ¯á¥œ 
š ˜ ¡˜«˜®à¨ã©œ ª §¦¬ ›œ¤ ˜¤ã¡¦¬¤ ©« ª ¬§æ¢¦ §œª ¡˜«š¦¨åœª.!)
[0;1m} T Audit paging: field help 11



RSFLTH12 {[0;1m
!J‹œ ˜¬«ã «¤ œ§ ¢¦šã œ¤œ¨šã, ¦  ¡˜«˜®à¨ã©œ ª ©˜ª §˜¨¦¬© á¦¤«˜  £œ ˜¤«å©«¨¦­ ®¨¦¤ ¡ã ©œ ¨á: ¦  § ¦ §¨æ©­˜«œª
œ£­˜¤å¦¤«˜  §¨é«œª. €¬«ã œå¤˜  ¡˜   § ¦ §¨˜¡« ¡ã ¢œ «¦¬¨šå˜ ¡˜«á ¡˜¤æ¤˜.!)
[0;1m} T Audit paging: field help 12











AUDSRCH {[0;1;32m
„¨œ¬¤˜ «¦¬ Audit Trail...
!FÄ
[0;1m} T Searching Audit Trail


AUDSEND {!0l[0;1;32m!FÄ

’â¢¦ª â¨œ¬¤˜ª.
[0;1m} T Searching Audit Trail, end of search


AUDNF {[0;1;31m
!J‘¬šš¤é£, ›œ¤ ™¨âŸ¡œ «å§¦«˜ ©®œ« ¡æ.!)
[0;1m} T Searching Audit Trail, nothing found


AUDSCAN {[0;1;31m!0l
† â¨œ¬¤˜ «œ¨£˜«å©«¡œ.
[0;1m} T Audit Trail search terminated.




LANGND {}
