#!/bin/bash
#
# DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER
# DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER
# DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER
#
# THIS FILE  R E M O V E S  (DELETES) ALL FILES PASSED AS ARGUMENTS
# B E W A R E ! ! !   N O   W A R N I N G S   G I V E N ! ! !
#
# $Id: cat-and-remove,v 2.0 2004/09/13 19:44:54 alexios Exp $
#
# $Log: cat-and-remove,v $
# Revision 2.0  2004/09/13 19:44:54  alexios
# Stepped version to recover CVS repository after near-catastrophic disk
# crash.
#
#


# Security measure: This script will only run for BBS users. Please
# do not remove this constraint. You won't like it, I promise.

if [ -e ${PREFIX}/etc/online/$USERID ]; then
    \cat $*
    \rm -f $*
else
    echo This protocol will only run for BBS users.
fi

# End of file.
