/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "test.h"

bool_t
xdr_foo_res (XDR *xdrs, foo_res *objp)
{
	 register long *buf;

	 if (!xdr_int (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_string (xdrs, &objp->foo_res_u.ret_string, ~0))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
