/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST_H_RPCGEN
#define _TEST_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct foo_res {
	int errno;
	union {
		char *ret_string;
	} foo_res_u;
};
typedef struct foo_res foo_res;

#define TESTPROG 0x204d4447
#define TESTVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define foo 1
extern  foo_res * foo_1(void *, CLIENT *);
extern  foo_res * foo_1_svc(void *, struct svc_req *);
extern int testprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define foo 1
extern  foo_res * foo_1();
extern  foo_res * foo_1_svc();
extern int testprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_foo_res (XDR *, foo_res*);

#else /* K&R C */
extern bool_t xdr_foo_res ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEST_H_RPCGEN */
