LEVEL2 {}

DEFWALL {Download the graffiti wall by default? YES} B

DEFANSI {Enable ANSI directives by default? YES} B

DEFLINS {How many lines to include by default? (0=all) 0} N 0 10000

WALLFIL {blt-wall} S 12 Filename of graffiti file


LEVEL3 {}

OGVT {[0m[30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [34m¬Ÿ£å©œ ª «¦¬ ’¦å®¦¬ š ˜ ‚¨á¯ £¦[0;30;47m ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³   «¦å®¦ª š ˜ š¨á¯ £¦ ©«˜ §˜¡â«˜:        [0;30;46m [@"X "t] [0;47;30m       (Space š ˜ ˜¢¢˜šã)  [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  ANSI ®¨é£˜«˜ ©«¦¤ «¦å®¦:                [0;30;46m [@"X "t] [0;47;30m       (Space š ˜ ˜¢¢˜šã)  [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  ‹âš ©«¦ª ˜¨ Ÿ£æª š¨˜££é¤:               [1;37;44m@5;0;10000;0n[0;47;30m     (0..10000, 0=æ¢œª)  [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  Ctrl-R: ¦ãŸœ ˜                 [0;1;42;33m@14;"OK"b[0;47;30mÜ    [0;1;41;33m@14;"€¡¬¨¦"b[0;47;30mÜ  [0;1;47;37m³ [0m
[30;47m ³                                   ßßßßßßßßßßßßßßßß     ßßßßßßßßßßßßßßßß  [0;1;47;37m³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m} T Setup, Visual template


OGLT {[2J[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [34m¬Ÿ£å©œ ª «¦¬ ’¦å®¦¬ š ˜ ‚¨á¯ £¦[0;30;47m ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³                                                                          [1;37m³ [0m
[30;47m ³ [31m1[30m.  «¦å®¦ª š ˜ š¨á¯ £¦ ©«˜ §˜¡â«˜ . . . . . . . . . . . . . . . . [34m@"X "t[0;1;47;37m   ³ [0m
[30;47m ³                                                                          [1;37m³ [0m
[30;47m ³ [31m2[30m. ANSI ®¨é£˜«˜ ©«¦¤ «¦å®¦  . . . . . . . . . . . . . . . . . . .  [34m@"X "t[0;1;47;37m   ³ [0m
[30;47m ³                                                                          [1;37m³ [0m
[30;47m ³ [31m3[30m. ‹âš ©«¦ª ˜¨ Ÿ£æª š¨˜££é¤  . . . . . . . . . . . . . . . . . . . [34m@5;0;10000;0n[0;1;47;37m ³ [0m
[30;47m ³                                                                          [1;37m³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0;1m
} T Setup QWK, Linear template


OGWALL {[0;1m
!J„¤œ¨š¦§¦ é¤«˜ª ˜¬«ã «¤ œ§ ¢¦šã, «á«œ «¤ œ ©˜šàšã «¦¬ ’¦å®¦¬ š ˜
‚¨á¯ £¦ ©«˜ §˜¡â«˜ ©˜ª.!)
[0;1m} T Setup QWK, Linear template, enable/disable wall


OGANSI {[0;1m
!J€¬«ã  œ§ ¢¦šã œ¢âš®œ  ˜¤ Ÿ˜ ¢˜£™˜¤œ«œ «¦¤ «¦å®¦ š ˜ š¨á¯ £¦ £œ ã ®à¨åª
ANSI ®¨é£˜. €¤ ¦ Off-line Reader ©˜ª £§¦¨œå ¤˜ ›œå¥œ  "bulletins" £œ ®¨é£˜,
«æ«œ œ¤œ¨š¦§¦ ã©«œ «¤ œ§ ¢¦šã ANSI.!)
[0;1m} T Setup QWK, Linear template, enable/disable ANSI colour


OGLINES {[0;1m
!J„›é ¨¬Ÿ£åœ«œ §æ©œª š¨˜££âª «¦¬ ’¦å®¦¬ Ÿ˜ ˜¤« š¨á­¦¤«˜  ©«¦ §˜¡â«¦ ©˜ª.
‹§¦¨œå«œ ¤˜ ›é©œ«œ â¤˜¤ ˜¨ Ÿ£æ ¦§æ 0 £â®¨  10.000 (©¬¤ãŸàª ¦ ’¦å®¦ª â®œ 
§¦¢ç ¢ šæ«œ¨œª š¨˜££âª). €¤ ›é©œ«œ 0, æ¢œª ¦  š¨˜££âª Ÿ˜ £œ«˜­â¨¦¤«˜ 
©«¦ §˜¡â«¦ ©˜ª.!)
[0;1m} T Setup QWK, Linear template, number of lines


DLHDR {[0;1m
[0;1;35m’[36m¦[33må[32m®[31m¦[34mª[37m š ˜ š¨á¯ £¦: } T Graffiti Wall Download: header


DLDMT {[0;1;33m «¦å®¦ª œå¤˜  ­¨œ©¡¦™˜££â¤¦ª ¡˜  á›œ ¦ª.
[0;1m} T Graffiti Wall Download: Empty wall


DLNAX {[0;1;31mƒœ¤ â®œ«œ §¨æ©™˜© ©«¦¤ «¦å®¦.
[0;1m} T Graffiti Wall Download: no access


DLOK {[0;1;32m„¤«á¥œ .
[0;1m} T Graffiti Wall Download: ok


ULWRH {[0;1m
[0;1;35m’[36m¦[33må[32m®[31m¦[34mª[37m š ˜ š¨á¯ £¦: } T Graffiti Wall Upload: Command header


ULWMT {[1;31mƒœ¤ ™¨âŸ¡˜¤ š¨˜££âª š ˜ š¨á¯ £¦.
[0;1m} T Graffiti Wall Upload: No lines found


ULWRT {[1;32m%s œ§ «¬®éª ¡˜  ¦  %d š¨˜££%s.
[0;1m} T Graffiti Wall Upload: Written all lines


ULNWR {[1;33m%s %d ˜§æ %d š¨˜££%s.
[0;1m} T Reply table: Written some lines


WRTSNG {‚¨á­«¡œ} T 'Written', singular form
WRTPLR {‚¨á­«¡˜¤} T 'Written', plural form

LINSNG {ã} T 'Lines', singular form
LINPLR {âª} T 'Lines', plural form



LANG {}


OGVT {[0m[30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [34mOff-line Graffiti Wall Settings[0;30;47m ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  Include graffiti wall in packages:      [0;30;46m [@"X "t] [0;47;30m        (Space to toggle)  [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  ANSI colour wall:                       [0;30;46m [@"X "t] [0;47;30m        (Space to toggle)  [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  Maximum number of lines:                [1;37;44m@5;0;10000;0n[0;47;30m      (0..10000, 0=all)  [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  Ctrl-R for help                 [0;1;42;33m@14;"OK"b[0;47;30mÜ    [0;1;41;33m@14;"Cancel"b[0;47;30mÜ  [0;1;47;37m³ [0m
[30;47m ³                                   ßßßßßßßßßßßßßßßß     ßßßßßßßßßßßßßßßß  [0;1;47;37m³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m} T Setup, Visual template


OGLT {[2J[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [34mOff-line Graffiti Wall Settings[0;30;47m ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³                                                                          [1;37m³ [0m
[30;47m ³ [31m1[30m. Include graffiti wall in pckages  . . . . . . . . . . . . . . . [34m@"X "t[0;1;47;37m   ³ [0m
[30;47m ³                                                                          [1;37m³ [0m
[30;47m ³ [31m2[30m. ANSI colour wall . . . . . . . . . . . . . . . . . . . . . . .  [34m@"X "t[0;1;47;37m   ³ [0m
[30;47m ³                                                                          [1;37m³ [0m
[30;47m ³ [31m3[30m. Maximum number of lines . . . . . . . . . . . . . . . . . . . . [34m@5;0;10000;0n[0;1;47;37m ³ [0m
[30;47m ³                                                                          [1;37m³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0;1m
} T Setup QWK, Linear template


OGWALL {[0;1m
!JTurn this on to have a copy of the Graffiti Wall included with
every package you download.!)
[0;1m} T Setup QWK, Linear template, enable/disable wall


OGANSI {[0;1m
!JThis option controls whether ANSI colour will be used in the Graffiti
Wall. In order to see the Wall in colour, your off-line reader must also
support ANSI colour directives.!)
[0;1m} T Setup QWK, Linear template, enable/disable ANSI colour


OGLINES {[0;1m
!JThis controls how much of the wall will be included in your packages.
The number limits the number of lines (entries) to be included, in the range
0-10,000. Zero has a special meaning: it includes the entire Wall.!)
[0;1m} T Setup QWK, Linear template, number of lines


DLHDR {[0;1m
[0;1;35mG[36mr[33ma[32mf[31mf[34mi[37m[35mt[36mi Wall: } T Graffiti Wall Download: header


DLDMT {[0;1;33mThe Wall is freshly painted and blank.
[0;1m} T Graffiti Wall Download: Empty wall


DLNAX {[0;1;31mYou have no access to the Graffiti Wall.
[0;1m} T Graffiti Wall Download: no access


DLOK {[0;1;32mDone.
[0;1m} T Graffiti Wall Download: ok


ULWRH {[0;1m
[0;1;35mG[36mr[33ma[32mf[31mf[34mi[37m[35mt[36mi Wall: } T Graffiti Wall Upload: Command header


ULWMT {[1;31mNo lines found to graffiti.
[0;1m} T Graffiti Wall Upload: No lines found


ULWRT {[1;32m%sSuccessfully written %d line%s.
[0;1m} T Graffiti Wall Upload: Written all lines


ULNWR {[1;33m%sWritten %d of %d line%s.
[0;1m} T Reply table: Written some lines


WRTSNG {} T 'Written', singular form
WRTPLR {} T 'Written', plural form

LINSNG {} T 'Lines', singular form
LINPLR {s} T 'Lines', plural form






LANGEND {}

