LEVEL2 {}


LEVEL3 {}

VHELP {[0m[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³ Megistos BBS Visual dialog/form manager                          †‡„ˆ€ [0;1;47;37m³ [0m
[30;47m ³ ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [0;1;47;37m³ [0m
[30;47m ³ [1;47;37m‰ˆŒ†‘†:[0;47;30m Tab, ‰á«à ™â¢¦ª, Ctrl-N: [34m„§æ£œ¤¦ §œ›å¦.[30m á¤à ™â¢¦ª, Ctrl-P: [34m¨¦- [0;1;47;37m³ [0m
[30;47m ³ [34mš¦ç£œ¤¦ §œ›å¦.[30m Enter: [34m„§æ£œ¤¦ §œ›å¦/œ¤œ¨š¦§¦å© '¡¦¬£§ ¦ç'.[30m   [1;47;37m„Œ’Š„‘: [0;1;47;37m³ [0m
[30;47m ³ Ctrl-L: [34m˜¤˜©®œ› áœ  «¤ ¦Ÿæ¤.[30m Ctrl-Q: [34m„¥¦›¦ª/˜¡ç¨à©.[30m Ctrl-S: [34m‘é© £¦/ [0;1;47;37m³ [0m
[30;47m ³ [34mœ§ ¡ç¨à©.[30m Ctrl-R: [34m„£­á¤ © ˜¬«ãª «ª ©œ¢å›˜ª ™¦ãŸœ ˜ª.[30m Ctrl-X: [34m‹œ«˜­¦¨á [0;1;47;37m³ [0m
[30;47m ³ [34m©œ line editor.[30m [1;47;37m„ƒˆ€ „ˆ‘ƒ“:[0;47;30m €¨ ©«œ¨æ ™â¢¦ª, Ctrl-B: [34mƒ¨¦£â˜ª ˜¨ ©«œ¨á.[30m [0;1;47;37m³ [0m
[30;47m ³ ƒœ¥ æ ™â¢¦ª, Ctrl-F: [34mƒ¨¦£â˜ª ›œ¥ á.[30m Home, Ctrl-A: [34m€¨®ã š¨˜££ãª.[30m     End, [0;1;47;37m³ [0m
[30;47m ³ Ctrl-E: [34m’â¢¦ª š¨˜££ãª.[30m Backspace, Ctrl-H: [34mƒ ˜š¨˜­ã §¨¦š¦ç£œ¤¦¬ ®˜¨˜¡«ã- [0;1;47;37m³ [0m
[30;47m ³ [34m¨˜.[30m Delete, Ctrl-D: [34mƒ ˜š¨˜­ã œ§æ£œ¤¦¬ ®˜¨˜¡«ã¨˜.[30m    [1;47;37mŠˆ‘’„‘:[0;47;30m ƒœ¥ æ ™â¢¦ª, [0;1;47;37m³ [0m
[30;47m ³ Ctrl-F, Space, +, =: [34m„§æ£œ¤ œ§ ¢¦šã.[30m    €¨ ©«œ¨æ ™â¢¦ª, Ctrl-B, Ctrl-D, [0;1;47;37m³ [0m
[30;47m ³ Backspace, -, _: [34m¨¦š¦ç£œ¤ œ§ ¢¦šã.[30m  [1;47;37mTOGGLE „ƒˆ€:[0;47;30m Space: [34m€¢¢˜šã ¡˜«á- [0;1;47;37m³ [0m
[30;47m ³ [34m©«˜©ª.[30m     [1;47;37m‰“‹ˆ€:[0;47;30m Enter, Space: [34m„¤œ¨š¦§¦å© ¡¦¬£§ ¦ç.[30m ƒœ¥ æ/€¨ ©«œ¨æ [0;1;47;37m³ [0m
[30;47m ³ ™â¢¦ª: [34m„§æ£œ¤¦/¨¦š¦ç£œ¤¦ §œ›å¦ (æ§àª «˜ á¤à/‰á«à ™â¢).[30m               [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³ [34mƒé©«œ [0;47;30mCtrl-O[34m ©œ ¦§¦ ¦›ã§¦«œ §œ›å¦ š ˜ ¢œ§«¦£œ¨ã §œ¨ š¨˜­ã «¦¬.           [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  â©«œ â¤˜ §¢ã¡«¨¦ š ˜ ¤˜ œ§ ©«¨â¯œ«œ.[s                                   [0;1;47;37m³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m[u} T Visual mode help screen


FHHDR {[0m[32mÛÛ  [1m¦ãŸœ ˜ š ˜ «¦ «¨â®¦¤ §œ›å¦  [42m[K!)
[0;1m} T Field Help, header


FHBUTN {[0;1m
!JŠ¬§á£˜ , ˜¬«æ «¦ œå›¦ª §œ›å¦¬ (¡¦¬£§å) ›œ¤ â®œ  ™¦ãŸœ ˜.
•¨© £œçœ  ˜§¢á š ˜ ¤˜ «œ¨£˜«å©œ  «¦ §¢˜å© ¦ › ˜¢æš¦¬, ©é¦¤«˜ª ã ˜¡¬¨é¤¦¤«˜ª
« ª ˜¢¢˜šâª §¦¬ §¨˜š£˜«¦§¦ ã©˜«œ, ã œ¡«œ¢é¤«˜ª ¡á§¦ ˜ á¢¢ › œ¨š˜©å˜.!)
[0;1m} T Field Help, buttons don't have help


FHFTR {[0;1m
[42m[K[0;1m

!J â©«œ â¤˜ §¢ã¡«¨¦ š ˜ ¤˜ œ§ ©«¨â¯œ«œ ©«¦ §¢˜å© ¦ › ˜¢æš¦¬.!)[0m } T Field Help, footer


NO {® } T 'No' setting for linear toggle fields

YES {Œ˜ } T 'Yes' setting for linear toggle fields


PROMPT {
!W[0;1mƒé©«œ «¦¤ ˜¨ Ÿ£æ «¦¬ §œ›å¦¬ §¦¬ Ÿâ¢œ«œ ¤˜ ˜¢¢á¥œ«œ, [33mOK[37m š ˜
©¬¤â®œ ˜, [33mX[37m š ˜ ˜¡ç¨à© ¡˜  â¥¦›¦, ã [33m?[37m š ˜ «¦ £œ¤¦ç:!) [0m} T Linear mode prompt


ERRSEL {
!W[0;1;31mŠ¬§á£˜ , ›œ¤ ¬§á¨®œ  œ§ ¢¦šã "%s".!)
[0;1m} T Linear mode, incorrect selection


FIELD {
!W[0;1mƒé©«œ «˜ ¤â˜ §œ¨ œ®æ£œ¤˜ «¦¬ §œ›å¦¬, ã [33mX[37m š ˜ ¤˜ ¡¨˜«ã©œ«œ «˜ §˜¢ á:!) [0m} T Linear mode field prompt


NERR {
!W[0;1;31m˜¨˜¡˜¢é ›é©«œ â¤˜¤ ˜¨ Ÿ£æ ˜§æ %d £â®¨  %d.!)
[0;1m} T Linear mode, numerical error


DERR {
!W[0;1;31m˜¨˜¡˜¢é ›é©«œ £å˜ âš¡¬¨ £œ¨¦£¤å˜ ©«¤ £¦¨­ã DD/MM/YYYY ã
DD/MM/YY.!)
[0;1m} T Linear mode, date error


UERR {
!W[0;1;31m’¦ ¯œ¬›é¤¬£¦ "[37m%s[31m" ›œ¤ ¬§á¨®œ . ˜¨˜¡˜¢é ¥˜¤˜§¨¦©§˜Ÿã©«œ.!)
[0;1m} T Linear mode, user ID error


CERR {
!W[0;1;31m’¦ class "[37m%s[31m" ›œ¤ ¬§á¨®œ . ƒé©«œ [33m?[31m š ˜
¡˜«á¢æš¦.!)
[0;1m} T Linear mode, user class error


CLSLSTHDR {[0;1;32m
“§á¨®¦¤«˜ classes:

!W} T List of classes: Header

CLSLSTTAB {%-20s} T List of classes: Tabulation

CLSLSTEND {!)
[0;1m} T List of classes: Footer


FCAN {
[0;1;33m’˜ §œ¨ œ®æ£œ¤˜ «¦¬ §œ›å¦¬ ›œ¤ á¢¢˜¥˜¤.
[0;1m} T Linear mode, field contents not changed


LISTMHDR {
[0;1;32mƒ¬¤˜«âª œ§ ¢¦šâª š ˜ ˜¬«æ «¦ §œ›å¦:

[0m} T Linear mode, list field menu header


LISTMENU {[0;1;33m%2d[37m. %s
} T Linear mode, list field menu line


LISTMFTR {} T  Linear more, list field menu footer


LIST {
!W[0;1mƒé©«œ «¤ œ§ ¢¦šã ©˜ª, [33m?[37m š ˜ «¦ £œ¤¦ç, ã [33mX[37m ˜¡ç¨à©:!) [0m} T Linear mode field prompt


TOGON {
[0;1;32m† œ§ ¢¦šã œ¤œ¨š¦§¦ ãŸ¡œ.
[0;1m} T Linear mode, toggle activated


TOGOFF {
[0;1;32m† œ§ ¢¦šã ˜§œ¤œ¨š¦§¦ ãŸ¡œ.
[0;1m} T Linear mode, toggle deactivated


CONFIRM {[0;1;31m
!W˜¨˜¡˜¢é œ§ ™œ™˜ é©«œ æ«  «ã©˜«œ ¤˜ [33m˜¡¬¨é©œ«œ[31m
« ª ˜¢¢˜šâª ©˜ª ([[33mY[31m]yes=¤˜  / [[33mN[31m]o=æ® ): [0m!)} T About to cancel. Do you confirm?


CONFERR {[0;1;31m
!J˜¨˜¡˜¢é ›é©«œ [33mY[31m ã [33mN[31m.!)
[0;1m} T Confirmation, invalid option


LANG {}

VHELP {[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³ Megistos BBS Visual dialog/form manager                             HELP [0;1;47;37m³ [0m
[30;47m ³ ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [0;1;47;37m³ [0m
[30;47m ³ [1;37mMOVEMENT[0;47;30m: Tab, Down arrow, Ctrl-N: [34mNext field.[30m Up arrow, Ctrl-P: [34mBack to [0;1;47;37m³ [0m
[30;47m ³ [34mprevious field. [30mEnter: [34mNext field/push button. [30m[1;37mSHORTCUTS[0;47;30m: Ctrl-L: [34mRedraw [0;1;47;37m³ [0m
[30;47m ³ [34mscreen. [30mCtrl-Q: [34mQuit/cancel. [30mCtrl-S: [34mSave/OK. [30mCtrl-R: [34mThis page. [30mCtrl-X: [34m[0;1;47;37m³ [0m
[30;47m ³ [34mswitch to line editor. [30m    [1;37mINPUT LINES[0;47;30m: Left arrow, Ctrl-B: [34mCursor left. [30m[0;1;47;37m³ [0m
[30;47m ³ Right arrow, Ctrl-F: [34mCursor right. [30m Home, Ctrl-A: [34mGo to first character. [30m[0;1;47;37m³ [0m
[30;47m ³ End, Ctrl-E: [34mGo to last character. [30m   Backspace, Ctrl-H: [34mDelete previous [0;1;47;37m³ [0m
[30;47m ³ [34mcharacter. [30mDelete, Ctrl-D: [34mDelete next character. [30m   [1;37mLISTS[0;47;30m: Right arrow, [0;1;47;37m³ [0m
[30;47m ³ Ctrl-F, Space, +, =: [34mCycle options forward. [30m Left arrow, Ctrl-B, Ctrl-D, [0;1;47;37m³ [0m
[30;47m ³ Backspace, -, _: [34mCycle options backwards. [30m [1;37mTOGGLES[0;47;30m: Space: [34mchange state. [30m[0;1;47;37m³ [0m
[30;47m ³ [1;37mBUTTONS[0;47;30m: [34mEnter, Space: [34mPush button. [30m Left arrow, right arrow: [34mNext/Prev- [0;1;47;37m³ [0m
[30;47m ³ [34mious field (as Up/Down arrow). [30m                                          [0;1;47;37m³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³ Press any key to go back.[s                                                [0;1;47;37m³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m[u} T Visual mode help screen


FHHDR {[0m[32mÛÛ  [1mHelp on the current field  [42m[K!)
[0;1m} T Field Help, header


FHBUTN {[0;1m
!JSorry, this type of field (button) has no help.
It's used to close this dialog box, saving or canceling
the effected changes, or executing some other function.!)
[0;1m} T Field Help, buttons don't have help


FHFTR {[0;1m
[42m[K[0;1m

!JPress any key to return to the dialog box.!)[0m } T Field Help, footer


NO {No } T 'No' setting for linear toggle fields

YES {Yes} T 'Yes' setting for linear toggle fields


PROMPT {
!W[0;1mPlease select the field to change. Enter [33mOK[37m to
save and go on, [33mX[37m to cancel and exit, or [33m?[37m for the menu:!) [0m} T Linear mode prompt


ERRSEL {
!W[0;1;31mI'm sorry, there is no such command as "%s".!)
[0;1m} T Linear mode, incorrect selection


FIELD {
!W[0;1mEnter the new contents of the field, or [33mX[37m to keep the old ones:!) [0m} T Linear mode field prompt


NERR {
!W[0;1;31mPlease enter a number between %d and %d.!)
[0;1m} T Linear mode, numerical error


DERR {
!W[0;1;31mPlease enter a valid date in the format DD/MM/YYYY or
DD/MM/YY.!)
[0;1m} T Linear mode, date error


UERR {
!W[0;1;31m"[37m%s[31m" is an unknown user ID. Please try again.!)
[0;1m} T Linear mode, user ID error


CERR {
!W[0;1;31mThere is no class "[37m%s[31m". Enter [33m?[31m for a list
of classes.!)
[0;1m} T Linear mode, user class error


CLSLSTHDR {[0;1;32m
Available classes:

!W} T List of classes: Header

CLSLSTTAB {%-20s} T List of classes: Tabulation

CLSLSTEND {!)
[0;1m} T List of classes: Footer


FCAN {
[0;1;33mThe contents of the field were not changed.
[0;1m} T Linear mode, field contents not changed


LISTMHDR {
[0;1;32mAvailable options for this field:

[0m} T Linear mode, list field menu header


LISTMENU {[0;1;33m%2d[37m. %s
} T Linear mode, list field menu line


LISTMFTR {} T  Linear more, list field menu footer


LIST {
!W[0;1mEnter your selection, [33m?[37m for the menu, or [33mX[37m to leave the field unchanged:!) [0m} T Linear mode field prompt


TOGON {
[0;1;32mThe option has been activated.
[0;1m} T Linear mode, toggle activated


TOGOFF {
[0;1;32mThe options has been deactivated.
[0;1m} T Linear mode, toggle deactivated


CONFIRM {[0;1;31m
Please confirm that you requested to [33mcancel[31m
all changes ([[33mY[31m]yes / [[33mN[31m]o): [0m} T About to cancel. Do you confirm?


CONFERR {[0;1;31m
Please enter [33mY[31m or [33mN[31m.
[0;1m} T Confirmation, invalid option


LANGEND {}
