LEVEL3 {}


MENU {[2J[0m[47;1;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;30;47m¿ [40m
[47;1;37m ³  [0;47;34mClass Editor                                  [0;47;30m³ [40m
[47;1;37m ³  [0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ  [0;47;30m³ [40m
[47;1;37m ³  [0;31;47mA[30mdd user class . . . . ƒ£ ¦¬¨šå˜ ¤â¦¬ class  ³ [40m
[47;1;37m ³  [0;31;47mD[30melete user class . . .  ƒ ˜š¨˜­ã œ¤æª class  ³ [40m
[47;1;37m ³  [0;31;47mE[30mdit user class  . . . . . €¢¢˜šã œ¤æª class  ³ [40m
[47;1;37m ³  [0;31;47mV[30miew user class . . . .  „£­á¤ © œ¤æª class  ³ [40m
[47;1;37m ³  [0;31;47mC[30mlass changes  . . ‰˜«á¢¦š¦ª ˜¢¢˜šé¤ classes  ³ [40m
[47;1;37m ³  [0;31;47mL[30mist classes  . . . .  ‰˜«á¢¦š¦ª «à¤ classes  ³ [40m
[47;1;37m ³  [0;31;47mM[30move users . . . . . . . ‹˜ ¡ã ˜¢¢˜šã class  ³ [40m
[47;1;37m ³                                                [0;47;30m³ [40m
[47;1;37m ³ [0;30;47me[31mX[30mit and Save . . . . . €§¦Ÿã¡œ¬© ¡˜  „¥¦›¦ª  ³ [40m
[47;1;37m ³  [0;31;47mQ[30muit, cancel  . . .  „¥¦›¦ª ®à¨åª ˜§¦Ÿã¡œ¬©  ³ [40m
[47;1;37m À[0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m
} T Class editor main menu


SHMENU {
[0;1;32mClass Editor[37m
!Wƒé©«œ «¤ œ§ ¢¦šã ©˜ª ([33mA[37m,[33mD[37m,[33mE[37m,[33mV[37m,[33mC[37m,[33mL[37m,[33mM[37m,[33mX[37m,[33mQ[37m, ã [33m?[37m š ˜ £œ¤¦ç): !)[0m} T Class editor short menu


ERRSEL {[0;31;1m
Š¬§á£˜ , ›œ¤ ¬§á¨®œ  œ§ ¢¦šã "%c".
[0m} T Incorrect selection


ADDCNAME {[0;1m
ƒ£ ¦¬¨šå˜ ¤â¦¬ class.
 !Wƒé©«œ «¦ æ¤¦£˜ «¦¬ ¤â¦¬ class (? š ˜ ¡˜«á¢¦š¦ ã› ¬§á¨®¦¤«à¤):  !)[0m} T Add new class, enter name


UNKCLSS {[0;31;1m
ƒœ¤ ¬§á¨®œ  class %s. ƒé©«œ ? š ˜ ¡˜«á¢¦š¦.
[0m} T Unknown Class name


NOCLSES {[0;33;1m
ƒœ¤ â®œ  ›£ ¦¬¨šŸœå ¡˜¤â¤˜ class £â®¨  ©« š£ãª.
[0m} T No classes in file


ALRDYEX {[0;31;1m
’¦ class %s ¬§á¨®œ  ã› ©«¦ ©ç©«£˜. „¢˜, ©¡â¯¦¬ ¡á«  ¡˜¢ç«œ¨¦... £§¦¨œåª.
[0m} T Class already exists


NUMERR {[0;31;1m
 ˜¨ Ÿ£æª §¦¬ ›é©˜«œ œå¤˜  œ¡«æª ¦¨åà¤.
[0m} T Number off-limits


BOOLERR {[0;31;1m
˜¨˜¡˜¢é ›é©«œ [33mY[31mes=Œ˜ , ã [33mN[31mo=® .
[0m} T Rebuff wrong boolean answer


TOOMANY {[0;31;1m
‚¡¢¦¬§... â®œ ª ¦¨å©œ  ã› %d classes! ƒœ¤ â®œ  á¢¢˜, ˜ª â¡˜¤œª ¦ ¡¦¤¦£å˜!
[0m} T Rebuff too many classes defined


ADDCQ1 {[0;1;32m
!J!Z„®œ«œ «¤ ›¬¤˜«æ««˜ ¤˜ ¦¨å©œ«œ «¦¤ £âš ©«¦ ®¨æ¤¦ §˜¨˜£¦¤ãª «¦¬ ®¨ã©« ©«¤
™á© ˜¤á ¡¢ã©. ‹§¦¨œå«œ, §®, ¤˜ ˜§˜š¦¨œç©œ«œ ©«¦¬ª ®¨ã©«œª ˜¬«¦ç «¦¬ class
¤˜ £â¤¦¬¤ ©«¤ ™á© §˜¨˜§á¤à ˜§æ 120 ¢œ§«á ˜¤á ¡¢ã©, ˜¤œ¥á¨««˜ ˜§æ «¦ §æ©˜
credits â®¦¬¤. €¬«æª ¦ §œ¨ ¦¨ ©£æª  ©®çœ  ‹Œ š ˜ £å˜ ¡¢ã©. ƒ¢˜›ã, ˜­¦ç
¦ ®¨ã©«ª £œå¤œ  120 ¢œ§«á  ©«¤ ™á©, £§¦¨œå ¤˜ ¡¢œå©œ , ¤˜ ¥˜¤˜§á¨œ ,
¡˜  Ÿ˜ £§¦¨œå ¤˜ £œå¤œ  á¢¢˜ 120 ¢œ§«á.!)

!W[37m‹âš ©«¦ª ®¨æ¤¦ª ©ç¤›œ©ª ˜¤á ¡¢ã©, ©œ ¢œ§«á (-1 = ®à¨åª æ¨ ¦): !)[0m} T Ask for time limit per call


ADDCQ2 {[0;1;32m
!J‹§¦¨œå«œ œ§å©ª ¤˜ §œ¨ ¦¨å©œ«œ «¦¤ £âš ©«¦ £œ¨ã© ¦ ®¨æ¤¦ ©ç¤›œ©ª «à¤
£œ¢é¤ ˜¬«¦ç «¦¬ class, œ¢âš®¦¤«˜ª â«©  §æ© é¨˜ ©¬¤¦¢ ¡á £§¦¨œå ¤˜ £œå¤œ 
¡á§¦ ¦ª ®¨ã©«ª ©«¤ ™á© ¡áŸœ £â¨˜.!)

!W[37m‹âš ©«¦ª £œ¨ã© ¦ª ®¨æ¤¦ª ©ç¤›œ©ª, ©œ ¢œ§«á (-1 = ®à¨åª æ¨ ¦): !)[0m} T Ask for time limit per day


ADDCQ3 {[0;1;32m
!J’¦ ©ç©«£˜ £§¦¨œå ¤˜ §¨¦©­â¨œ  ©«˜ £â¢ ˜¬«¦ç «¦¬ class ¡á§¦ ¦ §¦©æ ›à¨œá¤
®¨æ¤¦¬ ¡áŸœ £â¨˜. €¤, §®, ¦¨å©œ«œ ˜¬«æ «¦ §¦©æ ¤˜ œå¤˜  60 credits, ¡˜  â¤˜ª
®¨ã©«ª â®œ  15 ©«¦ «â¢¦ª «ª £â¨˜ª,  ™á© «¦¤ ˜¤œ™áœ  ©«˜ 60. €¤ â®œ 
§œ¨ ©©æ«œ¨˜ ˜§æ 60, ›œ¤ §˜å¨¤œ  «å§¦«˜.!)

!W[37mæ©˜ ›à¨œá¤ credits Ÿ˜ ›å¤œ«œ £œ¨©åàª; !)[0m} T Ask for free credits per day


ADDCQ3A {[0;1;32m
!J„¡«æª ˜§æ «¦¤ £œ¨ã© ¦ ›à¨œá¤ ®¨æ¤¦, £§¦¨œå«œ ¤˜ ¦¨å©œ«œ â¤˜ §¦©æ §¦¬ Ÿ˜
§¨¦©«åŸœ«˜  ©«¦¤ ¢¦š˜¨ ˜©£æ «à¤ £œ¢é¤ ˜¬«¦ç «¦¬ class ¡áŸœ œ™›¦£á›˜ (™¨á›¬
‰¬¨ ˜¡ãª §¨¦ª ƒœ¬«â¨˜). ‘œ ˜¤«åŸœ© £œ «¦¤ £œ¨ã© ¦ ›à¨œá¤ ®¨æ¤¦, æ£àª, «¦
§¦©æ §¦¬ Ÿ˜ ¦¨å©œ«œ «é¨˜ §¨¦©«åŸœ«˜  ©«¦¤ ˜¨ Ÿ£æ credits §¦¬ ã› â®œ  ¦
®¨ã©«ª. ƒ¢˜›ã, ˜¤ ›œ¤ ®¨© £¦§¦ œå«˜  ¡˜Ÿæ¢¦¬ ¦ ¢¦š˜¨ ˜©£æª, «˜ credits
«¦¬ Ÿ˜ ˜¬¥á¤¦¤«˜  ¡áŸœ œ™›¦£á›˜ ®à¨åª á¤à æ¨ ¦. ‹§¦¨œå«œ ¤˜ ¦¨å©œ«œ "­¦¨¦¢æš©"
«à¤ ®¨©«é¤ ›å¤¦¤«˜ª â¤˜ ˜¨¤« ¡æ §¦©æ.!)

!W[37mæ©˜ ›à¨œá¤ credits Ÿ˜ ›å¤œ«œ œ™›¦£˜› ˜åàª; !)[0m} T Ask for bonus credits per week


ADDCQ3B {[0;1;32m
!J‹§¦¨œå«œ œ§å©ª ¤˜ ›å¤œ«œ â¤˜ ©¬š¡œ¡¨ £â¤¦ §¦©æ ›à¨œá¤ credits ©«¦¬ª ®¨ã©«œª
¡áŸœ §¨é« «¦¬ £ã¤˜. ˆ©®çœ  œ›é æ,«  ¡˜  ©«¤ §¨¦š¦ç£œ¤ ¨çŸ£ © š ˜
«¦¤ œ™›¦£˜› ˜å¦ ›à¨œá¤ ®¨æ¤¦.!)

!W[37mæ©˜ ›à¨œá¤ credits Ÿ˜ ›å¤œ«œ £¤ ˜åàª; !)[0m} T Ask for bonus credits per month


ADDCQ4A {[0;1;32m
!J«˜¤ «œ¢œ é©¦¬¤ «˜ credits ¡á§¦ ¦¬ ®¨ã©«, ã æ«˜¤ ¦ ®¨ã©«ª ¬§œ¨™œå «˜
®¨¦¤ ¡á æ¨ á «¦¬,  ™á© £§¦¨œå ¤˜ «¦¬ ˜¢¢á¥œ  class ˜­¦ç «¦¤ ˜§¦©¬¤›â©œ .
€¬«æ œå¤˜  ®¨ã© £¦ ˜¤ Ÿâ¢œ«œ ¤˜ §œ¨ ¦¨å©œ«œ «¤ §¨æ©™˜© «à¤ ®¨©«é¤ §¦¬ ›œ¤
â®¦¬¤ £¦¤á›œª. €¤ ›œ¤ Ÿâ¢œ«œ ˜¢¢˜šã class, ›é©«œ «¦ æ¤¦£˜ «¦¬ å› ¦¬ «¦¬
class §¦¬ §¨¦©Ÿâ«œ«œ/œ¤£œ¨é¤œ«œ «é¨˜. † ˜¢¢˜šã ˜¬«ã œå¤˜  §¨¦©à¨ ¤ãª ­ç©ª.
‘«¦ œ§æ£œ¤¦ cleanup «¦¬ ›é©œ  ˜¬«æ£˜«˜ credits, ¦ ®¨ã©«ª Ÿ˜ œ§˜¤â¢Ÿœ  ©«¦
§¨¦š¦ç£œ¤æ «¦¬ class.!)

!W[37mƒé©«œ «¦ æ¤¦£˜ «¦¬ class (? š ˜ ¡˜«á¢¦š¦): !)[0m} T Class to go to when out of credits


ADDCQ4B {[0;1;32m
!J«˜¤ ›é©œ«œ paid credits ©œ â¤˜¤ ®¨ã©«, ©¬¤ãŸàª Ÿâ¢œ«œ ¡˜  ¤˜ ˜¢¢á¥œ«œ «¦
class «¦¬ ©œ ¡á«  £œ §œ¨ ©©æ«œ¨ §¨æ©™˜©. €¬«æ £§¦¨œå ¤˜ šå¤œ  ˜¬«æ£˜«˜,
œ­'æ©¦¤ ›¢é©œ«œ œ›é «¦ class ©«¦ ¦§¦å¦ Ÿâ¢œ«œ ¤˜ «¦¤ £œ«˜­â¨œ«œ. €¤ ›œ¤
Ÿâ¢œ«œ ¤˜ ˜¢¢á¥œ  class ¦ ®¨ã©«ª, ›é©«œ «¦ æ¤¦£˜ «¦¬ å› ¦¬ «¦¬ class §¦¬
§¨¦©Ÿâ«œ«œ/œ¤£œ¨é¤œ«œ «é¨˜.!)

!W[37mƒé©«œ «¦ æ¤¦£˜ «¦¬ class (? š ˜ ¡˜«á¢¦š¦): !)[0m} T Class to go to when paid credits posted


ADDCQ5 {[0;1;32m
!J€¤ ¦ ®¨ã©«ª ›œ¤ ©¬¤›œŸœå ©«¤ ™á© š ˜ ¡á§¦ ¦ ®¨¦¤ ¡æ › á©«£˜, £§¦¨¦ç£œ
¤˜ «¦¬ ˜¢¢á¥¦¬£œ class (˜¬«æ ¨¬Ÿ£åœ«˜  ©«¤ œ§æ£œ¤ œ¨é«©). ‹œ«á ˜§æ
§æ©œª £â¨œª Ÿâ¢œ«œ ¤˜ ©¬£™œå ˜¬«æ (0 = ©«¦ §¨é«¦ cleanup, 1 = ©«¦ œ§æ£œ¤¦,
¡¢§);!)

!W[37mƒé©«œ «¦ ®¨¦¤ ¡æ › á©«£˜ ©œ £â¨œª (-1 = §¦«â); !)[0m} T Number of NOT_AROUND days


ADDWHCL {[0;1;32m
‰˜  ©œ §¦ ¦ class Ÿ˜ «¦¤ ©«œå¢¦¬£œ;

!W[37mƒé©«œ «¦ æ¤¦£˜ «¦¬ class (? š ˜ ¡˜«á¢¦š¦): !)[0m} T Enter class name to go to


ADDCQ6 {[0;1;32m
!J€­¦ç ¦ ®¨ã©«ª §˜¨˜£œå¤œ  ©œ ˜¬«æ «¦ class š ˜ ¡á§¦ ¦ ®¨¦¤ ¡æ › á©«£˜,
£§¦¨¦ç£œ ¤˜ «¦¤ £œ«˜­â¨¦¬£œ ©œ á¢¢¦ class (§¦¬ Ÿ˜ ¦¨å©œ«œ ©«¤ œ§æ£œ¤
œ¨é«©). €¬«æ œå¤˜  ®¨ã© £¦ š ˜ «˜ œ¥ãª:!)

- •¨ã©«œª DEMO §¦¬ £œ«á ˜§æ ¢åšœª £â¨œª šå¤¦¤«˜  ¡˜¤¦¤ ¡¦å
- ‘¬¤›¨¦£«âª «à¤ ¦§¦åà¤  ©¬¤›¨¦£ã ¢ãšœ  £œ«á ˜§æ ¡á§¦ ¦ › á©«£˜

!W[37mƒé©«œ «¦ ®¨¦¤ ¡æ › á©«£˜ ©œ £â¨œª (-1 = §¦«â); !)[0m} T Class to go to after N days


ADDCQ7 {[0;1;32m
!J’˜ £â¢ ˜¬«¦ç «¦¬ class £§¦¨¦ç¤ ¤˜ œå¤˜  ¬§œ¨á¤à ®¨âà©ª credits (§® sysops).
€¤ ˜§˜¤«ã©œ«œ Ÿœ« ¡á ©«¤ §˜¨˜¡á«à œ¨é«©, ¦  ®¨ã©«œª ˜¬«¦ç «¦¬ class ›œ¤ Ÿ˜
¡˜«˜¤˜¢é¤¦¬¤ §¦«â credits.!)

!W[37m‡â¢œ«œ ¤˜ œå¤˜  ¬§œ¨á¤à ®¨âà©ª ˜¬«æ «¦ class ([33mY[37m/[33mN[37m); !)[0m} T Class exempt from charges?


ADDCQ8 {[0;1;32m
!J„§ ¢œ¡« ¡á, ¦  ®¨ã©«œª œ¤æª class £§¦¨¦ç¤ ¤˜ §˜¨˜¡á£¯¦¬¤ «¤ ™á©
¡˜  ¤˜ ©¬¤›œŸ¦ç¤ ˜§œ¬Ÿœå˜ª £œ «¦ Linux (˜¬«æ šå¤œ«˜  ›å¤¦¤«˜ª «¦¤
®˜¨˜¡«ã¨˜ '@@' ˜£â©àª §¨ ¤ ˜§æ «¦ ¯œ¬›é¤¬£¦, ©«¤ › ˜› ¡˜©å˜ ©ç¤›œ©ª).

!W[37m‡â¢œ«œ ¤˜ œ§ «¨˜§œå ˜¬«æ ©'˜¬«æ «¦ class ([33mY[37m/[33mN[37m); !)[0m} T Allow Linux access?


ADDCQ9 {[0;1;32m
!J‹§¦¨œå«œ ¤˜ ­« á¥œ«œ â¤˜ class «˜ £â¢ «¦¬ ¦§¦å¦¬ ›œ¤ â®¦¬¤ ¡˜¤ §¨æ©™˜©
©«¤ ™á©. €¬«æ £¦ áœ  §¦¢ç £œ ¡˜«á©«˜© suspend, £æ¤¦ §¦¬ ¬§æ¡œ «˜ 
©«¦¬ª ¡˜¤æ¤œª «à¤ classes (¡˜  ¦ ®¨ã©«ª §˜å¨¤œ  › ˜­¦¨œ« ¡æ £ã¤¬£˜ æ«˜¤
«¦¤ §œ«áœ   ™á©).!)

!W[37mŒ˜ ˜§˜š¦¨œç©à «¤ §¨æ©™˜© ©œ ˜¬«æ «¦ class ([33mY[37m/[33mN[37m); !)[0m} T Lock-out users in this class?


ADDCQ10 {[0;1;32m
!J€¤ Ÿâ¢œ«œ, £§¦¨œå«œ ¤˜ ˜§˜š¦¨œç©œ«œ «¤ £œ«˜­¦¨á credits ˜§æ ®¨ã©«œª
˜¬«¦ç «¦¬ class ©œ á¢¢¦¬ª ®¨ã©«œª.!)

!W[37mŒ˜ ˜§˜š¦¨œç©à «¤ £œ«˜­¦¨á £¦¤á›à¤ ([33mY[37m/[33mN[37m); !)[0m} T Prohibit credit transfers?


KEYPRO {[0;1;32m
!J’é¨˜ Ÿ˜ ¦¨å©œ«œ §¦ ˜ "¡¢œ › á" Ÿ˜ â®¦¬¤ ˜¬«¦£á«àª æ¢¦  ¦  ®¨ã©«œª ˜¬«¦ç «¦¬
class. “§á¨®¦¬¤ 128 › ˜­¦¨œ« ¡á ¡¢œ › á, ˜¨ Ÿ££â¤˜ ˜§æ «¦ 1 £â®¨  «¦ 128.
„§œ ›ã æ¢  ˜©­á¢œ ˜ «¦¬ ©¬©«ã£˜«¦ª ™˜©åœ«˜  ©«¤ â¥¬§¤ › ˜®œå¨© «à¤
¡¢œ › é¤, §¨¦©â¥«œ «  ¡á¤œ«œ!!)
[0;1m} T Key editor prologue


KEYED {[0;1;32m
ÉÍÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÍ»
º 0   ³    1    ³    2    ³    3    ³    4    ³    5    ³    6   6 º
º 1234567890123456789012345678901234567890123456789012345678901234 º
º [37m%s[32m º
ÌÍØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØÍ¹
º ³         ³         ³         ³    1    ³    1    ³    1    ³  1 º
º 6    7    ³    8    ³    9    ³    0    ³    1    ³    2    ³  2 º
º 5678901234567890123456789012345678901234567890123456789012345678 º
º [37m%s[32m º
ÈÍÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÍ¼
[0;1m} T Key Editor Template


KEYASK {
[0;1m!Wƒé©«œ «¦¤ ˜¨ Ÿ£æ «¦¬ ¡¢œ › ¦ç (1-128, ? š ˜ œ£­á¤ © ¡¢œ › é¤, 
ON=æ¢˜, OFF=¡˜¤â¤˜, OK š ˜ «â¢¦ª): !)[0m} T Key Editor, enter key


KEYON {[0;1;32m
’¦ ¡¢œ ›å %d §¨¦©«âŸ¡œ ©«¦ ©ç¤¦¢¦.
[0;1m} T Key Editor, added key


KEYOFF {[0;1;32m
’¦ ¡¢œ ›å %d ˜­˜ ¨âŸ¡œ ˜§æ «¦ ©ç¤¦¢¦.
[0;1m} T Key Editor, deleted key


CCHLHDR {[0;37m
ÚÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
³   ¤¦£˜   ³[7mİ                        €ŠŠ€‚„‘ CLASS                      Ş[0;37m³
³   Class   ³ €§¦¬©å˜    ‹â¨œª ³ ˜¨¦¬©å˜   ‹â¨œª ³ No Credits³Paid  Creds³
ÃÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄ´
} T Class change list header


CCHLTAB {[0m³ %-9s ³ %-9s ³ %4s ³ %-9s ³ %4s ³ %-9s ³ %-9s ³
} T Class change list line


CCHLFTR {[0mÀÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÙ

[0m} T Class change list footer


CLSLHDR {[0;37m
ÚÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
³   ¤¦£˜   ³[7mİ   •Œ‘    Ş[0;37m³[7mİ    ƒ—„€Œ •Œ‘    Ş[0;37mÃÄÄÄÄÄÄÄ¿
³   Class   ³ ‰¢ã© ³ †£â¨˜ ³ †£â¨˜ ³ „™›¦£ ³ ‹ã¤˜ª ³ Flags ³
ÃÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄ´
} T Class change list header


CLSLTAB {[0m³ %-9s ³ %5s ³ %5s ³ %5d ³ %5d ³ %5d ³ %c%c%c%c  ³
} T Class change list line


CLSLFTR {[0mÀÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÁÄÂÂÂÂÄÄÙ
ƒœ¤ ¡˜«˜¤˜¢é¤¦¤«˜  credits                   Ä 1 ÄÄÄÄÄÙ³³³
„§ «¨â§¦¤«˜  §¦¢¢˜§¢á logins                 Ä 2 ÄÄÄÄÄÄÙ³³
€§˜š¦¨œçœ«˜  «¦ login ©«¤ ™á©              Ä 3 ÄÄÄÄÄÄÄÙ³
„§ «¨â§œ«˜   £œ«˜­¦¨á credits §¨¦ª «¨å«¦¬ª  Ä 4 ÄÄÄÄÄÄÄÄÙ
[0m} T Class list footer


DELCNAME {[0;1m
ƒ ˜š¨˜­ã class.
!Wƒé©«œ «¦ æ¤¦£˜ «¦¬ class §¦¬ Ÿ˜ › ˜š¨á¯œ«œ (? š ˜ ¡˜«á¢¦š¦): !)[0m} T Delete class, enter name


DELCCNF {[0;1;32m
!W[37m‘åš¦¬¨˜ Ÿâ¢œ«œ ¤˜ «¦ › ˜š¨á¯à; ([33mY[37m/[33mN[37m); !)[0m} T Confirm class deletion


DELWARN {[0;1;33m
¨¦©¦®ã: !l
!J€¤ ¬§á¨®¦¬¤ ˜¡æ£˜ ®¨ã©«œª §¦¬ ˜¤ã¡¦¬¤ ©«¦ class §¦¬ › ˜š¨á¯˜«œ,
§¨â§œ  ¤˜ «¦¬ª £œ«˜¡ ¤ã©œ«œ ©œ â¤˜ ¬§á¨®¦¤ class £œ «¤ œ¤«¦¢ã
M ˜§æ «¦ ¡œ¤«¨ ¡æ £œ¤¦ç «¦¬ class editor.   ®¨ã©«œª §¦¬ ›œ¤
˜¤ã¡¦¬¤ ©œ ¡á§¦ ¦ ¬§á¨®¦¤ class ›œ¤ £§¦¨¦ç¤ ¤˜ £§¦¬¤ ©«¤ ™á©.!)
!0l[0m} T Class deletion warning


VEWCNAME {[0;1m
„£­á¤ © class.
!Wƒé©«œ «¦ æ¤¦£˜ «¦¬ class §¦¬ Ÿâ¢œ«œ ¤˜ ›œå«œ (? š ˜ ¡˜«á¢¦š¦): !)[0m} T View class, enter name


VIEWC1 {[0;1;32m
!FÄ
¤¦£˜ class: [37m%s[32m

} T View class, Line 1


VIEWC2 {!W€¤ ¦ ®¨ã©«ª ›œ¤ ©¬¤›œŸœå š ˜ [37m%d £â¨%s[32m, £œ«˜­â¨œ«˜  ©«¦ class [37m%s[32m.!)
} T View class, Line 2


DAYSNG {˜} T Day singular
DAYPLR {œª} T Day plural


VIEWC3 {!W‹œ«á ˜§æ [37m%d £â¨%s[32m, ¦ ®¨ã©«ª Ÿ˜ £œ«˜­œ¨Ÿœå ©«¦ class [37m%s[32m.!)
} T View class, Line 3


VIEWC4A {!W•¨ã©«œª ®à¨åª credits £œ«˜­â¨¦¤«˜  ©«¦ class [37m%s[32m.!)
} T View class, Line 4A


VIEWC4C {!W•¨ã©«œª §¦¬ ˜§¦¡«¦ç¤ paid credits £œ«˜­â¨¦¤«˜  ©«¦ class [37m%s[32m.!)
} T View class, Line 4C


VIEWC5 {
!W¨ ¦ ®¨æ¤¦¬ ©ç¤›œ©ª ˜¤á ¡¢ã©: [37m%5d ¢œ§«%s[32m.!)
} T View class, Line 5


VIEWC6 {!W¨ ¦ £œ¨ã© ¦¬ ®¨æ¤¦¬ ©ç¤›œ©ª: [37m%5d ¢œ§«%s[32m.!)
} T View class, Line 6


VIEWC7 {!Wƒà¨œá¤ ®¨æ¤¦ª ¡áŸœ £â¨˜:        [37m%5d credit%s[32m.!)
} T View class, Line 7


VIEWC7A {!Wƒà¨œá¤ ®¨æ¤¦ª ¡áŸœ œ™›¦£á›˜:    [37m%5d credit%s[32m.!)
} T View class, Line 7A


VIEWC7B {!Wƒà¨œá¤ ®¨æ¤¦ª ¡áŸœ £ã¤˜:        [37m%5d credit%s[32m.!)
} T View class, Line 7B


MINSNG {æ} T Minute singular
MINPLR {á} T Minute plural


CRDSNG {} T credit singular
CRDPLR {s} T credit plural


VIEWC8 {
!W  ®¨ã©«œª œå¤˜  ¬§œ¨á¤à ®¨âà©ª £œ credits.!)
} T View class, Line 8


VIEWC9 {
!W„§ «¨â§¦¤«˜  §¦¢¢˜§¢âª «˜¬«æ®¨¦¤œª ©¬¤›â©œ ª.!)
} T View class, Line 9


VIEWC10 {
!W€§˜š¦¨œçœ«˜   ©ç¤›œ© ©«¤ ™á©.!)
} T View class, Line 10.


VIEWC11 {
!W„§ «¨â§¦¤«˜  ¦  £œ«˜­¦¨âª credits ©œ á¢¢¦¬ª ®¨ã©«œª.!)
} T View class, Line 11.


VIEWKY {
‰¢œ › á: !i!W} T View Class, keys

VIEWKY1 {%d } T Single key

VIEWKY2 {%d-%d } T Key range

VIEWKYE {!)
!0l} T Key list end

VIEWKY0 {[‰˜¤â¤˜]!)
!0l} T Key list end, no keys


VIEWCEND {[32m!FÄ
[0m} T View class, end


MOVSRC {[0;1m
‹˜ ¡ã £œ«˜­¦¨á ®¨©«é¤ ˜§æ â¤˜ class ©œ â¤˜ á¢¢¦.
!Wƒé©«œ «¦ æ¤¦£˜ «¦¬ ˜¨® ¡¦ç class (? š ˜ ¡˜«á¢¦š¦): !)[0m} T Move class, enter source name


MOVTRG {[0;1m
!Wƒé©«œ «¦ ¤â¦ class š ˜ ˜¬«¦çª «¦¬ª ®¨ã©«œª (? š ˜ ¡˜«á¢¦š¦): !)[0m} T Move class, enter target name


NSAMCLS {[0;1;31m
!J€©œ, ˜¬«á œå¤˜  š ˜ «˜ ¡¦¨æ ›˜. „›à©œª ›ç¦ ­¦¨âª «¦ å› ¦ class!
€¤ Ÿâ¢œ ª ¤˜ £œ«˜¡ ¤ã©œ ª ®¨ã©«œª ˜§æ â¤˜ class ©œ â¤˜ á¢¢¦, ¡˜¢ã
 ›â˜ Ÿ˜ ã«˜¤ ¤˜ â› ¤œª ›ç¦ › ˜­¦¨œ« ¡á classes! ’©¡ «©¡ «©¡.!)
[0;1m} T Move class, class names must differ


MOVING {[0;1;32m
‹œ«˜¡ ¤é «¦¬ª ®¨ã©«œª «¦¬ class [37m%s[32m ©«¦ class [37m%s[32m.

˜¨˜¡˜¢é §œ¨ £â¤œ«œ.} T Moving users from one class to another


MOVOK {[0;1;32m

† › ˜› ¡˜©å˜ «œ¢œåà©œ œ§ «¬®éª. •¨ã©«œª §¦¬ £œ«˜¡ ¤ãŸ¡˜¤: [37m%d
[0;1m} T Move operation successful


DEFSTR {[0;1m[Enter=%s] [0m} T Default string value


DEFINT {[0;1m[Enter=%d] [0m} T Default integer value


DEFCHR {[0;1m[Enter=%c] [0m} T Default character value


EDTCNAME {[0;1m
€¢¢˜šã/„¤£â¨à© class.
!Wƒé©«œ «¦ æ¤¦£˜ «¦¬ class §¦¬ Ÿâ¢œ«œ ¤˜ œ¤£œ¨é©œ«œ (? š ˜ ¡˜«á¢¦š¦): !)[0m} T Edit class, enter name

IOERROR {[0;1;5;31m
‘•†: !i!J[0;1;31m’¦ ˜¨®œå¦ «à¤ classes ›œ¤ £§æ¨œ©œ ¤˜ š¨˜­«œå. €¬«æ œå¤˜ 
©£˜¤« ¡æ ¢áŸ¦ª! ¨â§œ  ¤˜ «¦ › ¦¨Ÿé©œ«œ «¦ ©¬¤«¦£æ«œ¨¦, ˜¢¢ éª ›œ¤
Ÿ˜ £§¦¨¦ç¤ ¤˜ ©¬¤›œŸ¦ç¤ ¦  ®¨ã©«œª.[0m!)
} T IO Error while writing class file

QUITWRN {[0;1;31m
!W…«ã©˜«œ ¤˜ ­çšœ«œ ˜§æ «¦¤ class editor ¡˜  ¤˜ ®á©œ«œ æ¢œª « ª ˜¢¢˜šâª
§¦¬ §¨˜š£˜«¦§¦ ã©˜«œ ©«¦ ˜¨®œå¦.!)

!W[31m‘åš¦¬¨˜ Ÿâ¢œ«œ ¤˜ œš¡˜«˜¢œå¯œ«œ; ([33mY[31m/[33mN[31m); !)[0m} T Confirm quit




LANG {}


MENU {[2J[0m[47;1;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;30;47m¿ [40m
[47;1;37m ³  [0;47;34mClass Editor                                  [0;47;30m³ [40m
[47;1;37m ³  [0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ  [0;47;30m³ [40m
[47;1;37m ³  [0;31;47mA[30mdd a new class                               ³ [40m
[47;1;37m ³  [0;31;47mD[30melete an existing class                      ³ [40m
[47;1;37m ³  [0;31;47mE[30mdit a class                                  ³ [40m
[47;1;37m ³  [0;31;47mV[30miew a class                                  ³ [40m
[47;1;37m ³  [0;31;47mC[30mlass transition table                        ³ [40m
[47;1;37m ³  [0;31;47mL[30mist all classes                              ³ [40m
[47;1;37m ³  [0;31;47mM[30move users from one class to another          ³ [40m
[47;1;37m ³                                                [0;47;30m³ [40m
[47;1;37m ³ [0;30;47me[31mX[30mit and Save                                  ³ [40m
[47;1;37m ³  [0;31;47mQ[30muit, cancel                                  ³ [40m
[47;1;37m À[0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m
} T Class editor main menu


SHMENU {
[0;1;32mClass Editor[37m
!WEnter your choice ([33mA[37m,[33mD[37m,[33mE[37m,[33mV[37m,[33mC[37m,[33mL[37m,[33mM[37m,[33mX[37m,[33mQ[37m, or [33m?[37m for the menu): !)[0m} T Class editor short menu


ERRSEL {[0;31;1m
Sorry, there is no option "%c".
[0m} T Incorrect selection


ADDCNAME {[0;1m
Create a new class.
!WEnter the name of the class (? for a list of existing classes):  !)[0m} T Add new class, enter name


UNKCLSS {[0;31;1m
No such class %s. Enter ? for a list.
[0m} T Unknown Class name


NOCLSES {[0;33;1m
There are currently no classes.
[0m} T No classes in file


ALRDYEX {[0;31;1m
Cass %s already exists. Come on, you can think of a better name!
[0m} T Class already exists


NUMERR {[0;31;1m
Sorry, that number cannot be accepted.
[0m} T Number off-limits


BOOLERR {[0;31;1m
Please enter [33mY[31mes, or [33mN[31mo.
[0m} T Rebuff wrong boolean answer


TOOMANY {[0;31;1m
Gulp... you've already defined %d classes! That's our limit!
[0m} T Rebuff too many classes defined


ADDCQ1 {[0;1;32m
!J!ZYou can set the maximum time a user can stay online per session. For example,
you can forbit users of this class to stay online more than 120 minutes per call,
regardless of how many credits they have. This limit is valid on a per-call basis.
After the 120 minutes go by and the user is disconnected, they can always redial
and get another 120 minutes.!)

!W[37mPer-call time limit in minutes (-1 = no limit): !)[0m} T Ask for time limit per call


ADDCQ2 {[0;1;32m
!JYou can also limit the maximum time a user can stay online every day.!)

!W[37mDaily time limit in minutes (-1 = no limit): !)[0m} T Ask for time limit per day


ADDCQ3 {[0;1;32m
!JThe system can offer members of this class an amount of free credits every day.
This is a credit top-up: if, for example, you set this to 60 credits, and a user
has 15 credits at the end of the day, the BBS will top the user up to 60 credits. If
the user has more than 60 credits, they get nothing.!)

!W[37mHow many free top-up credits per day? !)[0m} T Ask for free credits per day


ADDCQ3A {[0;1;32m
!JIn addition to free daily top-ups, you can set an amount of credits  
to be added to the user's account once a week (late Sunday night or
early Monday morning). Unlike the previous setting, this isn't a top-up quantity,
but an additive one. If you set this value to 100 credits, the user will receive
an extra hundred credits every week. If a user account isn't used, its credits
will increase weekly without limits. You can enter a negative amount to "tax"
users every week.!)

!W[37mHow many credits to add weekly? !)[0m} T Ask for bonus credits per week


ADDCQ3B {[0;1;32m
!JYou can also provide a similar credit boost or tax on a monthly basis (payable
on the 1st). Other than the frequency of payments, this setting is identical to the
previous one about weekly payments.!)

!W[37mHow many credits to add monthly? !)[0m} T Ask for bonus credits per month


ADDCQ4A {[0;1;32m
!JIf a user runs out of credits, or they exceed their time limits, the BBS
can change the user's class after the user is diconnected. This is useful if you
want to reduce the privileges of users who haven't payed. To keep the user in
the same class, enter the name of this class. This class change is temporary.
If the user is given a credit top-up at the next cleanup, they will revert to
the previous class.!)

!W[37mEnter the class to move to (? for a list): !)[0m} T Class to go to when out of credits


ADDCQ4B {[0;1;32m
!JWhen a user receives paid credits, you usually want to change their class
to something with better access privileges. This can be done automatically.
Just name the class the user should be moved on receipt of paid credits.
If you want the user to stay in this class, simply enter the name of this class.!)

!W[37mEnter the class to move to (? for a list): !)[0m} T Class to go to when paid credits posted


ADDCQ5 {[0;1;32m
!JIf the user doesn't connect to the BBS for some time, we can move them
to another class. This setting controls how many days you want users to stay in
this class if they don't use the system (0 = change at the first cleanup, 1 =
change at the second cleanup, and so on).!)

!W[37mEnter the timeout in days (-1 = never): !)[0m} T Number of NOT_AROUND days


ADDWHCL {[0;1;32m
!JOk, and what class do we move the user to?!)

!W[37mEnter the class to move to (? for a list): !)[0m} T Enter class name to go to


ADDCQ6 {[0;1;32m
!JWe can move users to another class after a certain time, regardless of
whether they connect or not. This is useful to implement, for instance:!)

  - Demo users who become regular users after a probation period.
  - Users whose subscription expires after a certain time (eg monthly).

!W[37mEnter the timeout in days (-1 = never); !)[0m} T Class to go to after N days


ADDCQ7 {[0;1;32m
!JMembers of this class can be exempt from charges (eg operators or staff,
or perhaps users with a monthly subscription but no per-minute credit charges).
If you answer yes to the following question, users' credits will never
diminish.!)

!W[37mMake this class exempt from charges ([33mY[37m/[33mN[37m)? !)[0m} T Class exempt from charges?


ADDCQ8 {[0;1;32m

!JYou can allow users of this class to bypass the BBS login and
enter the UNIX system directly (by typing the at-sign @@ right
before their user ID at the login prompt). The user will still be
required to authenticate themselves at the UNIX login prompt, but
this whole thing is a massive security risk (for network
connections, the Secure Shell is recommended), so think very
carefully before answering.

!W[37mAllow UNIX logins to this class ([33mY[37m/[33mN[37m)? !)[0m} T Allow Linux access?


ADDCQ9 {[0;1;32m
!JYou can create a class whose members can't even login to the BBS.
This is somewhat like a SUSPEND situation, only it's subject to class
transitions and the user gets a different, friendlier message
when they try to login.!)

!W[37mLock out users of this class ([33mY[37m/[33mN[37m)? !)[0m} T Lock-out users in this class?


ADDCQ10 {[0;1;32m
!JYou can forbid credit transfers from members of this class to other users.
This is useful in systems where certain users have massive hoards of credits
that you don't want other classes' users to have access to (to avoid credit
inflation over time, for instance).!)

!W[37mForbid this class to transfer credits ([33mY[37m/[33mN[37m)? !)[0m} T Prohibit credit transfers?


KEYPRO {[0;1;32m
!JNow you can set a number of "keys" that all users of this class will
automatically get. There are 128 such keys. Like UNIX groups, each key
can be configured to provide access to certain features of the system
(this mapping of key numbers to features is entirely up to you).
Be careful of what keys you enable here! Remember, you can always
give individual users extra keys if you need to.!)
[0;1m} T Key editor prologue


KEYED {[0;1;32m
ÉÍÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÍ»
º 0   ³    1    ³    2    ³    3    ³    4    ³    5    ³    6   6 º
º 1234567890123456789012345678901234567890123456789012345678901234 º
º [37m%s[32m º
ÌÍØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØØÍ¹
º ³         ³         ³         ³    1    ³    1    ³    1    ³  1 º
º 6    7    ³    8    ³    9    ³    0    ³    1    ³    2    ³  2 º
º 5678901234567890123456789012345678901234567890123456789012345678 º
º [37m%s[32m º
ÈÍÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÍ¼
[0;1m} T Key Editor Template


KEYASK {
[0;1m!WEnter key number (1-128, ? to show keys, 
ON=all, OFF=none, OK to end): !)[0m} T Key Editor, enter key


KEYON {[0;1;32m
Key %d was added to the keyring.
[0;1m} T Key Editor, added key


KEYOFF {[0;1;32m
Key %d was removed from the keyring.
[0;1m} T Key Editor, deleted key


CCHLHDR {[0;37m
ÚÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
³   Class   ³[7mİ                      CLASS TRANSITIONS                    Ş[0;37m³
³   Name    ³ Absence     Days ³ Presence    Days ³ No Credits³Paid  Creds³
ÃÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄ´
} T Class change list header


CCHLTAB {[0m³ %-9s ³ %-9s ³ %4s ³ %-9s ³ %4s ³ %-9s ³ %-9s ³
} T Class change list line


CCHLFTR {[0mÀÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÙ

[0m} T Class change list footer


CLSLHDR {[0;37m
ÚÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
³   Class   ³[7mİ    TIME     Ş[0;37m³[7mİ    ƒ—„€Œ •Œ‘    Ş[0;37mÃÄÄÄÄÄÄÄ¿
³   Name    ³  Call ³ Daily ³  Day  ³  Week ³ Month ³ Flags ³
ÃÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄ´
} T Class change list header


CLSLTAB {[0m³ %-9s ³ %5s ³ %5s ³ %5d ³ %5d ³ %5d ³ %c%c%c%c  ³
} T Class change list line


CLSLFTR {[0mÀÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÁÄÂÂÂÂÄÄÙ
Exempt from credit charges . . . . . . . . . . 1 ÄÄÄÄÄÙ³³³
(Reserved for future use) . . . . . . . . . .  2 ÄÄÄÄÄÄÙ³³
Locked out of the BBS  . . . . . . . . . . . . 3 ÄÄÄÄÄÄÄÙ³
Allowed to transfer credits to others . . . .  4 ÄÄÄÄÄÄÄÄÙ
[0m} T Class list footer


DELCNAME {[0;1m
Delete a class.
!WEnter class name to delete (? for a list): !)[0m} T Delete class, enter name


DELCCNF {[0;1;32m
!W[37mAre you sure you want this class deleted? ([33mY[37m/[33mN[37m) !)[0m} T Confirm class deletion


DELWARN {[0;1;33m
Caution: !l
!JAny users still in the class you've just deleted must be moved to
an existing class with the M command from the main menu of the
class editor. Users belonging to a non-existing class will not be
able to login, and will log system errors.!)
!0l[0m} T Class deletion warning


VEWCNAME {[0;1m
View a class.
!WEnter the name of the class you want to view (? for a list): !)[0m} T View class, enter name


VIEWC1 {[0;1;32m
!FÄ
Class name:  [37m%s[32m

} T View class, Line 1


VIEWC2 {!WIf users don't login for [37m%d %s[32m, they will be moved to class [37m%s[32m.!)
} T View class, Line 2


DAYSNG {day} T Day singular
DAYPLR {days} T Day plural


VIEWC3 {!WAfter [37m%d %s[32m, users will be moved to class [37m%s[32m.!)
} T View class, Line 3


VIEWC4A {!WUsers without credits will be moved to class [37m%s[32m.!)
} T View class, Line 4A


VIEWC4C {!WUsers obtaining paid credits will be moved to class [37m%s[32m.!)
} T View class, Line 4C


VIEWC5 {
!WPer-session time limit:         [37m%5d %s[32m.!)
} T View class, Line 5


VIEWC6 {!WDaily online time limit:        [37m%5d %s[32m.!)
} T View class, Line 6


VIEWC7 {!WFree daily top-up credits:      [37m%5d %s[32m.!)
} T View class, Line 7


VIEWC7A {!WFree weekly credits:            [37m%5d %s[32m.!)
} T View class, Line 7A


VIEWC7B {!WFree monthly credits:           [37m%5d %s[32m.!)
} T View class, Line 7B


MINSNG {minute} T Minute singular
MINPLR {minutes} T Minute plural


CRDSNG {credit} T credit singular
CRDPLR {credits} T credit plural


VIEWC8 {
!WUsers are exempt from credit charges.!)
} T View class, Line 8


VIEWC9 {
!W(Reserved flag is set)!)
} T View class, Line 9


VIEWC10 {
!WUsers of this class are locked out of the BBS.!)
} T View class, Line 10.


VIEWC11 {
!WUsers are allowed to transfer credits to others.!)
} T View class, Line 11.


VIEWKY {
Keys: !i!W} T View Class, keys

VIEWKY1 {%d } T Single key

VIEWKY2 {%d-%d } T Key range

VIEWKYE {!)
!0l} T Key list end

VIEWKY0 {[none]!)
!0l} T Key list end, no keys


VIEWCEND {[32m!FÄ
[0m} T View class, end


MOVSRC {[0;1m
Mass-move users from one class to another.
!WEnter the name of the class to move from (? for a list): !)[0m} T Move class, enter source name


MOVTRG {[0;1m
!WEnter the name of the new class for these users (? for a list): !)[0m} T Move class, enter target name


NSAMCLS {[0;1;31m
!JHey, you've just given the same class name twice! If you really
want to move users from one class to another, it'd help to have
two different class names!!)
[0;1m} T Move class, class names must differ


MOVING {[0;1;32m
Moving users from class [37m%s[32m to class [37m%s[32m.

Please wait.} T Moving users from one class to another


MOVOK {[0;1;32m

The mass move was successful. I've moved [37m%d[32m user(s).
[0;1m} T Move operation successful


DEFSTR {[0;1m[Enter=%s] [0m} T Default string value


DEFINT {[0;1m[Enter=%d] [0m} T Default integer value


DEFCHR {[0;1m[Enter=%c] [0m} T Default character value


EDTCNAME {[0;1m
Update/edit a class.
!WEnter the class to edit (? for a list): !)[0m} T Edit class, enter name

IOERROR {[0;1;5;31m
CAUTION: !i!J[0;1;31mThe class file could not be written due to
an I/O error. This is an serious error! Please correct it as soon
as possible, otherwise some or all users may not be able to login.[0m!)
} T IO Error while writing class file

QUITWRN {[0;1;31m
!WYou have requested to leave the class editor and lose all changes
you have made to the classes!!)

!W[31mAre you sure? ([33mY[31m/[33mN[31m); !)[0m} T Confirm quit




LANGEND {}

