LEVEL2 {}


ENTRYKEY {Key required to enter the Registry? 0} N 0 129


SYSKEY {Key required for privileged access to the Registry? 128} N 0 129


CRKEY {Key required to create a registry? 2} N 0 129


T1F1 {Template #1: Length of field #1: 35} N 0 255
T1F2 {Template #1: Length of field #2: 1} N 0 255
T1F3 {Template #1: Length of field #3: 2} N 0 255
T1F4 {Template #1: Length of field #4: 35} N 0 255
T1F5 {Template #1: Length of field #5: 35} N 0 255
T1F6 {Template #1: Length of field #6: 35} N 0 255
T1F7 {Template #1: Length of field #7: 15} N 0 255
T1F8 {Template #1: Length of field #8: 35} N 0 255
T1F9 {Template #1: Length of field #9: 35} N 0 255
T1F10 {Template #1: Length of field #10: 35} N 0 255
T1F11 {Template #1: Length of field #11: 35} N 0 255
T1F12 {Template #1: Length of field #12: 35} N 0 255
T1F13 {Template #1: Length of field #13: 35} N 0 255
T1F14 {Template #1: Length of field #14: 35} N 0 255
T1F15 {Template #1: Length of field #15: 35} N 0 255
T1F16 {Template #1: Length of field #16: 35} N 0 255
T1F17 {Template #1: Length of field #17: 35} N 0 255
T1F18 {Template #1: Length of field #18: 40} N 0 255
T1F19 {Template #1: Length of field #19: 40} N 0 255
T1F20 {Template #1: Length of field #20: 0} N 0 255
T1F21 {Template #1: Length of field #21: 0} N 0 255
T1F22 {Template #1: Length of field #22: 0} N 0 255
T1F23 {Template #1: Length of field #23: 0} N 0 255
T1F24 {Template #1: Length of field #24: 0} N 0 255
T1F25 {Template #1: Length of field #25: 0} N 0 255
T1F26 {Template #1: Length of field #26: 0} N 0 255
T1F27 {Template #1: Length of field #27: 0} N 0 255
T1F28 {Template #1: Length of field #28: 0} N 0 255
T1F29 {Template #1: Length of field #29: 0} N 0 255
T1F30 {Template #1: Length of field #30: 0} N 0 255


T2F1 {Template #2: Length of field #1: 40} N 0 255
T2F2 {Template #2: Length of field #2: 17} N 0 255
T2F3 {Template #2: Length of field #3: 40} N 0 255
T2F4 {Template #2: Length of field #4: 40} N 0 255
T2F5 {Template #2: Length of field #5: 40} N 0 255
T2F6 {Template #2: Length of field #6: 40} N 0 255
T2F7 {Template #2: Length of field #7: 40} N 0 255
T2F8 {Template #2: Length of field #8: 40} N 0 255
T2F9 {Template #2: Length of field #9: 40} N 0 255
T2F10 {Template #2: Length of field #10: 40} N 0 255
T2F11 {Template #2: Length of field #11: 40} N 0 255
T2F12 {Template #2: Length of field #12: 40} N 0 255
T2F13 {Template #2: Length of field #13: 40} N 0 255
T2F14 {Template #2: Length of field #14: 40} N 0 255
T2F15 {Template #2: Length of field #15: 40} N 0 255
T2F16 {Template #2: Length of field #16: 40} N 0 255
T2F17 {Template #2: Length of field #17: 40} N 0 255
T2F18 {Template #2: Length of field #18: 0} N 0 255
T2F19 {Template #2: Length of field #19: 0} N 0 255
T2F20 {Template #2: Length of field #20: 0} N 0 255
T2F21 {Template #2: Length of field #21: 0} N 0 255
T2F22 {Template #2: Length of field #22: 0} N 0 255
T2F23 {Template #2: Length of field #23: 0} N 0 255
T2F24 {Template #2: Length of field #24: 0} N 0 255
T2F25 {Template #2: Length of field #25: 0} N 0 255
T2F26 {Template #2: Length of field #26: 0} N 0 255
T2F27 {Template #2: Length of field #27: 0} N 0 255
T2F28 {Template #2: Length of field #28: 0} N 0 255
T2F29 {Template #2: Length of field #29: 0} N 0 255
T2F30 {Template #2: Length of field #30: 0} N 0 255


T3F1 {Template #3: Length of field #1: 59} N 0 255
T3F2 {Template #3: Length of field #2: 59} N 0 255
T3F3 {Template #3: Length of field #3: 59} N 0 255
T3F4 {Template #3: Length of field #4: 59} N 0 255
T3F5 {Template #3: Length of field #5: 59} N 0 255
T3F6 {Template #3: Length of field #6: 59} N 0 255
T3F7 {Template #3: Length of field #7: 59} N 0 255
T3F8 {Template #3: Length of field #8: 59} N 0 255
T3F9 {Template #3: Length of field #9: 59} N 0 255
T3F10 {Template #3: Length of field #10: 59} N 0 255
T3F11 {Template #3: Length of field #11: 59} N 0 255
T3F12 {Template #3: Length of field #12: 59} N 0 255
T3F13 {Template #3: Length of field #13: 59} N 0 255
T3F14 {Template #3: Length of field #14: 59} N 0 255
T3F15 {Template #3: Length of field #15: 59} N 0 255
T3F16 {Template #3: Length of field #16: 0} N 0 255
T3F17 {Template #3: Length of field #17: 0} N 0 255
T3F18 {Template #3: Length of field #18: 0} N 0 255
T3F19 {Template #3: Length of field #19: 0} N 0 255
T3F20 {Template #3: Length of field #20: 0} N 0 255
T3F21 {Template #3: Length of field #21: 0} N 0 255
T3F22 {Template #3: Length of field #22: 0} N 0 255
T3F23 {Template #3: Length of field #23: 0} N 0 255
T3F24 {Template #3: Length of field #24: 0} N 0 255
T3F25 {Template #3: Length of field #25: 0} N 0 255
T3F26 {Template #3: Length of field #26: 0} N 0 255
T3F27 {Template #3: Length of field #27: 0} N 0 255
T3F28 {Template #3: Length of field #28: 0} N 0 255
T3F29 {Template #3: Length of field #29: 0} N 0 255
T3F30 {Template #3: Length of field #30: 0} N 0 255



LEVEL3 {}


REGPLS {[0;1;32m

!Jƒœ¤ â®œ«œ ˜¡æ£˜ ©¬£§¢¨é©œ  «˜ ©«¦ ®œå˜ ©˜ª. ƒé©«œ
[33mR[32m ("Registry") ˜§æ «¦ ¡œ¤«¨ ¡æ £œ¤¦ç ã [33m/go registry[32m š ˜
¤˜ «˜ ›é©œ«œ.!)

[0;1m} T Registry login notice to users who aren't in Registry


REGHELP {[0;1;32m
!Jƒé©«œ [33m/r ¯œ¬›é¤¬£¦[32m š ˜ ¤˜ ›œå«œ «˜ ©«¦ ®œå˜ ¡á§¦ ¦¬ ®¨ã©«.
‚ ˜ §˜¨á›œ š£˜, £œ «¤ œ¤«¦¢ã [33m/r sysop[32m £§¦¨œå«œ ¤˜ ›œå«œ «˜
©«¦ ®œå˜ «¦¬ ¯œ¬›à¤ç£¦¬ Sysop.!)
[0;1m} T Registry help


REGERR {[0;1;31m
ƒœ¤ ¬§á¨®¦¬¤ ©«¦ ®œå˜ š ˜ ˜¬«æ «¦ ¯œ¬›é¤¬£¦.
[0;1m} T Registry error, unknown user



NOENTRY {[0;1;31m
Š¬§á£˜ , ›œ¤ â®œ«œ §¨æ©™˜© ©œ ˜¬«ã «¤ §œ¨ ¦®ã.
} T Access to the Registry denied


REGMNU {[2J[0m[47;1;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;30;47m¿ [40m
[47;1;37m ³  [0;47;30m                  ‰˜«á¢¦š¦ª •¨©«é¤                    [0;47;30m³ [40m
[47;1;37m ³  [0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ  [0;47;30m³ [40m
[47;1;37m ³  [0;31;47mA[30mbout the registry . . . . . . .  ‚œ¤ ¡âª ¢¨¦­¦¨åœª  [30m³ [40m
[47;1;37m ³  [0;31;47mD[30mirectory . . . . . . . . ‰˜«á¢¦š¦ª ©«¦ ®œåà¤ ®¨©«é¤  [30m³ [40m
[47;1;37m ³  [0;31;47mL[30mook up  . . . . . . . ƒœå«œ «˜ ©«¦ ®œå˜ á¢¢¦¬ ®¨ã©«  [30m³ [40m
[47;1;37m ³  [0;31;47mS[30mcan registry . . . . . . . „¨œ¬¤˜ š ˜ ¢â¥œ ª ¡¢œ › á  [30m³ [40m
[47;1;37m ³  [0;31;47mY[30mour entry  . . . . . . . . . .  ’˜ › ¡á ©˜ª ©«¦ ®œå˜  [30m³ [40m
[47;1;37m ³  [0;31;47mC[30mhange template  . . . . .  €¢¢˜šã £¦¨­ãª ¡˜«˜®é¨©ª  [30m³ [40m
[47;1;37m ³                                                         [0;47;30m³ [40m
[47;1;37m ³ [0;30;47me[31mX[30mit  . . . . . . . . . . . . . . . . . . . . . „¥¦›¦ª  [30m³ [40m
[47;1;37m À[0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0;1m
} T Registry main menu


VSHMENU {[0;1m
‰˜«á¢¦š¦ª •¨©«é¤
˜¨˜¡˜¢é ›é©«œ «¤ œ§ ¢¦šã ©˜ª: [0m} T Registry menu, very short prompt


SHMENU {[0;1m
‰˜«á¢¦š¦ª •¨©«é¤
!Wƒé©«œ «¤ œ§ ¢¦šã ©˜ª ([33mA[37m,[33mD[37m,[33mL[37m,[33mS[37m,[33mY[37m,[33mC[37m,[33mX[37m š ˜ â¥¦›¦, ã [33m?[37m š ˜ «¦ £œ¤¦ç): !)[0m} T Registry short menu


REGSMNU {[2J[0m[47;1;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;30;47m¿ [40m
[47;1;37m ³  [0;47;30m               ‡œä¡æª ‰˜«á¢¦š¦ª •¨©«é¤                [0;47;30m³ [40m
[47;1;37m ³  [0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ  [0;47;30m³ [40m
[47;1;37m ³  [0;31;47mA[30mbout the registry . . . . . . .  ‚œ¤ ¡âª ¢¨¦­¦¨åœª  [30m³ [40m
[47;1;37m ³  [0;31;47mD[30mirectory . . . . . . . . ‰˜«á¢¦š¦ª ©«¦ ®œåà¤ ®¨©«é¤  [30m³ [40m
[47;1;37m ³  [0;31;47mE[30mdit registry . . . . . €¢¢˜šã ©«¦ ®œåà¤ á¢¢¦¬ ®¨ã©«  [30m³ [40m
[47;1;37m ³  [0;31;47mL[30mook up . . . . . . .  ƒœå«œ «˜ ©«¦ ®œå˜ á¢¢¦¬ ®¨ã©«  [30m³ [40m
[47;1;37m ³  [0;31;47mS[30mcan registry . . . . . . . „¨œ¬¤˜ š ˜ ¢â¥œ ª ¡¢œ › á  [30m³ [40m
[47;1;37m ³  [0;31;47mY[30mour entry . . . . . . . . . . . ’˜ › ¡á ©˜ª ©«¦ ®œå˜  [30m³ [40m
[47;1;37m ³  [0;31;47mC[30mhange template  . . . . .  €¢¢˜šã £¦¨­ãª ¡˜«˜®é¨©ª  [30m³ [40m
[47;1;37m ³                                                         [0;47;30m³ [40m
[47;1;37m ³ [0;30;47me[31mX[30mit  . . . . . . . . . . . . . . . . . . . . . „¥¦›¦ª  [30m³ [40m
[47;1;37m À[0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0;1m
} T Registry main menu for sysops


SHSMENU {[0;1m
‰˜«á¢¦š¦ª •¨©«é¤
!Wƒé©«œ «¤ œ§ ¢¦šã ©˜ª ([33mA[37m,[33mD[37m,[33mE[37m,[33mL[37m,[33mS[37m,[33mY[37m,[33mC[37m,[33mX[37m š ˜ â¥¦›¦, ã [33m?[37m š ˜ «¦ £œ¤¦ç): !)[0m} T Registry short menu for sysops


ERRSEL {[0;1;31m
Š¬§á£˜ , ›œ¤ ¬§á¨®œ  œ§ ¢¦šã "%c".
[0;1m} T Wrong selection from the main registry menu


LEAVE {[0;1m
„¥¦›¦ª ˜§æ «¦¤ ‰˜«á¢¦š¦ •¨©«é¤...
} T Leaving the registry


ABOUT {[0;1m

!J ‰˜«á¢¦š¦ª •¨©«é¤ (Registry) ©˜ª ™¦Ÿá ¤˜ š¤à¨å©œ«œ ˜¢¢¦¬ª ®¨ã©«œª ©œ
˜¬«æ «¦ ©ç©«£˜, ¡˜  ¤˜ §œ¨ š¨á¯œ«œ «¦¤ œ˜¬«æ ©˜ª, é©«œ ¦  á¢¢¦  ¤˜ š¤à¨å©¦¬¤
œ©áª.!)

!J’˜ ©«¦ ®œå˜ §¦¬ ›å¤œ«œ œ›é (œ¤' ˜¤« Ÿâ©œ  £œ ˜¬«á §¦¬ ©˜ª «ãŸ¡˜¤ æ«˜¤
§¨à«¦£§ã¡˜«œ) œå¤˜  [5mƒˆ€‡„‘ˆ‹€ ‘’ ‰ˆŒ[0;1m. „á¤ ›œ¤ Ÿâ¢œ«œ ¤˜
˜§˜¤«ã©œ«œ ©œ ¡á§¦ ˜ œ¨é«© ›é©«œ "® ", "‰œ¤æ", ã ¢â¥œ ª £œ «¦ å› ¦ ¤æ£˜.
„§å©ª, œ¤' ˜¤« Ÿâ©œ  £œ «˜ ©«¦ ®œå˜ «¦¬ ¢¦š˜¨ ˜©£¦ç ©˜ª, «˜ ©«¦ ®œå˜ «¦¬
‰˜«˜¢æš¦¬ ›œ¤ ®¨œ áœ«˜  ¤˜ œå¤˜  ˜¢Ÿ ¤á ã ˜¡¨ ™ã.!)

!J€­¦ç â®œ«œ «œ¢œ é©œ  «¤ œ ©˜šàšã ©«¦ ®œåà¤, â®œ«œ «¤ ›¬¤˜«æ««˜ ¤˜ «˜
˜¢¢áœ«œ æ§¦«œ Ÿâ¢œ«œ. ‹§¦¨œå«œ œ¢œçŸœ¨˜ ¤˜ › ¦¨Ÿé¤œ«œ «˜ ©«¦ ®œå˜ ©˜ª §¦¬
â®¦¬¤ ˜¢¢á¥œ .!)

!J‚ ˜ ¤˜ ›œå«œ â¤˜ §œ¨ ¢§« ¡æ ¡˜«á¢¦š¦ «à¤ ©«¦ ®œåà¤ «à¤ á¢¢à¤ ®¨©«é¤,
›é©«œ [33mDA[37m. ‚ ˜ ¤˜ ©¬£§¢¨é©œ«œ/˜¢¢á¥œ«œ «˜ › ¡á ©˜ª ©«¦ ®œå˜, ›é©«œ
[33mY[37m. “§á¨®¦¬¤ «¨œ ª › ˜­¦¨œ« ¡âª £¦¨­âª ¡˜«˜®é¨©ª ©«¦¤ ‰˜«á¢¦š¦,
¡˜  £§¦¨œå«œ ¤˜ › ˜¢â¥œ«œ ¦§¦ ˜›ã§¦«œ ©˜ª ˜¨â©œ  ˜¤á §á©˜ ©« š£ã. ‘£œ é©«œ,
æ£àª, æ«  ˜¢¢á¦¤«˜ª ˜§æ £å˜ £¦¨­ã ©œ £å˜ á¢¢, «˜ ©«¦ ®œå˜ ©˜ª ®á¤¦¤«˜  ˜§æ
«¦¤ ¡˜«á¢¦š¦ £â®¨  ¤˜ «˜ ¥˜¤˜©¬£§¢¨é©œ«œ.   «¨œ ª £¦¨­âª œå¤˜  ¦  œ¥ãª:
œ¨˜© «œ®¤ ¡ã (§¨¦©à§ ¡ã), œ§˜ššœ¢£˜« ¡ã, ¡˜  šœ¤ ¡ãª ®¨ã©ª (®à¨åª ¦¤æ£˜«˜
§œ›åà¤). ƒé©«œ [33mC[37m š ˜ ¤˜ ˜¢¢á¥œ«œ «¤ £¦¨­ã «ª ¡˜«˜®é¨©ãª ©˜ª.!)

} T About the registry


DINTRO {[0;1m
!J€¬«ã  œ§ ¢¦šã ©˜ª œ§ «¨â§œ  ¤˜ ›œå«œ â¤˜¤ ¡˜«á¢¦š¦ «à¤ ©«¦ ®œåà¤ «à¤
®¨©«é¤. ‹§¦¨œå«œ ¤˜ › ˜¢â¥œ«œ ˜§æ §¦ æ š¨á££˜ Ÿâ¢œ«œ ¤˜ ˜¨®å©œ   œ£­á¤ ©
›å¤¦¤«˜ª ˜§¢éª «¦ š¨á££˜ «ª [5m€šš¢ ¡ãª[0;1m ˜¢­˜™ã«¦¬.!)

[5;33mÛÛ[0;1;33m  !J!i‹æ¤¦ ¦  ®¨ã©«œª §¦¬ â®¦¬¤ ©¬£§¢¨é©œ  «˜
©«¦ ®œå˜ «¦¬ª Ÿ˜ œ£­˜¤ ©«¦ç¤.!)!0l

!J˜«ã©«œ [33mEnter[37m ã [33mCtrl-C[37m ¡˜«á « › á¨¡œ ˜ «ª œ£­á¤ ©ª
š ˜ ¤˜ ©«˜£˜«ã©œ«œ.!)
[0;1m} T Registry directory, information


DLETTER {[0;1m
!Wƒé©«œ «¦ š¨á££˜ ˜§æ «¦ ¦§¦å¦ Ÿ˜ ˜¨®å©œ  ¦ ¡˜«á¢¦š¦ª
([33mA[37m-[33mZ[37m, [33m?[37m š ˜ ™¦ãŸœ ˜, ã [33mEnter[37m š ˜ ˜¡ç¨à©):!) [0m} T Registry directory, asking where to start


DIRERR {[0;1;31m
!W¨â§œ  ¤˜ ›é©œ«œ â¤˜ š¨á££˜ «ª [37m€šš¢ ¡ãª[31m ˜¢­˜™ã«¦¬ ã
[33mEnter[31m š ˜ â¥¦›¦.!)
[0;1m} T Registry directory, invalid starting letter


DIRHDR {[0;1;32m
 â©«œ [33mEnter[32m ã [33mCtrl-C[32m ¡˜«á «¤ œ£­á¤ © š ˜ ¤˜ ©«˜£˜«ã©œ«œ.

[37m•¨ã©«ª                                           œ¨ š¨˜­ã
-----------------------------------------------------------
} T Registry directory header


DIRLIN {[0;1;32m%-17s  !0v%40s!1v
} T Registry directory line


DIRFTR {[0;1m-----------------------------------------------------------

} T Registry directory footer


DIRCAN {[0;1;33m
’œ¨£˜« ©£æª › ˜› ¡˜©å˜ª.
[0;1m} T Registry directory terminated


SINTRO {[0;1m
!J€¬«ã  œ§ ¢¦šã ©˜ª œ§ «¨â§œ  ¤˜ ¯á¥œ«œ « ª ¡˜«˜®à¨ã©œ ª
«¦¬ ‰˜«˜¢æš¦¬ •¨©«é¤ š ˜ ¡á§¦¦ œª ¢â¥œ ª ¡¢œ › á. ‹§¦¨œå«œ ¤˜ › ˜¢â¥œ«œ
˜§æ §¦ æ š¨á££˜ Ÿâ¢œ«œ ¤˜ ˜¨®å©œ   â¨œ¬¤˜ ›å¤¦¤«˜ª ˜§¢éª «¦ š¨á££˜ «ª
[5m€šš¢ ¡ãª[0;1m ˜¢­˜™ã«¦¬.!)
[0;1m} T Directory scan, information


SLETTER {[0;1m
!Wƒé©«œ «¦ š¨á££˜ ˜§æ «¦ ¦§¦å¦ Ÿ˜ ˜¨®å©œ  ¦ ¡˜«á¢¦š¦ª
([33mA[37m-[33mZ[37m, ã [33mEnter[37m š ˜ ˜¡ç¨à©):!) [0m} T Directory scan, asking where to start


SCANKW {[0;1m

!J’é¨˜ ›é©«œ « ª ¢â¥œ ª ¡¢œ › á š ˜ « ª ¦§¦åœª Ÿâ¢œ«œ ¤˜ ¯á¥œ«œ.
  ¢â¥œ ª ¡¢œ › á §¨â§œ  ¤˜ ®à¨å¦¤«˜  £œ ¡œ¤æ › á©«£˜. † â¨œ¬¤˜ šå¤œ«˜ 
­à¤« ¡á, š ˜ ˜¬¥£â¤ ˜§¦«œ¢œ©£˜« ¡æ««˜.!)

!J˜¨á›œ š£˜: ƒå¤¦¤«˜ª [33mPascal BBS[37m, Ÿ˜ œ£­˜¤ ©«¦ç¤ ¦ 
¡˜«˜®à¨ã©œ ª §¦¬ §œ¨ â®¦¬¤ « ª ¢â¥œ ª Pascal ã BBS, ˜¢¢á ¡˜  "pascal" ã
"bbs", ã ˜¡æ£˜ ¡˜  "§˜©¡á¢".!)

!J˜«ã©«œ [33mEnter[37m ã [33mCtrl-C[37m ¡˜«á « › á¨¡œ ˜ «ª œ£­á¤ ©ª
š ˜ ¤˜ ©«˜£˜«ã©œ«œ.!)
[0;1m} T Directory scan, keyword information


GETKEYW {[0;1m
!Wƒé©«œ « ª ¢â¥œ ª ¡¢œ › á, [33m?[37m š ˜ ™¦ãŸœ ˜, ã [33mX[37m š ˜ â¥¦›¦: !)[0m} T Directory scan, asking for keywords


LKUPWHO {[0;1m
!Wƒé©«œ ¯œ¬›é¤¬£¦ ®¨ã©« ã [33mX[37m š ˜ â¥¦›¦:!) [0m} T Enter User-ID to look up


UIDERR {[0;1;31m
ƒœ¤ ¬§á¨®¦¬¤ ©«¦ ®œå˜ š ˜ ˜¬«æ «¦ ¯œ¬›é¤¬£¦.
[0;1m} T Unregistered User-ID


T1LOOKUP {[0;1;44m
[K!C‰˜«˜®é¨© «¦¬ £â¢¦¬ª %s[0;1m
!)
[32m¢ã¨œª æ¤¦£˜ . . . . . . . . [37m%s
[32m”ç¢¦  . . . . . . . . . . .  [37m%s
[32m†¢ ¡å˜ . . . . . . . . . . . [37m%s
[32m„§áššœ¢£˜ . . . . . . . . .  [37m%s
[32m¤¦£˜ „«˜ ¨å˜ª . . . . . . . [37m%s
[32mæ¢/œ¨ ¦®ã  . . . . . . .  [37m%s
[32m’¢â­à¤¦ . . . . . . . . . . [37m%s
[32m’ç§¦ª ¬§¦¢¦š ©«ã  . . . . .  [37m%s
[32m ¡¦šœ¤œ ˜¡ã ‰˜«á©«˜© . . . [37m%s
[32mâ¤œª š¢é©©œª . . . . . . .  [37m%s
[32m€š˜§£â¤ «˜ ¤å˜ . . . . . . [37m%s
[32m€š˜§£â¤ £¦¬© ¡ã . . . . .  [37m%s
[32m€š˜§£â¤¦ ™ ™¢å¦ . . . . . . [37m%s
[32m€š˜§£â¤¦ áŸ¢£˜  . . . . .  [37m%s
[32m€¢¢˜ œ¤› ˜­â¨¦¤«˜/Hobby  . . [37m%s
[32m‚œ¤ ¡âª §¢¨¦­¦¨åœª 1 . . .  [37m%s
[32m‚œ¤ ¡âª §¢¨¦­¦¨åœª 2  . . . [37m%s
[32mEmail › œçŸ¬¤© 1  . . . . . [37m%s
[32mEmail 2 ã Home Page . . . .  [37m%s
[32mœ¨å¢¯ . . . . . . . . . . [37m%s
[0;1m} T Registry lookup, template 1


T2LOOKUP {[0;1;44m
[K!C‰˜«˜®é¨© «¦¬ £â¢¦¬ª %s[0;1m
!)
[32m¤¦£˜«œ§é¤¬£¦ . . . . . . . . .  [37m%s
[32m”ç¢¦ ¡˜ /ã ¢ ¡å˜  . . . . . . . [37m%s
[32m¤¦£˜ œ«˜ ¨å˜ª  . . . . . . . .  [37m%s
[32m„§áššœ¢£˜/‡â© . . . . . . . . . [37m%s
[32m˜¨œ®æ£œ¤ ¬§¨œ©å˜ . . . . . .  [37m%s
[32mƒ œçŸ¬¤© (›æª ¡˜  ˜¨ Ÿ£æª) . . [37m%s
[32mTK/æ¢/œ¨ ¦®ã/„›¨˜  . . . . .  [37m%s
[32m’¢â­à¤˜ (voice) . . . . . . . . [37m%s
[32m’¢â­à¤˜ (data) . . . . . . . .  [37m%s
[32m’¢â­à¤˜ (fax) . . . . . . . . . [37m%s
[32mEmail › œçŸ¬¤© 1 . . . . . . .  [37m%s
[32mEmail › œçŸ¬¤© 2 ã WWW Page . . [37m%s
[32m‚œ¤ ¡âª §¢¨¦­¦¨åœª . . . . . .  [37m%s
                                 %s
                                 %s
                                 %s
                                 %s
[32mœ¨å¢¯ . . . . . . . . . . . . [37m%s
[0;1m} T Registry lookup, template 2


T3LOOKUP {[0;1;44m
[K!C‰˜«˜®é¨© «¦¬ £â¢¦¬ª %s[0;1m

%-60s
%-60s
%-60s
%-60s
%-60s
%-60s
%-60s
%-60s
%-60s
%-60s
%-60s
%-60s
%-60s
%-60s
%-60s

[32mœ¨å¢¯ . . . . .  [37m%-40s
!)[0;1m} T Registry lookup, template 3


EDITWHO {[0;1m
!Wƒé©«œ ¯œ¬›é¤¬£¦ ®¨ã©« ã [33mX[37m š ˜ â¥¦›¦:!) [0m} T Enter User-ID of registry to edit


EDITERR {[0;1;31m
€¬«æ «¦ ¯œ¬›é¤¬£¦ ›œ¤ ¬§á¨®œ  ©«¤ ™á©.
[0;1m} T Edit registry, unregistered User-ID


EDITNAX {[0;1;31m
!JŠ¬§á£˜ , ˜¢¢á «¦ œ§å§œ›¦ §¨æ©™˜©ãª ©˜ª ›œ¤ ©˜ª œ§ «¨â§œ 
¤˜ ©¬£§¢¨é©œ«œ ã ¤˜ œ¤£œ¨é©œ«œ «˜ ©«¦ ®œå˜ ©˜ª ˜¬«ã
«¤ ©« š£ã...!)
[0;1m} T Edit registry, no access to your registry


EDITOK {[0;1;32m
!J’˜ ©«¦ ®œå˜ ©˜ª â®¦¬¤ ˜§¦Ÿ¡œ¬«œå. „¬®˜¨ ©«¦ç£œ š ˜ «¤ ©¬££œ«¦®ã ©˜ª.!)
[0;1m
} T Registry stored ok


EDITCAN {[0;1;33m
!J  ˜¢¢˜šâª ˜¡¬¨éŸ¡˜¤.!)
[0;1m
} T Registry update cancelled


CHINFO {[0;1m
!J‹œ ˜¬«ã «¤ œ§ ¢¦šã £§¦¨œå«œ ¤˜ ˜¢¢á¥œ«œ «¤ £¦¨­ã «ª ¡˜«˜®é¨©ãª ©˜ª.
“§á¨®¦¬¤ «¨œ ª §¨¦¡˜Ÿ¦¨ ©£â¤œª £¦¨­âª š ˜ ¤˜ › ˜¢â¥œ«œ:!)

!W[33m1[37m. „¨˜©!i «œ®¤ ¡ã, §¨¦©à§ ¡ã ¡˜«˜®é¨©: ¤¦£˜«œ§é¤¬£¦, ­ç¢¦,
¢ ¡å˜, œ§áššœ¢£˜, æ¤¦£˜ œ«˜ ¨å˜ª, §æ¢/§œ¨ ¦®ã, «¢â­à¤¦, «ç§¦ª ¬§¦¢¦š ©«ã,
¦ ¡¦šœ¤œ ˜¡ã ¡˜«á©«˜©, ¥â¤œª š¢é©©œª, ˜š˜§£â¤ «˜ ¤å˜, £¦¬© ¡ã, ™ ™¢å¦,
áŸ¢£˜, hobby, ›ç¦ š¨˜££âª §¢¨¦­¦¨ é¤. ’˜ §œ¨ ©©æ«œ¨˜ §œ›å˜ œå¤˜  «à¤ 35
®˜¨˜¡«ã¨à¤.!)
!0l
!W[33m2[37m. „§˜š!išœ¢£˜« ¡ã ¡˜«˜®é¨©: ¤¦£˜«œ§é¤¬£¦, ­ç¢¦/¢ ¡å˜,
æ¤¦£˜ œ«˜¨å˜ª, œ§áššœ¢£˜/Ÿâ©, §˜¨œ®æ£œ¤ ¬§¨œ©å˜, › œçŸ¬¤©, «¢â­à¤˜
(voice, data ¡˜  fax), ›ç¦ email › œ¬Ÿç¤©œ ª, §â¤«œ š¨˜££âª šœ¤ ¡é¤
§¢¨¦­¦¨ é¤. ’˜ §œ¨ ©©æ«œ¨˜ §œ›å˜ œå¤˜  «à¤ 48 ®˜¨˜¡«ã¨à¤!)
!0l
!W[33m3[37m. ‚œ¤ !i¡ãª ®¨ã©ª ¡˜«˜®é¨©: 15 ˜¤é¤¬£˜ §œ›å˜ «à¤ 59
®˜¨˜¡«ã¨à¤.!)
!0l

!W[0;1;31;5mÛÛ[0;1;31m  ‘•†: !i€¢¢á¦¤«˜ª £¦¨­ã ¡˜«˜®é¨©ª, «˜
«¨â®¦¤«˜ §œ¨ œ®æ£œ¤˜ «ª ¡˜«˜®é¨©ãª ©˜ª [37m®á¤¦¤«˜ [31m ˜¤œ§ ©«¨œ§«å.!)
!0l
[0;1m} T Changing template, information


CHANGE {[0;1m
¦ ˜ Ÿâ¢œ«œ ¤˜ œå¤˜   ¤â˜ £¦¨­ã «ª ¡˜«˜®é¨©ãª ©˜ª;

[33m1[37m . . . . „¨˜© «œ®¤ ¡ã/¨¦©à§ ¡ã ¡˜«˜®é¨©
[33m2[37m  . . . . . . . . „§˜ššœ¢£˜« ¡ã ¡˜«˜®é¨©
[33m3[37m . . . . . . . . ‚œ¤ ¡ãª ®¨ã©ª ¡˜«˜®é¨©

!Wƒé©«œ «¤ œ§ ¢¦šã ©˜ª ([33m1[37m,[33m2[37m,[33m3[37m,[33m?[37m š ˜ ™¦ãŸœ ˜, ã X š ˜ â¥¦›¦):!) [0m} T Changing template


CHERR {[0;1;31m
Š¬§á£˜ ,  œ§ ¢¦šã "%c" ›œ¤ œå¤˜  ›¬¤˜«ã.
[0;1m} T Changing template, invalid option


REGCR {[0;1;33m
!J—ª «é¨˜ ›œ¤ œå®˜«œ ¡˜«˜®é¨©. ‘˜ª ›£ ¦¬¨šé £å˜ ¡œ¤ã ¡˜«˜®é¨©
£œ «¤ £¦¨­ã §¦¬ «ã©˜«œ...!)
[0;1m} T Creating registry and setting preferred template


NOCHANGE {[0;1;32m
!J† £¦¨­ã «ª ¡˜«˜®é¨©ãª ©˜ª ›œ¤ á¢¢˜¥œ.
’˜ §œ¨ œ®æ£œ¤˜ «ª ¡˜«˜®é¨©ãª ©˜ª §˜¨˜£â¤¦¬¤ àª â®¦¬¤.!)
[0;1m} T No change in the template


NONCHANGE {[0;1;32m
!J† £¦¨­ã «ª ¡˜«˜®é¨©ãª ã«˜¤ ã› ˜¬«ã §¦¬ œ§ ¢â¥˜«œ,
¡  â«©  ›œ¤ ®¨œ á©«¡œ ¤˜ ˜¢¢á¥œ . ’˜ §œ¨ œ®æ£œ¤˜ «ª
¡˜«˜®é¨©ãª ©˜ª §˜¨˜£â¤¦¬¤ àª â®¦¬¤.!)
[0;1m} T No template change needed


TMPLCH {[0;1;32m
!J† £¦¨­ã «ª ¡˜«˜®é¨©ãª ©˜ª á¢¢˜¥œ. ’˜ §œ¨ œ®æ£œ¤˜ «ª
(£œ œ¥˜å¨œ© «¤ §œ¨å¢¯) â®¦¬¤ › ˜š¨˜­œå.!)
[0;1m} T Template changed, registry erased


T1VISUAL {[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [34m‰˜«˜®é¨© ‹â¢¦¬ª[0;30;47m ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³  ¢ã¨œª æ¤¦£˜ . . . . . . . . . . [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  ”ç¢¦  . . . . . . . . . . . . .  [1;44;37m@1;1;0s[0;47;30m        †¢ ¡å˜ . . . . . . .  [1;44;37m@2;2;0s[0;1;47;37m  ³ [0m
[30;47m ³  „§áššœ¢£˜ . . . . . . . . . . .  [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  ¤¦£˜ œ«˜ ¨å˜ª . . . . . . . . . [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  æ¢/œ¨ ¦®ã  . . . . . . . . .  [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  ’¢â­à¤¦ . . . . . . . . . . . . [1;44;37m@15;15;0s[0;1;47;37m                      ³ [0m
[30;47m ³  ’ç§¦ª ¬§¦¢¦š ©«ã  . . . . . . .  [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³   ¡¦šœ¤œ ˜¡ã ¡˜«á©«˜© . . . . . [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  â¤œª š¢é©©œª . . . . . . . . .  [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  €š˜§£â¤ «˜ ¤å˜ . . . . . . . . [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  €š˜§£â¤ £¦¬© ¡ã . . . . . . .  [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  €š˜§£â¤¦ ™ ™¢å¦ . . . . . . . . [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  €š˜§£â¤¦ áŸ¢£˜  . . . . . . .  [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  €¢¢˜ œ¤› ˜­â¨¦¤«˜/hobby  . . . . [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  ‚œ¤ ¡âª §¢¨¦­¦¨åœª (1/2) . . .  [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  ‚œ¤ ¡âª §¢¨¦­¦¨åœª (2/2)  . . . [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Email › œçŸ¬¤© 1 . . . . . . .  [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Email 2 ã Home Page  . . . . . . [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  œ¨å¢¯  . . . . . . . . . . .  [1;44;37m@39;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Ctrl-R š ˜ ™¦ãŸœ ˜               [0;1;42;33m@14;"OK"b[0;47;30mÜ   [0;1;41;33m@14;"Cancel"b[0;47;30mÜ  [0;1;47;37m³ [0m
[30;47m ³                                    ßßßßßßßßßßßßßßßß    ßßßßßßßßßßßßßßßß  [0;1;47;37m³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m} T Visual template #1


T2VISUAL {[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [34m‰˜«˜®é¨© ‹â¢¦¬ª[0;30;47m ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³  ¤¦£˜«œ§é¤¬£¦ . . . . . . . . .  [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  ”ç¢¦ ¡˜ /ã ¢ ¡å˜  . . . . . . . [1;44;37m@17;17;0s[0;1;47;37m                    ³ [0m
[30;47m ³  ¤¦£˜ œ«˜ ¨å˜ª  . . . . . . . .  [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  „§áššœ¢£˜/‡â© . . . . . . . . . [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  ˜¨œ®æ£œ¤ ¬§¨œ©å˜ . . . . . .  [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  ƒ œçŸ¬¤© (›æª ¡˜  ˜¨ Ÿ£æª) . . [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  TK/æ¢/œ¨ ¦®ã/„›¨˜  . . . . .  [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  ’¢â­à¤˜ (voice) . . . . . . . . [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  ’¢â­à¤˜ (data) . . . . . . . .  [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  ’¢â­à¤˜ (fax) . . . . . . . . . [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Email › œçŸ¬¤© 1 . . . . . . .  [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Email › œçŸ¬¤© 2  . . . . . . . [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  ‚œ¤ ¡âª §¢¨¦­¦¨åœª (1/5) . . .  [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  ‚œ¤ ¡âª §¢¨¦­¦¨åœª (2/5)  . . . [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  ‚œ¤ ¡âª §¢¨¦­¦¨åœª (3/5) . . .  [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  ‚œ¤ ¡âª §¢¨¦­¦¨åœª (4/5)  . . . [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  ‚œ¤ ¡âª §¢¨¦­¦¨åœª (5/5) . . .  [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  œ¨å¢¯ . . . . . . . . . . . . [1;44;37m@39;35;0s[0;1;47;37m  ³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  Ctrl-R š ˜ ™¦ãŸœ ˜              [0;1;42;33m@14;"OK"b[0;47;30mÜ    [0;1;41;33m@14;"Cancel"b[0;47;30mÜ  [0;1;47;37m³ [0m
[30;47m ³                                   ßßßßßßßßßßßßßßßß     ßßßßßßßßßßßßßßßß  [0;1;47;37m³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m} T Visual template #2


T3VISUAL {[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [34m‰˜«˜®é¨© ‹â¢¦¬ª[0;30;47m ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³  [1;44;37m@59;59;0s[0;1;47;37m  ³ [0m
[30;47m ³  [1;44;37m@59;59;0s[0;1;47;37m  ³ [0m
[30;47m ³  [1;44;37m@59;59;0s[0;1;47;37m  ³ [0m
[30;47m ³  [1;44;37m@59;59;0s[0;1;47;37m  ³ [0m
[30;47m ³  [1;44;37m@59;59;0s[0;1;47;37m  ³ [0m
[30;47m ³  [1;44;37m@59;59;0s[0;1;47;37m  ³ [0m
[30;47m ³  [1;44;37m@59;59;0s[0;1;47;37m  ³ [0m
[30;47m ³  [1;44;37m@59;59;0s[0;1;47;37m  ³ [0m
[30;47m ³  [1;44;37m@59;59;0s[0;1;47;37m  ³ [0m
[30;47m ³  [1;44;37m@59;59;0s[0;1;47;37m  ³ [0m
[30;47m ³  [1;44;37m@59;59;0s[0;1;47;37m  ³ [0m
[30;47m ³  [1;44;37m@59;59;0s[0;1;47;37m  ³ [0m
[30;47m ³  [1;44;37m@59;59;0s[0;1;47;37m  ³ [0m
[30;47m ³  [1;44;37m@59;59;0s[0;1;47;37m  ³ [0m
[30;47m ³  [1;44;37m@59;59;0s[0;1;47;37m  ³ [0m
[30;47m ³                                                                 [0;1;47;37m³ [0m
[30;47m ³  œ¨å¢¯ . . . . . [1;44;37m@39;40;0s[0;1;47;37m  ³ [0m
[30;47m ³                                                                 [0;1;47;37m³ [0m
[30;47m ³  Ctrl-R š ˜ ™¦ãŸœ ˜     [0;1;42;33m@14;"OK"b[0;47;30mÜ    [0;1;41;33m@14;"Cancel"b[0;47;30mÜ  [0;1;47;37m³ [0m
[30;47m ³                          ßßßßßßßßßßßßßßßß     ßßßßßßßßßßßßßßßß  [0;1;47;37m³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m} T Visual template #3


T1LINEAR {[2J[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³ [31m 1[30m. ¢ã¨œª æ¤¦£˜:  . . . . . . [34m@35;35;0s[1;37m      ³ [0m
[30;47m ³ [31m 2[30m. ”ç¢¦: . . . . . . . . . .  [34m@1;1;0s[1;37m                                        ³ [0m
[30;47m ³ [31m 3[30m. †¢ ¡å˜:  . . . . . . . . . [34m@2;2;0s[1;37m                                       ³ [0m
[30;47m ³ [31m 4[30m. „§áššœ¢£˜:  . . . . . . .  [34m@35;35;0s[1;37m      ³ [0m
[30;47m ³ [31m 5[30m. ¤¦£˜ œ«˜ ¨å˜ª:  . . . . . [34m@35;35;0s[1;37m      ³ [0m
[30;47m ³ [31m 6[30m. æ¢/œ¨ ¦®ã: . . . . . .  [34m@35;35;0s[1;37m      ³ [0m
[30;47m ³ [31m 7[30m. ’¢â­à¤¦:  . . . . . . . . [34m@15;15;0s[1;37m                          ³ [0m
[30;47m ³ [31m 8[30m. ’ç§¦ª ¬§¦¢¦š ©«ã: . . . .  [34m@35;35;0s[1;37m      ³ [0m
[30;47m ³ [31m 9[30m.  ¡¦šœ¤œ ˜¡ã ¡˜«á©«˜©:  . [34m@35;35;0s[1;37m      ³ [0m
[30;47m ³ [31m10[30m. â¤œª š¢é©©œª:  . . . . .  [34m@35;35;0s[1;37m      ³ [0m
[30;47m ³ [31m11[30m. €š˜§£â¤ «˜ ¤å˜:  . . . . [34m@35;35;0s[1;37m      ³ [0m
[30;47m ³ [31m12[30m. €š˜§£â¤ £¦¬© ¡ã:  . . .  [34m@35;35;0s[1;37m      ³ [0m
[30;47m ³ [31m13[30m. €š˜§£â¤¦ ™ ™¢å¦:  . . . . [34m@35;35;0s[1;37m      ³ [0m
[30;47m ³ [31m14[30m. €š˜§£â¤¦ áŸ¢£˜: . . . .  [34m@35;35;0s[1;37m      ³ [0m
[30;47m ³ [31m15[30m. €¢¢˜ œ¤› ˜­â¨¦¤«˜/hobby: . [34m@35;35;0s[1;37m      ³ [0m
[30;47m ³ [31m16[30m. ‚œ¤ ¡âª §¢¨¦­¦¨åœª (1/2): [34m@35;35;0s[1;37m      ³ [0m
[30;47m ³ [31m17[30m. ‚œ¤ ¡âª §¢¨¦­¦¨åœª (2/2): [34m@35;35;0s[1;37m      ³ [0m
[30;47m ³ [31m18[30m. Email › œçŸ¬¤© 1: . . . . [34m@35;35;0s[1;37m      ³ [0m
[30;47m ³ [31m19[30m. Email 2 ã Home Page:  . .  [34m@35;35;0s[1;37m      ³ [0m
[30;47m ³ [31m20[30m. œ¨å¢¯:  . . . . . . . . [34m@39;40;0s[1;37m ³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m
} T Linear template #1

T1P1 {} T Linear template #1, prompt #1
T1P2 {} T Linear template #1, prompt #2
T1P3 {} T Linear template #1, prompt #3
T1P4 {} T Linear template #1, prompt #4
T1P5 {} T Linear template #1, prompt #5
T1P6 {} T Linear template #1, prompt #6
T1P7 {} T Linear template #1, prompt #7
T1P8 {} T Linear template #1, prompt #8
T1P9 {} T Linear template #1, prompt #9
T1P10 {} T Linear template #1, prompt #10
T1P11 {} T Linear template #1, prompt #11
T1P12 {} T Linear template #1, prompt #12
T1P13 {} T Linear template #1, prompt #13
T1P14 {} T Linear template #1, prompt #14
T1P15 {} T Linear template #1, prompt #15
T1P16 {} T Linear template #1, prompt #16
T1P17 {} T Linear template #1, prompt #17
T1P18 {} T Linear template #1, prompt #18
T1P19 {} T Linear template #1, prompt #19
T1P20 {} T Linear template #1, prompt #20
T1P21 {} T Linear template #1, prompt #21
T1P22 {} T Linear template #1, prompt #22
T1P23 {} T Linear template #1, prompt #23
T1P24 {} T Linear template #1, prompt #24
T1P25 {} T Linear template #1, prompt #25
T1P26 {} T Linear template #1, prompt #26
T1P27 {} T Linear template #1, prompt #27
T1P28 {} T Linear template #1, prompt #28
T1P29 {} T Linear template #1, prompt #29
T1P30 {} T Linear template #1, prompt #30


T2LINEAR {[2J[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³ [31m 1[30m. ¤¦£˜«œ§é¤¬£¦: . . . . [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m 2[30m. ”ç¢¦ ¡˜ /ã ¢ ¡å˜:  .  [34m@17;17;0s[0;1;47;37m                        ³ [0m
[30;47m ³ [31m 3[30m. ¤¦£˜ œ«˜ ¨å˜ª:  . . . [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m 4[30m. „§áššœ¢£˜/‡â©: . . .  [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m 5[30m. ˜¨œ®æ£œ¤ ¬§¨œ©å˜: . [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m 6[30m. ƒ œçŸ¬¤©:  . . . . .  [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m 7[30m. TK/æ¢/œ¨ ¦®ã/„›¨˜:  [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m 8[30m. ’¢â­à¤˜ (voice): . .  [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m 9[30m. ’¢â­à¤˜ (data): . . . [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m10[30m. ’¢â­à¤˜ (fax): . . .  [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m11[30m. Email › œçŸ¬¤© 1: . . [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m12[30m. Email › œçŸ¬¤© 2:  .  [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m13[30m. ‚œ¤ ¡âª §¢¨¦­¦¨åœª: . [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m14[30m. ‚œ¤ ¡âª §¢¨¦­¦¨åœª:   [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m15[30m. ‚œ¤ ¡âª §¢¨¦­¦¨åœª: . [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m16[30m. ‚œ¤ ¡âª §¢¨¦­¦¨åœª:   [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m17[30m. ‚œ¤ ¡âª §¢¨¦­¦¨åœª: . [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m18[30m. œ¨å¢¯: . . . . . .  [34m@39;40;0s[0;1;47;37m ³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m
} T Linear template #2


T2P1 {} T Linear template #2, prompt #1
T2P2 {} T Linear template #2, prompt #2
T2P3 {} T Linear template #2, prompt #3
T2P4 {} T Linear template #2, prompt #4
T2P5 {} T Linear template #2, prompt #5
T2P6 {} T Linear template #2, prompt #6
T2P7 {} T Linear template #2, prompt #7
T2P8 {} T Linear template #2, prompt #8
T2P9 {} T Linear template #2, prompt #9
T2P10 {} T Linear template #2, prompt #10
T2P11 {} T Linear template #2, prompt #11
T2P12 {} T Linear template #2, prompt #12
T2P13 {} T Linear template #2, prompt #13
T2P14 {} T Linear template #2, prompt #14
T2P15 {} T Linear template #2, prompt #15
T2P16 {} T Linear template #2, prompt #16
T2P17 {} T Linear template #2, prompt #17
T2P18 {} T Linear template #2, prompt #18
T2P19 {} T Linear template #2, prompt #19
T2P20 {} T Linear template #2, prompt #20
T2P21 {} T Linear template #2, prompt #21
T2P22 {} T Linear template #2, prompt #22
T2P23 {} T Linear template #2, prompt #23
T2P24 {} T Linear template #2, prompt #24
T2P25 {} T Linear template #2, prompt #25
T2P26 {} T Linear template #2, prompt #26
T2P27 {} T Linear template #2, prompt #27
T2P28 {} T Linear template #2, prompt #28
T2P29 {} T Linear template #2, prompt #28
T2P30 {} T Linear template #2, prompt #30


T3LINEAR {[2J[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³ [31m 1[30m. [34m@59;59;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m 2[30m. [34m@59;59;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m 3[30m. [34m@59;59;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m 4[30m. [34m@59;59;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m 5[30m. [34m@59;59;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m 6[30m. [34m@59;59;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m 7[30m. [34m@59;59;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m 8[30m. [34m@59;59;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m 9[30m. [34m@59;59;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m10[30m. [34m@59;59;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m11[30m. [34m@59;59;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m12[30m. [34m@59;59;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m13[30m. [34m@59;59;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m14[30m. [34m@59;59;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m15[30m. [34m@59;59;0s[0;1;47;37m ³ [0m
[30;47m ³                                                                 [1;37m³ [0m
[30;47m ³ [31m16[30m. œ¨å¢¯:          [34m@39;40;0s[0;1;47;37m ³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m
} T Linear template #3


T3P1 {} T Linear template #3, prompt #1
T3P2 {} T Linear template #3, prompt #2
T3P3 {} T Linear template #3, prompt #3
T3P4 {} T Linear template #3, prompt #4
T3P5 {} T Linear template #3, prompt #5
T3P6 {} T Linear template #3, prompt #6
T3P7 {} T Linear template #3, prompt #7
T3P8 {} T Linear template #3, prompt #8
T3P9 {} T Linear template #3, prompt #9
T3P10 {} T Linear template #3, prompt #10
T3P11 {} T Linear template #3, prompt #11
T3P12 {} T Linear template #3, prompt #12
T3P13 {} T Linear template #3, prompt #13
T3P14 {} T Linear template #3, prompt #14
T3P15 {} T Linear template #3, prompt #15
T3P16 {} T Linear template #3, prompt #16
T3P17 {} T Linear template #3, prompt #17
T3P18 {} T Linear template #3, prompt #18
T3P19 {} T Linear template #3, prompt #19
T3P20 {} T Linear template #3, prompt #20
T3P21 {} T Linear template #3, prompt #21
T3P22 {} T Linear template #3, prompt #22
T3P23 {} T Linear template #3, prompt #23
T3P24 {} T Linear template #3, prompt #24
T3P25 {} T Linear template #3, prompt #25
T3P26 {} T Linear template #3, prompt #26
T3P27 {} T Linear template #3, prompt #27
T3P28 {} T Linear template #3, prompt #28
T3P29 {} T Linear template #3, prompt #28
T3P30 {} T Linear template #3, prompt #30


LANG {}


REGPLS {[0;1;32m

!JYou haven't completed your registry yet. Enter
[33mR[32m ("Registry") from the main menu, or [33m/go registry[32m to
complete it.!)

[0;1m} T Registry login notice to users who aren't in Registry


NOENTRY {[0;1;31m
I'm sorry, you do not have access to this area.
} T Access to the Registry denied


REGMNU {[2J[0m[47;1;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;30;47m¿ [40m
[47;1;37m ³  [0;47;30m                   Registry of Users                   [0;47;30m³ [40m
[47;1;37m ³  [0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ  [0;47;30m³ [40m
[47;1;37m ³  [0;31;47mA[30mbout the registry . . . . . . .  General information  [30m³ [40m
[47;1;37m ³  [0;31;47mD[30mirectory . . . . . .  Brief List of registered users  [30m³ [40m
[47;1;37m ³  [0;31;47mL[30mook up  . . . . . . . . .  Look up a user's registry  [30m³ [40m
[47;1;37m ³  [0;31;47mS[30mcan registry . . . .  Search registries for keywords  [30m³ [40m
[47;1;37m ³  [0;31;47mY[30mour entry  . . . . . . . . . . .Update your registry  [30m³ [40m
[47;1;37m ³  [0;31;47mC[30mhange template  . . .  Change your registry template  [30m³ [40m
[47;1;37m ³                                                         [0;47;30m³ [40m
[47;1;37m ³ [0;30;47me[31mX[30mit                                                    [30m³ [40m
[47;1;37m À[0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0;1m
} T Registry main menu


VSHMENU {[0;1m
Registry of Users
Please enter your choice: [0m} T Registry menu, very short prompt


SHMENU {[0;1m
Registry of Users
!WEnter your choice ([33mA[37m,[33mD[37m,[33mL[37m,[33mS[37m,[33mY[37m,[33mC[37m,[33mX[37m to exit, or [33m?[37m for the menu): !)[0m} T Registry short menu


REGSMNU {[2J[0m[47;1;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;30;47m¿ [40m
[47;1;37m ³  [0;47;30m                   Registry of Users                   [0;47;30m³ [40m
[47;1;37m ³  [0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ  [0;47;30m³ [40m
[47;1;37m ³  [0;31;47mA[30mbout the registry . . . . . . .  General information  [30m³ [40m
[47;1;37m ³  [0;31;47mD[30mirectory . . . . . .  Brief List of registered users  [30m³ [40m
[47;1;37m ³  [0;31;47mE[30mdit registry . . . .  Change another user's registry  [30m³ [40m
[47;1;37m ³  [0;31;47mL[30mook up  . . . . . . . . .  Look up a user's registry  [30m³ [40m
[47;1;37m ³  [0;31;47mS[30mcan registry . . . .  Search registries for keywords  [30m³ [40m
[47;1;37m ³  [0;31;47mY[30mour entry  . . . . . . . . . . .Update your registry  [30m³ [40m
[47;1;37m ³  [0;31;47mC[30mhange template  . . .  Change your registry template  [30m³ [40m
[47;1;37m ³                                                         [0;47;30m³ [40m
[47;1;37m ³ [0;30;47me[31mX[30mit                                                    [30m³ [40m
[47;1;37m À[0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0;1m
} T Registry main menu for sysops


SHSMENU {[0;1m
Registry of Users
!WEnter your choice ([33mA[37m,[33mD[37m,[33mE[37m,[33mL[37m,[33mS[37m,[33mY[37m,[33mC[37m,[33mX[37m to exit, or [33m?[37m for the menç): !)[0m} T Registry short menu for sysops


ERRSEL {[0;1;31m
I'm sorry, "%c" is not an option.
[0;1m} T Wrong selection from the main registry menu


LEAVE {[0;1m
Leaving the Registry of Users...
} T Leaving the registry


ABOUT {[0;1m

!JThe Registry of Users helps you get acquainted with other users in this
system, and describe yourself so others will be able to know who you are.!)

!JThe data you will give here (in contrast to the ones you were required to
enter when you signed up) are [5mAVAILABLE TO THE PUBLIC[0;1m. If you don't
want to answer a question, enter "No", "Blank", or something like that. In contrast
to the data in your account, what you write in the Registry doesn't have to be
truthful or accurate.!)

!JAfter you finish entering your registry, you may change it as often as
you like. You may freely rectify and update your specifics whenever you want.!)

!JTo see a brief list of others' registries, enter [33mDA[37m.
To complete/alter your record, enter [33mY[37m. There are three different
registry templates, and you can choose whichever you want. Note, though, that
when changing the template, your record is erased until you rewrite it.
The three templates are as follows: personal registration, professional
(corporal), and generic (i.e. without field names). Enter [33mC[37m to change
your template.!)

} T About the registry


DINTRO {[0;1m
!JThis option allows you to see a list of other users' registries (their
user IDs and registry summaries are displayed in tabular form). You may choose
the letter from which the listing will begin.!)

[5;33mÛÛ[0;1;33m  !J!iOnly registered users will be listed.!)
!0l
!JPress [33mEnter[37m or [33mCtrl-C[37m during the listing to stop.!)
[0;1m} T Registry directory, information


DLETTER {[0;1m
!WEnter the letter from which the listing is to start
([33mA[37m-[33mZ[37m, [33m?[37m for help, or [33mEnter[37m to cancel):!) [0m} T Registry directory, asking where to start


DIRERR {[0;1;31m
!WYou must give an alphabetic character, or [33mEnter[31m to exit.!)
[0;1m} T Registry directory, invalid starting letter


DIRHDR {[0;1;32m
Press [33mEnter[32m or [33mCtrl-C[32m during the listing if you want to stop.

[37mUser                                                Summary
-----------------------------------------------------------
} T Registry directory header


DIRLIN {[0;1;32m%-17s  %40s
} T Registry directory line


DIRFTR {[0;1m-----------------------------------------------------------

} T Registry directory footer


DIRCAN {[0;1;33m
Listing terminated.
[0;1m} T Registry directory terminated


SINTRO {[0;1m
!JThis option allows you to scan the records of the Registry of Users
for a set of keywords. You may choose the letter from which the search
will begin.!)
[0;1m} T Directory scan, information


SLETTER {[0;1m
!WEnter the starting letter ([33mA[37m-[33mZ[37m, or [33mEnter[37m to cancel):!) [0m} T Directory scan, asking where to start


SCANKW {[0;1m

!JNow, please enter your desired keywords. The keywords must be delimited
by spaces. The search is conducted phonetically, for better results.!)

!JExample: If you enter [33mPascal BBS[37m, the Registry will be scanned
for the words Pascal or BBS, but also "pascal" or "bbs", or even "PasKAL".!)

!JPress [33mEnter[37m or [33mCtrl-C[37m to stop the listing.!)
[0;1m} T Directory scan, keyword information


GETKEYW {[0;1m
!WPlease enter your keywords, [33m?[37m for help, or [33mX[37m to exit: !)[0m} T Directory scan, asking for keywords


LKUPWHO {[0;1m
!WEnter user ID, or [33mX[37m to exit:!) [0m} T Enter User-ID to look up


UIDERR {[0;1;31m
There is no record of that user.
[0;1m} T Unregistered User-ID


T1LOOKUP {[0;1;44m
[K!CRegistry of %s[0;1m
!)
[32mFull name  . . . . . . . . . [37m%s
[32mSex . . . . . . . . . . . .  [37m%s
[32mAge  . . . . . . . . . . . . [37m%s
[32mProfession  . . . . . . . .  [37m%s
[32mCompany name . . . . . . . . [37m%s
[32mCity/Area . . . . . . . . .  [37m%s
[32mPhone number . . . . . . . . [37m%s
[32mComputer make and model . .  [37m%s
[32mMarital status . . . . . . . [37m%s
[32mForeign languages . . . . .  [37m%s
[32mFavourite fielm  . . . . . . [37m%s
[32mFavourite kind of music . .  [37m%s
[32mFavourite book . . . . . . . [37m%s
[32mFavourite sport . . . . . .  [37m%s
[32mOther interests/hobbies  . . [37m%s
[32mGeneric information . . . .  [37m%s
                             %s
[32mEmail address 1  . . . . . . [37m%s
[32mEmail 2 or Home Page  . . .  [37m%s
[32mSummary  . . . . . . . . . . [37m%s
[0;1m} T Registry lookup, template 1


T2LOOKUP {[0;1;44m
[K!CRegistry of %s[0;1m
!)
[32mFull name . . . . . . . . . . .  [37m%s
[32mSex and/or age . . . . . . . . . [37m%s
[32mCompany name  . . . . . . . . .  [37m%s
[32mProfession/Position  . . . . . . [37m%s
[32mOffered service . . . . . . . .  [37m%s
[32mMail address . . . . . . . . . . [37m%s
[32mZIP/City/Area/Headquarters  . .  [37m%s
[32mPhone numbers (voice)  . . . . . [37m%s
[32mPhone numbers (data)  . . . . .  [37m%s
[32mPhone numbers (fax)  . . . . . . [37m%s
[32mEmail address 1 . . . . . . . .  [37m%s
[32mEmail address 2  . . . . . . . . [37m%s
[32mGeneric information . . . . . .  [37m%s
                                 %s
                                 %s
                                 %s
                                 %s
[32mSummary  . . . . . . . . . . . . [37m%s
[0;1m} T Registry lookup, template 2


T3LOOKUP {[0;1;44m
[K!CRegistry of %s[0;1m

%-60s
%-60s
%-60s
%-60s
%-60s
%-60s
%-60s
%-60s
%-60s
%-60s
%-60s
%-60s
%-60s
%-60s
%-60s

[32mSummary . . . . . . [37m%-40s
!)[0;1m} T Registry lookup, template 3


EDITWHO {[0;1m
!WEnter a user ID or [33mX[37m to exit:!) [0m} T Enter User-ID of registry to edit


EDITERR {[0;1;31m
This user does not exist on @BBS@.
[0;1m} T Edit registry, unregistered User-ID


EDITNAX {[0;1;31m
!JI'm sorry, but your access level does not permit you to
complete your registry.!)
[0;1m} T Edit registry, no access to your registry


EDITOK {[0;1;32m
!JYour record has been saved. Thank you for your registration!)
[0;1m
} T Registry stored ok


EDITCAN {[0;1;33m
!JThe changes were cancelled.!)
[0;1m
} T Registry update cancelled


CHINFO {[0;1m
!JUsing this option you may change your registry template. There are
three predefined templates to choose from:!)

!W[33m1[37m. Pers!ional registry: Full name, sex, age, profession,
company name, city/area, phone number, computer model, marital status,
foreign languages, favourite film, kind of music, book, sport, hobby,
two lines of generic information. Most fields have a length of 35
characters.!)
!0l
!W[33m2[37m. Prof!iessional registry: Full name, sex/age, company name,
profession/position, offered service, address, phone numbers (voice, data
and fax), space for two email addresses, and five lines of generic info.
Most fields are 48 characters long.!)
!0l
!W[33m3[37m. Gene!iric registry: 15 unnamed fields of 59 characters each.!)
!0l

!W[0;1;31;5mÛÛ[0;1;31m  WARNING: !iBy changing your template, you automatically
[37merase[31m the contents of your current record.!)
!0l
[0;1m} T Changing template, information


CHANGE {[0;1m
Which template would you like?

[33m1[37m . . . . . . . . . .  Personal registry
[33m2[37m  . . . . . . . . Professional registry
[33m3[37m . . . . . . . . . . . Generic registry

!WEnter your selection ([33m1[37m,[33m2[37m,[33m3[37m,[33m?[37m for help, or X to exit):!) [0m} T Changing template


CHERR {[0;1;31m
I'm sorry, "%c" is not an option.
[0;1m} T Changing template, invalid option


REGCR {[0;1;33m
!JUp to now  you had no record. I have created a blank one using
the template you selected...!)
[0;1m} T Creating registry and setting preferred template


NOCHANGE {[0;1;32m
!JThe registry template did not change;
the contents of your record remain untouched.!)
[0;1m} T No change in the template


NONCHANGE {[0;1;32m
!JYou selected the template you were already using;
there was no need to change it. The contents of your record
remain untouched.!)
[0;1m} T No template change needed


TMPLCH {[0;1;32m
!JThe template of your registration has changed. The contents
of your record (except the summary) have been erased.!)
[0;1m} T Template changed, registry erased


T1VISUAL {[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [34mUser Registration[0;30;47m ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³  Full name  . . . . . . . . . . . [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Sex . . . . . . . . . . . . . .  [1;44;37m@1;1;0s[0;47;30m        Age . . . . . . . . . [1;44;37m@2;2;0s[0;1;47;37m  ³ [0m
[30;47m ³  Profession  . . . . . . . . . .  [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Company name . . . . . . . . . . [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  City/Area . . . . . . . . . . .  [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Phone number . . . . . . . . . . [1;44;37m@15;15;0s[0;1;47;37m                      ³ [0m
[30;47m ³  Make and model of computer  . .  [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Marital status . . . . . . . . . [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Foreign languages . . . . . . .  [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Favourite film . . . . . . . . . [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Favourite kind of music . . . .  [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Favourite book . . . . . . . . . [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Favourite sport . . . . . . . .  [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Other interests/hobbies  . . . . [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  General information (1/2) . . .  [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  General information (2/2)  . . . [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Email address 1 . . . . . . . .  [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Email address 2 or home page . . [1;44;37m@35;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Summary . . . . . . . . . . . .  [1;44;37m@39;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Ctrl-R for help                  [0;1;42;33m@14;"OK"b[0;47;30mÜ   [0;1;41;33m@14;"Cancel"b[0;47;30mÜ  [0;1;47;37m³ [0m
[30;47m ³                                    ßßßßßßßßßßßßßßßß    ßßßßßßßßßßßßßßßß  [0;1;47;37m³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m} T Visual template #1


T2VISUAL {[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [34mUser Registration[0;30;47m ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³  Full name . . . . . . . . . . .  [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Sex and/or age . . . . . . . . . [1;44;37m@17;17;0s[0;1;47;37m                    ³ [0m
[30;47m ³  Company name  . . . . . . . . .  [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Profession/Position  . . . . . . [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Offered Service . . . . . . . .  [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Address  . . . . . . . . . . . . [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  ZIP/City/Area/Headquarters  . .  [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Phone numbers (voice)  . . . . . [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Phone numbers (data)  . . . . .  [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Phone numbers (fax)  . . . . . . [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Email address 1 . . . . . . . .  [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Email address 2  . . . . . . . . [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Generic information (1/5) . . .  [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Generic information (2/5)  . . . [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Generic information (3/5) . . .  [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Generic information (4/5)  . . . [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Generic information (5/5) . . .  [1;44;37m@40;35;0s[0;1;47;37m  ³ [0m
[30;47m ³  Summary  . . . . . . . . . . . . [1;44;37m@39;35;0s[0;1;47;37m  ³ [0m
[30;47m ³                                                                          [0;1;47;37m³ [0m
[30;47m ³  Ctrl-R for help                 [0;1;42;33m@14;"OK"b[0;47;30mÜ    [0;1;41;33m@14;"Cancel"b[0;47;30mÜ  [0;1;47;37m³ [0m
[30;47m ³                                   ßßßßßßßßßßßßßßßß     ßßßßßßßßßßßßßßßß  [0;1;47;37m³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m} T Visual template #2


T3VISUAL {[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [34mUser Registration[0;30;47m ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³  [1;44;37m@59;59;0s[0;1;47;37m  ³ [0m
[30;47m ³  [1;44;37m@59;59;0s[0;1;47;37m  ³ [0m
[30;47m ³  [1;44;37m@59;59;0s[0;1;47;37m  ³ [0m
[30;47m ³  [1;44;37m@59;59;0s[0;1;47;37m  ³ [0m
[30;47m ³  [1;44;37m@59;59;0s[0;1;47;37m  ³ [0m
[30;47m ³  [1;44;37m@59;59;0s[0;1;47;37m  ³ [0m
[30;47m ³  [1;44;37m@59;59;0s[0;1;47;37m  ³ [0m
[30;47m ³  [1;44;37m@59;59;0s[0;1;47;37m  ³ [0m
[30;47m ³  [1;44;37m@59;59;0s[0;1;47;37m  ³ [0m
[30;47m ³  [1;44;37m@59;59;0s[0;1;47;37m  ³ [0m
[30;47m ³  [1;44;37m@59;59;0s[0;1;47;37m  ³ [0m
[30;47m ³  [1;44;37m@59;59;0s[0;1;47;37m  ³ [0m
[30;47m ³  [1;44;37m@59;59;0s[0;1;47;37m  ³ [0m
[30;47m ³  [1;44;37m@59;59;0s[0;1;47;37m  ³ [0m
[30;47m ³  [1;44;37m@59;59;0s[0;1;47;37m  ³ [0m
[30;47m ³                                                                 [0;1;47;37m³ [0m
[30;47m ³  Summary  . . . . . [1;44;37m@39;40;0s[0;1;47;37m  ³ [0m
[30;47m ³                                                                 [0;1;47;37m³ [0m
[30;47m ³  Ctrl-R for help        [0;1;42;33m@14;"OK"b[0;47;30mÜ    [0;1;41;33m@14;"Cancel"b[0;47;30mÜ  [0;1;47;37m³ [0m
[30;47m ³                          ßßßßßßßßßßßßßßßß     ßßßßßßßßßßßßßßßß  [0;1;47;37m³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m} T Visual template #3


T1LINEAR {[2J[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³ [31m 1[30m. Full name: . . . . . . . . [34m@35;35;0s[1;37m      ³ [0m
[30;47m ³ [31m 2[30m. Sex:  . . . . . . . . . .  [34m@1;1;0s[1;37m                                        ³ [0m
[30;47m ³ [31m 3[30m. Age: . . . . . . . . . . . [34m@2;2;0s[1;37m                                       ³ [0m
[30;47m ³ [31m 4[30m. Profession: . . . . . . .  [34m@35;35;0s[1;37m      ³ [0m
[30;47m ³ [31m 5[30m. Company name:  . . . . . . [34m@35;35;0s[1;37m      ³ [0m
[30;47m ³ [31m 6[30m. City/Area:  . . . . . . .  [34m@35;35;0s[1;37m      ³ [0m
[30;47m ³ [31m 7[30m. Phone number:  . . . . . . [34m@15;15;0s[1;37m                          ³ [0m
[30;47m ³ [31m 8[30m. Computer make and model:   [34m@35;35;0s[1;37m      ³ [0m
[30;47m ³ [31m 9[30m. Marital status:  . . . . . [34m@35;35;0s[1;37m      ³ [0m
[30;47m ³ [31m10[30m. Foreign languages:  . . .  [34m@35;35;0s[1;37m      ³ [0m
[30;47m ³ [31m11[30m. Favourite film:  . . . . . [34m@35;35;0s[1;37m      ³ [0m
[30;47m ³ [31m12[30m. Favourite kind of music:   [34m@35;35;0s[1;37m      ³ [0m
[30;47m ³ [31m13[30m. Favourite book: . . . . .  [34m@35;35;0s[1;37m      ³ [0m
[30;47m ³ [31m14[30m. Favourite sport: . . . . . [34m@35;35;0s[1;37m      ³ [0m
[30;47m ³ [31m15[30m. Other interests/hobbies:   [34m@35;35;0s[1;37m      ³ [0m
[30;47m ³ [31m16[30m. General information (1/2): [34m@35;35;0s[1;37m      ³ [0m
[30;47m ³ [31m17[30m. General information (2/2): [34m@35;35;0s[1;37m      ³ [0m
[30;47m ³ [31m18[30m. Summary: . . . . . . . . . [34m@39;40;0s[1;37m ³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m
} T Linear template #1

T1P1 {} T Linear template #1, prompt #1
T1P2 {} T Linear template #1, prompt #2
T1P3 {} T Linear template #1, prompt #3
T1P4 {} T Linear template #1, prompt #4
T1P5 {} T Linear template #1, prompt #5
T1P6 {} T Linear template #1, prompt #6
T1P7 {} T Linear template #1, prompt #7
T1P8 {} T Linear template #1, prompt #8
T1P9 {} T Linear template #1, prompt #9
T1P10 {} T Linear template #1, prompt #10
T1P11 {} T Linear template #1, prompt #11
T1P12 {} T Linear template #1, prompt #12
T1P13 {} T Linear template #1, prompt #13
T1P14 {} T Linear template #1, prompt #14

T1P15 {} T Linear template #1, prompt #15
T1P16 {} T Linear template #1, prompt #16
T1P17 {} T Linear template #1, prompt #17
T1P18 {} T Linear template #1, prompt #18
T1P19 {} T Linear template #1, prompt #19
T1P20 {} T Linear template #1, prompt #20
T1P21 {} T Linear template #1, prompt #21
T1P22 {} T Linear template #1, prompt #22
T1P23 {} T Linear template #1, prompt #23
T1P24 {} T Linear template #1, prompt #24
T1P25 {} T Linear template #1, prompt #25
T1P26 {} T Linear template #1, prompt #26
T1P27 {} T Linear template #1, prompt #27
T1P28 {} T Linear template #1, prompt #28
T1P29 {} T Linear template #1, prompt #29
T1P30 {} T Linear template #1, prompt #30


T2LINEAR {[2J[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³ [31m 1[30m. Full name: . . . . . . [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m 2[30m. Sex and/or age: . . .  [34m@17;17;0s[0;1;47;37m                        ³ [0m
[30;47m ³ [31m 3[30m. Company name:  . . . . [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m 4[30m. Profession/Position:   [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m 5[30m. Offered Service: . . . [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m 6[30m. Address:  . . . . . .  [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m 7[30m. ZIP/City/Area/HQ:  . . [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m 8[30m. Phone numbers (voice): [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m 9[30m. Phone numbers (data):  [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m10[30m. Phone numbers (fax): . [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m11[30m. Email address 1:  . .  [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m12[30m. Email address 2: . . . [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m13[30m. General information:   [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m14[30m. General information: . [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m15[30m. General information:   [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m16[30m. General information: . [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m17[30m. General information:   [34m@40;40;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m18[30m. Summary: . . . . . . . [34m@39;40;0s[0;1;47;37m ³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m
} T Linear template #2


T2P1 {} T Linear template #2, prompt #1
T2P2 {} T Linear template #2, prompt #2
T2P3 {} T Linear template #2, prompt #3
T2P4 {} T Linear template #2, prompt #4
T2P5 {} T Linear template #2, prompt #5
T2P6 {} T Linear template #2, prompt #6
T2P7 {} T Linear template #2, prompt #7
T2P8 {} T Linear template #2, prompt #8
T2P9 {} T Linear template #2, prompt #9
T2P10 {} T Linear template #2, prompt #10
T2P11 {} T Linear template #2, prompt #11
T2P12 {} T Linear template #2, prompt #12
T2P13 {} T Linear template #2, prompt #13
T2P14 {} T Linear template #2, prompt #14
T2P15 {} T Linear template #2, prompt #15
T2P16 {} T Linear template #2, prompt #16
T2P17 {} T Linear template #2, prompt #17
T2P18 {} T Linear template #2, prompt #18
T2P19 {} T Linear template #2, prompt #19
T2P20 {} T Linear template #2, prompt #20
T2P21 {} T Linear template #2, prompt #21
T2P22 {} T Linear template #2, prompt #22
T2P23 {} T Linear template #2, prompt #23
T2P24 {} T Linear template #2, prompt #24
T2P25 {} T Linear template #2, prompt #25
T2P26 {} T Linear template #2, prompt #26
T2P27 {} T Linear template #2, prompt #27
T2P28 {} T Linear template #2, prompt #28
T2P29 {} T Linear template #2, prompt #28
T2P30 {} T Linear template #2, prompt #30


T3LINEAR {[2J[0;30;47m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;1;37;47m¿ [0m
[30;47m ³ [31m 1[30m. [34m@59;59;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m 2[30m. [34m@59;59;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m 3[30m. [34m@59;59;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m 4[30m. [34m@59;59;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m 5[30m. [34m@59;59;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m 6[30m. [34m@59;59;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m 7[30m. [34m@59;59;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m 8[30m. [34m@59;59;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m 9[30m. [34m@59;59;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m10[30m. [34m@59;59;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m11[30m. [34m@59;59;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m12[30m. [34m@59;59;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m13[30m. [34m@59;59;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m14[30m. [34m@59;59;0s[0;1;47;37m ³ [0m
[30;47m ³ [31m15[30m. [34m@59;59;0s[0;1;47;37m ³ [0m
[30;47m ³                                                                 [1;37m³ [0m
[30;47m ³ [31m16[30m. Summary:           [34m@39;40;0s[0;1;47;37m ³ [0m
[30;47m À[0;1;37;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m
} T Linear template #3


T3P1 {} T Linear template #3, prompt #1
T3P2 {} T Linear template #3, prompt #2
T3P3 {} T Linear template #3, prompt #3
T3P4 {} T Linear template #3, prompt #4
T3P5 {} T Linear template #3, prompt #5
T3P6 {} T Linear template #3, prompt #6
T3P7 {} T Linear template #3, prompt #7
T3P8 {} T Linear template #3, prompt #8
T3P9 {} T Linear template #3, prompt #9
T3P10 {} T Linear template #3, prompt #10
T3P11 {} T Linear template #3, prompt #11
T3P12 {} T Linear template #3, prompt #12
T3P13 {} T Linear template #3, prompt #13
T3P14 {} T Linear template #3, prompt #14
T3P15 {} T Linear template #3, prompt #15
T3P16 {} T Linear template #3, prompt #16
T3P17 {} T Linear template #3, prompt #17
T3P18 {} T Linear template #3, prompt #18
T3P19 {} T Linear template #3, prompt #19
T3P20 {} T Linear template #3, prompt #20
T3P21 {} T Linear template #3, prompt #21
T3P22 {} T Linear template #3, prompt #22
T3P23 {} T Linear template #3, prompt #23
T3P24 {} T Linear template #3, prompt #24
T3P25 {} T Linear template #3, prompt #25
T3P26 {} T Linear template #3, prompt #26
T3P27 {} T Linear template #3, prompt #27
T3P28 {} T Linear template #3, prompt #28
T3P29 {} T Linear template #3, prompt #28
T3P30 {} T Linear template #3, prompt #30

LANGEND {}
