LEVEL2 {}

GRWID {Graph width in characters: 71} N 40 256

BARCHR {Character used for bars: Û} C

HLFCHR {'Half-bar' character used for bars: İ} C


LEVEL3 {}


CNTOPN {[0;1;31m
!JŠ¬§á£˜ , ˜¬«æ «¦ ˜¨®œå¦ ©«˜« ©« ¡é¤ ›œ¤ â®œ  ›£ ¦¬¨šŸœå ˜¡æ£˜.
‰˜«á §á©˜ § Ÿ˜¤æ««˜ ›£ ¦¬¨šœå«˜  ˜¬«ã «¤ ©« š£ã. ˜¨˜¡˜¢é ¥˜¤˜›¦¡ £á©«œ
©œ ¢åš¦.!)
[0;1m} T Can't open statistics file


BAUD {’˜®ç««œª ©ç¤›œ©ª} T Title string describing baud stats

CLSS {Classes} T Title string describing class stats
 
DAY {•¨ã© ©¬©«ã£˜«¦ª} T Title string describing BBS usage

MODS {Modules} T Title string describing module stats

TTY {‚¨˜££âª} T Title string describing tty stats


AVGCRD {‹â© £œ¨ã© ˜ ¡˜«˜¤á¢à© credits} T 'Mean credit consumption'

AVGMIN {‹â©¦ª £œ¨ã© ¦ª ®¨æ¤¦ª ®¨ã©ª (¢œ§«á)} T 'Mean time spent (mins)'

AVGCLL {‹â©¦ª £œ¨ã© ¦ª ˜¨ Ÿ£æª ¡¢ã©œà¤} T 'Mean number of calls'


TOTCRD {‘¬¤¦¢ ¡ã ¡˜«˜¤á¢à© credits} T 'Total credit consumption'

TOTMIN {‘¬¤¦¢ ¡æª ®¨æ¤¦ª ®¨ã©ª (¢œ§«á)} T 'Total time spent (mins)'

TOTCLL {‘¬¤¦¢ ¡æª ˜¨ Ÿ£æª ¡¢ã©œà¤} T 'Total number of calls'


TODAY {š ˜ ©ã£œ¨˜} T 'for today'

MONTH {š ˜ ˜¬«æ «¦¤ £ã¤˜} T 'for this month'

YEAR {š ˜ ­â«¦ª} T 'for this year'

EVER {} T 'ever'


HEADER {[0;47;1;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;30;47m¿ [0m
[47;1;37m ³ [0;47;30m%-74s [0;47;30m³ [0m
} T Graph title


TOP {[47;1;37m ³ [0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [0;47;30m³ [0m
} T Graph top row

GRLABEL {[47;1;37m ³ [0;47;30m%s º } T Graph row: label

GRBAR {[0;47;34m%s } } T Graph row: bar

GRNUM {[31m%s [0;47;30m³ [0m
}  T Graph row: number

BOTTOM {[47;1;37m ³ [0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [0;47;30m³ [0m
} T Graph bottom row

FTRAVG {[47;1;37m ³ [0;47;30m@BBS@, %s, %s.                                             [0;47;30m³ [0m
} T Graph footer for 'averages'

FTRTOT {[47;1;37m ³ [0;47;30m@BBS@, %s, %s.                      ‚œ¤ ¡æ ©ç¤¦¢¦: %7d [0;47;30m³ [0m
} T Graph footer for 'totals'

FTREND {[47;1;37m À[0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0;1m
} T Graph footer, end


AGESTATS {[0;47;1;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;30;47m¿ [0m
[47;1;37m ³ [0;47;30mƒ£¦š¨˜­ ¡á ©«¦ ®œå˜ (%-9s, %-5s)                                 [0;47;30m³ [0m
[47;1;37m ³ [0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [0;47;30m³ [0m
[47;1;37m ³ [0;47;34m                       -19    20-29    30-39    40-49    50-      ‘ç¤¦¢¦   [0;47;30m³ [0m
[47;1;37m ³ [0;47;30m                  ÚÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄ¿ [0;47;30m³ [0m
[47;1;37m ³ [0;47;34mIBM PC/compatible [30m³ %6d ³ %6d ³ %6d ³ %6d ³ %6d ³[31m %7d [30m³ [0;47;30m³ [0m
[47;1;37m ³ [0;47;34mApple Macintosh   [30m³ %6d ³ %6d ³ %6d ³ %6d ³ %6d ³[31m %7d [30m³ [0;47;30m³ [0m
[47;1;37m ³ [0;47;34mApple II*         [30m³ %6d ³ %6d ³ %6d ³ %6d ³ %6d ³[31m %7d [30m³ [0;47;30m³ [0m
[47;1;37m ³ [0;47;34mCommodore Amiga   [30m³ %6d ³ %6d ³ %6d ³ %6d ³ %6d ³[31m %7d [30m³ [0;47;30m³ [0m
[47;1;37m ³ [0;47;34mAtari             [30m³ %6d ³ %6d ³ %6d ³ %6d ³ %6d ³[31m %7d [30m³ [0;47;30m³ [0m
[47;1;37m ³ [0;47;34mAcorn Archimedes  [30m³ %6d ³ %6d ³ %6d ³ %6d ³ %6d ³[31m %7d [30m³ [0;47;30m³ [0m
[47;1;37m ³ [0;47;34mAmstrad CPC       [30m³ %6d ³ %6d ³ %6d ³ %6d ³ %6d ³[31m %7d [30m³ [0;47;30m³ [0m
[47;1;37m ³ [0;47;34m€š¤à©«¦           [30m³ %6d ³ %6d ³ %6d ³ %6d ³ %6d ³[31m %7d [30m³ [0;47;30m³ [0m
[47;1;37m ³ [0;47;34m‘ç¤¦¢¦            [30m³ [31m%6d [30m³ [31m%6d [30m³ [31m%6d [30m³ [31m%6d [30m³ [31m%6d [30m³[31m %7d [30m³ [0;47;30m³ [0m
[47;1;37m ³ [0;47;30m                  ÀÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÁÄÄÄÄ³ÄÄÄÄÙ [0;47;30m³ [0m
[47;1;37m ³ [0;47;30m    ÚÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´      [0;47;30m³ [0m
[47;1;37m ³ [0;47;34m  €¤›¨œª   ANSI   Visual   „«˜ ¨.  Suspnd  Exempt  Sysops           [30m³      [0;47;30m³ [0m
[47;1;37m ³ [0;47;30m  %6d  %6d  %6d   %6d  %6d  %6d  %6d           ³      [0;47;30m³ [0m
[47;1;37m ³ [0;47;30m    ÚÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ      [0;47;30m³ [0m
[47;1;37m ³ [0;47;34m „¢¢¤ ¡á  €šš¢ ¡á                                                         [0;47;30m³ [0m
[47;1;37m ³ [0;47;30m   %6d   %6d                                                         [0;47;30m³ [0m
[47;1;37m À[0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0;1m
} T Graph title











LANG {}












CNTOPN {[0;1;31m
!JSorry, this statistics file does not exist. It's probably still being
generated. Please try again later.!)
[0;1m} T Can't open statistics file


BAUD {Connection speeds} T Title string describing baud stats

CLSS {Classes} T Title string describing class stats
 
DAY {System usage} T Title string describing BBS usage

MODS {Modules} T Title string describing module stats

TTY {Channels} T Title string describing tty stats


AVGCRD {Mean daily credit consumption} T 'Mean credit consumption'

AVGMIN {Mean time spent (mins) daily} T 'Mean time spent (mins)'

AVGCLL {Mean daily connections} T 'Mean number of calls'


TOTCRD {Total credit consumtion} T 'Total credit consumption'

TOTMIN {Total time spend (mins)} T 'Total time spent (mins)'

TOTCLL {Total daily connections} T 'Total number of calls'


TODAY {for today} T 'for today'

MONTH {for this month} T 'for this month'

YEAR {for this year} T 'for this year'

EVER {ever} T 'ever'


HEADER {[0;47;1;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;30;47m¿ [0m
[47;1;37m ³ [0;47;30m%-74s [0;47;30m³ [0m
} T Graph title


TOP {[47;1;37m ³ [0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [0;47;30m³ [0m
} T Graph top row

GRLABEL {[47;1;37m ³ [0;47;30m%s ³ } T Graph row: label

GRBAR {[0;47;34m%s } } T Graph row: bar

GRNUM {[31m%s [0;47;30m³ [0m
}  T Graph row: number

BOTTOM {[47;1;37m ³ [0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [0;47;30m³ [0m
} T Graph bottom row

FTRAVG {[47;1;37m ³ [0;47;30m@BBS@, %s, %s.                                             [0;47;30m³ [0m
} T Graph footer for 'averages'

FTRTOT {[47;1;37m ³ [0;47;30m@BBS@, %s, %s.                              Totals: %7d [0;47;30m³ [0m
} T Graph footer for 'totals'

FTREND {[47;1;37m À[0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0;1m
} T Graph footer, end


AGESTATS {[0;47;1;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;30;47m¿ [0m
[47;1;37m ³ [0;47;30mSystem demographics (%-9s, %-5s)                                   [0;47;30m³ [0m
[47;1;37m ³ [0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ [0;47;30m³ [0m
[47;1;37m ³ [0;47;34m                       -19    20-29    30-39    40-49    50-       Total   [0;47;30m³ [0m
[47;1;37m ³ [0;47;30m                  ÚÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄ¿ [0;47;30m³ [0m
[47;1;37m ³ [0;47;34mIBM PC/compatible [30m³ %6d ³ %6d ³ %6d ³ %6d ³ %6d ³[31m %7d ³ [0;47;30m³ [0m
[47;1;37m ³ [0;47;34mApple Macintosh   [30m³ %6d ³ %6d ³ %6d ³ %6d ³ %6d ³[31m %7d ³ [0;47;30m³ [0m
[47;1;37m ³ [0;47;34mApple II*         [30m³ %6d ³ %6d ³ %6d ³ %6d ³ %6d ³[31m %7d ³ [0;47;30m³ [0m
[47;1;37m ³ [0;47;34mCommodore Amiga   [30m³ %6d ³ %6d ³ %6d ³ %6d ³ %6d ³[31m %7d ³ [0;47;30m³ [0m
[47;1;37m ³ [0;47;34mAtari             [30m³ %6d ³ %6d ³ %6d ³ %6d ³ %6d ³[31m %7d ³ [0;47;30m³ [0m
[47;1;37m ³ [0;47;34mAcorn Archimedes  [30m³ %6d ³ %6d ³ %6d ³ %6d ³ %6d ³[31m %7d ³ [0;47;30m³ [0m
[47;1;37m ³ [0;47;34mAmstrad CPC       [30m³ %6d ³ %6d ³ %6d ³ %6d ³ %6d ³[31m %7d ³ [0;47;30m³ [0m
[47;1;37m ³ [0;47;34mUnknown           [30m³ %6d ³ %6d ³ %6d ³ %6d ³ %6d ³[31m %7d ³ [0;47;30m³ [0m
[47;1;37m ³ [0;47;34mTotal             [30m³ [31m%6d [30m³ [31m%6d [30m³ [31m%6d [30m³ [31m%6d [30m³ [31m%6d [30m³[31m %7d [30m³ [0;47;30m³ [0m
[47;1;37m ³ [0;47;30m                  ÀÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÁÄÄÄÄ³ÄÄÄÄÙ [0;47;30m³ [0m
[47;1;37m ³ [0;47;30m    ÚÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´      [0;47;30m³ [0m
[47;1;37m ³ [0;47;34m   Male    ANSI   Visual    Corp.  Suspnd  Exempt  Sysops           ³      [0;47;30m³ [0m
[47;1;37m ³ [0;47;30m  %6d  %6d  %6d   %6d  %6d  %6d  %6d           ³      [0;47;30m³ [0m
[47;1;37m ³ [0;47;30m    ÚÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ      [0;47;30m³ [0m
[47;1;37m ³ [0;47;30m    Greek  English                                                         [0;47;30m³ [0m
[47;1;37m ³ [0;47;30m   %6d   %6d                                                         [0;47;30m³ [0m
[47;1;37m À[0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0;1m
} T Graph title


LANGEND {}
