/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _METASERVICES_H_RPCGEN
#define _METASERVICES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct registration_package_t {
	char codename[9];
	char bbstitle[52];
	char company[48];
	char address1[48];
	char address2[48];
	char city[48];
	char dataphone[48];
	char voicephone[48];
	int users_online;
	int lines_free;
	int lines_max;
	char *hostname;
	int port;
	char *url;
	char *email;
	char *access_allow;
	char *access_deny;
	char *bbs_ad;
	int bbs_uid;
	int bbs_gid;
	int bbsd_pid;
	char *prefix;
	int regtime;
	int flags;
};
typedef struct registration_package_t registration_package_t;

typedef struct info_package_t *info_package_p;

struct info_package_t {
	char codename[9];
	char bbstitle[52];
	char company[48];
	char address1[48];
	char address2[48];
	char city[48];
	char dataphone[48];
	char voicephone[48];
	int users_online;
	int lines_free;
	int lines_max;
	char *hostname;
	int port;
	char *url;
	char *email;
	char *bbs_ad;
	int disconnect;
	info_package_p next;
};
typedef struct info_package_t info_package_t;

typedef struct club_list_item_t *club_list_item_p;

struct club_list_request_t {
	char codename[9];
	char targetname[9];
};
typedef struct club_list_request_t club_list_request_t;

struct club_list_item_t {
	char club[16];
	char descr[64];
	club_list_item_p next;
};
typedef struct club_list_item_t club_list_item_t;
#define CLR_OK              0    /* Request ok */
#define CLR_UNKNOWN        -1    /* Target BBS is unknown */
#define CLR_NOTMEGISTOS    -2    /* Not running Megistos */
#define CLR_UNKNOWNCLUB    -3    /* Club does not exist/access denied */
#define CLR_CORRUPTMSG     -4    /* Unable to read message */
#define CLR_NOTAPPROVED    -5    /* Deferred, attachment not approved */
#define CLR_SIZE            6    /* size of error list array */

char *clr_errorlist[CLR_SIZE];

struct club_list {
	int result_code;
	union {
		club_list_item_p clubs;
	} club_list_u;
};
typedef struct club_list club_list;

struct club_header_request_t {
	char codename[9];
	char targetname[9];
	char club[16];
};
typedef struct club_header_request_t club_header_request_t;

struct club_header_t {
	char club[16];
	char descr[64];
	char clubop[24];
	int crdate;
	int crtime;
	int nmsgs;
	int nper;
	int nblts;
	int nfiles;
	int nfunapp;
	int msglife;
	char *banner;
};
typedef struct club_header_t club_header_t;

struct club_header {
	int result_code;
	union {
		club_header_t club;
	} club_header_u;
};
typedef struct club_header club_header;

struct ihave_request_t {
	char codename[9];
	char targetname[9];
	char club[16];
	u_int since_time;
};
typedef struct ihave_request_t ihave_request_t;

typedef struct ihave_entry_t *ihave_list_p;

struct ihave_entry_t {
	char *codename;
	char *orgclub;
	char *msgid;
	int time;
	int msgno;
	ihave_list_p next;
};
typedef struct ihave_entry_t ihave_entry_t;

struct ihave_list {
	int result_code;
	union {
		ihave_list_p ihave_list;
	} ihave_list_u;
};
typedef struct ihave_list ihave_list;

struct message_request_t {
	char codename[9];
	char targetname[9];
	char targetclub[16];
	int msgno;
	char compression;
};
typedef struct message_request_t message_request_t;

struct compr_t {
	int orig_msg_len;
	int orig_att_len;
};
typedef struct compr_t compr_t;

struct compr {
	char compression;
	union {
		struct compr_t compr;
	} compr_u;
};
typedef struct compr compr;


struct club_message_t {
	char from[80];
	char to[80];
	char subject[64];
	char fatt[16];
	long flags;
	int orgtime;
	int orgdate;
	compr comp_result;
	struct {
		u_int message_len;
		char *message_val;
	} message;
	struct {
		u_int attachment_len;
		char *attachment_val;
	} attachment;
};
typedef struct club_message_t club_message_t;

struct club_message {
	int result_code;
	union {
		club_message_t message;
	} club_message_u;
};
typedef struct club_message club_message;

#define METABBS_PROG 0x204d4447
#define METABBS_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define metabbs_register 1
extern  int * metabbs_register_1(registration_package_t *, CLIENT *);
extern  int * metabbs_register_1_svc(registration_package_t *, struct svc_req *);
#define metabbs_register_non_megistos 2
extern  int * metabbs_register_non_megistos_1(registration_package_t *, CLIENT *);
extern  int * metabbs_register_non_megistos_1_svc(registration_package_t *, struct svc_req *);
#define metabbs_request_info 10003
extern  info_package_p * metabbs_request_info_1(char **, CLIENT *);
extern  info_package_p * metabbs_request_info_1_svc(char **, struct svc_req *);
#define distclub_request_list 1000100
extern  struct club_list * distclub_request_list_1(club_list_request_t *, CLIENT *);
extern  struct club_list * distclub_request_list_1_svc(club_list_request_t *, struct svc_req *);
#define distclub_request_header 1000101
extern  struct club_header * distclub_request_header_1(club_header_request_t *, CLIENT *);
extern  struct club_header * distclub_request_header_1_svc(club_header_request_t *, struct svc_req *);
#define distclub_request_ihave 1000102
extern  struct ihave_list * distclub_request_ihave_1(ihave_request_t *, CLIENT *);
extern  struct ihave_list * distclub_request_ihave_1_svc(ihave_request_t *, struct svc_req *);
#define distclub_request_message 1000103
extern  struct club_message * distclub_request_message_1(message_request_t *, CLIENT *);
extern  struct club_message * distclub_request_message_1_svc(message_request_t *, struct svc_req *);
extern int metabbs_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define metabbs_register 1
extern  int * metabbs_register_1();
extern  int * metabbs_register_1_svc();
#define metabbs_register_non_megistos 2
extern  int * metabbs_register_non_megistos_1();
extern  int * metabbs_register_non_megistos_1_svc();
#define metabbs_request_info 10003
extern  info_package_p * metabbs_request_info_1();
extern  info_package_p * metabbs_request_info_1_svc();
#define distclub_request_list 1000100
extern  struct club_list * distclub_request_list_1();
extern  struct club_list * distclub_request_list_1_svc();
#define distclub_request_header 1000101
extern  struct club_header * distclub_request_header_1();
extern  struct club_header * distclub_request_header_1_svc();
#define distclub_request_ihave 1000102
extern  struct ihave_list * distclub_request_ihave_1();
extern  struct ihave_list * distclub_request_ihave_1_svc();
#define distclub_request_message 1000103
extern  struct club_message * distclub_request_message_1();
extern  struct club_message * distclub_request_message_1_svc();
extern int metabbs_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_registration_package_t (XDR *, registration_package_t*);
extern  bool_t xdr_info_package_p (XDR *, info_package_p*);
extern  bool_t xdr_info_package_t (XDR *, info_package_t*);
extern  bool_t xdr_club_list_item_p (XDR *, club_list_item_p*);
extern  bool_t xdr_club_list_request_t (XDR *, club_list_request_t*);
extern  bool_t xdr_club_list_item_t (XDR *, club_list_item_t*);
extern  bool_t xdr_club_list (XDR *, club_list*);
extern  bool_t xdr_club_header_request_t (XDR *, club_header_request_t*);
extern  bool_t xdr_club_header_t (XDR *, club_header_t*);
extern  bool_t xdr_club_header (XDR *, club_header*);
extern  bool_t xdr_ihave_request_t (XDR *, ihave_request_t*);
extern  bool_t xdr_ihave_list_p (XDR *, ihave_list_p*);
extern  bool_t xdr_ihave_entry_t (XDR *, ihave_entry_t*);
extern  bool_t xdr_ihave_list (XDR *, ihave_list*);
extern  bool_t xdr_message_request_t (XDR *, message_request_t*);
extern  bool_t xdr_compr_t (XDR *, compr_t*);
extern  bool_t xdr_compr (XDR *, compr*);
extern  bool_t xdr_compr (XDR *, compr*);
extern  bool_t xdr_club_message_t (XDR *, club_message_t*);
extern  bool_t xdr_club_message (XDR *, club_message*);

#else /* K&R C */
extern bool_t xdr_registration_package_t ();
extern bool_t xdr_info_package_p ();
extern bool_t xdr_info_package_t ();
extern bool_t xdr_club_list_item_p ();
extern bool_t xdr_club_list_request_t ();
extern bool_t xdr_club_list_item_t ();
extern bool_t xdr_club_list ();
extern bool_t xdr_club_header_request_t ();
extern bool_t xdr_club_header_t ();
extern bool_t xdr_club_header ();
extern bool_t xdr_ihave_request_t ();
extern bool_t xdr_ihave_list_p ();
extern bool_t xdr_ihave_entry_t ();
extern bool_t xdr_ihave_list ();
extern bool_t xdr_message_request_t ();
extern bool_t xdr_compr_t ();
extern bool_t xdr_compr ();
extern bool_t xdr_compr ();
extern bool_t xdr_club_message_t ();
extern bool_t xdr_club_message ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_METASERVICES_H_RPCGEN */
