/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/types.h>
#include <rpc/xdr.h>

#include "metaservices.h"

bool_t
xdr_registration_package_t(XDR *xdrs, registration_package_t *objp)
{

	 register long *buf=buf;

	 int i=i;

	 if (xdrs->x_op == XDR_ENCODE) {
	 if (!xdr_vector(xdrs, (char *)objp->codename, 9, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->bbstitle, 52, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->company, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->address1, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->address2, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->city, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->dataphone, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->voicephone, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 buf = XDR_INLINE(xdrs,3 * BYTES_PER_XDR_UNIT);
	   if (buf == NULL) {
		 if (!xdr_int(xdrs, &objp->users_online)) {
			 return (FALSE);
		 }
		 if (!xdr_int(xdrs, &objp->lines_free)) {
			 return (FALSE);
		 }
		 if (!xdr_int(xdrs, &objp->lines_max)) {
			 return (FALSE);
		 }

	  }
	  else {
		 IXDR_PUT_LONG(buf,objp->users_online);
		 IXDR_PUT_LONG(buf,objp->lines_free);
		 IXDR_PUT_LONG(buf,objp->lines_max);
	  }
	 if (!xdr_string(xdrs, &objp->hostname, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->port)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->url, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->email, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->access_allow, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->access_deny, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->bbs_ad, 8192)) {
		 return (FALSE);
	 }
	 buf = XDR_INLINE(xdrs,3 * BYTES_PER_XDR_UNIT);
	   if (buf == NULL) {
		 if (!xdr_int(xdrs, &objp->bbs_uid)) {
			 return (FALSE);
		 }
		 if (!xdr_int(xdrs, &objp->bbs_gid)) {
			 return (FALSE);
		 }
		 if (!xdr_int(xdrs, &objp->bbsd_pid)) {
			 return (FALSE);
		 }

	  }
	  else {
		 IXDR_PUT_LONG(buf,objp->bbs_uid);
		 IXDR_PUT_LONG(buf,objp->bbs_gid);
		 IXDR_PUT_LONG(buf,objp->bbsd_pid);
	  }
	 if (!xdr_string(xdrs, &objp->prefix, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->regtime)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->flags)) {
		 return (FALSE);
	 }

 	 return (TRUE);
	} else if (xdrs->x_op == XDR_DECODE) {
	 if (!xdr_vector(xdrs, (char *)objp->codename, 9, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->bbstitle, 52, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->company, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->address1, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->address2, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->city, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->dataphone, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->voicephone, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 buf = XDR_INLINE(xdrs,3 * BYTES_PER_XDR_UNIT);
	   if (buf == NULL) {
		 if (!xdr_int(xdrs, &objp->users_online)) {
			 return (FALSE);
		 }
		 if (!xdr_int(xdrs, &objp->lines_free)) {
			 return (FALSE);
		 }
		 if (!xdr_int(xdrs, &objp->lines_max)) {
			 return (FALSE);
		 }

	  }
	  else {
		 objp->users_online = IXDR_GET_LONG(buf);
		 objp->lines_free = IXDR_GET_LONG(buf);
		 objp->lines_max = IXDR_GET_LONG(buf);
	  }
	 if (!xdr_string(xdrs, &objp->hostname, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->port)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->url, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->email, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->access_allow, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->access_deny, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->bbs_ad, 8192)) {
		 return (FALSE);
	 }
	 buf = XDR_INLINE(xdrs,3 * BYTES_PER_XDR_UNIT);
	   if (buf == NULL) {
		 if (!xdr_int(xdrs, &objp->bbs_uid)) {
			 return (FALSE);
		 }
		 if (!xdr_int(xdrs, &objp->bbs_gid)) {
			 return (FALSE);
		 }
		 if (!xdr_int(xdrs, &objp->bbsd_pid)) {
			 return (FALSE);
		 }

	  }
	  else {
		 objp->bbs_uid = IXDR_GET_LONG(buf);
		 objp->bbs_gid = IXDR_GET_LONG(buf);
		 objp->bbsd_pid = IXDR_GET_LONG(buf);
	  }
	 if (!xdr_string(xdrs, &objp->prefix, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->regtime)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->flags)) {
		 return (FALSE);
	 }
	 return(TRUE);
	}

	 if (!xdr_vector(xdrs, (char *)objp->codename, 9, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->bbstitle, 52, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->company, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->address1, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->address2, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->city, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->dataphone, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->voicephone, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->users_online)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->lines_free)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->lines_max)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->hostname, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->port)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->url, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->email, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->access_allow, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->access_deny, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->bbs_ad, 8192)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->bbs_uid)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->bbs_gid)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->bbsd_pid)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->prefix, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->regtime)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->flags)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_info_package_p(XDR *xdrs, info_package_p *objp)
{

	 register long *buf=buf;

	 if (!xdr_pointer(xdrs, (char **)objp, sizeof(struct info_package_t), (xdrproc_t)xdr_info_package_t)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_info_package_t(XDR *xdrs, info_package_t *objp)
{

	 register long *buf=buf;

	 int i=i;

	 if (xdrs->x_op == XDR_ENCODE) {
	 if (!xdr_vector(xdrs, (char *)objp->codename, 9, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->bbstitle, 52, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->company, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->address1, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->address2, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->city, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->dataphone, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->voicephone, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 buf = XDR_INLINE(xdrs,3 * BYTES_PER_XDR_UNIT);
	   if (buf == NULL) {
		 if (!xdr_int(xdrs, &objp->users_online)) {
			 return (FALSE);
		 }
		 if (!xdr_int(xdrs, &objp->lines_free)) {
			 return (FALSE);
		 }
		 if (!xdr_int(xdrs, &objp->lines_max)) {
			 return (FALSE);
		 }

	  }
	  else {
		 IXDR_PUT_LONG(buf,objp->users_online);
		 IXDR_PUT_LONG(buf,objp->lines_free);
		 IXDR_PUT_LONG(buf,objp->lines_max);
	  }
	 if (!xdr_string(xdrs, &objp->hostname, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->port)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->url, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->email, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->bbs_ad, 8192)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->disconnect)) {
		 return (FALSE);
	 }
	 if (!xdr_info_package_p(xdrs, &objp->next)) {
		 return (FALSE);
	 }

 	 return (TRUE);
	} else if (xdrs->x_op == XDR_DECODE) {
	 if (!xdr_vector(xdrs, (char *)objp->codename, 9, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->bbstitle, 52, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->company, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->address1, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->address2, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->city, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->dataphone, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->voicephone, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 buf = XDR_INLINE(xdrs,3 * BYTES_PER_XDR_UNIT);
	   if (buf == NULL) {
		 if (!xdr_int(xdrs, &objp->users_online)) {
			 return (FALSE);
		 }
		 if (!xdr_int(xdrs, &objp->lines_free)) {
			 return (FALSE);
		 }
		 if (!xdr_int(xdrs, &objp->lines_max)) {
			 return (FALSE);
		 }

	  }
	  else {
		 objp->users_online = IXDR_GET_LONG(buf);
		 objp->lines_free = IXDR_GET_LONG(buf);
		 objp->lines_max = IXDR_GET_LONG(buf);
	  }
	 if (!xdr_string(xdrs, &objp->hostname, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->port)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->url, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->email, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->bbs_ad, 8192)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->disconnect)) {
		 return (FALSE);
	 }
	 if (!xdr_info_package_p(xdrs, &objp->next)) {
		 return (FALSE);
	 }
	 return(TRUE);
	}

	 if (!xdr_vector(xdrs, (char *)objp->codename, 9, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->bbstitle, 52, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->company, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->address1, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->address2, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->city, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->dataphone, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->voicephone, 48, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->users_online)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->lines_free)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->lines_max)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->hostname, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->port)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->url, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->email, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->bbs_ad, 8192)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->disconnect)) {
		 return (FALSE);
	 }
	 if (!xdr_info_package_p(xdrs, &objp->next)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_club_list_item_p(XDR *xdrs, club_list_item_p *objp)
{

	 register long *buf=buf;

	 if (!xdr_pointer(xdrs, (char **)objp, sizeof(struct club_list_item_t), (xdrproc_t)xdr_club_list_item_t)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_club_list_request_t(XDR *xdrs, club_list_request_t *objp)
{

	 register long *buf=buf;

	 int i=i;
	 if (!xdr_vector(xdrs, (char *)objp->codename, 9, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->targetname, 9, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_club_list_item_t(XDR *xdrs, club_list_item_t *objp)
{

	 register long *buf=buf;

	 int i=i;
	 if (!xdr_vector(xdrs, (char *)objp->club, 16, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->descr, 64, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_club_list_item_p(xdrs, &objp->next)) {
		 return (FALSE);
	 }
	return (TRUE);
}
char *clr_errorlist[CLR_SIZE]={  /* Index must be negated, of course! */
	"success",
	"target BBS is unknown",
	"target is not a Megistos BBS",
	"unknown club or access denied",
	"message is corrupted",
	"attachment not approved, transfer deferred",
};

bool_t
xdr_club_list(XDR *xdrs, club_list *objp)
{

	 register long *buf=buf;

	 if (!xdr_int(xdrs, &objp->result_code)) {
		 return (FALSE);
	 }
	switch (objp->result_code) {
	case 0:
		 if (!xdr_club_list_item_p(xdrs, &objp->club_list_u.clubs)) {
			 return (FALSE);
		 }
		break;
	default:
		break;
	}
	return (TRUE);
}

bool_t
xdr_club_header_request_t(XDR *xdrs, club_header_request_t *objp)
{

	 register long *buf=buf;

	 int i=i;
	 if (!xdr_vector(xdrs, (char *)objp->codename, 9, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->targetname, 9, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->club, 16, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_club_header_t(XDR *xdrs, club_header_t *objp)
{

	 register long *buf=buf;

	 int i=i;

	 if (xdrs->x_op == XDR_ENCODE) {
	 if (!xdr_vector(xdrs, (char *)objp->club, 16, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->descr, 64, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->clubop, 24, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 buf = XDR_INLINE(xdrs,8 * BYTES_PER_XDR_UNIT);
	   if (buf == NULL) {
		 if (!xdr_int(xdrs, &objp->crdate)) {
			 return (FALSE);
		 }
		 if (!xdr_int(xdrs, &objp->crtime)) {
			 return (FALSE);
		 }
		 if (!xdr_int(xdrs, &objp->nmsgs)) {
			 return (FALSE);
		 }
		 if (!xdr_int(xdrs, &objp->nper)) {
			 return (FALSE);
		 }
		 if (!xdr_int(xdrs, &objp->nblts)) {
			 return (FALSE);
		 }
		 if (!xdr_int(xdrs, &objp->nfiles)) {
			 return (FALSE);
		 }
		 if (!xdr_int(xdrs, &objp->nfunapp)) {
			 return (FALSE);
		 }
		 if (!xdr_int(xdrs, &objp->msglife)) {
			 return (FALSE);
		 }

	  }
	  else {
		 IXDR_PUT_LONG(buf,objp->crdate);
		 IXDR_PUT_LONG(buf,objp->crtime);
		 IXDR_PUT_LONG(buf,objp->nmsgs);
		 IXDR_PUT_LONG(buf,objp->nper);
		 IXDR_PUT_LONG(buf,objp->nblts);
		 IXDR_PUT_LONG(buf,objp->nfiles);
		 IXDR_PUT_LONG(buf,objp->nfunapp);
		 IXDR_PUT_LONG(buf,objp->msglife);
	  }
	 if (!xdr_string(xdrs, &objp->banner, ~0)) {
		 return (FALSE);
	 }

 	 return (TRUE);
	} else if (xdrs->x_op == XDR_DECODE) {
	 if (!xdr_vector(xdrs, (char *)objp->club, 16, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->descr, 64, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->clubop, 24, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 buf = XDR_INLINE(xdrs,8 * BYTES_PER_XDR_UNIT);
	   if (buf == NULL) {
		 if (!xdr_int(xdrs, &objp->crdate)) {
			 return (FALSE);
		 }
		 if (!xdr_int(xdrs, &objp->crtime)) {
			 return (FALSE);
		 }
		 if (!xdr_int(xdrs, &objp->nmsgs)) {
			 return (FALSE);
		 }
		 if (!xdr_int(xdrs, &objp->nper)) {
			 return (FALSE);
		 }
		 if (!xdr_int(xdrs, &objp->nblts)) {
			 return (FALSE);
		 }
		 if (!xdr_int(xdrs, &objp->nfiles)) {
			 return (FALSE);
		 }
		 if (!xdr_int(xdrs, &objp->nfunapp)) {
			 return (FALSE);
		 }
		 if (!xdr_int(xdrs, &objp->msglife)) {
			 return (FALSE);
		 }

	  }
	  else {
		 objp->crdate = IXDR_GET_LONG(buf);
		 objp->crtime = IXDR_GET_LONG(buf);
		 objp->nmsgs = IXDR_GET_LONG(buf);
		 objp->nper = IXDR_GET_LONG(buf);
		 objp->nblts = IXDR_GET_LONG(buf);
		 objp->nfiles = IXDR_GET_LONG(buf);
		 objp->nfunapp = IXDR_GET_LONG(buf);
		 objp->msglife = IXDR_GET_LONG(buf);
	  }
	 if (!xdr_string(xdrs, &objp->banner, ~0)) {
		 return (FALSE);
	 }
	 return(TRUE);
	}

	 if (!xdr_vector(xdrs, (char *)objp->club, 16, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->descr, 64, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->clubop, 24, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->crdate)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->crtime)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->nmsgs)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->nper)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->nblts)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->nfiles)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->nfunapp)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->msglife)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->banner, ~0)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_club_header(XDR *xdrs, club_header *objp)
{

	 register long *buf=buf;

	 if (!xdr_int(xdrs, &objp->result_code)) {
		 return (FALSE);
	 }
	switch (objp->result_code) {
	case 0:
		 if (!xdr_club_header_t(xdrs, &objp->club_header_u.club)) {
			 return (FALSE);
		 }
		break;
	default:
		break;
	}
	return (TRUE);
}

bool_t
xdr_ihave_request_t(XDR *xdrs, ihave_request_t *objp)
{

	 register long *buf=buf;

	 int i=i;
	 if (!xdr_vector(xdrs, (char *)objp->codename, 9, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->targetname, 9, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->club, 16, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_u_int(xdrs, &objp->since_time)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_ihave_list_p(XDR *xdrs, ihave_list_p *objp)
{

	 register long *buf=buf;

	 if (!xdr_pointer(xdrs, (char **)objp, sizeof(struct ihave_entry_t), (xdrproc_t)xdr_ihave_entry_t)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_ihave_entry_t(XDR *xdrs, ihave_entry_t *objp)
{

	 register long *buf=buf;

	 if (!xdr_string(xdrs, &objp->codename, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->orgclub, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->msgid, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->time)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->msgno)) {
		 return (FALSE);
	 }
	 if (!xdr_ihave_list_p(xdrs, &objp->next)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_ihave_list(XDR *xdrs, ihave_list *objp)
{

	 register long *buf=buf;

	 if (!xdr_int(xdrs, &objp->result_code)) {
		 return (FALSE);
	 }
	switch (objp->result_code) {
	case 0:
		 if (!xdr_ihave_list_p(xdrs, &objp->ihave_list_u.ihave_list)) {
			 return (FALSE);
		 }
		break;
	default:
		break;
	}
	return (TRUE);
}

bool_t
xdr_message_request_t(XDR *xdrs, message_request_t *objp)
{

	 register long *buf=buf;

	 int i=i;
	 if (!xdr_vector(xdrs, (char *)objp->codename, 9, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->targetname, 9, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->targetclub, 16, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->msgno)) {
		 return (FALSE);
	 }
	 if (!xdr_char(xdrs, &objp->compression)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_compr_t(XDR *xdrs, compr_t *objp)
{

	 register long *buf=buf;

	 if (!xdr_int(xdrs, &objp->orig_msg_len)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->orig_att_len)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_compr(XDR *xdrs, compr *objp)
{

	 register long *buf=buf;

	 if (!xdr_char(xdrs, &objp->compression)) {
		 return (FALSE);
	 }
	switch (objp->compression) {
	case 0:
		break;
	default:
		 if (!xdr_compr_t(xdrs, &objp->compr_u.compr)) {
			 return (FALSE);
		 }
		break;
	}
	return (TRUE);
}

bool_t
xdr_club_message_t(XDR *xdrs, club_message_t *objp)
{

	 register long *buf=buf;

	 int i=i;

	 if (xdrs->x_op == XDR_ENCODE) {
	 if (!xdr_vector(xdrs, (char *)objp->from, 80, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->to, 80, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->subject, 64, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->fatt, 16, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 buf = XDR_INLINE(xdrs,3 * BYTES_PER_XDR_UNIT);
	   if (buf == NULL) {
		 if (!xdr_long(xdrs, &objp->flags)) {
			 return (FALSE);
		 }
		 if (!xdr_int(xdrs, &objp->orgtime)) {
			 return (FALSE);
		 }
		 if (!xdr_int(xdrs, &objp->orgdate)) {
			 return (FALSE);
		 }

	  }
	  else {
		 IXDR_PUT_LONG(buf,objp->flags);
		 IXDR_PUT_LONG(buf,objp->orgtime);
		 IXDR_PUT_LONG(buf,objp->orgdate);
	  }
	 if (!xdr_compr(xdrs, &objp->comp_result)) {
		 return (FALSE);
	 }
	 if (!xdr_array(xdrs, (char **)&objp->message.message_val, (u_int *)&objp->message.message_len, ~0, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_array(xdrs, (char **)&objp->attachment.attachment_val, (u_int *)&objp->attachment.attachment_len, ~0, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }

 	 return (TRUE);
	} else if (xdrs->x_op == XDR_DECODE) {
	 if (!xdr_vector(xdrs, (char *)objp->from, 80, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->to, 80, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->subject, 64, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->fatt, 16, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 buf = XDR_INLINE(xdrs,3 * BYTES_PER_XDR_UNIT);
	   if (buf == NULL) {
		 if (!xdr_long(xdrs, &objp->flags)) {
			 return (FALSE);
		 }
		 if (!xdr_int(xdrs, &objp->orgtime)) {
			 return (FALSE);
		 }
		 if (!xdr_int(xdrs, &objp->orgdate)) {
			 return (FALSE);
		 }

	  }
	  else {
		 objp->flags = IXDR_GET_LONG(buf);
		 objp->orgtime = IXDR_GET_LONG(buf);
		 objp->orgdate = IXDR_GET_LONG(buf);
	  }
	 if (!xdr_compr(xdrs, &objp->comp_result)) {
		 return (FALSE);
	 }
	 if (!xdr_array(xdrs, (char **)&objp->message.message_val, (u_int *)&objp->message.message_len, ~0, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_array(xdrs, (char **)&objp->attachment.attachment_val, (u_int *)&objp->attachment.attachment_len, ~0, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 return(TRUE);
	}

	 if (!xdr_vector(xdrs, (char *)objp->from, 80, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->to, 80, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->subject, 64, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_vector(xdrs, (char *)objp->fatt, 16, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_long(xdrs, &objp->flags)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->orgtime)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->orgdate)) {
		 return (FALSE);
	 }
	 if (!xdr_compr(xdrs, &objp->comp_result)) {
		 return (FALSE);
	 }
	 if (!xdr_array(xdrs, (char **)&objp->message.message_val, (u_int *)&objp->message.message_len, ~0, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	 if (!xdr_array(xdrs, (char **)&objp->attachment.attachment_val, (u_int *)&objp->attachment.attachment_len, ~0, sizeof(char), (xdrproc_t)xdr_char)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_club_message(XDR *xdrs, club_message *objp)
{

	 register long *buf=buf;

	 if (!xdr_int(xdrs, &objp->result_code)) {
		 return (FALSE);
	 }
	switch (objp->result_code) {
	case 0:
		 if (!xdr_club_message_t(xdrs, &objp->club_message_u.message)) {
			 return (FALSE);
		 }
		break;
	default:
		break;
	}
	return (TRUE);
}
