/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "metaservices.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
metabbs_register_1(registration_package_t *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, metabbs_register, (xdrproc_t) xdr_registration_package_t, argp, (xdrproc_t) xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
metabbs_register_non_megistos_1(registration_package_t *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, metabbs_register_non_megistos, (xdrproc_t) xdr_registration_package_t, argp, (xdrproc_t) xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

info_package_p *
metabbs_request_info_1(char **argp, CLIENT *clnt)
{
	static info_package_p clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, metabbs_request_info, (xdrproc_t) xdr_wrapstring, argp, (xdrproc_t) xdr_info_package_p, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct club_list *
distclub_request_list_1(club_list_request_t *argp, CLIENT *clnt)
{
	static struct club_list clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, distclub_request_list, (xdrproc_t) xdr_club_list_request_t, argp, (xdrproc_t) xdr_club_list, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct club_header *
distclub_request_header_1(club_header_request_t *argp, CLIENT *clnt)
{
	static struct club_header clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, distclub_request_header, (xdrproc_t) xdr_club_header_request_t, argp, (xdrproc_t) xdr_club_header, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct ihave_list *
distclub_request_ihave_1(ihave_request_t *argp, CLIENT *clnt)
{
	static struct ihave_list clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, distclub_request_ihave, (xdrproc_t) xdr_ihave_request_t, argp, (xdrproc_t) xdr_ihave_list, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct club_message *
distclub_request_message_1(message_request_t *argp, CLIENT *clnt)
{
	static struct club_message clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, distclub_request_message, (xdrproc_t) xdr_message_request_t, argp, (xdrproc_t) xdr_club_message, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
