/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "metaservices.h"
#include <stdio.h>
#include <stdlib.h>/* getenv, exit */
#include <rpc/pmap_clnt.h> /* for pmap_unset */
#include <string.h> /* strcmp */ 
#include <sys/ioctl.h> /* ioctl, TIOCNOTTY */
#include <sys/types.h> /* open */
#include <sys/stat.h> /* open */
#include <fcntl.h> /* open */
#include <unistd.h> /* getdtablesize */
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <syslog.h>

#ifdef __STDC__
#define SIG_PF void(*)(int)
#endif
#include "parallelism.h"
extern int _rpcpmstart;		/* Started by a port monitor ? */
extern int _rpcfdtype;		/* Whether Stream or Datagram ? */

static
void _msgout(char* msg)
{
#ifdef RPC_SVC_FG
	if (_rpcpmstart)
		syslog(LOG_ERR, msg);
	else
		(void) fprintf(stderr, "%s\n", msg);
#else
	syslog(LOG_ERR, msg);
#endif
}

void
metabbs_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		registration_package_t metabbs_register_1_arg;
		registration_package_t metabbs_register_non_megistos_1_arg;
		char *metabbs_request_info_1_arg;
		club_list_request_t distclub_request_list_1_arg;
		club_header_request_t distclub_request_header_1_arg;
		ihave_request_t distclub_request_ihave_1_arg;
		message_request_t distclub_request_message_1_arg;
	} argument;
	char *result;
	xdrproc_t xdr_argument, xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply(transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case metabbs_register:
		xdr_argument = (xdrproc_t) xdr_registration_package_t;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) metabbs_register_1_svc;
		break;

	case metabbs_register_non_megistos:
		xdr_argument = (xdrproc_t) xdr_registration_package_t;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) metabbs_register_non_megistos_1_svc;
		break;

	case metabbs_request_info:
		xdr_argument = (xdrproc_t) xdr_wrapstring;
		xdr_result = (xdrproc_t) xdr_info_package_p;
		local = (char *(*)(char *, struct svc_req *)) metabbs_request_info_1_svc;
		break;

	case distclub_request_list:
		xdr_argument = (xdrproc_t) xdr_club_list_request_t;
		xdr_result = (xdrproc_t) xdr_club_list;
		local = (char *(*)(char *, struct svc_req *)) distclub_request_list_1_svc;
		break;

	case distclub_request_header:
		xdr_argument = (xdrproc_t) xdr_club_header_request_t;
		xdr_result = (xdrproc_t) xdr_club_header;
		local = (char *(*)(char *, struct svc_req *)) distclub_request_header_1_svc;
		break;

	case distclub_request_ihave:
		xdr_argument = (xdrproc_t) xdr_ihave_request_t;
		xdr_result = (xdrproc_t) xdr_ihave_list;
		local = (char *(*)(char *, struct svc_req *)) distclub_request_ihave_1_svc;
		break;

	case distclub_request_message:
		xdr_argument = (xdrproc_t) xdr_message_request_t;
		xdr_result = (xdrproc_t) xdr_club_message;
		local = (char *(*)(char *, struct svc_req *)) distclub_request_message_1_svc;
		break;

	default:
		svcerr_noproc(transp);
		return;
	}
	(void) memset((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs(transp, xdr_argument, (caddr_t) &argument)) {
		svcerr_decode(transp);
		return;
	}
	__CALL_PREAMBLE__
	result = (*local)((char *)&argument, rqstp);
	__CALL_POSTAMBLE__
	if (result != NULL && !svc_sendreply(transp, xdr_result, result)) {
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, xdr_argument, (caddr_t) &argument)) {
		_msgout("unable to free arguments");
		exit(1);
	}
	return;
}
