LEVEL2 {}

MAXLEN {Maximum line length in characters: 75} N 20 255

TXTUPLD {Text Editor Upload} S 50 File upload description


LEVEL3 {}


EDTMNU {[0;1m
[47;1;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;30;47m¿ [0m
[47;1;37m ³  [0;47;30m‚¨˜££ ¡æª editor ¡œ £â¤¦¬                                         [0;47;30m³ [0m
[47;1;37m ³  [0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ  [0;47;30m³ [0m
[47;1;37m ³  [0;47;31mA[30mppend  . . . ¨æ©Ÿœ©ž ¡œ £â¤¦¬   [31mN[30mew  . . . . . . .  Œâ¦ £ã¤¬£˜  ³ [0m
[47;1;37m ³  [0;47;31mC[30mhange . . . . €¢¢˜šã £¬¤ã£˜«¦ª   [31mR[30me-type . „§˜¤œ ©˜šàšã š¨˜££ãª  ³ [0m
[47;1;37m ³  [0;47;31mD[30melete  . . .  ƒ ˜š¨˜­ã š¨˜££ãª   [31mU[30mpload . . . €§¦©«¦¢ã ¡œ £â¤¦¬  ³ [0m
[47;1;37m ³  [0;47;31mH[30melp . . . . . . . . .  ¦ãŸœ ˜   [31mS[30mave  .  €§¦Ÿã¡œ¬©ž ¡˜  â¥¦›¦ª  ³ [0m
[47;1;37m ³  [0;47;31mI[30mnsert  . . „ ©˜šàšã š¨˜££ãª/é¤                                   ³ [0m
[47;1;37m ³  [0;47;31mL[30mist . . . .  „£­á¤ ©ž ¡œ £â¤¦¬   e[31mX[30mit  . . „š¡˜«á¢œ ¯ž ¡œ £â¤¦¬  ³ [0m
[47;1;37m À[0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m
[0;1m} T Editor menu


EDTMNUS {[0;1m
!Wƒé©«œ «ž¤ œ§ ¢¦šã ©˜ª ([33mA[37m,[33mC[37m,[33mD[37m,[33mH[37m,[33mI[37m,[33mL[37m,[33mN[37m,[33mR[37m,[33mU[37m,[33mS[37m,[33mX[37m, ã [33m?[37m š ˜ «¦ £œ¤¦ç): !)[0m} T Editor menu prompt


HELP {[2J[47;1;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;30;47m¿ [0m
[47;1;37m ³  [0;47;30m‚¨˜££ ¡æª editor ¡œ £â¤¦¬ - ¦ãŸœ ˜                                 [0;47;30m³ [0m
[47;1;37m ³  [0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ  [0;47;30m³ [0m
[47;1;37m ³  Append:[0;47;30m ’¦§¦Ÿœ«œå©«œ ©«¦ «â¢¦ª «¦¬ ¡œ £â¤¦¬, ¡˜  £§¦¨œå«œ ¤˜ §¨¦©-  ³ [0m
[47;1;37m ³  [0;30;47mŸâ©œ«œ š¨˜££âª ©« ª ã›ž ¬§á¨®¦¬©œª.   [1;37mChange:[0;47;30m ƒ ˜› ¡˜©å˜ find-rep-  ³ [0m
[47;1;37m ³  [0;30;47mlace ©œ £å˜ ã §œ¨ ©©æ«œ¨œª š¨˜££âª. [1;37mDelete:[0;47;30m ƒ ˜š¨˜­ã £å˜ª ã §œ¨ ©-  ³ [0m
[47;1;37m ³  [0;30;47m©¦«â¨à¤ š¨˜££é¤ (Ÿ˜ œ¨à«žŸœå«œ š ˜ œ§ ™œ™˜åà©ž).   [1;37mInsert:[0;47;30m ’¦§¦Ÿœ-  ³ [0m
[47;1;37m ³  [0;30;47m«œå©«œ â«©  é©«œ ¤˜ §¨¦©Ÿâ«œ«œ ¡œå£œ¤¦ ˜£â©àª §¨ ¤ ˜§æ £å˜ š¨˜££ã,  ³ [0m
[47;1;37m ³  [0;30;47m¡˜  £§¦¨œå«œ ¤˜ §¨¦©Ÿâ©œ«œ š¨˜££âª ©« ª ã›ž ¬§á¨®¦¬©œª.  [1;37mList:[0;47;30m „£-  ³ [0m
[47;1;37m ³  [0;30;47m­˜¤åœ  «¦ ¡œå£œ¤æ ©˜ª £œ ˜¨ Ÿ£¦çª š¨˜££é¤.     [1;37mNew:[0;47;30m „§ «¨â§œ  «ž¤  ³ [0m
[47;1;37m ³  [0;47;30m§¢ã¨ž  › ˜š¨˜­ã  «¦¬  ¡œ £â¤¦¬.  ‡˜  œ¨à«žŸœå«œ  š ˜  œ§ ™œ™˜åà©ž.  ³ [0m
[47;1;37m ³  Retype:[0;47;30m „§ «¨â§œ   «ž¤ œ§˜¤œ ©˜šàšã  £ ˜ª š¨˜££ãª,  ®à¨åª £œ«˜™¦¢ã  ³ [0m
[47;1;37m ³  [0;47;30m«¦¬ ¬§æ¢¦ §¦¬ ¡œ £â¤¦¬.     [1;37mUpload:[0;47;30m „§ «¨â§œ  «ž¤ œ ©˜šàšã â«¦ £¦¬  ³ [0m
[47;1;37m ³  [0;47;30m¡œ £â¤¦¬ £œ  «ž¤ ™¦ãŸœ ˜ œ¤æª §¨à«¦¡æ¢¦¬  «žª ˜¨œ©¡œå˜ª ©˜ª  (§.®.  ³ [0m
[47;1;37m ³  [0;47;30mZ-modem).       [1;37mSave:[0;47;30m €§¦Ÿž¡œçœ  «¦ ¡œå£œ¤æ ©˜ª ¡˜  «œ¨£˜«åœ  «¦¤  ³ [0m
[47;1;37m ³  [0;47;30meditor.     [1;37mExit:[0;47;30m „š¡˜«˜¢œå§œ  «¦ ¡œå£œ¤¦ ®à¨åª ¤˜ «¦ ˜§¦Ÿž¡œç©œ ,  ³ [0m
[47;1;37m ³  [0;47;30m¡˜  «œ¨£˜«åœ  «¦¤ editor.                                          ³ [0m
[47;1;37m À[0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m
[0;1m} T Editor help


ERRSEL {[0;1;31m
† œ§ ¢¦šã "%c" ›œ¤ œå¤˜  ›¬¤˜«ã.
} T Editor rebuff of help menu selection


LLDTBE {[0;1;32m
!W† «œ¢œ¬«˜å˜ š¨˜££ã › œš¨á­ž, «¦ ¡œå£œ¤¦ ©˜ª œå¤˜  §¢â¦¤ á›œ ¦.!)
[0;1m
} T Editor notify of last line deleted


ENTTXT {[0;1m
!W‘œ ˜¬«æ «¦ ©ž£œå¦ ˜¨®åœ«œ «ž¤ œ ©˜šàšã «¦¬ ¡œ £â¤¦¬ ©˜ª.!)

!J[32m’¦ ¡œå£œ¤¦ £§¦¨œå ¤˜ §œ¨ â®œ  £â®¨  [37m%d[32m ®˜¨˜¡«ã¨œª.
ƒé©«œ [33mOK[32m £æ¤¦ «¦¬ ©œ £ ˜ ¡œ¤ã š¨˜££ã š ˜ « ª œ§ ¢¦šâª ©¬¤«á¡«ž,
[33m/s[32m (save) š ˜ ¤˜ ˜§¦Ÿž¡œç©œ«œ ¡˜«œ¬Ÿœå˜¤ «¦ ¡œå£œ¤æ ©˜ª,
[33m/c[32m (cancel) š ˜ ˜¡ç¨à©ž (› ˜š¨˜­ã) «žª «œ¢œ¬«˜å˜ª š¨˜££ãª,
[33m/u[32m (upload) š ˜ ˜§¦©«¦¢ã â«¦ £¦¬ ¡œ £â¤¦¬, ã [33m?[32m š ˜ ™¦ãŸœ ˜.!)
[0m} T Editor instructions for typing message


SIZINFO {[0;1;32m
(š¨˜££âª: [37m%d[32m, bytes: [37m%d[32m ˜§æ [37m%d[32m)
[0;1m} T Editor text size info


ENTHLP {[0;1;32m
!J‘¬¤â® ©«œ ¤˜ ›å¤œ«œ ¡œå£œ¤¦.
ƒé©«œ [33mOK[32m £æ¤¦ «¦¬ ©œ £ ˜ ¡œ¤ã š¨˜££ã š ˜ « ª œ§ ¢¦šâª ©¬¤«á¡«ž,
[33m/s[32m (save) š ˜ ¤˜ ˜§¦Ÿž¡œç©œ«œ ¡˜«œ¬Ÿœå˜¤ «¦ ¡œå£œ¤æ ©˜ª,
[33m/c[32m (cancel) š ˜ ˜¡ç¨à©ž (› ˜š¨˜­ã) «žª «œ¢œ¬«˜å˜ª š¨˜££ãª,
[33m/u[32m (upload) š ˜ ˜§¦©«¦¢ã â«¦ £¦¬ ¡œ £â¤¦¬, ã [33m?[32m š ˜ ™¦ãŸœ ˜.!)

[0;1m} T Editor instructions given in mid-message


RULER {[0;1m
[36mÃÄÄÄÂÄÄÄÄÒÄÄÄÄÂÄÄÄÄÒÄÄÄÄÂÄÄÄÄÒÄÄÄÄÂÄ[37mÞÝ[36mÄÒÄÄÄÄÂÄÄÄÄÒÄÄÄÂÄÄÄÄÒÄÄÄÄÂÄÄÄÄÒÄÄÄÄ´
[0;1m
} T Editor ruler


REMINDER {[0;1;33;5m
!WÛÛ[0;1;33m  “„Œ‡“‹ˆ‘†: !iŽ › ¦¨Ÿà«ãª §œ¨ â®œ  ã›ž ¡œå£œ¤¦
(š¨˜££âª: [37m%d[33m, bytes: [37m%d[33m).!)
!0l[0;1m} T Editor reminder there's already text (eg quote) in the buffer


SIZEWARN {[0;1;33;5m
!WÛÛ[0;1;33m  Ž‘Ž•†: !iBytes §¦¬ ˜§¦£â¤¦¬¤ œ¢œçŸœ¨˜: [37m%d[33m.!)
!0l[0;1m} T Editor warning: remaining space less than one line


CANCEL {[0;1;33m
† š¨˜££ã %d › œš¨á­ž. (š¨˜££âª: [37m%d[32m, bytes: [37m%d[32m ˜§æ [37m%d[32m)
[0;1m} T Editor last line canceled


NCANCEL {[0;1;31m
ƒœ¤ ¬§á¨®¦¬¤ á¢¢œª š¨˜££âª š ˜ › ˜š¨˜­ã.
[0;1m} T Editor no more lines to delete


TXTLSTH {[0;1;32m
„£­á¤ ©ž «¦¬ ¡œ £â¤¦¬ ©˜ª:
[0;1m} T Editor displaying text


TXTHDR {
} T Editr text list header


TXTLST {[0m%03d [1m%s
} T Editor text list with line numbers 


INVLIN {[0;1m
€¨ Ÿ£æª š¨˜££ãª œ¡«æª «à¤ ¦¨åà¤.
} T Editor rebuff of bad line number


RWCHLN {[0;1m
!W€¢¢˜šã §¦ áª š¨˜££ãª/é¤; ƒé©«œ â¤˜¤ ˜¨ Ÿ£æ š¨˜££ãª,
ã â¤˜ › á©«ž£˜ š¨˜££é¤ ©«ž¤ £¦¨­ã n-m, §® %d-%d = æ¢œª ¦  š¨˜££âª)!) [0m} T Editor asking in what line to change text


RNGERR {[0;1;31m
!W‹ž ˜§¦›œ¡«æ › á©«ž£˜ š¨˜££é¤. ‹§¦¨œå«œ ¤˜ ›é©œ«œ:!)

* „¤˜¤ ˜¨ Ÿ£æ š¨˜££ãª (˜§æ %d £â®¨  %d)
* „¤˜ › á©«ž£˜ š¨˜££é¤ (§® 1-100, ã 1- ã -100)
[0;1m} T Editor Line number range invalid


RANGEOK {[0;1;32m
„§ ¢â¥˜«œ «¦ › á©«ž£˜ š¨˜££é¤ [37m%d-%d[32m.
[0;1m} T Editor line number range OK


FIND {[0;1m
€¢¢˜šã «å¤¦ª ¡œ £â¤¦¬;
:[0m} T Editor asking what text to change (source)


REPLACE {[0;1m
ƒé©«œ «¦ ¤â¦ ¡œå£œ¤¦ «é¨˜ (˜«ã©«œ ˜§¢éª Enter š ˜ ¤˜ › ˜š¨˜­œå)
:[0m} T Editor asking change to what (target)


REPLERR {[0;1m
!W‚¨˜££ã [37m%d[31m: !i’¦ ¡œå£œ¤¦ Ÿ˜ ¥œ§œ¨á©œ  «¦
æ¨ ¦ «à¤ [37m%d[31m bytes ˜¤ œ§œ¥œ¨š˜©«é ˜¬«ã «ž¤ š¨˜££ã.
† › ˜› ¡˜©å˜ ©«˜£˜«áœ  œ›é.!)
!0l[0;1m} T Editor process made text too long.


NCHNGD {[0;1;32m
€¢¢˜šâª §¦¬ âš ¤˜¤ ©«¦ ¡œå£œ¤¦: [37m%d
[0;1m} T Editor reporting number of text changes


NLNRDS {[0;1m
’¦ ¡œå£œ¤¦ â®œ  «é¨˜ àª œ¥ãª:
[0;1m} T Editor reporting actual changes


RETYPE {[0;1m
¦ á š¨˜££ã Ÿâ¢œ«œ ¤˜ œ§˜¤œ ©ášœ«œ; (%d-%d) [0m} T Editor retype what line


EDITLN {[0;1m
ƒé©«œ «ž ¤â˜ š¨˜££ã.
} T Editor R)etype line


DWDELN {[0;1m
!W¦ œª š¨˜££âª Ÿâ¢œ«œ ¤˜ › ˜š¨á¯œ«œ; ƒé©«œ â¤˜¤ ˜¨ Ÿ£æ š¨˜££ãª,
ã â¤˜ › á©«ž£˜ š¨˜££é¤ ©«ž¤ £¦¨­ã n-m, §® %d-%d = æ¢œª ¦  š¨˜££âª)!) [0m} T Editor D)elete what line


DELLIN {[0;1m
„å©«œ ©åš¦¬¨¦ª æ«  Ÿâ¢œ«œ ¤˜ › ˜š¨á¯œ«œ ˜¬«ã «ž š¨˜££ã;
( [[33mY[0;1m~]es=¤˜  / [[33mN[0;1m~]o=æ®  ) } T Editor confirm deletion of 1 line


DELLNS {[0;1m
„å©«œ ©åš¦¬¨¦ª æ«  Ÿâ¢œ«œ ¤˜ › ˜š¨á¯œ«œ ˜¬«âª « ª š¨˜££âª;
([[33mY[0;1m~]es=¤˜  / [[33mN[0;1m~]o=æ® ) } T Editor confirm deletion of >1 lines


YORN {[0;1;31m
˜¨˜¡˜¢é ˜§˜¤«ã©«œ £œ [[33m“[31m~]es=¤˜  ã [[33mN[31m~]o=æ® .
[0;1m} T Editor rebuff bad answer to Y/N question


INSERT {[0;1m
„ ©˜šàšã §¨å¤ ˜§æ §¦ á š¨˜££ã; (%d-%d) [0m} T Editor Insert question


ASKNEW {[0;1;31m
!J€¤ ˜§˜¤«ã©œ«œ £œ [33mY[31mes (¤˜ ) ©«ž¤ §˜¨˜¡á«à œ¨é«ž©ž,
«¦ ¡œå£œ¤æ ©˜ª Ÿ˜ œ¥˜¢ž­Ÿœå.!)
[0;1m
!W‡â¢œ«œ ¤˜ ¡˜Ÿ˜¨å©œ«œ «¦ ¡œå£œ¤æ ©˜ª; ([[33m“[37m]es=¤˜  ã [[33mN[37m]o=æ® ) [0m!)} T Editor confirm text wipe-out


TOOBIG {[0;1;31m
!Jƒœ¤ ¬§á¨®œ  ˜¨¡œ«æª ®é¨¦ª š ˜ ¤˜ ©¬¤œ®å©œ«œ «¦ ¡œå£œ¤æ ©˜ª.
ƒ ˜š¨á¯«œ ã ˜¢¢á¥«œ ¡á§¦ ˜ š¨˜££ã ã š¨˜££âª.!)
[0;1m} T Editor rebuff -- not enough room in text buffer


XFERERR {[0;1;31m
!JŠ¬§á£˜ , «¦ ˜¨®œå¦ §¦¬ £æ¢ ª ˜§¦©«œå¢˜«œ ®áŸž¡œ. ˜¨˜¡˜¢¦ç£œ
œ ›¦§¦ œå©«œ «¦¤ ®œ ¨ ©«ã ©¬©«ã£˜«¦ª š ˜ «¦ ©¬£™á¤.!)
[0;1m} T Editor error, unable to open uploaded file


SIZERR {[0;1m
!W’¦ ¡œå£œ¤¦ ¥œ§œ¨¤áœ  «¦ æ¨ ¦ «à¤ [37m%d[31m bytes.
† › ˜› ¡˜©å˜ ©«˜£˜«áœ  œ›é.!)
!0l[0;1m} T Editor process made text too long.


ABORT {[0;1;31m
!J€¤ ˜§˜¤«ã©œ«œ £œ [33mY[31mes (¤˜ ) ©«ž¤ §˜¨˜¡á«à œ¨é«ž©ž,
«¦ ¡œå£œ¤æ ©˜ª Ÿ˜ ®˜Ÿœå, ¡˜  Ÿ˜ ™šœå«œ ˜§æ «¦¤ editor.!)
[0;1m
!W‡â¢œ«œ ¤˜ œš¡˜«˜¢œå¯œ«œ «¦ ¡œå£œ¤¦ ¡˜  «¦¤ editor; ([[33m“[37m]es=¤˜  ã [[33mN[37m]o=æ® ) [0m!)} T Editor confirm exit


SAVEERR {[0;1;31m
!JŠ¬§á£˜ , ¬§ã¨¥œ ¢áŸ¦ª œšš¨˜­ãª ˜¤áš¤à©žª ¡˜«á «ž¤ ˜§¦Ÿã¡œ¬©ž
«¦¬ ˜¨®œå¦¬ («ç§¦ª Unix ¢áŸ¦¬ª: #%d, %s).!)
[0;1m} T Editor error, unable to save file


LANG {}


EDTMNU {[0;1m
[47;1;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;30;47m¿ [0m
[47;1;37m ³  [0;47;30mLine editor                                                       [0;47;30m³ [0m
[47;1;37m ³  [0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ  [0;47;30m³ [0m
[47;1;37m ³  [0;47;31mA[30mppend  . . . . . . .  Add text   [31mN[30mew  . . . . . . Wipe-out text  ³ [0m
[47;1;37m ³  [0;47;31mC[30mhange . . .  Find/Replace text   [31mR[30me-type . . . .  Retype a line  ³ [0m
[47;1;37m ³  [0;47;31mD[30melete  . . . .  Delete line(s)   [31mU[30mpload . . . . . . Upload text  ³ [0m
[47;1;37m ³  [0;47;31mH[30melp . . . . .  Command Summary   [31mS[30mave  . . . Save text and exit  ³ [0m
[47;1;37m ³  [0;47;31mI[30mnsert  . . . .  Insert line(s)                                   ³ [0m
[47;1;37m ³  [0;47;31mL[30mist . . . . . . . Display text   e[31mX[30mit . . . Quit without saving  ³ [0m
[47;1;37m À[0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m
[0;1m} T Editor menu


EDTMNUS {[0;1m
!WPlease enter your choice ([33mA[37m,[33mC[37m,[33mD[37m,[33mH[37m,[33mI[37m,[33mL[37m,[33mN[37m,[33mR[37m,[33mU[37m,[33mS[37m,[33mX[37m, or [33m?[37m for the menu): !)[0m} T Editor menu prompt


HELP {[2J[47;1;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;30;47m¿ [0m
[47;1;37m ³  [0;47;30mLine editor Help                                                    [0;47;30m³ [0m
[47;1;37m ³  [0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ  [0;47;30m³ [0m
[47;1;37m ³  Append:[0;47;30m You are  placed at the  end of the  text, and you may  add  ³ [0m
[47;1;37m ³  [0;30;47mlines.    [1;37mChange:[0;47;30m Find and replace text in a given range of lines.  ³ [0m
[47;1;37m ³  Delete:[0;47;30m Delete a range of lines (you will be asked to confirm your  ³ [0m
[47;1;37m ³  [0;30;47mintentions).  [1;37mInsert:[0;47;30m You are placed right before a given line and  ³ [0m
[47;1;37m ³  [0;30;47myou may insert text at that point.  [1;37mList:[0;47;30m Displays the edited text  ³ [0m
[47;1;37m ³  [0;30;47mwith line numbers.       [1;37mNew:[0;47;30m Allows you to wipe out your text and  ³ [0m
[47;1;37m ³  [0;30;47mrestart  from   scratch.  You  will  be  asked  to   confirm  your  ³ [0m
[47;1;37m ³  [0;30;47mintentions.      [1;37mRetype:[0;47;30m Allows you to retype a given line without  ³ [0m
[47;1;37m ³  [0;30;47maltering the rest of the text.     [1;37mUpload:[0;47;30m Allows the insertion of  ³ [0m
[47;1;37m ³  [0;30;47mprepared text using a file transfer protocol.     [1;37mSave:[0;47;30m Stores the  ³ [0m
[47;1;37m ³  [0;30;47mtext and leaves the editor.  [1;37mExit:[0;47;30m Quits the editor without saving  ³ [0m
[47;1;37m ³  [0;30;47mits contents.                                                       ³ [0m
[47;1;37m À[0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m
[0;1m} T Editor help


ERRSEL {[0;1;31m
"%c" is not an option.
} T Editor rebuff of help menu selection


LLDTBE {[0;1;32m
!WThe last line has already been deleted; there is no more text.!)
[0;1m
} T Editor notify of last line deleted


ENTTXT {[0;1m
!WYou may now begin typing your text.!)

!J[32mThe text may contain up to [37m%d[32m characters.
Enter [33mOK[32m on a line by itself for the editor menu,
[33m/s[32m to save the text and exit,
[33m/c[32m to cancel (delete) the last line,
[33m/u[32m to upload a prepared text file, or [33m?[32m for help.!)
[0m} T Editor instructions for typing message


SIZINFO {[0;1;32m
(line(s): [37m%d[32m, bytes: [37m%d[32m out of [37m%d[32m)
[0;1m} T Editor text size info


ENTHLP {[0;1;32m
!JCarry on entering text.
Enter [33mOK[32m on a line by itself for the editor menu,
[33m/s[32m to save the text and exit,
[33m/c[32m to cancel (delete) the last line,
[33m/u[32m to upload a prepared text file, or [33m?[32m for help.!)

[0;1m} T Editor instructions given in mid-message


RULER {[0;1m
[36mÃÄÄÄÂÄÄÄÄÒÄÄÄÄÂÄÄÄÄÒÄÄÄÄÂÄÄÄÄÒÄÄÄÄÂÄ[37mÞÝ[36mÄÒÄÄÄÄÂÄÄÄÄÒÄÄÄÂÄÄÄÄÒÄÄÄÄÂÄÄÄÄÒÄÄÄÄ´
[0;1m
} T Editor ruler


REMINDER {[0;1;33;5m
!WÛÛ[0;1;33m  REMINDER: !iThe editor already contains text
(line(s): [37m%d[33m, bytes: [37m%d[33m).!)
!0l[0;1m} T Editor reminder there's already text (eg quote) in the buffer


SIZEWARN {[0;1;33;5m
!WÛÛ[0;1;33m  WARNING: !iFree bytes remaining: [37m%d[33m.!)
!0l[0;1m} T Editor warning: remaining space less than one line


CANCEL {[0;1;33m
Line %d was deleted. (line(s): [37m%d[32m, bytes: [37m%d[32m out of [37m%d[32m)
[0;1m} T Editor last line canceled


NCANCEL {[0;1;31m
There are no more lines to delete.
[0;1m} T Editor no more lines to delete


TXTLSTH {[0;1;32m
Displaying your text:
[0;1m} T Editor displaying text


TXTHDR {
} T Editr text list header


TXTLST {[0m%03d [1m%s
} T Editor text list with line numbers 


INVLIN {[0;1m
Line number out of bounds.
} T Editor rebuff of bad line number


RWCHLN {[0;1m
!WChange what line(s)? Enter a line number,
or a line number range in the format n-m, eg %d-%d = all lines)!) [0m} T Editor asking in what line to change text


RNGERR {[0;1;31m
!WInvalid line number range. You may enter:!)

* A single line number (%d to %d)
* A line number range (eg 1-100 or 1- or -100)
[0;1m} T Editor Line number range invalid


RANGEOK {[0;1;32m
You have entered the range [37m%d-%d[32m.
[0;1m} T Editor line number range OK


FIND {[0;1m
Change what text?
:[0m} T Editor asking what text to change (source)


REPLACE {[0;1m
Change the text into what? (Just press Enter to delete it)
:[0m} T Editor asking change to what (target)


REPLERR {[0;1m
!WLine [37m%d[31m: !iThe text will grow beyond [37m%d[31m bytes
if we process this line. This procedure stops here.!)
!0l[0;1m} T Editor process made text too long.


NCHNGD {[0;1;32m
Number of changes to the text: [37m%d
[0;1m} T Editor reporting number of text changes


NLNRDS {[0;1m
The text looks like this now:
[0;1m} T Editor reporting actual changes


RETYPE {[0;1m
What line would you like to retype? (%d-%d) [0m} T Editor retype what line


EDITLN {[0;1m
Please retype the line.
} T Editor R)etype line


DWDELN {[0;1m
!WWhat line(s) would you like to delete? Enter a line number,
or a line number range in the format n-m, eg %d-%d = all lines)!) [0m} T Editor D)elete what line


DELLIN {[0;1m
Are you sure you want to delete this line?
([[33mY[0;1m]es / [[33mN[0;1m]o) } T Editor confirm deletion of 1 line


DELLNS {[0;1m
Are you sure you want to delete these lines?
([[33mY[0;1m]es / [[33mN[0;1m]o) } T Editor confirm deletion of >1 lines


YORN {[0;1;31m
Please enter either [[33m“[31m]es or [[33mN[31m~]o.
[0;1m} T Editor rebuff bad answer to Y/N question


INSERT {[0;1m
Insert text before what line? (%d-%d) [0m} T Editor Insert question


ASKNEW {[0;1;31m
!JIf you answer '[33mY[31mes' to the following question,
your text will be wiped out completely.!)
[0;1m
!WWould you like to wipe out your text? ([[33m“[37m]es / [[33mN[37m]o) [0m!)} T Editor confirm text wipe-out


TOOBIG {[0;1;31m
!JThere isn't enough space for you to continue typing.
Please either delete or change a line or lines. !)
[0;1m} T Editor rebuff -- not enough room in text buffer


XFERERR {[0;1;31m
!JSorry, the file you just uploaded was lost. Please
notify the system operator about this incident.!)
[0;1m} T Editor error, unable to open uploaded file


SIZERR {[0;1m
!WThe text is longer than [37m%d[31m bytes.
This process stops here.!)
!0l[0;1m} T Editor process made text too long.


ABORT {[0;1;31m
!JIf you answer '[33mY[31mes' to the following question,
your text will be lost, and you will quit the editor.!)
[0;1m
!WQuit the editor without saving? ([[33m“[37m]es / [[33mN[37m]o) [0m!)} T Editor confirm exit


SAVEERR {[0;1;31m
!JSorry, there was an I/O error while saving the file (Unix error: #%d,
%s).!)
[0;1m} T Editor error, unable to save file


LANGEND {}
