/* Automatically generated by mkversion.sh , do NOT edit. */

#define BJ_MAJORVERSION "0"
#define BJ_MINORVERSION "7"
#define BJ_COMPILED_BY  "bbs@vennea"
#define BJ_MAKE_NUMBER  "302"
#define BJ_DATE         "01-05-01 23:46"
