/***********************************************************
 **                                                       **
 **  This header file generated by msgidx. Do not alter.  **
 **                                                       **
 ***********************************************************/

#ifndef __OFFLINE_BULLETINS_UNAMBIGUOUS__
#define	DEFBLT 1
#define	DEFANSI 2
#define	BLTIDFN 3
#define	OBVT 4
#define	OBLT 5
#define	OBINDEX 6
#define	OBANSI 7
#define	OBDL 8
#define	OBDLMK 9
#define	OBDLMT 10
#define	OBDLPR 11
#define	OBDLFT 12
#define	OBDLUB 13
#define	OBDLOK 14
#define	OBDLIO 15
#define	OBDLCR 16
#define	OBUPL 17
#define	OBULIDOK 18
#define	OBULIDNN 19
#define	OBULRR 20
#define	OBULUC 21
#define	OBULUB 22
#define	OBULOK 23
#define	OBULEND 24
#else
#define	OFFLINE_BULLETINS_DEFBLT 1
#define	OFFLINE_BULLETINS_DEFANSI 2
#define	OFFLINE_BULLETINS_BLTIDFN 3
#define	OFFLINE_BULLETINS_OBVT 4
#define	OFFLINE_BULLETINS_OBLT 5
#define	OFFLINE_BULLETINS_OBINDEX 6
#define	OFFLINE_BULLETINS_OBANSI 7
#define	OFFLINE_BULLETINS_OBDL 8
#define	OFFLINE_BULLETINS_OBDLMK 9
#define	OFFLINE_BULLETINS_OBDLMT 10
#define	OFFLINE_BULLETINS_OBDLPR 11
#define	OFFLINE_BULLETINS_OBDLFT 12
#define	OFFLINE_BULLETINS_OBDLUB 13
#define	OFFLINE_BULLETINS_OBDLOK 14
#define	OFFLINE_BULLETINS_OBDLIO 15
#define	OFFLINE_BULLETINS_OBDLCR 16
#define	OFFLINE_BULLETINS_OBUPL 17
#define	OFFLINE_BULLETINS_OBULIDOK 18
#define	OFFLINE_BULLETINS_OBULIDNN 19
#define	OFFLINE_BULLETINS_OBULRR 20
#define	OFFLINE_BULLETINS_OBULUC 21
#define	OFFLINE_BULLETINS_OBULUB 22
#define	OFFLINE_BULLETINS_OBULOK 23
#define	OFFLINE_BULLETINS_OBULEND 24
#endif /* __OFFLINE_BULLETINS_UNAMBIGUOUS__ */
