/***********************************************************
 **                                                       **
 **  This header file generated by msgidx. Do not alter.  **
 **                                                       **
 ***********************************************************/

#ifndef __METABBS_CLIENT_UNAMBIGUOUS__
#define	USRLRM 1
#define	QRYLRM 2
#define	HOSTS 3
#define	LOCAL 4
#define	BEGIN 5
#define	LOOKUP 6
#define	DNSFAIL 7
#define	SENDREQ 8
#define	SENDOK 9
#define	SENDERR 10
#define	NOSYS 11
#define	SYSCOUNT1 12
#define	SYSCOUNT 13
#define	WARNTIME 14
#define	MINSNG 15
#define	MINPLR 16
#define	KICKOUT 17
#define	SYSTBLH 18
#define	SYSTBLL 19
#define	SYSTBLN 20
#define	SYSTBLF 21
#define	SYSMNU 22
#define	ERROPT 23
#define	BBSINFO 24
#define	BBSINFN 25
#define	BBSAD 26
#define	RUNTEL 27
#else
#define	METABBS_CLIENT_USRLRM 1
#define	METABBS_CLIENT_QRYLRM 2
#define	METABBS_CLIENT_HOSTS 3
#define	METABBS_CLIENT_LOCAL 4
#define	METABBS_CLIENT_BEGIN 5
#define	METABBS_CLIENT_LOOKUP 6
#define	METABBS_CLIENT_DNSFAIL 7
#define	METABBS_CLIENT_SENDREQ 8
#define	METABBS_CLIENT_SENDOK 9
#define	METABBS_CLIENT_SENDERR 10
#define	METABBS_CLIENT_NOSYS 11
#define	METABBS_CLIENT_SYSCOUNT1 12
#define	METABBS_CLIENT_SYSCOUNT 13
#define	METABBS_CLIENT_WARNTIME 14
#define	METABBS_CLIENT_MINSNG 15
#define	METABBS_CLIENT_MINPLR 16
#define	METABBS_CLIENT_KICKOUT 17
#define	METABBS_CLIENT_SYSTBLH 18
#define	METABBS_CLIENT_SYSTBLL 19
#define	METABBS_CLIENT_SYSTBLN 20
#define	METABBS_CLIENT_SYSTBLF 21
#define	METABBS_CLIENT_SYSMNU 22
#define	METABBS_CLIENT_ERROPT 23
#define	METABBS_CLIENT_BBSINFO 24
#define	METABBS_CLIENT_BBSINFN 25
#define	METABBS_CLIENT_BBSAD 26
#define	METABBS_CLIENT_RUNTEL 27
#endif /* __METABBS_CLIENT_UNAMBIGUOUS__ */
