/***********************************************************
 **                                                       **
 **  This header file generated by msgidx. Do not alter.  **
 **                                                       **
 ***********************************************************/

#ifndef __OFFLINE_GRAFFITI_UNAMBIGUOUS__
#define	DEFWALL 1
#define	DEFANSI 2
#define	DEFLINS 3
#define	WALLFIL 4
#define	OGVT 5
#define	OGLT 6
#define	OGWALL 7
#define	OGANSI 8
#define	OGLINES 9
#define	DLHDR 10
#define	DLDMT 11
#define	DLNAX 12
#define	DLOK 13
#define	ULWRH 14
#define	ULWMT 15
#define	ULWRT 16
#define	ULNWR 17
#define	WRTSNG 18
#define	WRTPLR 19
#define	LINSNG 20
#define	LINPLR 21
#else
#define	OFFLINE_GRAFFITI_DEFWALL 1
#define	OFFLINE_GRAFFITI_DEFANSI 2
#define	OFFLINE_GRAFFITI_DEFLINS 3
#define	OFFLINE_GRAFFITI_WALLFIL 4
#define	OFFLINE_GRAFFITI_OGVT 5
#define	OFFLINE_GRAFFITI_OGLT 6
#define	OFFLINE_GRAFFITI_OGWALL 7
#define	OFFLINE_GRAFFITI_OGANSI 8
#define	OFFLINE_GRAFFITI_OGLINES 9
#define	OFFLINE_GRAFFITI_DLHDR 10
#define	OFFLINE_GRAFFITI_DLDMT 11
#define	OFFLINE_GRAFFITI_DLNAX 12
#define	OFFLINE_GRAFFITI_DLOK 13
#define	OFFLINE_GRAFFITI_ULWRH 14
#define	OFFLINE_GRAFFITI_ULWMT 15
#define	OFFLINE_GRAFFITI_ULWRT 16
#define	OFFLINE_GRAFFITI_ULNWR 17
#define	OFFLINE_GRAFFITI_WRTSNG 18
#define	OFFLINE_GRAFFITI_WRTPLR 19
#define	OFFLINE_GRAFFITI_LINSNG 20
#define	OFFLINE_GRAFFITI_LINPLR 21
#endif /* __OFFLINE_GRAFFITI_UNAMBIGUOUS__ */
