/***********************************************************
 **                                                       **
 **  This header file generated by msgidx. Do not alter.  **
 **                                                       **
 ***********************************************************/

#ifndef __STATS_UNAMBIGUOUS__
#define	GRWID 1
#define	BARCHR 2
#define	HLFCHR 3
#define	CNTOPN 4
#define	BAUD 5
#define	CLSS 6
#define	DAY 7
#define	MODS 8
#define	TTY 9
#define	AVGCRD 10
#define	AVGMIN 11
#define	AVGCLL 12
#define	TOTCRD 13
#define	TOTMIN 14
#define	TOTCLL 15
#define	TODAY 16
#define	MONTH 17
#define	YEAR 18
#define	EVER 19
#define	HEADER 20
#define	TOP 21
#define	GRLABEL 22
#define	GRBAR 23
#define	GRNUM 24
#define	BOTTOM 25
#define	FTRAVG 26
#define	FTRTOT 27
#define	FTREND 28
#define	AGESTATS 29
#else
#define	STATS_GRWID 1
#define	STATS_BARCHR 2
#define	STATS_HLFCHR 3
#define	STATS_CNTOPN 4
#define	STATS_BAUD 5
#define	STATS_CLSS 6
#define	STATS_DAY 7
#define	STATS_MODS 8
#define	STATS_TTY 9
#define	STATS_AVGCRD 10
#define	STATS_AVGMIN 11
#define	STATS_AVGCLL 12
#define	STATS_TOTCRD 13
#define	STATS_TOTMIN 14
#define	STATS_TOTCLL 15
#define	STATS_TODAY 16
#define	STATS_MONTH 17
#define	STATS_YEAR 18
#define	STATS_EVER 19
#define	STATS_HEADER 20
#define	STATS_TOP 21
#define	STATS_GRLABEL 22
#define	STATS_GRBAR 23
#define	STATS_GRNUM 24
#define	STATS_BOTTOM 25
#define	STATS_FTRAVG 26
#define	STATS_FTRTOT 27
#define	STATS_FTREND 28
#define	STATS_AGESTATS 29
#endif /* __STATS_UNAMBIGUOUS__ */
