/***********************************************************
 **                                                       **
 **  This header file generated by msgidx. Do not alter.  **
 **                                                       **
 ***********************************************************/

#ifndef __BBSDIALOG_SAMPLE_UNAMBIGUOUS__
#define	VISUAL 1
#define	LINEAR 2
#define	FIELD1 3
#define	FIELD2 4
#define	FIELD3 5
#define	FIELD4 6
#define	FIELD5 7
#define	FIELD6 8
#define	FIELD7 9
#else
#define	BBSDIALOG_SAMPLE_VISUAL 1
#define	BBSDIALOG_SAMPLE_LINEAR 2
#define	BBSDIALOG_SAMPLE_FIELD1 3
#define	BBSDIALOG_SAMPLE_FIELD2 4
#define	BBSDIALOG_SAMPLE_FIELD3 5
#define	BBSDIALOG_SAMPLE_FIELD4 6
#define	BBSDIALOG_SAMPLE_FIELD5 7
#define	BBSDIALOG_SAMPLE_FIELD6 8
#define	BBSDIALOG_SAMPLE_FIELD7 9
#endif /* __BBSDIALOG_SAMPLE_UNAMBIGUOUS__ */
