#!/bin/sh

# Locate GNU make

TRY="make gmake gnumake /usr/local/bin/make /usr/local/bin/gnumake"

a=`(
    for a in $TRY; do
	($a --version 2>&1 | grep -q "GNU Make") && echo $a
    done
)|head -1`

if [ .$a = . ]; then exit 1; fi
echo $a
