/***********************************************************
 **                                                       **
 **  This header file generated by msgidx. Do not alter.  **
 **                                                       **
 ***********************************************************/

#ifndef __LINED_UNAMBIGUOUS__
#define	MAXLEN 1
#define	TXTUPLD 2
#define	EDTMNU 3
#define	EDTMNUS 4
#define	HELP 5
#define	ERRSEL 6
#define	LLDTBE 7
#define	ENTTXT 8
#define	SIZINFO 9
#define	ENTHLP 10
#define	RULER 11
#define	REMINDER 12
#define	SIZEWARN 13
#define	CANCEL 14
#define	NCANCEL 15
#define	TXTLSTH 16
#define	TXTHDR 17
#define	TXTLST 18
#define	INVLIN 19
#define	RWCHLN 20
#define	RNGERR 21
#define	RANGEOK 22
#define	FIND 23
#define	REPLACE 24
#define	REPLERR 25
#define	NCHNGD 26
#define	NLNRDS 27
#define	RETYPE 28
#define	EDITLN 29
#define	DWDELN 30
#define	DELLIN 31
#define	DELLNS 32
#define	YORN 33
#define	INSERT 34
#define	ASKNEW 35
#define	TOOBIG 36
#define	XFERERR 37
#define	SIZERR 38
#define	ABORT 39
#define	SAVEERR 40
#else
#define	LINED_MAXLEN 1
#define	LINED_TXTUPLD 2
#define	LINED_EDTMNU 3
#define	LINED_EDTMNUS 4
#define	LINED_HELP 5
#define	LINED_ERRSEL 6
#define	LINED_LLDTBE 7
#define	LINED_ENTTXT 8
#define	LINED_SIZINFO 9
#define	LINED_ENTHLP 10
#define	LINED_RULER 11
#define	LINED_REMINDER 12
#define	LINED_SIZEWARN 13
#define	LINED_CANCEL 14
#define	LINED_NCANCEL 15
#define	LINED_TXTLSTH 16
#define	LINED_TXTHDR 17
#define	LINED_TXTLST 18
#define	LINED_INVLIN 19
#define	LINED_RWCHLN 20
#define	LINED_RNGERR 21
#define	LINED_RANGEOK 22
#define	LINED_FIND 23
#define	LINED_REPLACE 24
#define	LINED_REPLERR 25
#define	LINED_NCHNGD 26
#define	LINED_NLNRDS 27
#define	LINED_RETYPE 28
#define	LINED_EDITLN 29
#define	LINED_DWDELN 30
#define	LINED_DELLIN 31
#define	LINED_DELLNS 32
#define	LINED_YORN 33
#define	LINED_INSERT 34
#define	LINED_ASKNEW 35
#define	LINED_TOOBIG 36
#define	LINED_XFERERR 37
#define	LINED_SIZERR 38
#define	LINED_ABORT 39
#define	LINED_SAVEERR 40
#endif /* __LINED_UNAMBIGUOUS__ */
