include ../CONFIG/Make.config

# Right about the only thing we can do here is check things in and out

all:
		@echo Nothing needs to be made here.

clean:
		$(RM) *~ core #*#

depend dep:

distclean:	clean


include $(CONFIGDIR)/Make.RCS

.PHONY:	all clean dep depend distclean
