#!/bin/sh
#
# $Id: login-telnet,v 2.0 2004/09/13 19:44:54 alexios Exp $
#
# $Log: login-telnet,v $
# Revision 2.0  2004/09/13 19:44:54  alexios
# Stepped version to recover CVS repository after near-catastrophic disk
# crash.
#
# Revision 1.1  2004/02/29 12:28:17  alexios
# Initial revision.
#

# Get the prefix

PREFIX=`echo $0 | sed 's/bin\/[^\/]\+$//'`

# Check the prefix.

[ -r ${PREFIX}/etc/paths ] || exit 1

# Set us up.

. ${PREFIX}/etc/paths

# BAUD=0 indicates this is a telnet connection.

export BAUD=0
declare -xr BAUD

# Off we go.

exec ${PREFIX}/bin/daemons/emud
