/***********************************************************
 **                                                       **
 **  This header file generated by msgidx. Do not alter.  **
 **                                                       **
 ***********************************************************/

#ifndef __OFFLINE_NEWS_UNAMBIGUOUS__
#define	ONKEY 1
#define	DEFNEWS 2
#define	NEWSFILE 3
#define	ONVT 4
#define	ONLT 5
#define	ONNEWS 6
#define	ONDHDR 7
#define	ONDMT 8
#define	ONDNAX 9
#define	ONDOK 10
#else
#define	OFFLINE_NEWS_ONKEY 1
#define	OFFLINE_NEWS_DEFNEWS 2
#define	OFFLINE_NEWS_NEWSFILE 3
#define	OFFLINE_NEWS_ONVT 4
#define	OFFLINE_NEWS_ONLT 5
#define	OFFLINE_NEWS_ONNEWS 6
#define	OFFLINE_NEWS_ONDHDR 7
#define	OFFLINE_NEWS_ONDMT 8
#define	OFFLINE_NEWS_ONDNAX 9
#define	OFFLINE_NEWS_ONDOK 10
#endif /* __OFFLINE_NEWS_UNAMBIGUOUS__ */
