LEVEL2 {}

RMARGIN {Default right margin: 75} N 20 999

VSCRINC {Vertical scrolling increment: 10} N 1 25

HSCRINC {Horizontal scrolling increment: 10} N 1 25

PAGEINC {Page up/down increment (0= 1 screenful): 0} N 0 100

INSERT {Turn insert mode on at start of session? YES} B

FORMAT {Default formatting mode: JUSTIFY} E NONE LEFT RIGHT CENTRE JUSTIFY

TXTUPLD {Text Editor Upload} S 50 File upload description

QTECHRS {>} S 20 Quote character(s)

QTEMAXC {Maximum column where quote chr may appear: 3} N 1 10


CFGTXT {Foreground of normal text: WHITE} E BLACK DARKBLUE DARKGREEN DARKCYAN DARKRED DARKMAGENTA BROWN GREY DARKGREY BLUE GREEN CYAN RED MAGENTA YELLOW WHITE

CBGTXT {Background of normal text: BLACK} E BLACK BLUE GREEN CYAN RED MAGENTA BROWN GREY


CFGBLK {Foreground of block text: WHITE} E BLACK DARKBLUE DARKGREEN DARKCYAN DARKRED DARKMAGENTA BROWN GREY DARKGREY BLUE GREEN CYAN RED MAGENTA YELLOW WHITE

CBGBLK {Background of block text: GREEN} E BLACK BLUE GREEN CYAN RED MAGENTA BROWN GREY


CFGFND {Foreground of found text: MAGENTA} E BLACK DARKBLUE DARKGREEN DARKCYAN DARKRED DARKMAGENTA BROWN GREY DARKGREY BLUE GREEN CYAN RED MAGENTA YELLOW WHITE

CBGFND {Background of found text: BLACK} E BLACK BLUE GREEN CYAN RED MAGENTA BROWN GREY


CFGQTE {Foreground of quoted text: GREEN} E BLACK DARKBLUE DARKGREEN DARKCYAN DARKRED DARKMAGENTA BROWN GREY DARKGREY BLUE GREEN CYAN RED MAGENTA YELLOW WHITE

CBGQTE {Background of quoted text: BLACK} E BLACK BLUE GREEN CYAN RED MAGENTA BROWN GREY


LEVEL3 {}


LOADERR {[0;1;31m
!W’¦ ¡œå£œ¤¦ ¥œ§œ¨¤áœ  «¦ æ¨ ¦ «à¤ [37m%d[31m bytes.
ƒœ¤ £§¦¨œå ¤˜ ­¦¨«àŸœå ¦¢æ¡¢¨¦ ©«¦¤ ©¬¤«á¡« ¡œ £â¤¦¬.!)
!0l[0m

[2J} T File is too big


STOVR {Overwrite} T Top Status line 'Overwrite' string

STINS {Insert   } T Top Status line 'Insert' string


STNONE {No formatting} T Top Status line 'no formatting' string

STLEFT {Left-flush   } Top Status line 'left flush' string

STRGHT {Right-flush  } Top Status line 'right flush' string

STCNTR {Centre       } Top Status line 'centre' string

STJUST {Justify      } Top Status line 'justify' string


STATUST {[0;30;46m[K%4d,%-3d  %6d/%d bytes  %s  %s  ¢á«¦ª %d} T Top Status line


STATUSB {[K[0;1;36m Escape [0;30;46m Meta (M-)  [0;1;36m Ctrl-O [0;30;46m Format     [0;1;36m Ctrl-K [0;30;46m Blocks     [0;1;36m Ctrl-L [0;30;46m Redraw[K
K[0;1;36m Ctrl-R [0;30;46m ¦ãŸœ ˜    [0;1;36m Ctrl-S [0;30;46m „¥¦›¦ª     [0;1;36m Ctrl-C [0;30;46m €¡ç¨à©    [0;1;36m Meta-F [0;30;46m Reformat[K} T Bottom Status lines

STATUSM {[K[0;30;42m Meta-              [0;1;32m    V   [0;30;42m ‘œ¢å›˜ -   [0;1;32m    <   [0;30;42m €¨®ã       [0;1;32m    X   [0;30;42m „¥¦›¦ª[K
[K[0;1;32m Ctrl-R [0;30;42m ¦ãŸœ ˜    [0;1;32m    %   [0;30;42m Find/repl. [0;1;32m    >   [0;30;42m ’â¢¦ª      [0;1;32m    Q   [0;30;42m €¡ç¨à©[K} T Bottom Status lines, meta key

STATUSO {[K[0;30;42m Formatting-        [0;1;32m    I   [0;30;42m Insert     [0;1;32m    L   [0;30;42m €¨ ©«œ¨á   [0;1;32m    C   [0;30;42m ‰â¤«¨¦[K
[K[0;1;32m Ctrl-R [0;30;42m ¦ãŸœ ˜    [0;1;32m    R   [0;30;42m ƒœ¥ á      [0;1;32m    J   [0;30;42m ‘«¦å® ©   [0;1;32m    N   [0;30;42m ’å§¦«˜[K} T Bottom Status lines, formatting

STATUSK {[K[0;30;42m Blocks-            [0;1;32m    B   [0;30;42m €¨®ã       [0;1;32m    K   [0;30;42m ’â¢¦ª      [0;1;32m    C   [0;30;42m €¤« š¨˜­ã[K
[K[0;1;32m Ctrl-R [0;30;42m ¦ãŸœ ˜    [0;1;32m    V   [0;30;42m ‹œ«˜¡å¤© [0;1;32m    Y   [0;30;42m ƒ ˜š¨˜­ã   [0;1;32m        [0;30;42m       [K} T Bottom Status lines, blocks 


ERRSIZ {[0;1;33;41m[K”«á©˜«œ «¦ æ¨ ¦ £œšâŸ¦¬ª «¦¬ ¡œ £â¤¦¬ ©˜ª.} T Error: reached size limit

ERRFMT {[0;1;33;41m[K’¦ ¡œå£œ¤¦ ¥œ§â¨˜©œ «¦ æ¨ ¦ £œšâŸ¦¬ª. ‡˜ ¡¦§œå æ«˜¤ ™šœå«œ ˜§æ «¦¤ editor.} T Error: exceeded size limit


HELP1 {[0;1;47;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;47;30m¿ [0m
[0;1;47;37m ³ [0;30;47mFull Screen Editor                                    †‡„ˆ€ - ‘œ¢å›˜ 1/4 ³ [0m
[0;1;47;37m ³ [0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ ³ [0m
[0;1;47;37m ³ ‰ˆŒ†‘†:[0;30;47m C-P  [34má¤à           [30mC-N  [34m‰á«à            [30mÚÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄ¿ [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m        C-B  [34m€¨ ©«œ¨á       [30mC-F  [34mƒœ¥ á           [30m³ Home: ³  Up   ³ PgUp: ³ [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m        C-A  [34m€¨®ã š¨˜££ãª   [30mC-E  [34m’â¢¦ª š¨˜££ãª   [30m³  C-A  ³  C-P  ³  C-T  ³ [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m        C-T  [34m¨¦š. ‘œ¢å›˜  [30mC-V  [34m„§æ£. ©œ¢å›˜    [30mÃÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄ´ [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m        C-Q  [34m€¨®ã ¡œ £â¤¦¬  [30mC-W  [34m’â¢¦ª ¡œ £â¤¦¬  [30m³ Left: ³       ³ Rght: ³ [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m        M-<  [34m€¨®ã ¡œ £â¤¦¬  [30mM->  [34m’â¢¦ª ¡œ £â¤¦¬  [30m³  C-B  ³       ³  C-F  ³ [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m                                                 ÃÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄ´ [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m        '† ®¨© £¦§¦ ã©«œ «˜ ™â¢ (ANSI/VT).     ³ End:  ³ Down: ³ PgDn: ³ [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m                                                 ³  C-E  ³  C-N  ³  C-V  ³ [0;47;30m³ [0m
[0;1;47;37m ³ ƒˆ€‚€”†: [0;30;47mC-D  [34mƒ ˜š¨˜­ã œ§æ£œ¤¦¬ ®˜¨˜¡«ã¨˜       [30mÀÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÙ [0;47;30m³ [0m
[0;1;47;37m ³           [0;30;47mC-Y  [34mƒ ˜š¨˜­ã «¨â®¦¬©˜ª š¨˜££ãª                                  [0;47;30m³ [0m
[0;1;47;37m ³                                                                            [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m (C-A = Ctrl-A, M-A = Esc + A ã Alt-A ˜¤ ™¨å©¡œ©«œ ©œ Linux ¡¦¤©æ¢˜)       [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m (1" ˜­¦ç § â©œ«œ â¤˜ œ › ¡æ §¢ã¡«¨¦, œ£­˜¤å¦¤«˜  ›ç¦ š¨˜££âª ™¦ãŸœ ˜ª)   [0;47;30m³ [0m
[0;1;47;37m ³                                                                            [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m Enter š ˜ «¤ œ§æ£œ¤ ©œ¢å›˜, ¦§¦ ¦›ã§¦«œ á¢¢¦ §¢ã¡«¨¦ š ˜ œ§ ©«¨¦­ã.     [0;47;30m³ [0m
[0;1;47;37m À[0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m
} T Help, page 1 (basic commands)


HELP2 {[0;1;47;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;47;30m¿ [0m
[0;1;47;37m ³ [0;30;47mFull Screen Editor                                    †‡„ˆ€ - ‘œ¢å›˜ 2/4 ³ [0m
[0;1;47;37m ³ [0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ ³ [0m
[0;1;47;37m ³ €ŠŠ„‘ „Œ’Š„‘:[0;30;47m                                                             ³ [0m
[0;1;47;37m ³ [0;30;47m    C-K F [34m–á¥ £¦ š ˜ ¡œå£œ¤¦ (Find)                                        [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m    C-U   [34m‘¬¤â®œ ˜ ¯˜¥å£˜«¦ª (Find next)                                   [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m    C-K A [34m€¤« ¡˜«á©«˜© ¡œ £â¤¦¬ (Find-Replace)                            [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m                                                                           ³ [0m
[0;1;47;37m ³ [0;30;47m    C-K B [34m€¨®ã ˜§¦©§á©£˜«¦ª (Block beginning)                              [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m    C-K K [34m’â¢¦ª ˜§¦©§á©£˜«¦ª (Block end)                                   [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m    C-K C [34m€¤« š¨˜­ã ˜§¦©§á©£˜«¦ª (Copy block)                              [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m    C-K M [34m‹œ«˜¡å¤© ˜§¦©§á©£˜«¦ª (Move block)                             [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m    C-K V [34m’¦ å› ¦                                                          [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m    C-K Y [34mƒ ˜š¨˜­ã ˜§¦©§á©£˜«¦ª                                            [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m                                                                           ³ [0m
[0;1;47;37m ³ [0;30;47m    C-K R [34mçŸ£ © ›œ¥ ¦ç §œ¨ Ÿà¨å¦¬                                        ³ [0m
[0;1;47;37m ³ [0;30;47m                                                                           [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m                                                                           ³ [0m
[0;1;47;37m ³ [0;30;47m Enter š ˜ «¤ œ§æ£œ¤ ©œ¢å›˜, ¦§¦ ¦›ã§¦«œ á¢¢¦ §¢ã¡«¨¦ š ˜ œ§ ©«¨¦­ã.     [0;47;30m³ [0m
[0;1;47;37m À[0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m
} T Help, page 2 (blocks, etc.)


HELP3 {[0;1;47;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;47;30m¿ [0m
[0;1;47;37m ³ [0;30;47mFull Screen Editor                                    †‡„ˆ€ - ‘œ¢å›˜ 3/4 ³ [0m
[0;1;47;37m ³ [0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ ³ [0m
[0;1;47;37m ³ ‹”ˆ†‘† ‰„ˆ‹„Œ“:[0;30;47m                                                      [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m    C-O I ã M-I [34mInsert/Overtype mode (œ ©˜šàšã/¬§œ¨¡á¢¬¯ ¡œ £â¤¦¬)        [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m    C-O L ã M-L [34m‘«¦å® © ˜¨ ©«œ¨á (wrap)                                   [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m    C-O C ã M-C [34m‰œ¤«¨á¨ ©£˜ š¨˜££é¤                                        [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m    C-O R ã M-R [34m‘«¦å® © ›œ¥ á                                             [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m    C-O J ã M-J [34m‘«¦å® © ˜¨ ©«œ¨á ¡˜  ›œ¥ á (justify)                      [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m    C-O N ã M-N [34m€§œ¤œ¨š¦§¦å© £¦¨­¦§¦å©ª (›œ¤ ©¬¤ ©«á«˜ )               [0;47;30m³ [0m
[0;1;47;37m ³                                                                            [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m    M-F         [34m‹¦¨­¦§¦å© §˜¨˜š¨á­¦¬ ˜§æ «¤ «¨â®¦¬©˜ š¨˜££ã ¡˜  ¡á«à    [0;47;30m³ [0m
[0;1;47;37m ³                                                                            [0;47;30m³ [0m
[0;1;47;37m ³ [0;47;30m€¬«æ£˜« £¦¨­¦§¦å© «ª «œ¢œ¬«˜å˜ª š¨˜££ãª šå¤œ«˜  £œ «¤ §åœ© «¦¬ Enter ³ [0m
[0;1;47;37m ³ [0;47;30m¡˜  £æ¤¦ š ˜ ©«¦å® © ›œ¥ á ¡˜  ¡œ¤«¨á¨ ©£˜. ‘«¤ ©«¦å® © ˜¨ ©«œ¨á (wrap) ³ [0m
[0;1;47;37m ³ [0;47;30m £¦¨­¦§¦å© šå¤œ«˜  ¡˜Ÿéª §¢¡«¨¦¢¦šœå«œ.  ‘«¦ Justify ›œ¤ šå¤œ«˜  ˜¬«æ- ³ [0m
[0;1;47;37m ³ [0;47;30m£˜« ©«¦å® ©.  â©«œ Tab ©«¤ ˜¨®ã «ª §˜¨˜š¨á­¦¬ š ˜ ¤˜ «¤ ©«¦ ®å©œ«œ.  ³ [0m
[0;1;47;37m ³                                                                            [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m Enter š ˜ «¤ œ§æ£œ¤ ©œ¢å›˜, ¦§¦ ¦›ã§¦«œ á¢¢¦ §¢ã¡«¨¦ š ˜ œ§ ©«¨¦­ã.     [0;47;30m³ [0m
[0;1;47;37m À[0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m
} T Help, page 3 (formatting)


HELP4 {[0;1;47;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;47;30m¿ [0m
[0;1;47;37m ³ [0;30;47mFull Screen Editor                                    †‡„ˆ€ - ‘œ¢å›˜ 4/4 ³ [0m
[0;1;47;37m ³ [0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ ³ [0m
[0;1;47;37m ³ „ˆƒˆ‰„‘ „Œ’Š„‘ ‰€ˆ „ƒ‘[0;30;47m                                                 [0;47;30m³ [0m
[0;1;47;37m ³                                                                            [0;47;30m³ [0m
[0;1;47;37m ³ [0;47;30mC-S ã M-X  [34m€§¦Ÿã¡œ¬© «¦¬ ¡œ £â¤¦¬ ¡˜  â¥¦›¦ª                              [30m³ [0m
[0;1;47;37m ³ [0;47;30mC-Y ã M-Q  [34m„š¡˜«á¢œ ¯ «¦¬ ¡œ £â¤¦¬ ¡˜  â¥¦›¦ª                             [30m³ [0m
[0;1;47;37m ³ [0;47;30mC-X        [34m‹œ«á™˜© «¦¬ ¡œ £â¤¦¬ ©«¦¤ line editor                          [30m³ [0m
[0;1;47;37m ³                                                                            [0;47;30m³ [0m
[0;1;47;37m ³ [0;47;30mC-Z        [34m€§¦©«¦¢ã (upload) â«¦ £¦¬ ¡œ £â¤¦¬ ©«¦¤ editor                  [30m³ [0m
[0;1;47;37m ³                                                                            [0;47;30m³ [0m
[0;1;47;37m ³ [0;47;30m‹§¦¨œå«œ ¤˜  œ ©ášœ«œ ¡œå£œ¤˜ £œ œ › ¡¦çª ®˜¨˜¡«ã¨œª  (§® ANSI œ¤«¦¢âª) £œ ³ [0m
[0;1;47;37m ³ [0;47;30m«¤ «œ¢œ¬«˜å˜ œ¤«¦¢ã. ’¬®æ¤ œ › ¡¦å ®˜¨˜¡«ã¨œª œ£­˜¤å¦¤«˜  ©˜¤ œ¨à«£˜« - ³ [0m
[0;1;47;37m ³ [0;47;30m¡á ('?'). † £¦¨­¦§¦å© «¦¬ â«¦ £¦¬ ¡œ £â¤¦¬ œå¤˜  › ¡ã ©˜ª œ¬Ÿç¤.        ³ [0m
[0;1;47;37m ³                                                                            [0;47;30m³ [0m
[0;1;47;37m ³ [0;47;30m‘œ §œ¨å§«à© §¦¬, ¡˜«á «¤ â¥¦›æ  ©˜ª ˜§æ «¦¤ editor, «¦ ¡œå£œ¤¦ ¥œ§œ¨¤áœ  ³ [0m
[0;1;47;37m ³ [0;47;30m«¦ æ¨ ¦ £œšâŸ¦¬ª (§® ¢æšà £¦¨­¦§¦å©ª), «¦ œ§ §¢â¦¤ ¡œå£œ¤¦ Ÿ˜ › ˜š¨˜­œå. ³ [0m
[0;1;47;37m ³                                                                            [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m  â©«œ ¦§¦ ¦›ã§¦«œ §¢ã¡«¨¦ š ˜ œ§ ©«¨¦­ã ©«¦ ¡œå£œ¤¦.                     [0;47;30m³ [0m
[0;1;47;37m À[0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m
} T Help, page 4 (exiting etc.)


FIND1 {[0;30;42m[K –á¥ £¦ š ˜ ¡œå£œ¤¦. ƒé©«œ «¦ ¡œå£œ¤¦ §¦¬ Ÿâ¢œ«œ ¤˜ ™¨œå«œ.
[K >} T Find, enter text to search for

FIND2 {[0;30;42m[K –á¥ £¦ š ˜ ¡œå£œ¤¦. ’  œå›¦ª â¨œ¬¤˜ª Ÿâ¢œ«œ;
[K[0;1;32m  Enter [0;30;42m €¬©«¨ã    [0;1;32m    I   [0;30;42m ‰œ­./£ ¡¨á [0;1;32m    P   [0;30;42m ”à¤« ¡ã   [0;1;32m        [0;30;42m       [K} T Find, enter search options


FREP1 {[0;30;42m[K €¢¢˜šã ¡œ £â¤¦¬. ƒé©«œ «¦ ¡œå£œ¤¦ §¦¬ Ÿâ¢œ«œ ¤˜ ™¨œå«œ.
[K >} T Find-Replace, enter text to search for

FREP2 {[0;30;42m[K €¢¢˜šã ¡œ £â¤¦¬. ƒé©«œ «¦ ¤â¦ ¡œå£œ¤¦.
[K >} T Find-Replace, enter text to replace with

FREP3 {[0;30;42m[K €¢¢˜šã ¡œ £â¤¦¬. ’  œå›¦ª â¨œ¬¤˜ª Ÿâ¢œ«œ;
[K[0;1;32m  Enter [0;30;42m €¬©«¨ã    [0;1;32m    I   [0;30;42m ‰œ­./£ ¡¨á [0;1;32m    P   [0;30;42m ”à¤« ¡ã   [0;1;32m        [0;30;42m       [K} T Find-Replace, enter search options

FREP4 {[0;30;42m[K ’¦ ¡œå£œ¤¦ ™¨âŸ¡œ. Œ˜ «¦ ˜¤« ¡˜«˜©«ã©à;
[K[0;1;32m    Y   [0;30;42m Œ˜         [0;1;32m    N   [0;30;42m ®         [0;1;32m    A   [0;30;42m Œ˜  ©œ æ¢˜ [0;1;32m    Q   [0;30;42m €¡ç¨à©[K} T Find-Replace, replace commands


RMARG {[0;30;42m[K çŸ£ © ›œ¥ ¦ç §œ¨ Ÿà¨å¦¬. ƒé©«œ â¤˜¤ ˜¨ Ÿ£æ (20-999).
[K >} T Set right margin


QUIT {[0;30;42m[K ˜¨˜¡˜¢é œ§ ™œ™˜ é©«œ æ«  Ÿâ¢œ«œ ¤˜ œš¡˜«˜¢œå¯œ«œ «¦ ¡œå£œ¤æ ©˜ª.
[K[0;1;32m    Y   [0;30;42m Œ˜         [0;1;32m    N   [0;30;42m ®         [0;1;32m        [0;30;42m            [0;1;32m        [0;30;42m        [K} T Quit, ask for confirmation


XFERERR {[0;1;31m
!JŠ¬§á£˜ , «¦ ˜¨®œå¦ §¦¬ £æ¢ ª ˜§¦©«œå¢˜«œ ®áŸ¡œ. ˜¨˜¡˜¢¦ç£œ
œ ›¦§¦ œå©«œ «¦¤ ®œ ¨ ©«ã ©¬©«ã£˜«¦ª š ˜ «¦ ©¬£™á¤.!)
[0;1m[2J} T Editor error, unable to open uploaded file


CLRSCR {[2J} T Clear screen upon exit (possibly faster than curses)


SAVEERR {[0;1;31m


!JŠ¬§á£˜ , ¬§ã¨¥œ ¢áŸ¦ª œšš¨˜­ãª ˜¤áš¤à©ª ¡˜«á «¤ ˜§¦Ÿã¡œ¬©
«¦¬ ˜¨®œå¦¬ («ç§¦ª Unix ¢áŸ¦¬ª: #%d, %s).!)
[0;1m} T Editor error, unable to save file


LANG {}

LOADERR {[0;1;31m
!WThe size of the text is beyond the limit of [37m%d[31m bytes.
It cannot be loaded into the editor and has been truncated.!)
!0l[0;1m

[2J} T File is too big


STOVR {Overwrite} T Top Status line 'Overwrite' string

STINS {Insert   } T Top Status line 'Insert' string


STNONE {No formatting} T Top Status line 'no formatting' string

STLEFT {Left-flush   } Top Status line 'left flush' string

STRGHT {Right-flush  } Top Status line 'right flush' string

STCNTR {Centre       } Top Status line 'centre' string

STJUST {Justify      } Top Status line 'justify' string


STATUST {[0;30;46m[K%4d,%-3d  %6d/%d bytes  %s  %s  Width %d} T Top Status line


STATUSB {[K[0;1;36m Escape [0;30;46m Meta (M-)  [0;1;36m Ctrl-O [0;30;46m Format     [0;1;36m Ctrl-K [0;30;46m Blocks     [0;1;36m Ctrl-L [0;30;46m Redraw[K
[K[0;1;36m Ctrl-R [0;30;46m Help       [0;1;36m Ctrl-S [0;30;46m Save, exit [0;1;36m Ctrl-C [0;30;46m Abort      [0;1;36m Tab    [0;30;46m Reformat[K} T Bottom Status lines

STATUSM {[K[0;30;42m Meta-              [0;1;32m    V   [0;30;42m Page up    [0;1;32m    <   [0;30;42m Top        [0;1;32m    X   [0;30;42m Save, exit[K
[K[0;1;32m Ctrl-R [0;30;42m Help       [0;1;32m    %   [0;30;42m Find/repl. [0;1;32m    >   [0;30;42m Bottom     [0;1;32m    Q   [0;30;42m Abort     [K} T Bottom Status lines, meta key

STATUSO {[K[0;30;42m Formatting-        [0;1;32m    I   [0;30;42m Insert     [0;1;32m    L   [0;30;42m Left       [0;1;32m    C   [0;30;42m Centre[K
[K[0;1;32m Ctrl-R [0;30;42m Help       [0;1;32m    R   [0;30;42m Right      [0;1;32m    J   [0;30;42m Justify    [0;1;32m    N   [0;30;42m None  [K} T Bottom Status lines, formatting

STATUSK {[K[0;30;42m Blocks-            [0;1;32m    B   [0;30;42m Begin      [0;1;32m    K   [0;30;42m End        [0;1;32m    C   [0;30;42m Copy     [K
[K[0;1;32m Ctrl-R [0;30;42m Help       [0;1;32m    V   [0;30;42m Move       [0;1;32m    Y   [0;30;42m Delete     [0;1;32m        [0;30;42m       [K} T Bottom Status lines, blocks 


ERRSIZ {[0;1;33;41m[KYou have reached the size limit.} T Error: reached size limit

ERRFMT {[0;1;33;41m[KYour text has surpassed the size limit. It will be truncated upon exit.} T Error: exceeded size limit


HELP1 {[0;1;47;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;47;30m¿ [0m
[0;1;47;37m ³ [0;30;47mFull Screen Editor                                         HELP - Page 1/4 ³ [0m
[0;1;47;37m ³ [0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ ³ [0m
[0;1;47;37m ³ ‰ˆŒ†‘†:[0;30;47m C-P  [34mMove up         [30mC-N  [34mMove down      [30mÚÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄ¿ [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m        C-B  [34mMove left       [30mC-F  [34mMove right     [30m³ Home: ³  Up   ³ PgUp: ³ [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m        C-A  [34mGo to column 1  [30mC-E  [34mEnd of line    [30m³  C-A  ³  C-P  ³  C-T  ³ [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m        C-T  [34mPage up         [30mC-V  [34mPage down      [30mÃÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄ´ [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m        C-Q  [34mTop of text     [30mC-W  [34mBottom of text [30m³ Left: ³       ³ Rght: ³ [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m        M-<  [34mTop of text     [30mM->  [34mBottom of text [30m³  C-B  ³       ³  C-F  ³ [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m                                                 ÃÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄ´ [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m        Or use the arrow keys (ANSI/VT).         ³ End:  ³ Down: ³ PgDn: ³ [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m                                                 ³  C-E  ³  C-N  ³  C-V  ³ [0;47;30m³ [0m
[0;1;47;37m ³ ƒˆ€‚€”†: [0;30;47mC-D  [34mDelete next character             [30mÀÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÙ [0;47;30m³ [0m
[0;1;47;37m ³           [0;30;47mC-Y  [34mDelete current line                                         [0;47;30m³ [0m
[0;1;47;37m ³                                                                            [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m (C-A = Ctrl-A, M-A = Esc + A or Alt-A if you're on a Un*x console)        [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m (1 second after pressing a special key, two help lines will appear)       [0;47;30m³ [0m
[0;1;47;37m ³                                                                            [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m Enter for the next page, any other key to return.                         [0;47;30m³ [0m
[0;1;47;37m À[0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m
} T Help, page 1 (basic commands)


HELP2 {[0;1;47;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;47;30m¿ [0m
[0;1;47;37m ³ [0;30;47mFull Screen Editor                                         HELP - Page 2/4 ³ [0m
[0;1;47;37m ³ [0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ ³ [0m
[0;1;47;37m ³ OTHER COMMANDS:[0;30;47m                                                            ³ [0m
[0;1;47;37m ³ [0;30;47m    C-K F [34mSearch for text                                                  [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m    C-U   [34mFind next occurence                                              [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m    C-K A [34mFind and replace text                                            [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m                                                                           ³ [0m
[0;1;47;37m ³ [0;30;47m    C-K B [34mSet beginning of block                                           [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m    C-K K [34mSet end of block                                                 [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m    C-K C [34mCopy block                                                       [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m    C-K M [34mMove block                                                       [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m    C-K V [34mMove block                                                       [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m    C-K Y [34mDelete block                                                     [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m                                                                           ³ [0m
[0;1;47;37m ³ [0;30;47m    C-K R [34mSet right margin                                                 ³ [0m
[0;1;47;37m ³ [0;30;47m                                                                           [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m                                                                           ³ [0m
[0;1;47;37m ³ [0;30;47m Enter for the next page, any other key to return.                         [0;47;30m³ [0m
[0;1;47;37m À[0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m
} T Help, page 2 (blocks, etc.)


HELP3 {[0;1;47;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;47;30m¿ [0m
[0;1;47;37m ³ [0;30;47mFull Screen Editor                                         HELP - Page 3/4 ³ [0m
[0;1;47;37m ³ [0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ ³ [0m
[0;1;47;37m ³ TEXT FORMATTING:[0;30;47m                                                           [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m    C-O I or M-I [34mInsert/Overtype mode                                      [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m    C-O L or M-L [34mLeft justify (wrap around)                                [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m    C-O C or M-C [34mCentre lines                                              [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m    C-O R or M-R [34mFlush right                                               [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m    C-O J or M-J [34mLeft and right justification                              [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m    C-O N or M-N [34mNo formatting (not recommended)                           [0;47;30m³ [0m
[0;1;47;37m ³                                                                            [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m    Tab         [34mReformat paragraph starting from current line              [0;47;30m³ [0m
[0;1;47;37m ³                                                                            [0;47;30m³ [0m
[0;1;47;37m ³ [0;47;30mLines  typed  are  automatically formatted  when Enter is  pressed, if the ³ [0m
[0;1;47;37m ³ [0;47;30mformatting mode is 'flush right' or 'centre'. For left justification, your ³ [0m
[0;1;47;37m ³ [0;47;30mtext is formatted while you type.  For left and right justification, there ³ [0m
[0;1;47;37m ³ [0;47;30mis no auto formatting. Press Tab to format the current paragraph.          ³ [0m
[0;1;47;37m ³                                                                            [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m Enter for the next page, any other key to return.                         [0;47;30m³ [0m
[0;1;47;37m À[0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m
} T Help, page 3 (formatting)


HELP4 {[0;1;47;37m ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ[0;47;30m¿ [0m
[0;1;47;37m ³ [0;30;47mFull Screen Editor                                         HELP - Page 4/4 ³ [0m
[0;1;47;37m ³ [0;30;47mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ ³ [0m
[0;1;47;37m ³ SPECIAL COMMANDS AND EXITING:[0;30;47m                                              [0;47;30m³ [0m
[0;1;47;37m ³                                                                            [0;47;30m³ [0m
[0;1;47;37m ³ [0;47;30mC-S or M-X  [34mSave the text and exit                                         [30m³ [0m
[0;1;47;37m ³ [0;47;30mC-Y or M-Q  [34mAbort the editing session and lose the text                    [30m³ [0m
[0;1;47;37m ³ [0;47;30mC-X         [34mMove the text to the line editor                               [30m³ [0m
[0;1;47;37m ³                                                                            [0;47;30m³ [0m
[0;1;47;37m ³ [0;47;30mC-Z         [34mUpload a preformatted file into the editor                     [30m³ [0m
[0;1;47;37m ³                                                                            [0;47;30m³ [0m
[0;1;47;37m ³ [0;47;30mYou can upload files  with special characters  (eg ANSI directives)  using ³ [0m
[0;1;47;37m ³ [0;47;30mthe upload command. Any special  characters will appear as question-marks  ³ [0m
[0;1;47;37m ³ [0;47;30m('?'). Formatting the text is entirely your responsibility.                ³ [0m
[0;1;47;37m ³                                                                            [0;47;30m³ [0m
[0;1;47;37m ³ [0;47;30mIf, during exit from the editor,  your text is over the size limit (eg due ³ [0m
[0;1;47;37m ³ [0;47;30mto reformatting), it will be truncated.                                    ³ [0m
[0;1;47;37m ³                                                                            [0;47;30m³ [0m
[0;1;47;37m ³ [0;30;47m Press any key to return to the editor.                                    [0;47;30m³ [0m
[0;1;47;37m À[0;47;30mÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ [0m
} T Help, page 4 (exiting etc.)


FIND1 {[0;30;42m[K Find text. Please enter the text to search for.
[K >} T Find, enter text to search for

FIND2 {[0;30;42m[K Find text. Please enter the desired search type:
[K[0;1;32m  Enter [0;30;42m Strict     [0;1;32m    I   [0;30;42m No case    [0;1;32m    P   [0;30;42m Phonetic   [0;1;32m        [0;30;42m       [K} T Find, enter search options


FREP1 {[0;30;42m[K Find/Replace. Enter the text to search for.
[K >} T Find-Replace, enter text to search for

FREP2 {[0;30;42m[K Find/Replace. Enter the replacement text.
[K >} T Find-Replace, enter text to replace with

FREP3 {[0;30;42m[K Find/Replace. Please enter the desired search type:
[K[0;1;32m  Enter [0;30;42m Strict     [0;1;32m    I   [0;30;42m No case    [0;1;32m    P   [0;30;42m Phonetic   [0;1;32m        [0;30;42m       [K} T Find-Replace, enter search options

FREP4 {[0;30;42m[K The text was located. Replace it?          
[K[0;1;32m    Y   [0;30;42m Yes        [0;1;32m    N   [0;30;42m No         [0;1;32m    A   [0;30;42m Yes to all [0;1;32m    Q   [0;30;42m Cancel [K} T Find-Replace, replace commands


RMARG {[0;30;42m[K Set right margin. Please enter a number (20-79).
[K >} T Set right margin


QUIT {[0;30;42m[K Please confirm that you intend to lose your text.    
[K[0;1;32m    Y   [0;30;42m Yes        [0;1;32m    N   [0;30;42m No         [0;1;32m        [0;30;42m            [0;1;32m        [0;30;42m        [K} T Quit, ask for confirmation


XFERERR {[0;1;31m
!JSorry, the file you just uploaded was lost. Please
notify the system operator about this incident.!)
[0;1m[2J} T Editor error, unable to open uploaded file


CLRSCR {[2J} T Clear screen upon exit (possibly faster than curses)

SAVEERR {[0;1;31m


!JSorry, there was an I/O error while saving the file (Unix error: #%d,
%s).!)
[0;1m} T Editor error, unable to save file





LANGEND {}
